In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil_types/plsda/soil_types.csv', sep=';') # local copy of Toledo and Guarapuava soil datasets
data = data_complete.loc[:, '1.32':'13.1']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.32':'13.1'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.32':'13.1'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:34:32,544 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:34:32,623 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:34:32,669 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:34:32,751 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[247, 0], [0, 254]]",1.0,1.0,1.0,"[[107, 0], [0, 109]]"

## Definição das Zonas Espectrais

In [3]:
spectral_cuts = [
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.37),
('Ti ka', 4.37, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('Ni', 7.30, 7.91),
('Cu', 7.91, 8.20),
('Zn', 8.20, 9.0),
('background1', 9.0, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background2', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
]

## Pvector and SHAP

In [4]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df

   energy    Pvector           Zone
0    6.42  38.192949          Fe ka
1     7.1  13.648747          Fe kb
2    3.32   7.823500              K
3    5.92   4.147603             Mn
4   12.84   3.515694         sum Fe
5    2.62   3.346369      Rh L + Ar
6    1.74   3.190167             Si
7    4.98   3.110417          Ti kb
8    8.02   2.888905             Cu
9    4.48   2.277795          Ti ka
10    5.4   2.127635             Cr
11   2.04   2.058032              P
12   1.46   1.988857             Al
13    9.3   1.840636    background1
14  11.16   1.739729    background2
15   8.66   1.527217             Zn
16   7.34   1.500846             Ni
17  10.74   1.492663  Fe ka + Ti ka
18   3.56   1.440126          Ca ka
19   2.54   1.383906              S
20   4.12   1.188830          Ca kb
21   1.32   0.386146            NaN

In [5]:
shap_global_importance = pd.read_csv('shap_soil_type.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP           Zone
0     6.42       0.066660          Fe ka
1     4.50       0.001514          Ti ka
2     3.70       0.000280          Ca ka
3     7.08       0.000226          Fe kb
4     4.80       0.000213          Ti kb
5     7.60       0.000203             Ni
6     3.04       0.000201      Rh L + Ar
7     2.40       0.000157              S
8    10.22       0.000138    background1
9     8.10       0.000137             Cu
10    4.16       0.000134          Ca kb
11   12.12       0.000130    background2
12    5.92       0.000129             Mn
13    5.70       0.000125             Cr
14    3.48       0.000111              K
15    8.94       0.000082             Zn
16   12.80       0.000079         sum Fe
17    1.86       0.000076              P
18    1.46       0.000070             Al
19    1.68       0.000067             Si
20   10.96       0.000061  Fe ka + Ti ka
21    1.32       0.000000            NaN

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Al': VE = 87.97%, dim = 15 variáveis
Zona 'Si': VE = 96.43%, dim = 12 variáveis
Zona 'P': VE = 62.58%, dim = 17 variáveis
Zona 'S': VE = 44.25%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 73.64%, dim = 33 variáveis
Zona 'K': VE = 95.35%, dim = 16 variáveis
Zona 'Ca ka': VE = 98.88%, dim = 16 variáveis
Zona 'Ca kb': VE = 74.22%, dim = 27 variáveis
Zona 'Ti ka': VE = 85.88%, dim = 19 variáveis
Zona 'Ti kb': VE = 88.37%, dim = 19 variáveis
Zona 'Cr': VE = 82.96%, dim = 33 variáveis
Zona 'Mn': VE = 94.39%, dim = 18 variáveis
Zona 'Fe ka': VE = 91.33%, dim = 34 variáveis
Zona 'Fe kb': VE = 90.72%, dim = 26 variáveis
Zona 'Ni': VE = 58.25%, dim = 31 variáveis
Zona 'Cu': VE = 84.29%, dim = 15 variáveis
Zona 'Zn': VE = 60.20%, dim = 41 variáveis
Zona 'background1': VE = 61.89%, dim = 85 variáveis
Zona 'Fe ka + Ti ka': VE = 55.37%, dim = 23 variáveis
Zona 'background2': VE = 50.79%, dim = 71 variáveis
Zona 'sum Fe': VE = 90.84%, dim = 28 variáveis

Scores DataFrame shape: (501, 21)

In [7]:
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(svm_model[4]['SVC'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 124
Removida: Fe kb > -3.67 -> Fe ka <= 4.25 (3.8055) | Mantida: Fe ka <= 4.25 -> Fe kb > -3.67 (9.4592)
Removida: Ti kb > -1.01 -> Rh L + Ar > -0.69 (0.4768) | Mantida: Rh L + Ar > -0.69 -> Ti kb > -1.01 (0.7920)
Removida: Si > -1.03 -> Rh L + Ar > -0.69 (0.5311) | Mantida: Rh L + Ar > -0.69 -> Si > -1.03 (0.7834)
Removida: Ti kb > -1.01 -> Si > -1.03 (0.2325) | Mantida: Si > -1.03 -> Ti kb > -1.01 (0.7573)
Removida: Ti ka > -0.55 -> Ti kb > -1.01 (0.2354) | Mantida: Ti kb > -1.01 -> Ti ka > -0.55 (0.4789)
Removida: Ti ka > -0.55 -> Si > -1.03 (0.2236) | Mantida: Si > -1.03 -> Ti ka > -0.55 (0.2535)
Removida: Rh L + Ar <= 0.76 -> Ti ka > -0.55 (0.3704) | Mantida: Ti ka > -0.55 -> Rh L + Ar <= 0.76 (0.4499)
Removida: Ti ka > -0.55 -> Mn > -0.74 (0.2038) | Mantida: Mn > -0.74 -> Ti ka > -0.55 (0.2257)
Removida: Mn > -0.74 -> Ti ka > 0.61 (0.2172) | Mantida: Ti ka > 0.61 -> Mn > -0.74 (0.3991)
Removida: Ti ka > 0.61 -> sum Fe > -0.60 (0.3907) | Mantida: sum Fe > -0.60 -> Ti ka > 0.61 (0.7953)
Removida: sum Fe > -0.60 -> Ca ka > -1.89 (0.2019) | Mantida: Ca ka > -1.89 -> sum Fe > -0.60 (0.2361)
Removida: Ti kb > -0.36 -> Ti ka > 0.61 (0.3625) | Mantida: Ti ka > 0.61 -> Ti kb > -0.36 (0.3679)
Removida: Cr > -0.67 -> Ti kb > -0.36 (0.4924) | Mantida: Ti kb > -0.36 -> Cr > -0.67 (0.5490)
Removida: Ti kb > -0.36 -> Ti kb <= 1.01 (0.1723) | Mantida: Ti kb <= 1.01 -> Ti kb > -0.36 (0.3633)
Removida: Cr > -0.67 -> Ca ka > -1.89 (0.1653) | Mantida: Ca ka > -1.89 -> Cr > -0.67 (0.4194)
Removida: Cr <= 0.70 -> Cr > -0.67 (0.3255) | Mantida: Cr > -0.67 -> Cr <= 0.70 (0.3329)
Removida: Ti kb <= 1.01 -> Cr > -0.67 (0.1792) | Mantida: Cr > -0.67 -> Ti kb <= 1.01 (0.6664)
Removida: Cr <= 0.70 -> Ca ka > -1.89 (0.1568) | Mantida: Ca ka > -1.89 -> Cr <= 0.70 (0.3898)
Removida: Cr <= 0.70 -> Ti kb <= 1.01 (0.3220) | Mantida: Ti kb <= 1.01 -> Cr <= 0.70 (0.5203)
Removida: Si <= 1.00 -> Cr <= 0.70 (0.1938) | Mantida: Cr <= 0.70 -> Si <= 1.00 (0.4769)
Removida: Si > -0.46 -> Si <= 1.00 (0.3330) | Mantida: Si <= 1.00 -> Si > -0.46 (0.9998)
Removida: Cu > -0.46 -> Si > -0.46 (0.1340) | Mantida: Si > -0.46 -> Cu > -0.46 (0.8294)
Removida: Cu > -0.46 -> Ca ka > -1.23 (0.1411) | Mantida: Ca ka > -1.23 -> Cu > -0.46 (0.3189)
Removida: Mn <= 0.30 -> Cu <= 0.48 (0.2877) | Mantida: Cu <= 0.48 -> Mn <= 0.30 (0.5069)
Removida: Mn <= 0.30 -> sum Fe <= 0.39 (0.1367) | Mantida: sum Fe <= 0.39 -> Mn <= 0.30 (0.3621)
Removida: Rh L + Ar > -0.44 -> Mn <= 0.30 (0.1029) | Mantida: Mn <= 0.30 -> Rh L + Ar > -0.44 (0.2751)
Removida: sum Fe <= 0.39 -> Cu <= 0.48 (0.1392) | Mantida: Cu <= 0.48 -> sum Fe <= 0.39 (0.3718)
Removida: Cu <= 0.48 -> Rh L + Ar > -0.44 (0.1285) | Mantida: Rh L + Ar > -0.44 -> Cu <= 0.48 (0.2177)
Removida: Cu <= 0.48 -> Ca ka > -1.23 (0.1296) | Mantida: Ca ka > -1.23 -> Cu <= 0.48 (0.1543)
Removida: sum Fe <= 0.39 -> Ca ka <= 1.70 (0.1270) | Mantida: Ca ka <= 1.70 -> sum Fe <= 0.39 (0.2881)
Removida: Ca ka <= 1.70 -> Ca ka > -1.23 (0.1275) | Mantida: Ca ka > -1.23 -> Ca ka <= 1.70 (0.1451)
Removida: Ca ka <= 1.70 -> Rh L + Ar > -0.44 (0.1417) | Mantida: Rh L + Ar > -0.44 -> Ca ka <= 1.70 (0.1964)
Removida: Rh L + Ar > -0.44 -> sum Fe <= 0.39 (0.3058) | Mantida: sum Fe <= 0.39 -> Rh L + Ar > -0.44 (0.5189)
Removida: background1 > -0.46 -> Cr > -0.21 (0.0693) | Mantida: Cr > -0.21 -> background1 > -0.46 (0.2775)
Removida: Al > -0.53 -> background1 > -0.46 (0.0986) | Mantida: background1 > -0.46 -> Al > -0.53 (0.1352)
Removida: background1 > -0.46 -> Ca ka > -0.35 (0.0654) | Mantida: Ca ka > -0.35 -> background1 > -0.46 (0.1111)
Removida: background1 > -0.46 -> Ti ka <= -0.55 (0.0716) | Mantida: Ti ka <= -0.55 -> background1 > -0.46 (0.0993)
Removida: Ca ka > -1.23 -> Cr > -0.21 (0.1289) | Mantida: Cr > -0.21 -> Ca ka > -1.23 (0.1986)
Removida: Al > -0.53 -> Al > -0.20 (0.1988) | Mantida: Al > -0.20 -> Al > -0.53 (0.3746)
Removida: Ti ka <= -0.55 -> Al > -0.20 (0.0980) | Mantida: Al > -0.20 -> Ti ka <= -0.55 (0.1019)
Removida: Ca kb <= 0.45 -> Ti ka <= -0.55 (0.1368) | Mantida: Ti ka <= -0.55 -> Ca kb <= 0.45 (0.1689)
Removida: background1 > -0.15 -> Ti ka <= -0.55 (0.0556) | Mantida: Ti ka <= -0.55 -> background1 > -0.15 (0.0752)
Removida: Rh L + Ar <= 0.33 -> Ca kb <= 0.45 (0.1525) | Mantida: Ca kb <= 0.45 -> Rh L + Ar <= 0.33 (0.2174)
Removida: background1 > -0.15 -> Ca kb <= 0.45 (0.1176) | Mantida: Ca kb <= 0.45 -> background1 > -0.15 (0.2835)
Removida: background1 > -0.15 -> Rh L + Ar <= 0.33 (0.0539) | Mantida: Rh L + Ar <= 0.33 -> background1 > -0.15 (0.2114)
Removida: background2 > -0.34 -> Al > 0.14 (0.0411) | Mantida: Al > 0.14 -> background2 > -0.34 (0.0716)
Removida: background2 > -0.34 -> Ti kb > 0.24 (0.0405) | Mantida: Ti kb > 0.24 -> background2 > -0.34 (0.2260)
Removida: background2 > -0.34 -> Ca kb > -0.51 (0.0839) | Mantida: Ca kb > -0.51 -> background2 > -0.34 (0.1241)
Removida: Ti kb > 0.24 -> Cu > -0.21 (0.0695) | Mantida: Cu > -0.21 -> Ti kb > 0.24 (0.2088)
Removida: Al > 0.14 -> Cu > -0.21 (0.0712) | Mantida: Cu > -0.21 -> Al > 0.14 (0.2670)
Removida: Cu > -0.21 -> Ca kb > -0.51 (0.0666) | Mantida: Ca kb > -0.51 -> Cu > -0.21 (0.1258)
Removida: Cr <= 0.18 -> Ti kb > 0.24 (0.0556) | Mantida: Ti kb > 0.24 -> Cr <= 0.18 (0.0715)
Removida: background1 <= 0.48 -> Ti kb > 0.24 (0.0421) | Mantida: Ti kb > 0.24 -> background1 <= 0.48 (0.1302)
Removida: Cr <= 0.18 -> Ca kb > -0.51 (0.0625) | Mantida: Ca kb > -0.51 -> Cr <= 0.18 (0.1094)
Removida: Ca kb <= 0.02 -> Cr <= 0.18 (0.0505) | Mantida: Cr <= 0.18 -> Ca kb <= 0.02 (0.1107)
Removida: background1 <= 0.48 -> Cr <= 0.18 (0.0406) | Mantida: Cr <= 0.18 -> background1 <= 0.48 (0.0592)
Removida: Ca kb > -0.51 -> Al > 0.14 (0.1126) | Mantida: Al > 0.14 -> Ca kb > -0.51 (0.1364)
Removida: Ti kb <= 0.24 -> Al > 0.14 (0.0636) | Mantida: Al > 0.14 -> Ti kb <= 0.24 (0.1327)
Removida: background2 > -0.12 -> Ca kb <= 0.02 (0.0330) | Mantida: Ca kb <= 0.02 -> background2 > -0.12 (0.0966)
Removida: Ca kb <= 0.02 -> background1 <= 0.48 (0.0463) | Mantida: background1 <= 0.48 -> Ca kb <= 0.02 (0.1711)
Removida: background1 <= 0.48 -> background2 > -0.12 (0.0412) | Mantida: background2 > -0.12 -> background1 <= 0.48 (0.1007)
Removida: background2 > -0.12 -> Ti ka <= 0.61 (0.0323) | Mantida: Ti ka <= 0.61 -> background2 > -0.12 (0.0526)
Removida: Cu <= 0.18 -> background2 > -0.12 (0.0510) | Mantida: background2 > -0.12 -> Cu <= 0.18 (0.0612)
Removida: Cu <= 0.18 -> Ti ka <= 0.61 (0.0500) | Mantida: Ti ka <= 0.61 -> Cu <= 0.18 (0.0536)
Removida: Ti ka <= 0.61 -> P > -0.32 (0.0498) | Mantida: P > -0.32 -> Ti ka <= 0.61 (0.0603)
Removida: P > -0.32 -> Cu <= 0.18 (0.0315) | Mantida: Cu <= 0.18 -> P > -0.32 (0.0511)
Removida: Zn > -0.31 -> Ti kb <= -0.36 (0.0324) | Mantida: Ti kb <= -0.36 -> Zn > -0.31 (0.0484)
Removida: Zn > -0.08 -> Ti kb <= -0.36 (0.0301) | Mantida: Ti kb <= -0.36 -> Zn > -0.08 (0.0437)
Removida: Ti kb <= -0.36 -> Si <= 0.21 (0.0522) | Mantida: Si <= 0.21 -> Ti kb <= -0.36 (0.0547)
Removida: P > -0.32 -> Ti kb <= -0.36 (0.0318) | Mantida: Ti kb <= -0.36 -> P > -0.32 (0.0502)
Removida: background2 > 0.08 -> Ti kb <= -0.36 (0.0231) | Mantida: Ti kb <= -0.36 -> background2 > 0.08 (0.0433)
Removida: Zn > -0.31 -> background1 > 0.08 (0.0596) | Mantida: background1 > 0.08 -> Zn > -0.31 (0.0635)
Removida: Zn > -0.31 -> P > -0.32 (0.0604) | Mantida: P > -0.32 -> Zn > -0.31 (0.1060)
Removida: background2 <= 0.35 -> Zn > -0.31 (0.0491) | Mantida: Zn > -0.31 -> background2 <= 0.35 (0.0931)
Removida: P > -0.16 -> background1 > 0.08 (0.0269) | Mantida: background1 > 0.08 -> P > -0.16 (0.0286)
Removida: background1 > 0.08 -> Zn > -0.08 (0.0274) | Mantida: Zn > -0.08 -> background1 > 0.08 (0.0280)
Removida: background2 > 0.08 -> background1 > 0.08 (0.0226) | Mantida: background1 > 0.08 -> background2 > 0.08 (0.0275)
Removida: background2 <= 0.35 -> background1 > 0.08 (0.0228) | Mantida: background1 > 0.08 -> background2 <= 0.35 (0.0295)
Removida: P > -0.32 -> background2 <= 0.35 (0.0306) | Mantida: background2 <= 0.35 -> P > -0.32 (0.0511)
Removida: Zn > -0.08 -> background2 <= 0.35 (0.0278) | Mantida: background2 <= 0.35 -> Zn > -0.08 (0.0496)
Removida: P > -0.16 -> Zn > -0.08 (0.0321) | Mantida: Zn > -0.08 -> P > -0.16 (0.0554)
Removida: background2 > 0.08 -> P > -0.16 (0.0426) | Mantida: P > -0.16 -> background2 > 0.08 (0.0542)
Removida: background2 > 0.08 -> K > -0.35 (0.0202) | Mantida: K > -0.35 -> background2 > 0.08 (0.0377)
Removida: Zn > 0.10 -> P > -0.16 (0.0241) | Mantida: P > -0.16 -> Zn > 0.10 (0.0248)
Removida: Ca kb <= -0.25 -> Ca ka <= -0.35 (0.0217) | Mantida: Ca ka <= -0.35 -> Ca kb <= -0.25 (0.0301)
Removida: Zn > 0.10 -> Ca ka <= -0.35 (0.0202) | Mantida: Ca ka <= -0.35 -> Zn > 0.10 (0.0397)
Removida: Zn > 0.10 -> Ni > -0.28 (0.0239) | Mantida: Ni > -0.28 -> Zn > 0.10 (0.0684)
Removida: Ca kb > -0.25 -> Ni > -0.28 (0.0283) | Mantida: Ni > -0.28 -> Ca kb > -0.25 (0.0420)
Removida: P > 0.02 -> Ni > -0.06 (0.0213) | Mantida: Ni > -0.06 -> P > 0.02 (0.0634)
Removida: P <= 0.30 -> Ni > -0.06 (0.0192) | Mantida: Ni > -0.06 -> P <= 0.30 (0.0204)
Removida: P <= 0.30 -> K > -0.35 (0.0213) | Mantida: K > -0.35 -> P <= 0.30 (0.0683)
Removida: Cr <= -0.21 -> K > -0.35 (0.0268) | Mantida: K > -0.35 -> Cr <= -0.21 (0.0304)
Removida: Ca kb <= -0.25 -> P <= 0.30 (0.0251) | Mantida: P <= 0.30 -> Ca kb <= -0.25 (0.0413)
Removida: P <= 0.30 -> P > 0.02 (0.0422) | Mantida: P > 0.02 -> P <= 0.30 (0.0643)
Removida: P <= 0.30 -> Ni > 0.09 (0.0207) | Mantida: Ni > 0.09 -> P <= 0.30 (0.0357)
Removida: Ca kb <= -0.25 -> Ca kb > -0.25 (0.0220) | Mantida: Ca kb > -0.25 -> Ca kb <= -0.25 (0.0254)
Removida: Ni > 0.09 -> Cr <= -0.21 (0.0165) | Mantida: Cr <= -0.21 -> Ni > 0.09 (0.0229)
Removida: K > -0.01 -> Cr <= -0.21 (0.0255) | Mantida: Cr <= -0.21 -> K > -0.01 (0.0470)
Removida: Ni > 0.09 -> Si > 0.21 (0.0155) | Mantida: Si > 0.21 -> Ni > 0.09 (0.0267)
Removida: Ni > 0.09 -> K > -0.01 (0.0154) | Mantida: K > -0.01 -> Ni > 0.09 (0.0303)
Removida: background2 <= 0.08 -> Ni > 0.09 (0.0287) | Mantida: Ni > 0.09 -> background2 <= 0.08 (0.0460)
Removida: Si > 0.21 -> K <= 0.22 (0.0121) | Mantida: K <= 0.22 -> Si > 0.21 (0.0132)
Removida: Si > 0.21 -> Al <= 0.14 (0.0215) | Mantida: Al <= 0.14 -> Si > 0.21 (0.0251)
Removida: K > -0.01 -> Si > 0.21 (0.0215) | Mantida: Si > 0.21 -> K > -0.01 (0.0267)
Removida: background1 <= 0.08 -> P <= 0.02 (0.0276) | Mantida: P <= 0.02 -> background1 <= 0.08 (0.0323)
Removida: P <= 0.02 -> K > -0.01 (0.0148) | Mantida: K > -0.01 -> P <= 0.02 (0.0246)
Removida: K > -0.19 -> K > -0.01 (0.0201) | Mantida: K > -0.01 -> K > -0.19 (0.0239)
Removida: background1 <= 0.08 -> Fe ka + Ti ka <= 0.26 (0.0280) | Mantida: Fe ka + Ti ka <= 0.26 -> background1 <= 0.08 (0.0380)
Removida: Fe ka + Ti ka <= 0.11 -> Fe ka + Ti ka <= 0.26 (0.0133) | Mantida: Fe ka + Ti ka <= 0.26 -> Fe ka + Ti ka <= 0.11 (0.0372)
Removida: Fe ka + Ti ka <= 0.11 -> background1 <= 0.08 (0.0122) | Mantida: background1 <= 0.08 -> Fe ka + Ti ka <= 0.11 (0.0123)
Removida: Ca kb > -0.25 -> background1 <= 0.08 (0.0127) | Mantida: background1 <= 0.08 -> Ca kb > -0.25 (0.0151)
Removida: Fe ka + Ti ka <= 0.11 -> Al <= 0.14 (0.0109) | Mantida: Al <= 0.14 -> Fe ka + Ti ka <= 0.11 (0.0178)
Removida: S <= 0.16 -> Si <= -0.46 (0.0059) | Mantida: Si <= -0.46 -> S <= 0.16 (0.0445)
Removida: S <= 0.04 -> Si <= -0.46 (0.0063) | Mantida: Si <= -0.46 -> S <= 0.04 (0.0155)
Removida: S <= 0.16 -> Cr > 0.18 (0.0134) | Mantida: Cr > 0.18 -> S <= 0.16 (0.0367)
Removida: S <= 0.16 -> S <= 0.04 (0.0065) | Mantida: S <= 0.04 -> S <= 0.16 (0.0124)
Removida: S <= 0.16 -> Fe ka + Ti ka <= -0.06 (0.0062) | Mantida: Fe ka + Ti ka <= -0.06 -> S <= 0.16 (0.0068)
Removida: S <= 0.04 -> Fe ka + Ti ka <= -0.06 (0.0065) | Mantida: Fe ka + Ti ka <= -0.06 -> S <= 0.04 (0.0095)
Removida: Fe ka + Ti ka <= -0.06 -> Ca kb > 0.02 (0.0073) | Mantida: Ca kb > 0.02 -> Fe ka + Ti ka <= -0.06 (0.0096)
Removida: Fe ka + Ti ka <= -0.06 -> K <= 0.22 (0.0090) | Mantida: K <= 0.22 -> Fe ka + Ti ka <= -0.06 (0.0347)
Removida: S <= 0.04 -> P <= -0.16 (0.0066) | Mantida: P <= -0.16 -> S <= 0.04 (0.0187)
Removida: P <= -0.16 -> K <= 0.22 (0.0113) | Mantida: K <= 0.22 -> P <= -0.16 (0.0172)
Removida: P <= -0.16 -> Ca ka <= -1.23 (0.0095) | Mantida: Ca ka <= -1.23 -> P <= -0.16 (0.0311)
Removida: S <= 0.04 -> K <= 0.22 (0.0063) | Mantida: K <= 0.22 -> S <= 0.04 (0.0171)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 585 | Removidas: 124
Nós predicados: 102
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 107
Removida: Fe ka <= 11.65 -> Fe ka > -9.83 (3.3219) | Mantida: Fe ka > -9.83 -> Fe ka <= 11.65 (31.1907)
Removida: Fe kb > -3.67 -> Fe ka <= 4.25 (2.5797) | Mantida: Fe ka <= 4.25 -> Fe kb > -3.67 (9.4078)
Removida: Fe kb <= 4.31 -> Fe kb > -3.67 (1.2181) | Mantida: Fe kb > -3.67 -> Fe kb <= 4.31 (8.7864)
Removida: Ti ka > -1.99 -> Mn <= 1.02 (0.6068) | Mantida: Mn <= 1.02 -> Ti ka > -1.99 (2.3519)
Removida: Si > -1.03 -> Ti ka > -1.99 (0.2670) | Mantida: Ti ka > -1.99 -> Si > -1.03 (0.5481)
Removida: Rh L + Ar > -0.69 -> Ti kb > -1.01 (0.3910) | Mantida: Ti kb > -1.01 -> Rh L + Ar > -0.69 (1.2149)
Removida: Ti ka > -0.55 -> Ti kb > -1.01 (0.4866) | Mantida: Ti kb > -1.01 -> Ti ka > -0.55 (0.7063)
Removida: Ti kb > -1.01 -> Si > -1.03 (0.2378) | Mantida: Si > -1.03 -> Ti kb > -1.01 (0.5343)
Removida: Rh L + Ar <= 0.76 -> Ti kb > -1.01 (0.1872) | Mantida: Ti kb > -1.01 -> Rh L + Ar <= 0.76 (0.2215)
Removida: Si > -1.03 -> Rh L + Ar > -0.69 (0.2584) | Mantida: Rh L + Ar > -0.69 -> Si > -1.03 (0.6016)
Removida: Rh L + Ar > -0.69 -> Ti ka > -0.55 (0.1970) | Mantida: Ti ka > -0.55 -> Rh L + Ar > -0.69 (0.2386)
Removida: Ti ka > -0.55 -> Si > -1.03 (0.4294) | Mantida: Si > -1.03 -> Ti ka > -0.55 (0.5436)
Removida: Rh L + Ar <= 0.76 -> Ti ka > -0.55 (0.3660) | Mantida: Ti ka > -0.55 -> Rh L + Ar <= 0.76 (0.4394)
Removida: Mn > -0.74 -> Ti ka > -0.55 (0.2232) | Mantida: Ti ka > -0.55 -> Mn > -0.74 (0.4219)
Removida: Ti ka > 0.61 -> Rh L + Ar <= 0.76 (0.2165) | Mantida: Rh L + Ar <= 0.76 -> Ti ka > 0.61 (0.7308)
Removida: Rh L + Ar <= 0.76 -> Ca ka > -1.89 (0.1807) | Mantida: Ca ka > -1.89 -> Rh L + Ar <= 0.76 (0.2479)
Removida: Ti ka > 0.61 -> sum Fe > -0.60 (0.3907) | Mantida: sum Fe > -0.60 -> Ti ka > 0.61 (0.6008)
Removida: Ca ka > -1.89 -> Ti ka > 0.61 (0.2236) | Mantida: Ti ka > 0.61 -> Ca ka > -1.89 (0.3733)
Removida: Ca ka > -1.89 -> Mn > -0.74 (0.2373) | Mantida: Mn > -0.74 -> Ca ka > -1.89 (0.4717)
Removida: Ti kb > -0.36 -> sum Fe > -0.60 (0.1932) | Mantida: sum Fe > -0.60 -> Ti kb > -0.36 (0.2062)
Removida: Ti kb > -0.36 -> Ca ka > -1.89 (0.1771) | Mantida: Ca ka > -1.89 -> Ti kb > -0.36 (1.0725)
Removida: Ti kb > -0.36 -> Ti kb <= 1.01 (0.1789) | Mantida: Ti kb <= 1.01 -> Ti kb > -0.36 (0.1812)
Removida: Cr > -0.67 -> Ca ka > -1.23 (0.1692) | Mantida: Ca ka > -1.23 -> Cr > -0.67 (0.1979)
Removida: Ti kb <= 1.01 -> Cr > -0.67 (0.1781) | Mantida: Cr > -0.67 -> Ti kb <= 1.01 (0.3315)
Removida: Ti kb <= 1.01 -> Cr <= 0.70 (0.5223) | Mantida: Cr <= 0.70 -> Ti kb <= 1.01 (0.6446)
Removida: Si > -0.46 -> Cr <= 0.70 (0.1862) | Mantida: Cr <= 0.70 -> Si > -0.46 (0.3162)
Removida: Si <= 1.00 -> Si > -0.46 (0.5159) | Mantida: Si > -0.46 -> Si <= 1.00 (0.6900)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -9.83,Fe ka > -9.83,Fe ka > -9.83,Fe ka > -9.83
1,Fe ka <= 11.65,Fe ka <= 11.65,Fe ka <= 11.65,Fe ka <= 11.65
2,Fe ka <= 4.25,Fe ka > -5.77,Fe ka > -5.77,Fe ka > -5.77
3,Fe ka > -5.77,Fe ka <= 4.25,Fe ka <= 4.25,Fe ka <= 4.25
4,Fe kb > -3.67,Fe kb > -3.67,Fe kb > -3.67,Fe kb > -3.67
...,...,...,...,...
105,NaN,Zn <= -0.08,Class_A,NaN
106,NaN,Ni <= -0.06,Class_B,NaN
107,NaN,S <= -0.07,NaN,NaN
108,NaN,Class_A,NaN,NaN
109,NaN,Class_B,NaN,NaN

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -9.83,20.420307,Fe ka,-9.83,>
1,Fe kb > -3.67,8.444839,Fe kb,-3.67,>
2,Mn > -1.21,3.888434,Mn,-1.21,>
3,sum Fe > -1.11,3.184910,sum Fe,-1.11,>
4,Ti ka > -1.99,0.992262,Ti ka,-1.99,>
5,Rh L + Ar <= 0.76,0.980888,Rh L + Ar,0.76,<=
6,Ti kb > -1.01,0.928389,Ti kb,-1.01,>
7,Ca ka > -1.89,0.883664,Ca ka,-1.89,>
8,Si <= 1.00,0.856164,Si,1.00,<=
9,Cr <= 0.70,0.764329,Cr,0.70,<=
10,Cu > -0.46,0.632451,Cu,-0.46,>
11,Al > -0.20,0.441450,Al,-0.20,>
12,background1 > -0.46,0.395442,background1,-0.46,>
13,Ca kb <= 0.45,0.353474,Ca kb,0.45,<=
14,background2 > -0.34,0.319540,background2,-0.34,>
15,K > -0.19,0.223039,K,-0.19,>
16,Zn > -0.31,0.222258,Zn,-0.31,>
17,P > -0.32,0.222007,P,-0.32,>
18,Ni > -0.28,0.206454,Ni,-0.28,>
19,Fe ka + Ti ka <= 0.26,0.194064,Fe ka + Ti ka,0.26,<=
20,S <= 0.16,0.146058,S,0.16,<=
21,Class_A,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Al': VE = 94.39%, dim = 15 variáveis
Zona 'Si': VE = 97.95%, dim = 12 variáveis
Zona 'P': VE = 63.93%, dim = 17 variáveis
Zona 'S': VE = 50.04%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 82.78%, dim = 33 variáveis
Zona 'K': VE = 97.13%, dim = 16 variáveis
Zona 'Ca ka': VE = 99.41%, dim = 16 variáveis
Zona 'Ca kb': VE = 73.60%, dim = 27 variáveis
Zona 'Ti ka': VE = 92.52%, dim = 19 variáveis
Zona 'Ti kb': VE = 91.98%, dim = 19 variáveis
Zona 'Cr': VE = 83.92%, dim = 33 variáveis
Zona 'Mn': VE = 95.74%, dim = 18 variáveis
Zona 'Fe ka': VE = 94.87%, dim = 34 variáveis
Zona 'Fe kb': VE = 94.17%, dim = 26 variáveis
Zona 'Ni': VE = 58.62%, dim = 31 variáveis
Zona 'Cu': VE = 85.47%, dim = 15 variáveis
Zona 'Zn': VE = 60.21%, dim = 41 variáveis
Zona 'background1': VE = 61.93%, dim = 85 variáveis
Zona 'Fe ka + Ti ka': VE = 58.87%, dim = 23 variáveis
Zona 'background2': VE = 51.14%, dim = 71 variáveis
Zona 'sum Fe': VE = 94.31%, dim = 28 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > -9.83,20.420307,Fe ka,-9.83,>,-178.952975,247.0,0.001731,Fe ka > -178.952975
1,Fe ka <= 11.65,15.678693,Fe ka,11.65,<=,188.786502,94.0,0.001158,Fe ka <= 188.786502
2,Fe ka > -5.77,10.387961,Fe ka,-5.77,>,-103.046579,408.0,0.004763,Fe ka > -103.046579
3,Fe ka <= 4.25,9.511881,Fe ka,4.25,<=,87.045387,38.0,0.001079,Fe ka <= 87.045387
4,Fe kb > -3.67,8.444839,Fe kb,-3.67,>,-25.194168,311.0,0.001842,Fe kb > -25.194168
...,...,...,...,...,...,...,...,...,...
106,S > 0.04,0.000232,S,0.04,>,0.036958,195.0,0.000109,S > 0.036958
107,Ni <= -0.06,0.000217,Ni,-0.06,<=,-0.094370,282.0,0.000178,Ni <= -0.094370
108,Zn <= -0.08,0.000151,Zn,-0.08,<=,-0.077538,384.0,0.000025,Zn <= -0.077538
109,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
110,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Range de energias: 6.14 - 6.8
  - Variância explicada pela PC1: 94.87%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 126 predicados...
  Predicado: Al > -0.53 (n=318)
    Zona: 15 colunas
    Importance: 0.000219
  Predicado: Al <= -0.20 (n=156)
    Zona: 15 colunas
    Importance: 0.000498
  Predicado: Al > -0.20 (n=244)
    Zona: 15 colunas
    Importance: 0.000250
  Predicado: Al <= 0.14 (n=237)
    Zona: 15 colunas
    Importance: 0.000378
  Predicado: Al > 0.14 (n=163)
    Zona: 15 colunas
    Importance: 0.000301
  Predicado: Al <= 0.58 (n=317)
    Zona: 15 colunas
    Importance: 0.000343
  Predicado: Si > -1.03 (n=320)
    Zona: 12 colunas
    Importance: 0.000749
  Predicado: Si <= -0.46 (n=158)
    Zona: 12 colunas
    Importance: 0.000162
  Predicado: Si > -0.46 (n=242)
    Zona: 12 colunas
    Importance: 0.000975
  Predicado: Si <= 0.21 (n=239)
    Zona: 12 colunas
    Importance: 0.000113
  Predicado: Si > 0.21 (n=161)
    Zona: 12 colunas
    Importance: 0.001456
  Predicado: Si <= 1.00 (n=322)
    Zona: 12 colunas
    Importance: 0.000163
  Predicado: P > -0.32 (n=313)
    Zona: 17 colunas
    Importance: 0.000084
  Predicado: P <= -0.16 (n=164)
    Zona: 17 colunas
    Importance: 0.000104
  Predicado: P > -0.16 (n=236)
    Zona: 17 colunas
    Importance: 0.000097
  Predicado: P <= 0.02 (n=248)
    Zona: 17 colunas
    Importance: 0.000090
  Predicado: P > 0.02 (n=152)
    Zona: 17 colunas
    Importance: 0.000117
  Predicado: P <= 0.30 (n=318)
    Zona: 17 colunas
    Importance: 0.000084
  Predicado: S > -0.16 (n=312)
    Zona: 18 colunas
    Importance: 0.000022
  Predicado: S <= -0.07 (n=159)
    Zona: 18 colunas
    Importance: 0.000018
  Predicado: S > -0.07 (n=241)
    Zona: 18 colunas
    Importance: 0.000026
  Predicado: S <= 0.04 (n=241)
    Zona: 18 colunas
    Importance: 0.000021
  Predicado: S > 0.04 (n=159)
    Zona: 18 colunas
    Importance: 0.000026
  Predicado: S <= 0.16 (n=323)
    Zona: 18 colunas
    Importance: 0.000025
  Predicado: Rh L + Ar > -0.69 (n=321)
    Zona: 33 colunas
    Importance: 0.000391
  Predicado: Rh L + Ar <= -0.44 (n=157)
    Zona: 33 colunas
    Importance: 0.000213
  Predicado: Rh L + Ar > -0.44 (n=243)
    Zona: 33 colunas
    Importance: 0.000463
  Predicado: Rh L + Ar <= 0.33 (n=235)
    Zona: 33 colunas
    Importance: 0.000392
  Predicado: Rh L + Ar > 0.33 (n=165)
    Zona: 33 colunas
    Importance: 0.000327
  Predicado: Rh L + Ar <= 0.76 (n=320)
    Zona: 33 colunas
    Importance: 0.000395
  Predicado: K > -0.35 (n=322)
    Zona: 16 colunas
    Importance: 0.001227
  Predicado: K <= -0.19 (n=162)
    Zona: 16 colunas
    Importance: 0.000013
  Predicado: K > -0.19 (n=238)
    Zona: 16 colunas
    Importance: 0.001656
  Predicado: K <= -0.01 (n=243)
    Zona: 16 colunas
    Importance: 0.000013
  Predicado: K > -0.01 (n=157)
    Zona: 16 colunas
    Importance: 0.002504
  Predicado: K <= 0.22 (n=317)
    Zona: 16 colunas
    Importance: 0.000017
  Predicado: Ca ka > -1.89 (n=317)
    Zona: 16 colunas
    Importance: 0.001846
  Predicado: Ca ka <= -1.23 (n=163)
    Zona: 16 colunas
    Importance: 0.000547
  Predicado: Ca ka > -1.23 (n=237)
    Zona: 16 colunas
    Importance: 0.002330
  Predicado: Ca ka <= -0.35 (n=243)
    Zona: 16 colunas
    Importance: 0.000433
  Predicado: Ca ka > -0.35 (n=157)
    Zona: 16 colunas
    Importance: 0.003415
  Predicado: Ca ka <= 1.70 (n=323)
    Zona: 16 colunas
    Importance: 0.000553
  Predicado: Ca kb > -0.51 (n=321)
    Zona: 27 colunas
    Importance: 0.000123
  Predicado: Ca kb <= -0.25 (n=159)
    Zona: 27 colunas
    Importance: 0.000058
  Predicado: Ca kb > -0.25 (n=241)
    Zona: 27 colunas
    Importance: 0.000136
  Predicado: Ca kb <= 0.02 (n=238)
    Zona: 27 colunas
    Importance: 0.000046
  Predicado: Ca kb > 0.02 (n=162)
    Zona: 27 colunas
    Importance: 0.000191
  Predicado: Ca kb <= 0.45 (n=322)
    Zona: 27 colunas
    Importance: 0.000051
  Predicado: Ti ka > -1.99 (n=316)
    Zona: 19 colunas
    Importance: 0.003153
  Predicado: Ti ka <= -0.55 (n=161)
    Zona: 19 colunas
    Importance: 0.007452
  Predicado: Ti ka > -0.55 (n=239)
    Zona: 19 colunas
    Importance: 0.003807
  Predicado: Ti ka <= 0.61 (n=238)
    Zona: 19 colunas
    Importance: 0.005223
  Predicado: Ti ka > 0.61 (n=162)
    Zona: 19 colunas
    Importance: 0.005349
  Predicado: Ti ka <= 1.87 (n=320)
    Zona: 19 colunas
    Importance: 0.004822
  Predicado: Ti kb > -1.01 (n=319)
    Zona: 19 colunas
    Importance: 0.000233
  Predicado: Ti kb <= -0.36 (n=160)
    Zona: 19 colunas
    Importance: 0.000357
  Predicado: Ti kb > -0.36 (n=240)
    Zona: 19 colunas
    Importance: 0.000172
  Predicado: Ti kb <= 0.24 (n=240)
    Zona: 19 colunas
    Importance: 0.000281
  Predicado: Ti kb > 0.24 (n=160)
    Zona: 19 colunas
    Importance: 0.000195
  Predicado: Ti kb <= 1.01 (n=318)
    Zona: 19 colunas
    Importance: 0.000273
  Predicado: Cr > -0.67 (n=323)
    Zona: 33 colunas
    Importance: 0.000187
  Predicado: Cr <= -0.21 (n=159)
    Zona: 33 colunas
    Importance: 0.000330
  Predicado: Cr > -0.21 (n=241)
    Zona: 33 colunas
    Importance: 0.000147
  Predicado: Cr <= 0.18 (n=241)
    Zona: 33 colunas
    Importance: 0.000290
  Predicado: Cr > 0.18 (n=159)
    Zona: 33 colunas
    Importance: 0.000113
  Predicado: Cr <= 0.70 (n=318)
    Zona: 33 colunas
    Importance: 0.000257
  Predicado: Mn > -1.21 (n=322)
    Zona: 18 colunas
    Importance: 0.000392
  Predicado: Mn <= -0.74 (n=159)
    Zona: 18 colunas
    Importance: 0.000349
  Predicado: Mn > -0.74 (n=241)
    Zona: 18 colunas
    Importance: 0.000454
  Predicado: Mn <= 0.30 (n=242)
    Zona: 18 colunas
    Importance: 0.000351
  Predicado: Mn > 0.30 (n=158)
    Zona: 18 colunas
    Importance: 0.000505
  Predicado: Mn <= 1.02 (n=319)
    Zona: 18 colunas
    Importance: 0.000329
  Predicado: Fe ka > -9.83 (n=321)
    Zona: 34 colunas
    Importance: 0.271674
  Predicado: Fe ka <= -5.77 (n=158)
    Zona: 34 colunas
    Importance: 0.288999
  Predicado: Fe ka > -5.77 (n=242)
    Zona: 34 colunas
    Importance: 0.327683
  Predicado: Fe ka <= 4.25 (n=239)
    Zona: 34 colunas
    Importance: 0.217311
  Predicado: Fe ka > 4.25 (n=161)
    Zona: 34 colunas
    Importance: 0.453564
  Predicado: Fe ka <= 11.65 (n=316)
    Zona: 34 colunas
    Importance: 0.251057
  Predicado: Fe kb > -3.67 (n=322)
    Zona: 26 colunas
    Importance: 0.002597
  Predicado: Fe kb <= -2.08 (n=160)
    Zona: 26 colunas
    Importance: 0.003232
  Predicado: Fe kb > -2.08 (n=240)
    Zona: 26 colunas
    Importance: 0.002950
  Predicado: Fe kb <= 1.44 (n=240)
    Zona: 26 colunas
    Importance: 0.002667
  Predicado: Fe kb > 1.44 (n=160)
    Zona: 26 colunas
    Importance: 0.003655
  Predicado: Fe kb <= 4.31 (n=315)
    Zona: 26 colunas
    Importance: 0.002513
  Predicado: Ni > -0.28 (n=319)
    Zona: 31 colunas
    Importance: 0.000111
  Predicado: Ni <= -0.06 (n=163)
    Zona: 31 colunas
    Importance: 0.000173
  Predicado: Ni > -0.06 (n=237)
    Zona: 31 colunas
    Importance: 0.000130
  Predicado: Ni <= 0.09 (n=241)
    Zona: 31 colunas
    Importance: 0.000125
  Predicado: Ni > 0.09 (n=159)
    Zona: 31 colunas
    Importance: 0.000180
  Predicado: Ni <= 0.26 (n=320)
    Zona: 31 colunas
    Importance: 0.000105
  Predicado: Cu > -0.46 (n=323)
    Zona: 15 colunas
    Importance: 0.000190
  Predicado: Cu <= -0.21 (n=155)
    Zona: 15 colunas
    Importance: 0.000093
  Predicado: Cu > -0.21 (n=245)
    Zona: 15 colunas
    Importance: 0.000238
  Predicado: Cu <= 0.18 (n=238)
    Zona: 15 colunas
    Importance: 0.000088
  Predicado: Cu > 0.18 (n=162)
    Zona: 15 colunas
    Importance: 0.000320
  Predicado: Cu <= 0.48 (n=317)
    Zona: 15 colunas
    Importance: 0.000095
  Predicado: Zn > -0.31 (n=322)
    Zona: 41 colunas
    Importance: 0.000167
  Predicado: Zn <= -0.08 (n=166)
    Zona: 41 colunas
    Importance: 0.000227
  Predicado: Zn > -0.08 (n=234)
    Zona: 41 colunas
    Importance: 0.000207
  Predicado: Zn <= 0.10 (n=237)
    Zona: 41 colunas
    Importance: 0.000169
  Predicado: Zn > 0.10 (n=163)
    Zona: 41 colunas
    Importance: 0.000283
  Predicado: Zn <= 0.32 (n=324)
    Zona: 41 colunas
    Importance: 0.000139
  Predicado: background1 > -0.46 (n=313)
    Zona: 85 colunas
    Importance: 0.000491
  Predicado: background1 <= -0.15 (n=163)
    Zona: 85 colunas
    Importance: 0.000716
  Predicado: background1 > -0.15 (n=237)
    Zona: 85 colunas
    Importance: 0.000528
  Predicado: background1 <= 0.08 (n=240)
    Zona: 85 colunas
    Importance: 0.000504
  Predicado: background1 > 0.08 (n=160)
    Zona: 85 colunas
    Importance: 0.000756
  Predicado: background1 <= 0.48 (n=320)
    Zona: 85 colunas
    Importance: 0.000428
  Predicado: Fe ka + Ti ka > -0.25 (n=316)
    Zona: 23 colunas
    Importance: 0.000102
  Predicado: Fe ka + Ti ka <= -0.06 (n=159)
    Zona: 23 colunas
    Importance: 0.000189
  Predicado: Fe ka + Ti ka > -0.06 (n=241)
    Zona: 23 colunas
    Importance: 0.000089
  Predicado: Fe ka + Ti ka <= 0.11 (n=240)
    Zona: 23 colunas
    Importance: 0.000129
  Predicado: Fe ka + Ti ka > 0.11 (n=160)
    Zona: 23 colunas
    Importance: 0.000129
  Predicado: Fe ka + Ti ka <= 0.26 (n=320)
    Zona: 23 colunas
    Importance: 0.000107
  Predicado: background2 > -0.34 (n=314)
    Zona: 71 colunas
    Importance: 0.000296
  Predicado: background2 <= -0.12 (n=160)
    Zona: 71 colunas
    Importance: 0.000447
  Predicado: background2 > -0.12 (n=240)
    Zona: 71 colunas
    Importance: 0.000301
  Predicado: background2 <= 0.08 (n=242)
    Zona: 71 colunas
    Importance: 0.000303
  Predicado: background2 > 0.08 (n=158)
    Zona: 71 colunas
    Importance: 0.000445
  Predicado: background2 <= 0.35 (n=321)
    Zona: 71 colunas
    Importance: 0.000263
  Predicado: sum Fe > -1.11 (n=322)
    Zona: 28 colunas
    Importance: 0.000147
  Predicado: sum Fe <= -0.60 (n=155)
    Zona: 28 colunas
    Importance: 0.000109
  Predicado: sum Fe > -0.60 (n=245)
    Zona: 28 colunas
    Importance: 0.000178
  Predicado: sum Fe <= 0.39 (n=237)
    Zona: 28 colunas
    Importance: 0.000114
  Predicado: sum Fe > 0.39 (n=163)
    Zona: 28 colunas
    Importance: 0.000206
  Predicado: sum Fe <= 1.27 (n=315)
    Zona: 28 colunas
    Importance: 0.000109

[Bag_2] Processando 126 predicados...
  Predicado: Al > -0.53 (n=322)
    Zona: 15 colunas
    Importance: 0.000233
  Predicado: Al <= -0.20 (n=161)
    Zona: 15 colunas
    Importance: 0.000699
  Predicado: Al > -0.20 (n=239)
    Zona: 15 colunas
    Importance: 0.000260
  Predicado: Al <= 0.14 (n=242)
    Zona: 15 colunas
    Importance: 0.000485
  Predicado: Al > 0.14 (n=158)
    Zona: 15 colunas
    Importance: 0.000362
  Predicado: Al <= 0.58 (n=323)
    Zona: 15 colunas
    Importance: 0.000415
  Predicado: Si > -1.03 (n=324)
    Zona: 12 colunas
    Importance: 0.000763
  Predicado: Si <= -0.46 (n=159)
    Zona: 12 colunas
    Importance: 0.000181
  Predicado: Si > -0.46 (n=241)
    Zona: 12 colunas
    Importance: 0.000988
  Predicado: Si <= 0.21 (n=247)
    Zona: 12 colunas
    Importance: 0.000124
  Predicado: Si > 0.21 (n=153)
    Zona: 12 colunas
    Importance: 0.001543
  Predicado: Si <= 1.00 (n=326)
    Zona: 12 colunas
    Importance: 0.000147
  Predicado: P > -0.32 (n=318)
    Zona: 17 colunas
    Importance: 0.000099
  Predicado: P <= -0.16 (n=161)
    Zona: 17 colunas
    Importance: 0.000073
  Predicado: P > -0.16 (n=239)
    Zona: 17 colunas
    Importance: 0.000111
  Predicado: P <= 0.02 (n=243)
    Zona: 17 colunas
    Importance: 0.000070
  Predicado: P > 0.02 (n=157)
    Zona: 17 colunas
    Importance: 0.000136
  Predicado: P <= 0.30 (n=316)
    Zona: 17 colunas
    Importance: 0.000069
  Predicado: S > -0.16 (n=318)
    Zona: 18 colunas
    Importance: 0.000024
  Predicado: S <= -0.07 (n=160)
    Zona: 18 colunas
    Importance: 0.000006
  Predicado: S > -0.07 (n=240)
    Zona: 18 colunas
    Importance: 0.000030
  Predicado: S <= 0.04 (n=247)
    Zona: 18 colunas
    Importance: 0.000015
  Predicado: S > 0.04 (n=153)
    Zona: 18 colunas
    Importance: 0.000029
  Predicado: S <= 0.16 (n=326)
    Zona: 18 colunas
    Importance: 0.000022
  Predicado: Rh L + Ar > -0.69 (n=320)
    Zona: 33 colunas
    Importance: 0.000376
  Predicado: Rh L + Ar <= -0.44 (n=166)
    Zona: 33 colunas
    Importance: 0.000206
  Predicado: Rh L + Ar > -0.44 (n=234)
    Zona: 33 colunas
    Importance: 0.000440
  Predicado: Rh L + Ar <= 0.33 (n=242)
    Zona: 33 colunas
    Importance: 0.000350
  Predicado: Rh L + Ar > 0.33 (n=158)
    Zona: 33 colunas
    Importance: 0.000332
  Predicado: Rh L + Ar <= 0.76 (n=324)
    Zona: 33 colunas
    Importance: 0.000365
  Predicado: K > -0.35 (n=315)
    Zona: 16 colunas
    Importance: 0.001257
  Predicado: K <= -0.19 (n=169)
    Zona: 16 colunas
    Importance: 0.000015
  Predicado: K > -0.19 (n=231)
    Zona: 16 colunas
    Importance: 0.001710
  Predicado: K <= -0.01 (n=249)
    Zona: 16 colunas
    Importance: 0.000012
  Predicado: K > -0.01 (n=151)
    Zona: 16 colunas
    Importance: 0.002613
  Predicado: K <= 0.22 (n=320)
    Zona: 16 colunas
    Importance: 0.000021
  Predicado: Ca ka > -1.89 (n=315)
    Zona: 16 colunas
    Importance: 0.001963
  Predicado: Ca ka <= -1.23 (n=169)
    Zona: 16 colunas
    Importance: 0.000550
  Predicado: Ca ka > -1.23 (n=231)
    Zona: 16 colunas
    Importance: 0.002512
  Predicado: Ca ka <= -0.35 (n=249)
    Zona: 16 colunas
    Importance: 0.000406
  Predicado: Ca ka > -0.35 (n=151)
    Zona: 16 colunas
    Importance: 0.003790
  Predicado: Ca ka <= 1.70 (n=323)
    Zona: 16 colunas
    Importance: 0.000678
  Predicado: Ca kb > -0.51 (n=313)
    Zona: 27 colunas
    Importance: 0.000109
  Predicado: Ca kb <= -0.25 (n=162)
    Zona: 27 colunas
    Importance: 0.000044
  Predicado: Ca kb > -0.25 (n=238)
    Zona: 27 colunas
    Importance: 0.000125
  Predicado: Ca kb <= 0.02 (n=249)
    Zona: 27 colunas
    Importance: 0.000048
  Predicado: Ca kb > 0.02 (n=151)
    Zona: 27 colunas
    Importance: 0.000164
  Predicado: Ca kb <= 0.45 (n=324)
    Zona: 27 colunas
    Importance: 0.000058
  Predicado: Ti ka > -1.99 (n=320)
    Zona: 19 colunas
    Importance: 0.003650
  Predicado: Ti ka <= -0.55 (n=161)
    Zona: 19 colunas
    Importance: 0.006175
  Predicado: Ti ka > -0.55 (n=239)
    Zona: 19 colunas
    Importance: 0.003838
  Predicado: Ti ka <= 0.61 (n=244)
    Zona: 19 colunas
    Importance: 0.004282
  Predicado: Ti ka > 0.61 (n=156)
    Zona: 19 colunas
    Importance: 0.005556
  Predicado: Ti ka <= 1.87 (n=325)
    Zona: 19 colunas
    Importance: 0.004050
  Predicado: Ti kb > -1.01 (n=318)
    Zona: 19 colunas
    Importance: 0.000218
  Predicado: Ti kb <= -0.36 (n=163)
    Zona: 19 colunas
    Importance: 0.000295
  Predicado: Ti kb > -0.36 (n=237)
    Zona: 19 colunas
    Importance: 0.000201
  Predicado: Ti kb <= 0.24 (n=245)
    Zona: 19 colunas
    Importance: 0.000271
  Predicado: Ti kb > 0.24 (n=155)
    Zona: 19 colunas
    Importance: 0.000189
  Predicado: Ti kb <= 1.01 (n=323)
    Zona: 19 colunas
    Importance: 0.000265
  Predicado: Cr > -0.67 (n=319)
    Zona: 33 colunas
    Importance: 0.000175
  Predicado: Cr <= -0.21 (n=165)
    Zona: 33 colunas
    Importance: 0.000300
  Predicado: Cr > -0.21 (n=235)
    Zona: 33 colunas
    Importance: 0.000154
  Predicado: Cr <= 0.18 (n=240)
    Zona: 33 colunas
    Importance: 0.000277
  Predicado: Cr > 0.18 (n=160)
    Zona: 33 colunas
    Importance: 0.000120
  Predicado: Cr <= 0.70 (n=324)
    Zona: 33 colunas
    Importance: 0.000247
  Predicado: Mn > -1.21 (n=315)
    Zona: 18 colunas
    Importance: 0.000483
  Predicado: Mn <= -0.74 (n=166)
    Zona: 18 colunas
    Importance: 0.000342
  Predicado: Mn > -0.74 (n=234)
    Zona: 18 colunas
    Importance: 0.000571
  Predicado: Mn <= 0.30 (n=245)
    Zona: 18 colunas
    Importance: 0.000341
  Predicado: Mn > 0.30 (n=155)
    Zona: 18 colunas
    Importance: 0.000689
  Predicado: Mn <= 1.02 (n=325)
    Zona: 18 colunas
    Importance: 0.000349
  Predicado: Fe ka > -9.83 (n=317)
    Zona: 34 colunas
    Importance: 0.269286
  Predicado: Fe ka <= -5.77 (n=166)
    Zona: 34 colunas
    Importance: 0.282077
  Predicado: Fe ka > -5.77 (n=234)
    Zona: 34 colunas
    Importance: 0.327317
  Predicado: Fe ka <= 4.25 (n=243)
    Zona: 34 colunas
    Importance: 0.220567
  Predicado: Fe ka > 4.25 (n=157)
    Zona: 34 colunas
    Importance: 0.444708
  Predicado: Fe ka <= 11.65 (n=320)
    Zona: 34 colunas
    Importance: 0.249529
  Predicado: Fe kb > -3.67 (n=318)
    Zona: 26 colunas
    Importance: 0.002656
  Predicado: Fe kb <= -2.08 (n=165)
    Zona: 26 colunas
    Importance: 0.003143
  Predicado: Fe kb > -2.08 (n=235)
    Zona: 26 colunas
    Importance: 0.003058
  Predicado: Fe kb <= 1.44 (n=241)
    Zona: 26 colunas
    Importance: 0.002741
  Predicado: Fe kb > 1.44 (n=159)
    Zona: 26 colunas
    Importance: 0.003627
  Predicado: Fe kb <= 4.31 (n=321)
    Zona: 26 colunas
    Importance: 0.002542
  Predicado: Ni > -0.28 (n=326)
    Zona: 31 colunas
    Importance: 0.000121
  Predicado: Ni <= -0.06 (n=163)
    Zona: 31 colunas
    Importance: 0.000236
  Predicado: Ni > -0.06 (n=237)
    Zona: 31 colunas
    Importance: 0.000136
  Predicado: Ni <= 0.09 (n=244)
    Zona: 31 colunas
    Importance: 0.000160
  Predicado: Ni > 0.09 (n=156)
    Zona: 31 colunas
    Importance: 0.000204
  Predicado: Ni <= 0.26 (n=322)
    Zona: 31 colunas
    Importance: 0.000132
  Predicado: Cu > -0.46 (n=318)
    Zona: 15 colunas
    Importance: 0.000166
  Predicado: Cu <= -0.21 (n=165)
    Zona: 15 colunas
    Importance: 0.000093
  Predicado: Cu > -0.21 (n=235)
    Zona: 15 colunas
    Importance: 0.000208
  Predicado: Cu <= 0.18 (n=241)
    Zona: 15 colunas
    Importance: 0.000110
  Predicado: Cu > 0.18 (n=159)
    Zona: 15 colunas
    Importance: 0.000236
  Predicado: Cu <= 0.48 (n=321)
    Zona: 15 colunas
    Importance: 0.000111
  Predicado: Zn > -0.31 (n=326)
    Zona: 41 colunas
    Importance: 0.000193
  Predicado: Zn <= -0.08 (n=167)
    Zona: 41 colunas
    Importance: 0.000304
  Predicado: Zn > -0.08 (n=233)
    Zona: 41 colunas
    Importance: 0.000236
  Predicado: Zn <= 0.10 (n=243)
    Zona: 41 colunas
    Importance: 0.000212
  Predicado: Zn > 0.10 (n=157)
    Zona: 41 colunas
    Importance: 0.000344
  Predicado: Zn <= 0.32 (n=326)
    Zona: 41 colunas
    Importance: 0.000176
  Predicado: background1 > -0.46 (n=317)
    Zona: 85 colunas
    Importance: 0.000477
  Predicado: background1 <= -0.15 (n=158)
    Zona: 85 colunas
    Importance: 0.000828
  Predicado: background1 > -0.15 (n=242)
    Zona: 85 colunas
    Importance: 0.000571
  Predicado: background1 <= 0.08 (n=244)
    Zona: 85 colunas
    Importance: 0.000554

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Fe ka > 4.25,Fe ka > 4.25,Fe ka > 4.25,Fe ka > 4.25
1,Fe ka > -5.77,Fe ka > -5.77,Fe ka > -5.77,Fe ka > -5.77
2,Fe ka <= -5.77,Fe ka <= -5.77,Fe ka <= -5.77,Fe ka <= -5.77
3,Fe ka > -9.83,Fe ka > -9.83,Fe ka > -9.83,Fe ka > -9.83
4,Fe ka <= 11.65,Fe ka <= 11.65,Fe ka <= 11.65,Fe ka <= 11.65
...,...,...,...,...
123,S > 0.04,S <= -0.07,S > -0.16,S <= -0.07
124,S <= 0.04,K <= -0.19,K <= -0.19,S > -0.16
125,S <= -0.07,K <= -0.01,S <= -0.07,S <= 0.04
126,Class_A,Class_A,Class_A,Class_A
127,Class_B,Class_B,Class_B,Class_B

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

          Predicate  Perturbation
0      Fe ka > 4.25      0.453564
1     Fe ka > -5.77      0.327683
2    Fe ka <= -5.77      0.288999
3     Fe ka > -9.83      0.271674
4    Fe ka <= 11.65      0.251057
..              ...           ...
121       S <= 0.04      0.000021
122      S <= -0.07      0.000018
123       K <= 0.22      0.000017
124      K <= -0.01      0.000013
125      K <= -0.19      0.000013

[126 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > 4.25,33.726066,Fe ka,4.25,>
1,Ti ka <= -0.55,0.512573,Ti ka,-0.55,<=
2,Fe kb <= -2.08,0.356791,Fe kb,-2.08,<=
3,Ca ka > -0.35,0.318930,Ca ka,-0.35,>
4,K > -0.01,0.229622,K,-0.01,>
5,Ca kb <= 0.45,0.139571,Ca kb,0.45,<=
6,Si > 0.21,0.120229,Si,0.21,>
7,P <= 0.30,0.090481,P,0.30,<=
8,Cu <= -0.21,0.056745,Cu,-0.21,<=
9,Rh L + Ar <= 0.33,0.054529,Rh L + Ar,0.33,<=
10,Mn > -1.21,0.048964,Mn,-1.21,>
11,Al <= 0.58,0.045374,Al,0.58,<=
12,background1 > 0.08,0.045013,background1,0.08,>
13,background2 > 0.08,0.039763,background2,0.08,>
14,Fe ka + Ti ka > -0.06,0.029412,Fe ka + Ti ka,-0.06,>
15,sum Fe <= -0.60,0.027755,sum Fe,-0.60,<=
16,Zn > 0.10,0.027043,Zn,0.10,>
17,Ti kb <= -0.36,0.026219,Ti kb,-0.36,<=
18,Ni <= 0.26,0.024147,Ni,0.26,<=
19,Cr <= -0.21,0.022678,Cr,-0.21,<=
20,S > -0.07,0.000109,S,-0.07,>
21,Class_B,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > 4.25,33.726066,Fe ka,4.25,>,87.045387,38.0,0.001079,Fe ka > 87.045387
1,Fe ka > -5.77,25.653554,Fe ka,-5.77,>,-103.046579,408.0,0.004763,Fe ka > -103.046579
2,Fe ka <= -5.77,20.269064,Fe ka,-5.77,<=,-103.046579,408.0,0.004763,Fe ka <= -103.046579
3,Fe ka > -9.83,15.032997,Fe ka,-9.83,>,-178.952975,247.0,0.001731,Fe ka > -178.952975
4,Fe ka <= 11.65,9.493358,Fe ka,11.65,<=,188.786502,94.0,0.001158,Fe ka <= 188.786502
...,...,...,...,...,...,...,...,...,...
123,K <= -0.19,0.000066,K,-0.19,<=,-0.266533,231.0,0.000657,K <= -0.266533
124,S <= 0.04,0.000061,S,0.04,<=,0.036958,195.0,0.000109,S <= 0.036958
125,S <= -0.07,0.000055,S,-0.07,<=,-0.047908,438.0,0.001616,S <= -0.047908
126,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
127,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [16]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Variância explicada pela PC1: 94.87%

In [17]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba           Zone
0    6.42                      0.012566          Fe ka
1    4.52                      0.000823          Ti ka
2     7.1                      0.000752          Fe kb
3    3.68                      0.000578          Ca ka
4    3.32                      0.000181              K
5    5.92                      0.000173             Mn
6    1.72                      0.000108             Si
7    1.48                      0.000108             Al
8    2.62                      0.000063      Rh L + Ar
9    8.02                      0.000058             Cu
10    4.9                      0.000056          Ti kb
11  12.82                      0.000048         sum Fe
12   2.02                      0.000034              P
13    5.4                      0.000026             Cr
14   4.04                      0.000025          Ca kb
15    9.3                      0.000020    background1
16  11.24                      0.000016    background2
17  10.98                      0.000015  Fe ka + Ti ka
18    8.6                      0.000013             Zn
19   7.32                      0.000012             Ni
20   2.54                      0.000010              S
21   1.32                      0.000002            NaN

In [18]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka
1,Fe kb,Ti ka,Ti ka,Ti ka,Fe kb
2,K,Ca ka,Fe kb,Fe kb,Mn
3,Mn,Fe kb,Ca ka,Ca ka,sum Fe
4,sum Fe,Ti kb,K,K,Ti ka
5,Rh L + Ar,Ni,Mn,Ca kb,Rh L + Ar
6,Si,Rh L + Ar,Si,Si,Ti kb
7,Ti kb,S,Al,P,Ca ka
8,Cu,background1,Rh L + Ar,Cu,Si
9,Ti ka,Cu,Cu,Rh L + Ar,Cr
10,Cr,Ca kb,Ti kb,Mn,Cu
11,P,background2,sum Fe,Al,Al
12,Al,Mn,P,background1,background1
13,background1,Cr,Cr,background2,Ca kb
14,background2,K,Ca kb,Fe ka + Ti ka,background2
15,Zn,Zn,background1,sum Fe,K
16,Ni,sum Fe,background2,Zn,Zn
17,Fe ka + Ti ka,P,Fe ka + Ti ka,Ti kb,P
18,Ca ka,Al,Zn,Ni,Ni
19,S,Si,Ni,Cr,Fe ka + Ti ka
20,Ca kb,Fe ka + Ti ka,S,S,S
21,NaN,NaN,NaN,None,None

In [19]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_18316\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
7       Permutation  LRC_perturbation   0.943944
3       SVM_pvector    LRC_covariance   0.851693
4              Shap       Permutation   0.851531
5              Shap  LRC_perturbation   0.849610
1       SVM_pvector       Permutation   0.693148
8       Permutation    LRC_covariance   0.688817
2       SVM_pvector  LRC_perturbation   0.673482
9  LRC_perturbation    LRC_covariance   0.667230
6              Shap    LRC_covariance   0.636412
0       SVM_pvector              Shap   0.593498

In [20]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')