In [4]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' can be imported
import sys
from pathlib import Path # for path manipulations
# Move three levels up from current working directory to reach workspace root
workspace_root = Path.cwd().parent.parent.parent.resolve() 
smx_dir = workspace_root / 'smx'  # Path to smx folder
if str(smx_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(smx_dir)) # insert at the start of sys.path to prioritize local modules

#Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{workspace_root}/real_datasets/xrf/soyben.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.40':'23.10']  # selecting only the spectral features (columns with numeric names)

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.40':'23.10'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.40':'23.10'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)


Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

2026-03-10 07:09:47,863 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-03-10 07:09:47,872 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-03-10 07:09:47,977 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

2026-03-10 07:09:47,983 - kennard_stone.utils._pairwise:114[INFO] - Calculating pairwise distances using scikit-learn.

In [5]:
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=2,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
#vip_scores_mat.T.plot()
plsda_results[0]

,LVs,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy CV,Sensitivity CV,Specificity CV,CM CV,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred,X Cum Exp Var,Y Cum Exp Var,X Ind Exp Var,Y Ind Exp Var
0,1,0.640625,0.178571,1.000000,"[[36, 0], [23, 5]]",0.1875,0.035714,0.305556,"[[11, 25], [27, 1]]",0.551724,0.000000,1.0000,"[[16, 0], [13, 0]]",35.285791,2.955985,35.285791,2.955985
1,2,0.750000,0.642857,0.833333,"[[30, 6], [10, 18]]",0.5625,0.428571,0.666667,"[[24, 12], [16, 12]]",0.758621,0.538462,0.9375,"[[15, 1], [6, 7]]",47.497340,20.981041,12.211548,18.025056

In [6]:
Xcalclass.T.plot()

## Definição das Zonas Espectrais

In [7]:
spectral_cuts = [
('Al', 1.40, 1.66),
('Si', 1.66, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.18),
('Ti ka', 4.18, 4.66),
('background1', 5.08, 5.72),
('Mn', 5.72, 6.14),
('Fe ka', 6.14, 6.68),
('Fe kb', 6.68, 7.20),
('Ni', 7.20, 7.70),
('Cu', 7.70, 8.30),
('Zn ka', 8.30, 9.10),
('Zn kb', 9.10, 9.87),
('background2', 9.87, 13.00),
('Rb', 13.00, 13.75),
('Sr', 13.75, 14.61),
('Zr', 14.61, 15.50),
('background3', 15.50, 17.70),
('Compton ka', 17.70, 19.80),
('Rayleigh ka', 19.80, 20.58),
('Compton kb', 20.58, 22.12),
('Rayleigh kb', 22.12, 23.10),
]

## VIP, Regression Coefficients e SHAP (como no original)

In [8]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

In [9]:
shap_global_importance = pd.read_csv('shap_soyben.csv', sep=';') # loading previously saved shap_unique_df

# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP         Zone
0     6.37       0.015023        Fe ka
1     8.61       0.014527        Zn ka
2    19.14       0.011377   Compton ka
3     3.38       0.009249            K
4    20.30       0.005949  Rayleigh ka
5    14.21       0.003696           Sr
6     3.80       0.003196        Ca ka
7     7.11       0.002052        Fe kb
8    13.31       0.001576           Rb
9     5.89       0.001527           Mn
10    4.10       0.001089        Ca kb
11    7.97       0.000663           Cu
12   21.50       0.000655   Compton kb
13   10.21       0.000405  background2
14    2.30       0.000250            S
15    2.04       0.000230            P
16   16.74       0.000214  background3
17    9.81       0.000199        Zn kb
18    2.50       0.000110    Rh L + Ar
19   15.03       0.000050           Zr
20    1.40       0.000000           Al
21   22.82       0.000000  Rayleigh kb
22    5.00       0.000000          NaN
23    5.09       0.000000  background1
24    4.62       0.000000        Ti ka
25    1.70       0.000000           Si
26    7.21       0.000000           Ni

In [10]:
# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP         Zone
0     6.37       0.015023        Fe ka
1     8.61       0.014527        Zn ka
2    19.14       0.011377   Compton ka
3     3.38       0.009249            K
4    20.30       0.005949  Rayleigh ka
5    14.21       0.003696           Sr
6     3.80       0.003196        Ca ka
7     7.11       0.002052        Fe kb
8    13.31       0.001576           Rb
9     5.89       0.001527           Mn
10    4.10       0.001089        Ca kb
11    7.97       0.000663           Cu
12   21.50       0.000655   Compton kb
13   10.21       0.000405  background2
14    2.30       0.000250            S
15    2.04       0.000230            P
16   16.74       0.000214  background3
17    9.81       0.000199        Zn kb
18    2.50       0.000110    Rh L + Ar
19   15.03       0.000050           Zr
20    4.28       0.000000        Ti ka
21    1.84       0.000000           Si
22    1.52       0.000000           Al
23    7.21       0.000000           Ni
24    5.61       0.000000  background1
25    4.92       0.000000          NaN
26   22.90       0.000000  Rayleigh kb

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [11]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zone 'Al': VE = 55.54%, dim = 14 variables
Zone 'Si': VE = 54.98%, dim = 11 variables
Zone 'P': VE = 51.00%, dim = 16 variables
Zone 'S': VE = 44.42%, dim = 15 variables
Zone 'Rh L + Ar': VE = 35.74%, dim = 34 variables
Zone 'K': VE = 75.72%, dim = 19 variables
Zone 'Ca ka': VE = 60.16%, dim = 21 variables
Zone 'Ca kb': VE = 42.52%, dim = 17 variables
Zone 'Ti ka': VE = 26.26%, dim = 25 variables
Zone 'background1': VE = 15.02%, dim = 32 variables
Zone 'Mn': VE = 28.44%, dim = 21 variables
Zone 'Fe ka': VE = 98.64%, dim = 27 variables
Zone 'Fe kb': VE = 92.97%, dim = 26 variables
Zone 'Ni': VE = 21.03%, dim = 25 variables
Zone 'Cu': VE = 20.61%, dim = 30 variables
Zone 'Zn ka': VE = 52.61%, dim = 40 variables
Zone 'Zn kb': VE = 21.01%, dim = 39 variables
Zone 'background2': VE = 51.35%, dim = 157 variables
Zone 'Rb': VE = 72.91%, dim = 38 variables
Zone 'Sr': VE = 75.87%, dim = 44 variables
Zone 'Zr': VE = 78.49%, dim = 45 variables
Zone 'background3': VE = 81.72%, dim = 110 variables
Zone 'Compton ka': VE = 87.75%, dim = 106 variables
Zone 'Rayleigh ka': VE = 84.42%, dim = 40 variables
Zone 'Compton kb': VE = 84.51%, dim = 78 variables
Zone 'Rayleigh kb': VE = 79.51%, dim = 50 variables

Scores DataFrame shape: (64, 26)

In [12]:
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred_cont
)

In [13]:
# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        perturbation_mode='median',
        stats_source='full',
        aim='regression',
        metric='mean_abs_diff',
        normalize_by_zone_size=True,   # ← ativa a normalização
        zone_size_exponent=1.0,        # ← √n (moderado); use 1.0 para n completo
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graph(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Samples: Yes | Predicates: No (All) | Valid: 161 | Discarded: 47
Bag_2 | Samples: Yes | Predicates: No (All) | Valid: 178 | Discarded: 30
Bag_3 | Samples: Yes | Predicates: No (All) | Valid: 156 | Discarded: 52
Bag_4 | Samples: Yes | Predicates: No (All) | Valid: 169 | Discarded: 39
Bag_5 | Samples: Yes | Predicates: No (All) | Valid: 178 | Discarded: 30
Bag_6 | Samples: Yes | Predicates: No (All) | Valid: 163 | Discarded: 45
Bag_7 | Samples: Yes | Predicates: No (All) | Valid: 162 | Discarded: 46
Bag_8 | Samples: Yes | Predicates: No (All) | Valid: 167 | Discarded: 41
Bag_9 | Samples: Yes | Predicates: No (All) | Valid: 175 | Discarded: 33
Bag_10 | Samples: Yes | Predicates: No (All) | Valid: 162 | Discarded: 46
======================================================================
PERTURBATION IMPORTANCE FOR PREDICATES
======================================================================
Task type (aim): regression
Perturbation mode: median
Statistics source: full
Metric: mean_abs_diff
Total folds: 10
Zone-size normalization: ENABLED (exponent=1.0)


[Bag_1] Processing 161 predicates...
  Predicate: Al > -0.12 (n=40)
    Zone: 14 columns
    Normalized importance: 0.000193 / 14
    Importance: 0.002696
  Predicate: Al <= -0.03 (n=19)
    Zone: 14 columns
    Normalized importance: 0.000274 / 14
    Importance: 0.003841
  Predicate: Al > -0.03 (n=32)
    Zone: 14 columns
    Normalized importance: 0.000202 / 14
    Importance: 0.002827
  Predicate: Al <= 0.04 (n=32)
    Zone: 14 columns
    Normalized importance: 0.000207 / 14
    Importance: 0.002896
  Predicate: Al > 0.04 (n=19)
    Zone: 14 columns
    Normalized importance: 0.000266 / 14
    Importance: 0.003725
  Predicate: Al <= 0.13 (n=41)
    Zone: 14 columns
    Normalized importance: 0.000206 / 14
    Importance: 0.002888
  Predicate: Si > -0.09 (n=40)
    Zone: 11 columns
    Normalized importance: 0.000149 / 11
    Importance: 0.001634
  Predicate: Si <= -0.02 (n=22)
    Zone: 11 columns
    Normalized importance: 0.000242 / 11
    Importance: 0.002659
  Predicate: Si > -0.02 (n=29)
    Zone: 11 columns
    Normalized importance: 0.000162 / 11
    Importance: 0.001777
  Predicate: Si <= 0.03 (n=28)
    Zone: 11 columns
    Normalized importance: 0.000219 / 11
    Importance: 0.002414
  Predicate: Si > 0.03 (n=23)
    Zone: 11 columns
    Normalized importance: 0.000168 / 11
    Importance: 0.001846
  Predicate: Si <= 0.10 (n=41)
    Zone: 11 columns
    Normalized importance: 0.000186 / 11
    Importance: 0.002044
  Predicate: P > -0.12 (n=40)
    Zone: 16 columns
    Normalized importance: 0.000194 / 16
    Importance: 0.003102
  Predicate: P <= -0.04 (n=21)
    Zone: 16 columns
    Normalized importance: 0.000156 / 16
    Importance: 0.002496
  Predicate: P > -0.04 (n=30)
    Zone: 16 columns
    Normalized importance: 0.000200 / 16
    Importance: 0.003205
  Predicate: P <= 0.05 (n=30)
    Zone: 16 columns
    Normalized importance: 0.000166 / 16
    Importance: 0.002652
  Predicate: P > 0.05 (n=21)
    Zone: 16 columns
    Normalized importance: 0.000205 / 16
    Importance: 0.003285
  Predicate: P <= 0.13 (n=39)
    Zone: 16 columns
    Normalized importance: 0.000177 / 16
    Importance: 0.002837
  Predicate: P > 0.13 (n=12)
    Zone: 16 columns
    Normalized importance: 0.000197 / 16
    Importance: 0.003160
  Predicate: S > -0.09 (n=40)
    Zone: 15 columns
    Normalized importance: 0.000282 / 15
    Importance: 0.004223
  Predicate: S <= -0.02 (n=20)
    Zone: 15 columns
    Normalized importance: 0.000333 / 15
    Importance: 0.004994
  Predicate: S > -0.02 (n=31)
    Zone: 15 columns
    Normalized importance: 0.000311 / 15
    Importance: 0.004661
  Predicate: S <= 0.03 (n=32)
    Zone: 15 columns
    Normalized importance: 0.000269 / 15
    Importance: 0.004029
  Predicate: S > 0.03 (n=19)
    Zone: 15 columns
    Normalized importance: 0.000405 / 15
    Importance: 0.006076
  Predicate: S <= 0.10 (n=41)
    Zone: 15 columns
    Normalized importance: 0.000262 / 15
    Importance: 0.003930
  Predicate: Rh L + Ar > -0.12 (n=40)
    Zone: 34 columns
    Normalized importance: 0.000155 / 34
    Importance: 0.005270
  Predicate: Rh L + Ar <= -0.03 (n=22)
    Zone: 34 columns
    Normalized importance: 0.000201 / 34
    Importance: 0.006824
  Predicate: Rh L + Ar > -0.03 (n=29)
    Zone: 34 columns
    Normalized importance: 0.000153 / 34
    Importance: 0.005203
  Predicate: Rh L + Ar <= 0.04 (n=29)
    Zone: 34 columns
    Normalized importance: 0.000198 / 34
    Importance: 0.006719
  Predicate: Rh L + Ar > 0.04 (n=22)
    Zone: 34 columns
    Normalized importance: 0.000142 / 34
    Importance: 0.004826
  Predicate: Rh L + Ar <= 0.12 (n=40)
    Zone: 34 columns
    Normalized importance: 0.000169 / 34
    Importance: 0.005730
  Predicate: K > -0.35 (n=41)
    Zone: 19 columns
    Normalized importance: 0.001058 / 19
    Importance: 0.020095
  Predicate: K <= -0.11 (n=21)
    Zone: 19 columns
    Normalized importance: 0.001307 / 19
    Importance: 0.024833
  Predicate: K > -0.11 (n=30)
    Zone: 19 columns
    Normalized importance: 0.001219 / 19
    Importance: 0.023153
  Predicate: K <= 0.10 (n=30)
    Zone: 19 columns
    Normalized importance: 0.001038 / 19
    Importance: 0.019714
  Predicate: K > 0.10 (n=21)
    Zone: 19 columns
    Normalized importance: 0.001566 / 19
    Importance: 0.029746
  Predicate: K <= 0.30 (n=39)
    Zone: 19 columns
    Normalized importance: 0.000968 / 19
    Importance: 0.018394
  Predicate: K > 0.30 (n=12)
    Zone: 19 columns
    Normalized importance: 0.002187 / 19
    Importance: 0.041558
  Predicate: Ca ka > -0.21 (n=40)
    Zone: 21 columns
    Normalized importance: 0.000961 / 21
    Importance: 0.020183
  Predicate: Ca ka <= -0.09 (n=24)
    Zone: 21 columns
    Normalized importance: 0.000825 / 21
    Importance: 0.017322
  Predicate: Ca ka > -0.09 (n=27)
    Zone: 21 columns
    Normalized importance: 0.001208 / 21
    Importance: 0.025374
  Predicate: Ca ka <= 0.01 (n=32)
    Zone: 21 columns
    Normalized importance: 0.000718 / 21
    Importance: 0.015072
  Predicate: Ca ka > 0.01 (n=19)
    Zone: 21 columns
    Normalized importance: 0.001550 / 21
    Importance: 0.032554
  Predicate: Ca ka <= 0.23 (n=41)
    Zone: 21 columns
    Normalized importance: 0.000726 / 21
    Importance: 0.015254
  Predicate: Ca kb > -0.11 (n=40)
    Zone: 17 columns
    Normalized importance: 0.000206 / 17
    Importance: 0.003501
  Predicate: Ca kb <= -0.03 (n=23)
    Zone: 17 columns
    Normalized importance: 0.000223 / 17
    Importance: 0.003792
  Predicate: Ca kb > -0.03 (n=28)
    Zone: 17 columns
    Normalized importance: 0.000237 / 17
    Importance: 0.004021
  Predicate: Ca kb <= 0.01 (n=30)
    Zone: 17 columns
    Normalized importance: 0.000199 / 17
    Importance: 0.003391
  Predicate: Ca kb > 0.01 (n=21)
    Zone: 17 columns
    Normalized importance: 0.000275 / 17
    Importance: 0.004670
  Predicate: Ca kb <= 0.12 (n=42)
    Zone: 17 columns
    Normalized importance: 0.000192 / 17
    Importance: 0.003261
  Predicate: Ti ka > -0.08 (n=40)
    Zone: 25 columns
    Normalized importance: 0.000137 / 25
    Importance: 0.003417
  Predicate: Ti ka <= -0.04 (n=18)
    Zone: 25 columns
    Normalized importance: 0.000130 / 25
    Importance: 0.003238
  Predicate: Ti ka > -0.04 (n=33)
    Zone: 25 columns
    Normalized importance: 0.000136 / 25
    Importance: 0.003392
  Predicate: Ti ka <= 0.01 (n=31)
    Zone: 25 columns
    Normalized importance: 0.000123 / 25
    Importance: 0.003082
  Predicate: Ti ka > 0.01 (n=20)
    Zone: 25 columns
    Normalized importance: 0.000149 / 25
    Importance: 0.003734
  Predicate: Ti ka <= 0.09 (n=40)
    Zone: 25 columns
    Normalized importance: 0.000135 / 25
    Importance: 0.003379
  Predicate: background1 <= -0.08 (n=12)
    Zone: 32 columns
    Normalized importance: 0.000145 / 32
    Importance: 0.004645
  Predicate: background1 > -0.08 (n=39)
    Zone: 32 columns
    Normalized importance: 0.000157 / 32
    Importance: 0.005020
  Predicate: background1 <= -0.01 (n=24)
    Zone: 32 columns
    Normalized importance: 0.000135 / 32
    Importance: 0.004310
  Predicate: background1 > -0.01 (n=27)
    Zone: 32 columns
    Normalized importance: 0.000171 / 32
    Importance: 0.005484
  Predicate: background1 <= 0.02 (n=30)
    Zone: 32 columns
    Normalized importance: 0.000133 / 32
    Importance: 0.004255
  Predicate: background1 > 0.02 (n=21)
    Zone: 32 columns
    Normalized importance: 0.000184 / 32
    Importance: 0.005898
  Predicate: background1 <= 0.06 (n=39)
    Zone: 32 columns
    Normalized importance: 0.000138 / 32
    Importance: 0.004420
  Predicate: background1 > 0.06 (n=12)
    Zone: 32 columns
    Normalized importance: 0.000206 / 32
    Importance: 0.006596
  Predicate: Mn > -0.10 (n=40)
    Zone: 21 columns
    Normalized importance: 0.000562 / 21
    Importance: 0.011807
  Predicate: Mn <= -0.04 (n=21)
    Zone: 21 columns
    Normalized importance: 0.000629 / 21
    Importance: 0.013215
  Predicate: Mn > -0.04 (n=30)
    Zone: 21 columns
    Normalized importance: 0.000638 / 21
    Importance: 0.013405
  Predicate: Mn <= 0.04 (n=30)
    Zone: 21 columns
    Normalized importance: 0.000518 / 21
    Importance: 0.010874
  Predicate: Mn > 0.04 (n=21)
    Zone: 21 columns
    Normalized importance: 0.000802 / 21
    Importance: 0.016832
  Predicate: Mn <= 0.12 (n=42)
    Zone: 21 columns
    Normalized importance: 0.000518 / 21
    Importance: 0.010880
  Predicate: Fe ka > -0.76 (n=42)
    Zone: 27 columns
    Normalized importance: 0.001026 / 27
    Importance: 0.027689
  Predicate: Fe ka <= -0.63 (n=22)
    Zone: 27 columns
    Normalized importance: 0.000312 / 27
    Importance: 0.008426
  Predicate: Fe ka > -0.63 (n=29)
    Zone: 27 columns
    Normalized importance: 0.001390 / 27
    Importance: 0.037539
  Predicate: Fe ka <= -0.51 (n=30)
    Zone: 27 columns
    Normalized importance: 0.000272 / 27
    Importance: 0.007337
  Predicate: Fe ka > -0.51 (n=21)
    Zone: 27 columns
    Normalized importance: 0.001859 / 27
    Importance: 0.050185
  Predicate: Fe ka <= 0.20 (n=43)
    Zone: 27 columns
    Normalized importance: 0.000294 / 27
    Importance: 0.007933
  Predicate: Fe kb > -0.32 (n=42)
    Zone: 26 columns
    Normalized importance: 0.000151 / 26
    Importance: 0.003922
  Predicate: Fe kb <= -0.24 (n=18)
    Zone: 26 columns
    Normalized importance: 0.000119 / 26
    Importance: 0.003087
  Predicate: Fe kb > -0.24 (n=33)
    Zone: 26 columns
    Normalized importance: 0.000157 / 26
    Importance: 0.004094
  Predicate: Fe kb <= -0.17 (n=31)
    Zone: 26 columns
    Normalized importance: 0.000109 / 26
    Importance: 0.002838
  Predicate: Fe kb > -0.17 (n=20)
    Zone: 26 columns
    Normalized importance: 0.000198 / 26
    Importance: 0.005136
  Predicate: Fe kb <= 0.05 (n=43)
    Zone: 26 columns
    Normalized importance: 0.000115 / 26
    Importance: 0.002999
  Predicate: Ni > -0.07 (n=42)
    Zone: 25 columns
    Normalized importance: 0.000109 / 25
    Importance: 0.002721
  Predicate: Ni <= -0.04 (n=19)
    Zone: 25 columns
    Normalized importance: 0.000116 / 25
    Importance: 0.002891
  Predicate: Ni > -0.04 (n=32)
    Zone: 25 columns
    Normalized importance: 0.000105 / 25
    Importance: 0.002628
  Predicate: Ni <= 0.00 (n=32)
    Zone: 25 columns
    Normalized importance: 0.000106 / 25
    Importance: 0.002646
  Predicate: Ni > 0.00 (n=19)
    Zone: 25 columns
    Normalized importance: 0.000114 / 25
    Importance: 0.002862
  Predicate: Ni <= 0.05 (n=44)
    Zone: 25 columns
    Normalized importance: 0.000109 / 25
    Importance: 0.002713
  Predicate: Cu <= -0.09 (n=12)
    Zone: 30 columns
    Normalized importance: 0.000402 / 30
    Importance: 0.012045
  Predicate: Cu > -0.09 (n=39)
    Zone: 30 columns
    Normalized importance: 0.000314 / 30
    Importance: 0.009427
  Predicate: Cu <= -0.03 (n=21)
    Zone: 30 columns
    Normalized importance: 0.000310 / 30
    Importance: 0.009303
  Predicate: Cu > -0.03 (n=30)
    Zone: 30 columns
    Normalized importance: 0.000352 / 30
    Importance: 0.010561
  Predicate: Cu <= 0.01 (n=31)
    Zone: 30 columns
    Normalized importance: 0.000263 / 30
    Importance: 0.007898
  Predicate: Cu > 0.01 (n=20)
    Zone: 30 columns
    Normalized importance: 0.000446 / 30
    Importance: 0.013368
  Predicate: Cu <= 0.09 (n=40)
    Zone: 30 columns
    Normalized importance: 0.000255 / 30
    Importance: 0.007664
  Predicate: Zn ka > -0.29 (n=42)
    Zone: 40 columns
    Normalized importance: 0.001394 / 40
    Importance: 0.055765
  Predicate: Zn ka <= -0.06 (n=19)
    Zone: 40 columns
    Normalized importance: 0.001946 / 40
    Importance: 0.077848
  Predicate: Zn ka > -0.06 (n=32)
    Zone: 40 columns
    Normalized importance: 0.001450 / 40
    Importance: 0.057999
  Predicate: Zn ka <= 0.09 (n=30)
    Zone: 40 columns
    Normalized importance: 0.001341 / 40
    Importance: 0.053657
  Predicate: Zn ka > 0.09 (n=21)
    Zone: 40 columns
    Normalized importance: 0.002054 / 40
    Importance: 0.082160
  Predicate: Zn ka <= 0.24 (n=41)
    Zone: 40 columns
    Normalized importance: 0.001255 / 40
    Importance: 0.050205
  Predicate: Zn kb > -0.09 (n=41)
    Zone: 39 columns
    Normalized importance: 0.000230 / 39
    Importance: 0.008969
  Predicate: Zn kb <= -0.03 (n=19)
    Zone: 39 columns
    Normalized importance: 0.000277 / 39
    Importance: 0.010789
  Predicate: Zn kb > -0.03 (n=32)
    Zone: 39 columns
    Normalized importance: 0.000254 / 39
    Importance: 0.009925
  Predicate: Zn kb <= 0.03 (n=31)
    Zone: 39 columns
    Normalized importance: 0.000209 / 39
    Importance: 0.008150
  Predicate: Zn kb > 0.03 (n=20)
    Zone: 39 columns
    Normalized importance: 0.000346 / 39
    Importance: 0.013498
  Predicate: Zn kb <= 0.11 (n=40)
    Zone: 39 columns
    Normalized importance: 0.000203 / 39
    Importance: 0.007906
  Predicate: background2 > -0.33 (n=41)
    Zone: 157 columns
    Normalized importance: 0.000222 / 157
    Importance: 0.034834
  Predicate: background2 <= -0.08 (n=20)
    Zone: 157 columns
    Normalized importance: 0.000318 / 157
    Importance: 0.049972
  Predicate: background2 > -0.08 (n=31)
    Zone: 157 columns
    Normalized importance: 0.000254 / 157
    Importance: 0.039923
  Predicate: background2 <= 0.17 (n=30)
    Zone: 157 columns
    Normalized importance: 0.000239 / 157
    Importance: 0.037587
  Predicate: background2 > 0.17 (n=21)
    Zone: 157 columns
    Normalized importance: 0.000336 / 157
    Importance: 0.052830
  Predicate: background2 <= 0.35 (n=40)
    Zone: 157 columns
    Normalized importance: 0.000210 / 157
    Importance: 0.032974
  Predicate: Rb > -0.28 (n=41)
    Zone: 38 columns
    Normalized importance: 0.000200 / 38
    Importance: 0.007591
  Predicate: Rb <= -0.08 (n=21)
    Zone: 38 columns
    Normalized importance: 0.000212 / 38
    Importance: 0.008050
  Predicate: Rb > -0.08 (n=30)
    Zone: 38 columns
    Normalized importance: 0.000200 / 38
    Importance: 0.007615
  Predicate: Rb <= 0.06 (n=30)
    Zone: 38 columns
    Normalized importance: 0.000185 / 38
    Importance: 0.007037
  Predicate: Rb > 0.06 (n=21)
    Zone: 38 columns
    Normalized importance: 0.000234 / 38
    Importance: 0.008876
  Predicate: Rb <= 0.29 (n=40)
    Zone: 38 columns
    Normalized importance: 0.000185 / 38
    Importance: 0.007016
  Predicate: Sr > -0.34 (n=42)
    Zone: 44 columns
    Normalized importance: 0.000471 / 44
    Importance: 0.020712
  Predicate: Sr <= -0.05 (n=20)
    Zone: 44 columns
    Normalized importance: 0.000945 / 44
    Importance: 0.041591
  Predicate: Sr > -0.05 (n=31)
    Zone: 44 columns
    Normalized importance: 0.000496 / 44
    Importance: 0.021824
  Predicate: Sr <= 0.15 (n=29)
    Zone: 44 columns
    Normalized importance: 0.000722 / 44
    Importance: 0.031753
  Predicate: Sr > 0.15 (n=22)
    Zone: 44 columns
    Normalized importance: 0.000607 / 44
    Importance: 0.026706
  Predicate: Sr <= 0.42 (n=41)
    Zone: 44 columns
    Normalized importance: 0.000612 / 44
    Importance: 0.026934
  Predicate: Zr > -0.35 (n=41)
    Zone: 45 columns
    Normalized importance: 0.000238 / 45
    Importance: 0.010729
  Predicate: Zr <= -0.07 (n=20)
    Zone: 45 columns
    Normalized importance: 0.000394 / 45
    Importance: 0.017743
  Predicate: Zr > -0.07 (n=31)
    Zone: 45 columns
    Normalized importance: 0.000260 / 45
    Importance: 0.011713
  Predicate: Zr <= 0.13 (n=30)
    Zone: 45 columns
    Normalized importance: 0.000285 / 45
    Importance: 0.012826
  Predicate: Zr > 0.13 (n=21)
    Zone: 45 columns
    Normalized importance: 0.000353 / 45
    Importance: 0.015866
  Predicate: Zr <= 0.43 (n=40)
    Zone: 45 columns
    Normalized importance: 0.000243 / 45
    Importance: 0.010942
  Predicate: background3 > -0.60 (n=41)
    Zone: 110 columns
    Normalized importance: 0.000083 / 110
    Importance: 0.009178
  Predicate: background3 <= -0.12 (n=21)
    Zone: 110 columns
    Normalized importance: 0.000101 / 110
    Importance: 0.011134
  Predicate: background3 > -0.12 (n=30)
    Zone: 110 columns
    Normalized importance: 0.000083 / 110
    Importance: 0.009123
  Predicate: background3 <= 0.21 (n=30)
    Zone: 110 columns
    Normalized importance: 0.000090 / 110
    Importance: 0.009941
  Predicate: background3 > 0.21 (n=21)
    Zone: 110 columns
    Normalized importance: 0.000091 / 110
    Importance: 0.009965
  Predicate: background3 <= 0.69 (n=41)
    Zone: 110 columns
    Normalized importance: 0.000083 / 110
    Importance: 0.009163
  Predicate: Compton ka > -0.95 (n=40)
    Zone: 106 columns
    Normalized importance: 0.000742 / 106
    Importance: 0.078703
  Predicate: Compton ka <= -0.14 (n=20)
    Zone: 106 columns
    Normalized importance: 0.000605 / 106
    Importance: 0.064120
  Predicate: Compton ka > -0.14 (n=31)
    Zone: 106 columns
    Normalized importance: 0.000771 / 106
    Importance: 0.081778
  Predicate: Compton ka <= 0.44 (n=29)
    Zone: 106 columns
    Normalized importance: 0.000596 / 106
    Importance: 0.063201
  Predicate: Compton ka > 0.44 (n=22)
    Zone: 106 columns
    Normalized importance: 0.000851 / 106
    Importance: 0.090213
  Predicate: Compton ka <= 1.10 (n=40)
    Zone: 106 columns
    Normalized importance: 0.000597 / 106
    Importance: 0.063312
  Predicate: Rayleigh ka > -0.45 (n=41)
    Zone: 40 columns
    Normalized importance: 0.001397 / 40
    Importance: 0.055869
  Predicate: Rayleigh ka <= -0.08 (n=21)
    Zone: 40 columns
    Normalized importance: 0.001856 / 40
    Importance: 0.074227
  Predicate: Rayleigh ka > -0.08 (n=30)
    Zone: 40 columns
    Normalized importance: 0.001649 / 40
    Importance: 0.065965
  Predicate: Rayleigh ka <= 0.17 (n=29)
    Zone: 40 columns
    Normalized importance: 0.001498 / 40
    Importance: 0.059915
  Predicate: Rayleigh ka > 0.17 (n=22)
    Zone: 40 columns
    Normalized importance: 0.002046 / 40
    Importance: 0.081826
  Predicate: Rayleigh ka <= 0.61 (n=41)
    Zone: 40 columns
    Normalized importance: 0.001364 / 40
    Importance: 0.054562
  Predicate: Compton kb > -0.56 (n=41)
    Zone: 78 columns
    Normalized importance: 0.000450 / 78
    Importance: 0.035122
  Predicate: Compton kb <= -0.10 (n=19)
    Zone: 78 columns
    Normalized importance: 0.000811 / 78
    Importance: 0.063279
  Predicate: Compton kb > -0.10 (n=32)
    Zone: 78 columns
    Normalized importance: 0.000498 / 78
    Importance: 0.038823
  Predicate: Compton kb <= 0.26 (n=30)
    Zone: 78 columns
    Normalized importance: 0.000564 / 78
    Importance: 0.044016
  Predicate: Compton kb > 0.26 (n=21)
    Zone: 78 columns
    Normalized importance: 0.000686 / 78
    Importance: 0.053531

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Rayleigh ka > 0.17,K > 0.10,Fe ka > 0.20,Fe ka > 0.20
1,Zn ka > 0.09,Fe ka > 0.20,K <= -0.35,Rayleigh ka <= -0.45
2,Fe ka > 0.20,Rayleigh ka > -0.08,Zn ka <= -0.06,Fe ka > -0.51
3,Rayleigh ka > -0.08,Rayleigh ka > 0.61,Zn ka > 0.24,Zn ka > 0.09
4,Rayleigh ka > 0.61,Rayleigh ka <= -0.45,Rayleigh ka <= -0.45,Rayleigh ka > 0.61
...,...,...,...,...
200,Ti ka > 0.09,Ni <= 0.05,NaN,Class_A
201,background3 > 0.69,Ni > -0.04,NaN,Class_B
202,background1 <= -0.08,Ni <= 0.00,NaN,NaN
203,Class_A,Class_A,NaN,NaN
204,Class_B,Class_B,NaN,NaN

In [14]:
all_results_pert[0]['pert_results_dict']['Bag_1']

               Predicate  Perturbation
0               K > 0.30      0.002187
1           Zn ka > 0.09      0.002054
2     Rayleigh ka > 0.17      0.002046
3         Zn ka <= -0.06      0.001946
4          Fe ka > -0.51      0.001859
..                   ...           ...
156   background3 > 0.21      0.000091
157  background3 <= 0.21      0.000090
158  background3 > -0.60      0.000083
159  background3 <= 0.69      0.000083
160  background3 > -0.12      0.000083

[161 rows x 2 columns]

In [15]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > 0.20,4.496036,Fe ka,0.20,>
1,Rayleigh ka > 0.61,3.968191,Rayleigh ka,0.61,>
2,Zn ka > 0.24,3.864212,Zn ka,0.24,>
3,K > 0.10,3.523537,K,0.10,>
4,Ca ka > 0.23,3.140880,Ca ka,0.23,>
5,Compton kb <= -0.56,2.570937,Compton kb,-0.56,<=
6,Sr <= -0.34,2.445429,Sr,-0.34,<=
7,Mn > 0.12,2.245269,Mn,0.12,>
8,Compton ka > 1.10,2.112159,Compton ka,1.10,>
9,Zr <= -0.35,1.198956,Zr,-0.35,<=
10,background2 > 0.35,1.081194,background2,0.35,>
11,S > 0.10,0.925768,S,0.10,>
12,Rayleigh kb > 0.40,0.833270,Rayleigh kb,0.40,>
13,Cu > 0.01,0.697389,Cu,0.01,>
14,Si <= -0.09,0.694023,Si,-0.09,<=
15,Ca kb > 0.12,0.689845,Ca kb,0.12,>
16,Zn kb > 0.03,0.683521,Zn kb,0.03,>
17,Al <= -0.12,0.646332,Al,-0.12,<=
18,Rb > 0.06,0.598852,Rb,0.06,>
19,Fe kb > -0.17,0.572422,Fe kb,-0.17,>
20,P > 0.13,0.564646,P,0.13,>
21,Rh L + Ar <= -0.12,0.520102,Rh L + Ar,-0.12,<=
22,background1 > 0.02,0.475193,background1,0.02,>
23,background3 > 0.69,0.456760,background3,0.69,>
24,Ti ka > -0.04,0.456154,Ti ka,-0.04,>
25,Ni > -0.07,0.415725,Ni,-0.07,>
26,Class_A,0.000000,NaN,NaN,NaN

In [16]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

Zone 'Al': VE = 55.89%, dim = 14 variables
Zone 'Si': VE = 55.01%, dim = 11 variables
Zone 'P': VE = 51.19%, dim = 16 variables
Zone 'S': VE = 44.29%, dim = 15 variables
Zone 'Rh L + Ar': VE = 33.87%, dim = 34 variables
Zone 'K': VE = 86.68%, dim = 19 variables
Zone 'Ca ka': VE = 75.18%, dim = 21 variables
Zone 'Ca kb': VE = 50.79%, dim = 17 variables
Zone 'Ti ka': VE = 26.72%, dim = 25 variables
Zone 'background1': VE = 15.25%, dim = 32 variables
Zone 'Mn': VE = 39.81%, dim = 21 variables
Zone 'Fe ka': VE = 99.45%, dim = 27 variables
Zone 'Fe kb': VE = 96.24%, dim = 26 variables
Zone 'Ni': VE = 14.60%, dim = 25 variables
Zone 'Cu': VE = 29.19%, dim = 30 variables
Zone 'Zn ka': VE = 71.13%, dim = 40 variables
Zone 'Zn kb': VE = 23.10%, dim = 39 variables
Zone 'background2': VE = 56.54%, dim = 157 variables
Zone 'Rb': VE = 73.07%, dim = 38 variables
Zone 'Sr': VE = 76.07%, dim = 44 variables
Zone 'Zr': VE = 78.51%, dim = 45 variables
Zone 'background3': VE = 81.75%, dim = 110 variables
Zone 'Compton ka': VE = 89.43%, dim = 106 variables
Zone 'Rayleigh ka': VE = 85.21%, dim = 40 variables
Zone 'Compton kb': VE = 84.84%, dim = 78 variables
Zone 'Rayleigh kb': VE = 79.58%, dim = 50 variables

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > 0.20,4.496036,Fe ka,0.20,>,0.114600,9.0,0.037587,Fe ka > 0.114600
1,Rayleigh ka > 0.61,3.968191,Rayleigh ka,0.61,>,0.928593,31.0,0.005251,Rayleigh ka > 0.928593
2,Zn ka > 0.24,3.864212,Zn ka,0.24,>,0.157867,21.0,0.007783,Zn ka > 0.157867
3,Rayleigh ka <= -0.45,3.812978,Rayleigh ka,-0.45,<=,-0.654311,43.0,0.018916,Rayleigh ka <= -0.654311
4,Zn ka > 0.09,3.774683,Zn ka,0.09,>,0.067920,41.0,0.011108,Zn ka > 0.067920
...,...,...,...,...,...,...,...,...,...
202,Ni <= 0.00,0.389582,Ni,0.00,<=,0.006415,42.0,0.005439,Ni <= 0.006415
203,Rayleigh kb <= -0.35,0.358344,Rayleigh kb,-0.35,<=,-0.358182,42.0,0.000043,Rayleigh kb <= -0.358182
204,P <= -0.12,0.326598,P,-0.12,<=,-0.067320,19.0,0.000425,P <= -0.067320
205,Class_A,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,Class_B,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 27 variáveis espectrais
  - Variância explicada pela PC1: 99.45%

In [18]:
# Permutation importance baseado em mudança nas predições do modelo PLS
# Medimos a média da diferença absoluta entre as predições originais e as predições
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Predições base do modelo PLS
baseline_pred = pls_model.predict(Xcalclass_prep)
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_pred = pls_model.predict(X_perm)
        diffs.append(np.mean(np.abs(baseline_pred - perm_pred)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance': importance_list
})
permutation_df.sort_values(by='Permutation_importance', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance', ascending=False)
permutation_unique_df

   energy  Permutation_importance         Zone
0    6.37                0.017083        Fe ka
1   19.14                0.014691   Compton ka
2    8.65                0.012119        Zn ka
3   20.38                0.011483  Rayleigh ka
4    3.38                0.008879            K
5   14.21                0.007897           Sr
6   21.50                0.006601   Compton kb
7    3.78                0.005907        Ca ka
8    7.11                0.005667        Fe kb
9    5.89                0.005519           Mn
10  13.31                0.005193           Rb
11  12.33                0.003966  background2
12  15.64                0.003752  background3
13  14.81                0.003222           Zr
14   2.50                0.003149    Rh L + Ar
15   4.10                0.003123        Ca kb
16   9.55                0.003049        Zn kb
17  22.16                0.003007  Rayleigh kb
18   7.97                0.002511           Cu
19   4.50                0.002286        Ti ka
20   2.30                0.002216            S
21   2.12                0.001915            P
22   7.67                0.001852           Ni
23   5.51                0.001654  background1
24   4.92                0.001557          NaN
25   1.42                0.001509           Al
26   1.66                0.001274           Si

In [19]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'VIP_Score': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_Coefficient' : pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

      VIP_Score Reg_Coefficient         Shap  Permutation LRC_perturbation
0         Fe ka           Zn ka        Fe ka        Fe ka            Fe ka
1         Zn ka              Mn        Zn ka   Compton ka      Rayleigh ka
2         Fe kb     Rayleigh ka   Compton ka        Zn ka            Zn ka
3   Rayleigh ka           Ca ka            K  Rayleigh ka                K
4            Mn              Sr  Rayleigh ka            K            Ca ka
5         Ca ka              Rb           Sr           Sr       Compton kb
6            Sr      Compton ka        Ca ka   Compton kb               Sr
7            Rb     background2        Fe kb        Ca ka               Mn
8    Compton ka               K           Rb        Fe kb       Compton ka
9   background2      Compton kb           Mn           Mn               Zr
10   Compton kb           Zn kb        Ca kb           Rb      background2
11            K           Fe ka           Cu  background2                S
12        Zn kb           Ca kb   Compton kb  background3      Rayleigh kb
13           Cu       Rh L + Ar  background2           Zr               Cu
14        Ca kb              Cu            S    Rh L + Ar               Si
15    Rh L + Ar              Ni            P        Ca kb            Ca kb
16           Ni     background3  background3        Zn kb            Zn kb
17  background3               S        Zn kb  Rayleigh kb               Al
18            S           Ti ka    Rh L + Ar           Cu               Rb
19        Ti ka           Fe kb           Zr        Ti ka            Fe kb
20          NaN              Zr        Ti ka            S                P
21           Zr             NaN           Si            P        Rh L + Ar
22  background1     background1           Al           Ni      background1
23  Rayleigh kb               P           Ni  background1      background3
24            P     Rayleigh kb  background1          NaN            Ti ka
25           Al              Al          NaN           Al               Ni
26           Si              Si  Rayleigh kb           Si              NaN

In [20]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

          Method_1          Method_2 RBO_Score
7             Shap       Permutation  0.829765
1        VIP_Score              Shap  0.797887
9      Permutation  LRC_perturbation  0.749552
8             Shap  LRC_perturbation  0.743331
3        VIP_Score  LRC_perturbation  0.722673
2        VIP_Score       Permutation  0.707349
0        VIP_Score   Reg_Coefficient  0.349158
4  Reg_Coefficient              Shap  0.297535
6  Reg_Coefficient  LRC_perturbation  0.276624
5  Reg_Coefficient       Permutation  0.211297

In [21]:
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')