In [4]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil_types/plsda/soil_types.csv', sep=';') # local copy of Toledo and Guarapuava soil datasets
data = data_complete.loc[:, '1.32':'13.1']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.32':'13.1'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.32':'13.1'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=2,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)
# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)
plsda_results[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 16:52:53,407 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 16:52:53,488 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 16:52:53,545 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 16:52:53,627 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

,LVs,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy CV,Sensitivity CV,Specificity CV,CM CV,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred,X Cum Exp Var,Y Cum Exp Var,X Ind Exp Var,Y Ind Exp Var
0,1,0.984032,1.000000,0.967611,"[[239, 8], [0, 254]]",0.980040,0.996063,0.963563,"[[238, 9], [1, 253]]",0.99537,1.0,0.990654,"[[106, 1], [0, 109]]",80.828131,40.015220,80.828131,40.015220
1,2,0.996008,0.996063,0.995951,"[[246, 1], [1, 253]]",0.996008,0.996063,0.995951,"[[246, 1], [1, 253]]",1.00000,1.0,1.000000,"[[107, 0], [0, 109]]",87.116272,43.666036,6.288141,3.650816

## Definição das Zonas Espectrais

In [5]:
spectral_cuts = [
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.37),
('Ti ka', 4.37, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('Ni', 7.30, 7.91),
('Cu', 7.91, 8.20),
('Zn', 8.20, 9.0),
('background1', 9.0, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background2', 11.14, 12.55),
('sum Fe' , 12.55, 13.1),
]

## VIP, Regression Coefficients e SHAP (como no original)

In [6]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

In [7]:
shap_global_importance = pd.read_csv('shap_soil_types.csv', sep=';') # loading previously saved shap_unique_df

# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP           Zone
0     6.40       0.057341          Fe ka
1     3.70       0.005081          Ca ka
2     4.50       0.002779          Ti ka
3     5.90       0.000083             Mn
4     7.08       0.000042          Fe kb
5     3.04       0.000000      Rh L + Ar
6     5.76       0.000000             Cr
7     2.22       0.000000              S
8     1.36       0.000000             Al
9     1.86       0.000000              P
10    1.32       0.000000            NaN
11    3.88       0.000000          Ca kb
12    3.22       0.000000              K
13    1.74       0.000000             Si
14   10.70       0.000000  Fe ka + Ti ka
15   12.62       0.000000         sum Fe
16   12.00       0.000000    background2
17    7.62       0.000000             Ni
18    8.84       0.000000             Zn
19    8.00       0.000000             Cu
20    9.04       0.000000    background1
21    4.76       0.000000          Ti kb

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [8]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Al': VE = 87.97%, dim = 15 variáveis
Zona 'Si': VE = 96.43%, dim = 12 variáveis
Zona 'P': VE = 62.58%, dim = 17 variáveis
Zona 'S': VE = 44.25%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 73.64%, dim = 33 variáveis
Zona 'K': VE = 95.35%, dim = 16 variáveis
Zona 'Ca ka': VE = 98.88%, dim = 16 variáveis
Zona 'Ca kb': VE = 74.22%, dim = 27 variáveis
Zona 'Ti ka': VE = 85.88%, dim = 19 variáveis
Zona 'Ti kb': VE = 88.37%, dim = 19 variáveis
Zona 'Cr': VE = 82.96%, dim = 33 variáveis
Zona 'Mn': VE = 94.39%, dim = 18 variáveis
Zona 'Fe ka': VE = 91.33%, dim = 34 variáveis
Zona 'Fe kb': VE = 90.72%, dim = 26 variáveis
Zona 'Ni': VE = 58.25%, dim = 31 variáveis
Zona 'Cu': VE = 84.29%, dim = 15 variáveis
Zona 'Zn': VE = 60.20%, dim = 41 variáveis
Zona 'background1': VE = 61.89%, dim = 85 variáveis
Zona 'Fe ka + Ti ka': VE = 55.37%, dim = 23 variáveis
Zona 'background2': VE = 50.79%, dim = 71 variáveis
Zona 'sum Fe': VE = 90.84%, dim = 28 variáveis

Scores DataFrame shape: (501, 21)

In [9]:
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred_cont
)

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 134
Removida: Fe ka <= 11.65 -> Fe ka > -9.83 (12.6096) | Mantida: Fe ka > -9.83 -> Fe ka <= 11.65 (18.8564)
Removida: Fe kb <= 4.31 -> Fe kb > -3.67 (4.6255) | Mantida: Fe kb > -3.67 -> Fe kb <= 4.31 (6.9028)
Removida: Mn <= 1.02 -> sum Fe <= 1.27 (0.6748) | Mantida: sum Fe <= 1.27 -> Mn <= 1.02 (2.2858)
Removida: Fe ka <= -5.77 -> sum Fe <= 1.27 (0.3169) | Mantida: sum Fe <= 1.27 -> Fe ka <= -5.77 (0.6450)
Removida: Fe ka <= -5.77 -> Ca ka > -1.89 (0.6231) | Mantida: Ca ka > -1.89 -> Fe ka <= -5.77 (0.7010)
Removida: Ca ka > -1.89 -> Ti ka > -1.99 (0.3005) | Mantida: Ti ka > -1.99 -> Ca ka > -1.89 (1.2927)
Removida: Ti ka > -1.99 -> Ca ka > -0.35 (0.2621) | Mantida: Ca ka > -0.35 -> Ti ka > -1.99 (0.5813)
Removida: Ti ka > -1.99 -> Ca ka > -1.23 (0.2496) | Mantida: Ca ka > -1.23 -> Ti ka > -1.99 (0.6031)
Removida: Ca ka > -1.23 -> Ca ka > -1.89 (0.3488) | Mantida: Ca ka > -1.89 -> Ca ka > -1.23 (1.1738)
Removida: Ca ka > -1.23 -> Ca ka > -0.35 (0.2996) | Mantida: Ca ka > -0.35 -> Ca ka > -1.23 (0.6031)
Removida: Rh L + Ar > -0.69 -> Fe ka > 4.25 (0.1719) | Mantida: Fe ka > 4.25 -> Rh L + Ar > -0.69 (0.6759)
Removida: Ti ka > -0.55 -> Fe ka > 4.25 (0.1925) | Mantida: Fe ka > 4.25 -> Ti ka > -0.55 (0.2216)
Removida: Fe ka > 4.25 -> Si > -1.03 (0.1944) | Mantida: Si > -1.03 -> Fe ka > 4.25 (0.2141)
Removida: Rh L + Ar <= 0.76 -> Rh L + Ar > -0.69 (0.5157) | Mantida: Rh L + Ar > -0.69 -> Rh L + Ar <= 0.76 (0.5211)
Removida: Rh L + Ar > -0.69 -> Ti kb <= 1.01 (0.1758) | Mantida: Ti kb <= 1.01 -> Rh L + Ar > -0.69 (0.4225)
Removida: Rh L + Ar <= 0.76 -> Mn > -0.74 (0.1678) | Mantida: Mn > -0.74 -> Rh L + Ar <= 0.76 (0.2216)
Removida: Si > -1.03 -> Ti kb > -1.01 (0.2323) | Mantida: Ti kb > -1.01 -> Si > -1.03 (0.4062)
Removida: Ti kb <= 1.01 -> Ti kb > -1.01 (0.3903) | Mantida: Ti kb > -1.01 -> Ti kb <= 1.01 (0.4167)
Removida: Ti ka > -0.55 -> Ca ka > -0.35 (0.1963) | Mantida: Ca ka > -0.35 -> Ti ka > -0.55 (0.2240)
Removida: Si > -1.03 -> Ti ka > -0.55 (0.2197) | Mantida: Ti ka > -0.55 -> Si > -1.03 (0.3718)
Removida: Ti kb <= 1.01 -> Ca ka > -0.35 (0.2019) | Mantida: Ca ka > -0.35 -> Ti kb <= 1.01 (0.7017)
Removida: Ti kb > -0.36 -> Ca ka > -0.35 (0.1564) | Mantida: Ca ka > -0.35 -> Ti kb > -0.36 (0.1696)
Removida: Cr <= 0.70 -> Si > -1.03 (0.1709) | Mantida: Si > -1.03 -> Cr <= 0.70 (0.6108)
Removida: Cr > -0.67 -> Si > -1.03 (0.1737) | Mantida: Si > -1.03 -> Cr > -0.67 (0.4042)
Removida: sum Fe > -0.60 -> Mn > -0.74 (0.3904) | Mantida: Mn > -0.74 -> sum Fe > -0.60 (0.4147)
Removida: sum Fe > -0.60 -> Si <= 1.00 (0.1981) | Mantida: Si <= 1.00 -> sum Fe > -0.60 (0.2205)
Removida: Si <= 1.00 -> Mn > -0.74 (0.1935) | Mantida: Mn > -0.74 -> Si <= 1.00 (0.3995)
Removida: Si <= 1.00 -> Cr > -0.67 (0.4029) | Mantida: Cr > -0.67 -> Si <= 1.00 (0.6821)
Removida: Cr <= 0.70 -> Cr > -0.67 (0.1731) | Mantida: Cr > -0.67 -> Cr <= 0.70 (0.5169)
Removida: Mn <= 0.30 -> Ti kb > -0.36 (0.1528) | Mantida: Ti kb > -0.36 -> Mn <= 0.30 (0.7405)
Removida: sum Fe <= 0.39 -> Mn <= 0.30 (0.1396) | Mantida: Mn <= 0.30 -> sum Fe <= 0.39 (0.7217)
Removida: Cu <= 0.48 -> Mn <= 0.30 (0.3812) | Mantida: Mn <= 0.30 -> Cu <= 0.48 (0.4402)
Removida: sum Fe <= 0.39 -> Cu <= 0.48 (0.2761) | Mantida: Cu <= 0.48 -> sum Fe <= 0.39 (0.5148)
Removida: Fe kb <= -2.08 -> Cu > -0.46 (0.1266) | Mantida: Cu > -0.46 -> Fe kb <= -2.08 (0.4641)
Removida: Ca ka <= 1.70 -> Ca kb > -0.51 (0.1035) | Mantida: Ca kb > -0.51 -> Ca ka <= 1.70 (0.1448)
Removida: Rh L + Ar > -0.44 -> Fe kb <= -2.08 (0.1005) | Mantida: Fe kb <= -2.08 -> Rh L + Ar > -0.44 (0.3524)
Removida: Rh L + Ar > -0.44 -> Cr > -0.21 (0.1776) | Mantida: Cr > -0.21 -> Rh L + Ar > -0.44 (0.3177)
Removida: Rh L + Ar > -0.44 -> Ti ka <= 1.87 (0.0960) | Mantida: Ti ka <= 1.87 -> Rh L + Ar > -0.44 (0.1055)
Removida: Rh L + Ar > -0.44 -> Ti kb <= 0.24 (0.0935) | Mantida: Ti kb <= 0.24 -> Rh L + Ar > -0.44 (0.1138)
Removida: Si > -0.46 -> Ti kb <= 0.24 (0.1137) | Mantida: Ti kb <= 0.24 -> Si > -0.46 (0.3053)
Removida: Ti kb <= 0.24 -> Cr > -0.21 (0.1102) | Mantida: Cr > -0.21 -> Ti kb <= 0.24 (0.2013)
Removida: Al > -0.53 -> Ti kb <= 0.24 (0.1930) | Mantida: Ti kb <= 0.24 -> Al > -0.53 (0.2072)
Removida: Ti kb <= 0.24 -> Ti ka <= 1.87 (0.1122) | Mantida: Ti ka <= 1.87 -> Ti kb <= 0.24 (0.2119)
Removida: Ca kb > -0.51 -> Al > -0.53 (0.0805) | Mantida: Al > -0.53 -> Ca kb > -0.51 (0.1951)
Removida: Ti kb <= -0.36 -> Cr <= 0.18 (0.0905) | Mantida: Cr <= 0.18 -> Ti kb <= -0.36 (0.1598)
Removida: Ca kb > -0.51 -> Cr <= 0.18 (0.0771) | Mantida: Cr <= 0.18 -> Ca kb > -0.51 (0.1667)
Removida: Cr <= 0.18 -> Al > -0.20 (0.0872) | Mantida: Al > -0.20 -> Cr <= 0.18 (0.0884)
Removida: Fe kb > 1.44 -> Ti ka <= 1.87 (0.0777) | Mantida: Ti ka <= 1.87 -> Fe kb > 1.44 (0.0939)
Removida: Ti ka <= 1.87 -> Si <= 0.21 (0.0732) | Mantida: Si <= 0.21 -> Ti ka <= 1.87 (0.0855)
Removida: Al > -0.20 -> Ca kb <= 0.45 (0.0894) | Mantida: Ca kb <= 0.45 -> Al > -0.20 (0.1486)
Removida: Ca kb <= 0.45 -> Ti kb <= -0.36 (0.1501) | Mantida: Ti kb <= -0.36 -> Ca kb <= 0.45 (0.1688)
Removida: Ti kb <= -0.36 -> Al > -0.20 (0.1816) | Mantida: Al > -0.20 -> Ti kb <= -0.36 (0.2662)
Removida: Al > -0.20 -> Fe kb > 1.44 (0.0843) | Mantida: Fe kb > 1.44 -> Al > -0.20 (0.1740)
Removida: Ca kb > -0.51 -> Ti kb <= -0.36 (0.0761) | Mantida: Ti kb <= -0.36 -> Ca kb > -0.51 (0.0855)
Removida: Rh L + Ar <= 0.33 -> Ca kb > -0.51 (0.0668) | Mantida: Ca kb > -0.51 -> Rh L + Ar <= 0.33 (0.0713)
Removida: Fe kb > 1.44 -> Rh L + Ar <= 0.33 (0.1635) | Mantida: Rh L + Ar <= 0.33 -> Fe kb > 1.44 (0.1993)
Removida: Si <= 0.21 -> Rh L + Ar <= 0.33 (0.0908) | Mantida: Rh L + Ar <= 0.33 -> Si <= 0.21 (0.1400)
Removida: Fe kb > 1.44 -> Si <= 0.21 (0.2444) | Mantida: Si <= 0.21 -> Fe kb > 1.44 (0.2561)
Removida: background1 > -0.46 -> Ca kb <= 0.02 (0.0947) | Mantida: Ca kb <= 0.02 -> background1 > -0.46 (0.2257)
Removida: Cu <= 0.18 -> Ca kb <= 0.02 (0.1251) | Mantida: Ca kb <= 0.02 -> Cu <= 0.18 (0.1658)
Removida: Cu <= 0.18 -> background1 > -0.46 (0.1235) | Mantida: background1 > -0.46 -> Cu <= 0.18 (0.1878)
Removida: Ti kb > 0.24 -> Cu > -0.21 (0.0580) | Mantida: Cu > -0.21 -> Ti kb > 0.24 (0.2307)
Removida: Cu > -0.21 -> Al > 0.14 (0.0538) | Mantida: Al > 0.14 -> Cu > -0.21 (0.0583)
Removida: background1 > -0.15 -> Cu > -0.21 (0.0402) | Mantida: Cu > -0.21 -> background1 > -0.15 (0.2172)
Removida: Al > 0.14 -> Ti kb > 0.24 (0.0615) | Mantida: Ti kb > 0.24 -> Al > 0.14 (0.1182)
Removida: background1 > -0.15 -> Ti kb > 0.24 (0.0368) | Mantida: Ti kb > 0.24 -> background1 > -0.15 (0.1099)
Removida: background1 > -0.15 -> Al > 0.14 (0.0387) | Mantida: Al > 0.14 -> background1 > -0.15 (0.1686)
Removida: background2 > -0.34 -> Al > 0.14 (0.0294) | Mantida: Al > 0.14 -> background2 > -0.34 (0.1612)
Removida: background1 > -0.15 -> Ca kb > 0.02 (0.0387) | Mantida: Ca kb > 0.02 -> background1 > -0.15 (0.0483)
Removida: Cr <= -0.21 -> background2 > -0.34 (0.0960) | Mantida: background2 > -0.34 -> Cr <= -0.21 (0.1139)
Removida: Cr <= -0.21 -> Al <= 0.58 (0.0460) | Mantida: Al <= 0.58 -> Cr <= -0.21 (0.0936)
Removida: Si <= -0.46 -> Cr <= -0.21 (0.0541) | Mantida: Cr <= -0.21 -> Si <= -0.46 (0.1728)
Removida: Al <= 0.58 -> K > -0.01 (0.0437) | Mantida: K > -0.01 -> Al <= 0.58 (0.0447)
Removida: Al <= 0.58 -> Si <= -0.46 (0.0479) | Mantida: Si <= -0.46 -> Al <= 0.58 (0.0981)
Removida: Si <= -0.46 -> K > -0.01 (0.0438) | Mantida: K > -0.01 -> Si <= -0.46 (0.0493)
Removida: background1 <= 0.48 -> Cr > 0.18 (0.0269) | Mantida: Cr > 0.18 -> background1 <= 0.48 (0.0397)
Removida: background1 <= 0.48 -> Ca ka <= -0.35 (0.0255) | Mantida: Ca ka <= -0.35 -> background1 <= 0.48 (0.0407)
Removida: background2 > -0.12 -> background1 <= 0.48 (0.0214) | Mantida: background1 <= 0.48 -> background2 > -0.12 (0.0285)
Removida: Ca kb <= -0.25 -> background2 > -0.12 (0.0315) | Mantida: background2 > -0.12 -> Ca kb <= -0.25 (0.0407)
Removida: Fe ka + Ti ka <= 0.26 -> background2 > -0.12 (0.0215) | Mantida: background2 > -0.12 -> Fe ka + Ti ka <= 0.26 (0.0421)
Removida: Ca kb <= -0.25 -> background1 <= 0.48 (0.0301) | Mantida: background1 <= 0.48 -> Ca kb <= -0.25 (0.0790)
Removida: Fe ka + Ti ka <= 0.26 -> sum Fe > 0.39 (0.0423) | Mantida: sum Fe > 0.39 -> Fe ka + Ti ka <= 0.26 (0.1021)
Removida: sum Fe <= -0.60 -> sum Fe > 0.39 (0.0338) | Mantida: sum Fe > 0.39 -> sum Fe <= -0.60 (0.0692)
Removida: Fe ka + Ti ka <= 0.26 -> P > -0.32 (0.0219) | Mantida: P > -0.32 -> Fe ka + Ti ka <= 0.26 (0.0231)
Removida: P > -0.16 -> sum Fe <= -0.60 (0.0225) | Mantida: sum Fe <= -0.60 -> P > -0.16 (0.0333)
Removida: Mn <= -0.74 -> sum Fe <= -0.60 (0.0355) | Mantida: sum Fe <= -0.60 -> Mn <= -0.74 (0.0980)
Removida: P > -0.32 -> Mn <= -0.74 (0.0223) | Mantida: Mn <= -0.74 -> P > -0.32 (0.0682)
Removida: Fe ka + Ti ka <= 0.11 -> P > -0.32 (0.0200) | Mantida: P > -0.32 -> Fe ka + Ti ka <= 0.11 (0.0460)
Removida: Zn > -0.08 -> P > -0.32 (0.0192) | Mantida: P > -0.32 -> Zn > -0.08 (0.0208)
Removida: background2 <= 0.35 -> Mn <= -0.74 (0.0186) | Mantida: Mn <= -0.74 -> background2 <= 0.35 (0.0328)
Removida: Zn > -0.31 -> Fe ka + Ti ka <= 0.11 (0.0208) | Mantida: Fe ka + Ti ka <= 0.11 -> Zn > -0.31 (0.0566)
Removida: Zn > -0.08 -> Zn > -0.31 (0.0187) | Mantida: Zn > -0.31 -> Zn > -0.08 (0.0370)
Removida: background2 <= 0.35 -> Fe ka + Ti ka <= 0.11 (0.0174) | Mantida: Fe ka + Ti ka <= 0.11 -> background2 <= 0.35 (0.0369)
Removida: Fe ka + Ti ka <= 0.11 -> Zn > -0.08 (0.0185) | Mantida: Zn > -0.08 -> Fe ka + Ti ka <= 0.11 (0.0207)
Removida: Fe ka + Ti ka <= 0.11 -> P > -0.16 (0.0177) | Mantida: P > -0.16 -> Fe ka + Ti ka <= 0.11 (0.0212)
Removida: Fe ka + Ti ka <= -0.06 -> background1 > 0.08 (0.0147) | Mantida: background1 > 0.08 -> Fe ka + Ti ka <= -0.06 (0.0159)
Removida: Zn > 0.10 -> Zn > -0.08 (0.0203) | Mantida: Zn > -0.08 -> Zn > 0.10 (0.0714)
Removida: background2 > 0.08 -> Zn > 0.10 (0.0155) | Mantida: Zn > 0.10 -> background2 > 0.08 (0.0496)
Removida: Zn > 0.10 -> P > 0.02 (0.0157) | Mantida: P > 0.02 -> Zn > 0.10 (0.0373)
Removida: background2 > 0.08 -> Ni <= 0.09 (0.0124) | Mantida: Ni <= 0.09 -> background2 > 0.08 (0.0139)
Removida: Ni > -0.06 -> background2 > 0.08 (0.0162) | Mantida: background2 > 0.08 -> Ni > -0.06 (0.0263)
Removida: Fe ka + Ti ka <= -0.06 -> background2 > 0.08 (0.0158) | Mantida: background2 > 0.08 -> Fe ka + Ti ka <= -0.06 (0.0275)
Removida: Ni > -0.06 -> Ca ka <= -1.23 (0.0159) | Mantida: Ca ka <= -1.23 -> Ni > -0.06 (0.0234)
Removida: P > 0.02 -> Ni > -0.28 (0.0159) | Mantida: Ni > -0.28 -> P > 0.02 (0.0180)
Removida: Fe ka + Ti ka <= -0.06 -> Ni > -0.06 (0.0143) | Mantida: Ni > -0.06 -> Fe ka + Ti ka <= -0.06 (0.0148)
Removida: Fe ka + Ti ka <= -0.06 -> Ni <= 0.09 (0.0140) | Mantida: Ni <= 0.09 -> Fe ka + Ti ka <= -0.06 (0.0142)
Removida: Ni > -0.28 -> K <= 0.22 (0.0137) | Mantida: K <= 0.22 -> Ni > -0.28 (0.0205)
Removida: Ni > -0.28 -> P <= 0.30 (0.0125) | Mantida: P <= 0.30 -> Ni > -0.28 (0.0142)
Removida: Ni > -0.28 -> Si > 0.21 (0.0147) | Mantida: Si > 0.21 -> Ni > -0.28 (0.0234)
Removida: Ni > 0.09 -> Ni > -0.28 (0.0130) | Mantida: Ni > -0.28 -> Ni > 0.09 (0.0133)
Removida: P <= 0.30 -> K <= 0.22 (0.0136) | Mantida: K <= 0.22 -> P <= 0.30 (0.0203)
Removida: P <= 0.30 -> Ni <= 0.09 (0.0130) | Mantida: Ni <= 0.09 -> P <= 0.30 (0.0131)
Removida: Ni <= 0.09 -> Cu <= -0.21 (0.0125) | Mantida: Cu <= -0.21 -> Ni <= 0.09 (0.0168)
Removida: P <= 0.30 -> Zn <= -0.08 (0.0133) | Mantida: Zn <= -0.08 -> P <= 0.30 (0.0135)
Removida: Rh L + Ar <= -0.44 -> Zn <= -0.08 (0.0100) | Mantida: Zn <= -0.08 -> Rh L + Ar <= -0.44 (0.0158)
Removida: Zn <= -0.08 -> K <= -0.19 (0.0119) | Mantida: K <= -0.19 -> Zn <= -0.08 (0.0138)
Removida: Zn <= -0.08 -> Si > 0.21 (0.0113) | Mantida: Si > 0.21 -> Zn <= -0.08 (0.0152)
Removida: Zn <= 0.10 -> Cu <= -0.21 (0.0247) | Mantida: Cu <= -0.21 -> Zn <= 0.10 (0.0505)
Removida: Ni <= 0.26 -> Cu <= -0.21 (0.0117) | Mantida: Cu <= -0.21 -> Ni <= 0.26 (0.0166)
Removida: Ni <= 0.26 -> Zn <= 0.10 (0.0099) | Mantida: Zn <= 0.10 -> Ni <= 0.26 (0.0232)
Removida: Ni <= -0.06 -> Ni > 0.09 (0.0116) | Mantida: Ni > 0.09 -> Ni <= -0.06 (0.0136)
Removida: S <= 0.16 -> K > -0.35 (0.0056) | Mantida: K > -0.35 -> S <= 0.16 (0.0174)
Removida: K > -0.35 -> K <= -0.01 (0.0117) | Mantida: K <= -0.01 -> K > -0.35 (0.0142)
Removida: S <= 0.16 -> S <= 0.04 (0.0131) | Mantida: S <= 0.04 -> S <= 0.16 (0.0137)
Removida: S <= 0.16 -> background2 <= 0.08 (0.0067) | Mantida: background2 <= 0.08 -> S <= 0.16 (0.0080)
Removida: S <= 0.16 -> K <= -0.01 (0.0137) | Mantida: K <= -0.01 -> S <= 0.16 (0.0291)
Removida: Rh L + Ar <= -0.44 -> K <= -0.19 (0.0091) | Mantida: K <= -0.19 -> Rh L + Ar <= -0.44 (0.0367)
Removida: Ni <= 0.26 -> P <= 0.02 (0.0101) | Mantida: P <= 0.02 -> Ni <= 0.26 (0.0226)
Removida: P <= 0.02 -> S <= 0.04 (0.0102) | Mantida: S <= 0.04 -> P <= 0.02 (0.0212)
Removida: Zn <= 0.32 -> S <= 0.04 (0.0096) | Mantida: S <= 0.04 -> Zn <= 0.32 (0.0206)
Removida: P <= -0.16 -> background2 <= 0.08 (0.0073) | Mantida: background2 <= 0.08 -> P <= -0.16 (0.0075)
Removida: S <= -0.07 -> background2 <= 0.08 (0.0047) | Mantida: background2 <= 0.08 -> S <= -0.07 (0.0056)
Removida: P <= -0.16 -> Ti ka <= 0.61 (0.0091) | Mantida: Ti ka <= 0.61 -> P <= -0.16 (0.0101)
Removida: P <= -0.16 -> Al <= 0.14 (0.0076) | Mantida: Al <= 0.14 -> P <= -0.16 (0.0131)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 695 | Removidas: 134
Nós predicados: 116
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 147
Removida: Fe ka <= 11.65 -> Fe ka > -9.83 (3.1783) | Mantida: Fe ka > -9.83 -> Fe ka <= 11.65 (28.5052)
Removida: Fe kb <= 4.31 -> Fe kb > -3.67 (1.1756) | Mantida: Fe kb > -3.67 -> Fe kb <= 4.31 (10.4297)
Removida: sum Fe <= 1.27 -> sum Fe > -1.11 (0.3335) | Mantida: sum Fe > -1.11 -> sum Fe <= 1.27 (1.7356)
Removida: Mn <= 1.02 -> sum Fe <= 1.27 (0.9959) | Mantida: sum Fe <= 1.27 -> Mn <= 1.02 (1.2883)
Removida: sum Fe <= 1.27 -> Ca ka > -1.89 (0.3082) | Mantida: Ca ka > -1.89 -> sum Fe <= 1.27 (0.3742)
Removida: Ti ka > -1.99 -> sum Fe <= 1.27 (0.3079) | Mantida: sum Fe <= 1.27 -> Ti ka > -1.99 (0.6353)
Removida: Fe ka <= -5.77 -> Mn <= 1.02 (0.3210) | Mantida: Mn <= 1.02 -> Fe ka <= -5.77 (0.9929)
Removida: Ti ka > -1.99 -> Mn <= 1.02 (0.2963) | Mantida: Mn <= 1.02 -> Ti ka > -1.99 (0.6654)
Removida: Mn <= 1.02 -> Ca ka > -1.89 (0.3231) | Mantida: Ca ka > -1.89 -> Mn <= 1.02 (0.3311)
Removida: Fe ka <= -5.77 -> Ti ka > -1.99 (0.5806) | Mantida: Ti ka > -1.99 -> Fe ka <= -5.77 (0.8471)
Removida: Ca ka > -1.89 -> Fe ka <= -5.77 (0.6124) | Mantida: Fe ka <= -5.77 -> Ca ka > -1.89 (1.1067)
Removida: Ti ka > -1.99 -> Ca ka > -1.89 (0.2766) | Mantida: Ca ka > -1.89 -> Ti ka > -1.99 (0.2997)
Removida: Ti ka > -1.99 -> Ca ka > -0.35 (0.2569) | Mantida: Ca ka > -0.35 -> Ti ka > -1.99 (0.2972)
Removida: Ca ka > -1.23 -> Ca ka > -1.89 (0.3019) | Mantida: Ca ka > -1.89 -> Ca ka > -1.23 (1.1953)
Removida: Fe ka > 4.25 -> Ca ka > -0.35 (0.2057) | Mantida: Ca ka > -0.35 -> Fe ka > 4.25 (0.5532)
Removida: Rh L + Ar > -0.69 -> Ti kb > -1.01 (0.5192) | Mantida: Ti kb > -1.01 -> Rh L + Ar > -0.69 (0.6493)
Removida: Fe ka > 4.25 -> Ti kb > -1.01 (0.2209) | Mantida: Ti kb > -1.01 -> Fe ka > 4.25 (0.4327)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka <= 11.65,Fe ka > -9.83,Fe ka <= 11.65,Fe ka <= 11.65
1,Fe ka > -9.83,Fe ka <= 11.65,Fe ka > -9.83,Fe ka > -9.83
2,Fe ka > -5.77,Fe ka > -5.77,Fe ka > -5.77,Fe ka > -5.77
3,Fe ka <= 4.25,Fe ka <= 4.25,Fe ka <= 4.25,Fe ka <= 4.25
4,Fe kb <= 4.31,Fe kb > -3.67,Fe kb <= 4.31,Fe kb > -3.67
...,...,...,...,...
116,Class_A,Zn <= 0.32,Mn > 0.30,background2 <= 0.08
117,Class_B,Ni > -0.28,Class_A,Class_A
118,NaN,background1 <= -0.15,Class_B,Class_B
119,NaN,Class_A,NaN,NaN
120,NaN,Class_B,NaN,NaN

In [11]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -9.83,18.150354,Fe ka,-9.83,>
1,Fe kb > -3.67,7.874621,Fe kb,-3.67,>
2,Mn > -1.21,2.886596,Mn,-1.21,>
3,sum Fe > -1.11,1.677744,sum Fe,-1.11,>
4,Ca ka > -1.89,1.249961,Ca ka,-1.89,>
5,Cr <= 0.70,1.233161,Cr,0.70,<=
6,Si > -1.03,1.205354,Si,-1.03,>
7,Ti kb > -1.01,1.192183,Ti kb,-1.01,>
8,Rh L + Ar > -0.69,1.150659,Rh L + Ar,-0.69,>
9,Ti ka > -1.99,1.043970,Ti ka,-1.99,>
10,Cu <= 0.48,0.518220,Cu,0.48,<=
11,Al > -0.53,0.416539,Al,-0.53,>
12,Ca kb <= 0.45,0.416425,Ca kb,0.45,<=
13,background1 > -0.46,0.308949,background1,-0.46,>
14,background2 > -0.34,0.281253,background2,-0.34,>
15,K > -0.01,0.260492,K,-0.01,>
16,Fe ka + Ti ka <= 0.26,0.226200,Fe ka + Ti ka,0.26,<=
17,P > -0.32,0.221307,P,-0.32,>
18,Zn > -0.31,0.210109,Zn,-0.31,>
19,Ni <= 0.09,0.199820,Ni,0.09,<=
20,S <= 0.04,0.174343,S,0.04,<=
21,Class_B,0.000000,None,None,None

In [12]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Al': VE = 94.39%, dim = 15 variáveis
Zona 'Si': VE = 97.95%, dim = 12 variáveis
Zona 'P': VE = 63.93%, dim = 17 variáveis
Zona 'S': VE = 50.04%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 82.78%, dim = 33 variáveis
Zona 'K': VE = 97.13%, dim = 16 variáveis
Zona 'Ca ka': VE = 99.41%, dim = 16 variáveis
Zona 'Ca kb': VE = 73.60%, dim = 27 variáveis
Zona 'Ti ka': VE = 92.52%, dim = 19 variáveis
Zona 'Ti kb': VE = 91.98%, dim = 19 variáveis
Zona 'Cr': VE = 83.92%, dim = 33 variáveis
Zona 'Mn': VE = 95.74%, dim = 18 variáveis
Zona 'Fe ka': VE = 94.87%, dim = 34 variáveis
Zona 'Fe kb': VE = 94.17%, dim = 26 variáveis
Zona 'Ni': VE = 58.62%, dim = 31 variáveis
Zona 'Cu': VE = 85.47%, dim = 15 variáveis
Zona 'Zn': VE = 60.21%, dim = 41 variáveis
Zona 'background1': VE = 61.93%, dim = 85 variáveis
Zona 'Fe ka + Ti ka': VE = 58.87%, dim = 23 variáveis
Zona 'background2': VE = 51.14%, dim = 71 variáveis
Zona 'sum Fe': VE = 94.31%, dim = 28 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > -9.83,18.150354,Fe ka,-9.83,>,-178.952975,247.0,0.001731,Fe ka > -178.952975
1,Fe ka <= 11.65,17.850936,Fe ka,11.65,<=,188.786502,94.0,0.001158,Fe ka <= 188.786502
2,Fe ka > -5.77,13.578404,Fe ka,-5.77,>,-103.046579,408.0,0.004763,Fe ka > -103.046579
3,Fe ka <= 4.25,9.467533,Fe ka,4.25,<=,87.045387,38.0,0.001079,Fe ka <= 87.045387
4,Fe kb > -3.67,7.874621,Fe kb,-3.67,>,-25.194168,311.0,0.001842,Fe kb > -25.194168
...,...,...,...,...,...,...,...,...,...
116,Al <= -0.20,0.152320,Al,-0.20,<=,-0.386500,229.0,0.003328,Al <= -0.386500
117,Mn > 0.30,0.126641,Mn,0.30,>,0.465060,12.0,0.000253,Mn > 0.465060
118,S > 0.04,0.107822,S,0.04,>,0.036958,195.0,0.000109,S > 0.036958
119,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
120,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [28]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Range de energias: 6.14 - 6.8
  - Variância explicada pela PC1: 94.87%

In [14]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='regression',
        metric='mean_abs_diff', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): regression
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 126 predicados...
  Predicado: Al > -0.53 (n=318)
    Zona: 15 colunas
    Importance: 0.003863
  Predicado: Al <= -0.20 (n=156)
    Zona: 15 colunas
    Importance: 0.005098
  Predicado: Al > -0.20 (n=244)
    Zona: 15 colunas
    Importance: 0.004134
  Predicado: Al <= 0.14 (n=237)
    Zona: 15 colunas
    Importance: 0.003607
  Predicado: Al > 0.14 (n=163)
    Zona: 15 colunas
    Importance: 0.005824
  Predicado: Al <= 0.58 (n=317)
    Zona: 15 colunas
    Importance: 0.003532
  Predicado: Si > -1.03 (n=320)
    Zona: 12 colunas
    Importance: 0.001237
  Predicado: Si <= -0.46 (n=158)
    Zona: 12 colunas
    Importance: 0.001402
  Predicado: Si > -0.46 (n=242)
    Zona: 12 colunas
    Importance: 0.001361
  Predicado: Si <= 0.21 (n=239)
    Zona: 12 colunas
    Importance: 0.001005
  Predicado: Si > 0.21 (n=161)
    Zona: 12 colunas
    Importance: 0.001930
  Predicado: Si <= 1.00 (n=322)
    Zona: 12 colunas
    Importance: 0.001018
  Predicado: P > -0.32 (n=313)
    Zona: 17 colunas
    Importance: 0.000737
  Predicado: P <= -0.16 (n=164)
    Zona: 17 colunas
    Importance: 0.000710
  Predicado: P > -0.16 (n=236)
    Zona: 17 colunas
    Importance: 0.000828
  Predicado: P <= 0.02 (n=248)
    Zona: 17 colunas
    Importance: 0.000575
  Predicado: P > 0.02 (n=152)
    Zona: 17 colunas
    Importance: 0.001112
  Predicado: P <= 0.30 (n=318)
    Zona: 17 colunas
    Importance: 0.000570
  Predicado: S > -0.16 (n=312)
    Zona: 18 colunas
    Importance: 0.000136
  Predicado: S <= -0.07 (n=159)
    Zona: 18 colunas
    Importance: 0.000139
  Predicado: S > -0.07 (n=241)
    Zona: 18 colunas
    Importance: 0.000147
  Predicado: S <= 0.04 (n=241)
    Zona: 18 colunas
    Importance: 0.000119
  Predicado: S > 0.04 (n=159)
    Zona: 18 colunas
    Importance: 0.000183
  Predicado: S <= 0.16 (n=323)
    Zona: 18 colunas
    Importance: 0.000118
  Predicado: Rh L + Ar > -0.69 (n=321)
    Zona: 33 colunas
    Importance: 0.003938
  Predicado: Rh L + Ar <= -0.44 (n=157)
    Zona: 33 colunas
    Importance: 0.002986
  Predicado: Rh L + Ar > -0.44 (n=243)
    Zona: 33 colunas
    Importance: 0.004461
  Predicado: Rh L + Ar <= 0.33 (n=235)
    Zona: 33 colunas
    Importance: 0.002831
  Predicado: Rh L + Ar > 0.33 (n=165)
    Zona: 33 colunas
    Importance: 0.005378
  Predicado: Rh L + Ar <= 0.76 (n=320)
    Zona: 33 colunas
    Importance: 0.003377
  Predicado: K > -0.35 (n=322)
    Zona: 16 colunas
    Importance: 0.001550
  Predicado: K <= -0.19 (n=162)
    Zona: 16 colunas
    Importance: 0.001312
  Predicado: K > -0.19 (n=238)
    Zona: 16 colunas
    Importance: 0.001822
  Predicado: K <= -0.01 (n=243)
    Zona: 16 colunas
    Importance: 0.000955
  Predicado: K > -0.01 (n=157)
    Zona: 16 colunas
    Importance: 0.002638
  Predicado: K <= 0.22 (n=317)
    Zona: 16 colunas
    Importance: 0.000928
  Predicado: Ca ka > -1.89 (n=317)
    Zona: 16 colunas
    Importance: 0.047931
  Predicado: Ca ka <= -1.23 (n=163)
    Zona: 16 colunas
    Importance: 0.029065
  Predicado: Ca ka > -1.23 (n=237)
    Zona: 16 colunas
    Importance: 0.057562
  Predicado: Ca ka <= -0.35 (n=243)
    Zona: 16 colunas
    Importance: 0.021336
  Predicado: Ca ka > -0.35 (n=157)
    Zona: 16 colunas
    Importance: 0.084044
  Predicado: Ca ka <= 1.70 (n=323)
    Zona: 16 colunas
    Importance: 0.025171
  Predicado: Ca kb > -0.51 (n=321)
    Zona: 27 colunas
    Importance: 0.002503
  Predicado: Ca kb <= -0.25 (n=159)
    Zona: 27 colunas
    Importance: 0.001879
  Predicado: Ca kb > -0.25 (n=241)
    Zona: 27 colunas
    Importance: 0.002897
  Predicado: Ca kb <= 0.02 (n=238)
    Zona: 27 colunas
    Importance: 0.001472
  Predicado: Ca kb > 0.02 (n=162)
    Zona: 27 colunas
    Importance: 0.003992
  Predicado: Ca kb <= 0.45 (n=322)
    Zona: 27 colunas
    Importance: 0.001516
  Predicado: Ti ka > -1.99 (n=316)
    Zona: 19 colunas
    Importance: 0.040210
  Predicado: Ti ka <= -0.55 (n=161)
    Zona: 19 colunas
    Importance: 0.060520
  Predicado: Ti ka > -0.55 (n=239)
    Zona: 19 colunas
    Importance: 0.043427
  Predicado: Ti ka <= 0.61 (n=238)
    Zona: 19 colunas
    Importance: 0.044101
  Predicado: Ti ka > 0.61 (n=162)
    Zona: 19 colunas
    Importance: 0.059424
  Predicado: Ti ka <= 1.87 (n=320)
    Zona: 19 colunas
    Importance: 0.041216
  Predicado: Ti kb > -1.01 (n=319)
    Zona: 19 colunas
    Importance: 0.004300
  Predicado: Ti kb <= -0.36 (n=160)
    Zona: 19 colunas
    Importance: 0.005952
  Predicado: Ti kb > -0.36 (n=240)
    Zona: 19 colunas
    Importance: 0.004659
  Predicado: Ti kb <= 0.24 (n=240)
    Zona: 19 colunas
    Importance: 0.004373
  Predicado: Ti kb > 0.24 (n=160)
    Zona: 19 colunas
    Importance: 0.006381
  Predicado: Ti kb <= 1.01 (n=318)
    Zona: 19 colunas
    Importance: 0.004231
  Predicado: Cr > -0.67 (n=323)
    Zona: 33 colunas
    Importance: 0.000892
  Predicado: Cr <= -0.21 (n=159)
    Zona: 33 colunas
    Importance: 0.001335
  Predicado: Cr > -0.21 (n=241)
    Zona: 33 colunas
    Importance: 0.000969
  Predicado: Cr <= 0.18 (n=241)
    Zona: 33 colunas
    Importance: 0.001333
  Predicado: Cr > 0.18 (n=159)
    Zona: 33 colunas
    Importance: 0.000782
  Predicado: Cr <= 0.70 (n=318)
    Zona: 33 colunas
    Importance: 0.001179
  Predicado: Mn > -1.21 (n=322)
    Zona: 18 colunas
    Importance: 0.012673
  Predicado: Mn <= -0.74 (n=159)
    Zona: 18 colunas
    Importance: 0.009389
  Predicado: Mn > -0.74 (n=241)
    Zona: 18 colunas
    Importance: 0.014737
  Predicado: Mn <= 0.30 (n=242)
    Zona: 18 colunas
    Importance: 0.007358
  Predicado: Mn > 0.30 (n=158)
    Zona: 18 colunas
    Importance: 0.020657
  Predicado: Mn <= 1.02 (n=319)
    Zona: 18 colunas
    Importance: 0.008275
  Predicado: Fe ka > -9.83 (n=321)
    Zona: 34 colunas
    Importance: 0.342019
  Predicado: Fe ka <= -5.77 (n=158)
    Zona: 34 colunas
    Importance: 0.371452
  Predicado: Fe ka > -5.77 (n=242)
    Zona: 34 colunas
    Importance: 0.372174
  Predicado: Fe ka <= 4.25 (n=239)
    Zona: 34 colunas
    Importance: 0.290746
  Predicado: Fe ka > 4.25 (n=161)
    Zona: 34 colunas
    Importance: 0.492344
  Predicado: Fe ka <= 11.65 (n=316)
    Zona: 34 colunas
    Importance: 0.315511
  Predicado: Fe kb > -3.67 (n=322)
    Zona: 26 colunas
    Importance: 0.041188
  Predicado: Fe kb <= -2.08 (n=160)
    Zona: 26 colunas
    Importance: 0.047123
  Predicado: Fe kb > -2.08 (n=240)
    Zona: 26 colunas
    Importance: 0.044503
  Predicado: Fe kb <= 1.44 (n=240)
    Zona: 26 colunas
    Importance: 0.036847
  Predicado: Fe kb > 1.44 (n=160)
    Zona: 26 colunas
    Importance: 0.058607
  Predicado: Fe kb <= 4.31 (n=315)
    Zona: 26 colunas
    Importance: 0.039104
  Predicado: Ni > -0.28 (n=319)
    Zona: 31 colunas
    Importance: 0.001185
  Predicado: Ni <= -0.06 (n=163)
    Zona: 31 colunas
    Importance: 0.001762
  Predicado: Ni > -0.06 (n=237)
    Zona: 31 colunas
    Importance: 0.001279
  Predicado: Ni <= 0.09 (n=241)
    Zona: 31 colunas
    Importance: 0.001272
  Predicado: Ni > 0.09 (n=159)
    Zona: 31 colunas
    Importance: 0.001783
  Predicado: Ni <= 0.26 (n=320)
    Zona: 31 colunas
    Importance: 0.001205
  Predicado: Cu > -0.46 (n=323)
    Zona: 15 colunas
    Importance: 0.001431
  Predicado: Cu <= -0.21 (n=155)
    Zona: 15 colunas
    Importance: 0.001439
  Predicado: Cu > -0.21 (n=245)
    Zona: 15 colunas
    Importance: 0.001536
  Predicado: Cu <= 0.18 (n=238)
    Zona: 15 colunas
    Importance: 0.001166
  Predicado: Cu > 0.18 (n=162)
    Zona: 15 colunas
    Importance: 0.001987
  Predicado: Cu <= 0.48 (n=317)
    Zona: 15 colunas
    Importance: 0.001249
  Predicado: Zn > -0.31 (n=322)
    Zona: 41 colunas
    Importance: 0.001689
  Predicado: Zn <= -0.08 (n=166)
    Zona: 41 colunas
    Importance: 0.002394
  Predicado: Zn > -0.08 (n=234)
    Zona: 41 colunas
    Importance: 0.001852
  Predicado: Zn <= 0.10 (n=237)
    Zona: 41 colunas
    Importance: 0.001779
  Predicado: Zn > 0.10 (n=163)
    Zona: 41 colunas
    Importance: 0.002511
  Predicado: Zn <= 0.32 (n=324)
    Zona: 41 colunas
    Importance: 0.001704
  Predicado: background1 > -0.46 (n=313)
    Zona: 85 colunas
    Importance: 0.004131
  Predicado: background1 <= -0.15 (n=163)
    Zona: 85 colunas
    Importance: 0.005693
  Predicado: background1 > -0.15 (n=237)
    Zona: 85 colunas
    Importance: 0.004433
  Predicado: background1 <= 0.08 (n=240)
    Zona: 85 colunas
    Importance: 0.004065
  Predicado: background1 > 0.08 (n=160)
    Zona: 85 colunas
    Importance: 0.006268
  Predicado: background1 <= 0.48 (n=320)
    Zona: 85 colunas
    Importance: 0.003897
  Predicado: Fe ka + Ti ka > -0.25 (n=316)
    Zona: 23 colunas
    Importance: 0.000973
  Predicado: Fe ka + Ti ka <= -0.06 (n=159)
    Zona: 23 colunas
    Importance: 0.001545
  Predicado: Fe ka + Ti ka > -0.06 (n=241)
    Zona: 23 colunas
    Importance: 0.001045
  Predicado: Fe ka + Ti ka <= 0.11 (n=240)
    Zona: 23 colunas
    Importance: 0.001128
  Predicado: Fe ka + Ti ka > 0.11 (n=160)
    Zona: 23 colunas
    Importance: 0.001417
  Predicado: Fe ka + Ti ka <= 0.26 (n=320)
    Zona: 23 colunas
    Importance: 0.001081
  Predicado: background2 > -0.34 (n=314)
    Zona: 71 colunas
    Importance: 0.002325
  Predicado: background2 <= -0.12 (n=160)
    Zona: 71 colunas
    Importance: 0.003290
  Predicado: background2 > -0.12 (n=240)
    Zona: 71 colunas
    Importance: 0.002459
  Predicado: background2 <= 0.08 (n=242)
    Zona: 71 colunas
    Importance: 0.002334
  Predicado: background2 > 0.08 (n=158)
    Zona: 71 colunas
    Importance: 0.003492
  Predicado: background2 <= 0.35 (n=321)
    Zona: 71 colunas
    Importance: 0.002236
  Predicado: sum Fe > -1.11 (n=322)
    Zona: 28 colunas
    Importance: 0.003446
  Predicado: sum Fe <= -0.60 (n=155)
    Zona: 28 colunas
    Importance: 0.003516
  Predicado: sum Fe > -0.60 (n=245)
    Zona: 28 colunas
    Importance: 0.003717
  Predicado: sum Fe <= 0.39 (n=237)
    Zona: 28 colunas
    Importance: 0.002770
  Predicado: sum Fe > 0.39 (n=163)
    Zona: 28 colunas
    Importance: 0.004902
  Predicado: sum Fe <= 1.27 (n=315)
    Zona: 28 colunas
    Importance: 0.002999

[Bag_2] Processando 126 predicados...
  Predicado: Al > -0.53 (n=322)
    Zona: 15 colunas
    Importance: 0.003752
  Predicado: Al <= -0.20 (n=161)
    Zona: 15 colunas
    Importance: 0.004978
  Predicado: Al > -0.20 (n=239)
    Zona: 15 colunas
    Importance: 0.004045
  Predicado: Al <= 0.14 (n=242)
    Zona: 15 colunas
    Importance: 0.003552
  Predicado: Al > 0.14 (n=158)
    Zona: 15 colunas
    Importance: 0.005751
  Predicado: Al <= 0.58 (n=323)
    Zona: 15 colunas
    Importance: 0.003496
  Predicado: Si > -1.03 (n=324)
    Zona: 12 colunas
    Importance: 0.001192
  Predicado: Si <= -0.46 (n=159)
    Zona: 12 colunas
    Importance: 0.001352
  Predicado: Si > -0.46 (n=241)
    Zona: 12 colunas
    Importance: 0.001317
  Predicado: Si <= 0.21 (n=247)
    Zona: 12 colunas
    Importance: 0.000953
  Predicado: Si > 0.21 (n=153)
    Zona: 12 colunas
    Importance: 0.001942
  Predicado: Si <= 1.00 (n=326)
    Zona: 12 colunas
    Importance: 0.000978
  Predicado: P > -0.32 (n=318)
    Zona: 17 colunas
    Importance: 0.000730
  Predicado: P <= -0.16 (n=161)
    Zona: 17 colunas
    Importance: 0.000696
  Predicado: P > -0.16 (n=239)
    Zona: 17 colunas
    Importance: 0.000826
  Predicado: P <= 0.02 (n=243)
    Zona: 17 colunas
    Importance: 0.000563
  Predicado: P > 0.02 (n=157)
    Zona: 17 colunas
    Importance: 0.001099
  Predicado: P <= 0.30 (n=316)
    Zona: 17 colunas
    Importance: 0.000551
  Predicado: S > -0.16 (n=318)
    Zona: 18 colunas
    Importance: 0.000136
  Predicado: S <= -0.07 (n=160)
    Zona: 18 colunas
    Importance: 0.000141
  Predicado: S > -0.07 (n=240)
    Zona: 18 colunas
    Importance: 0.000147
  Predicado: S <= 0.04 (n=247)
    Zona: 18 colunas
    Importance: 0.000120
  Predicado: S > 0.04 (n=153)
    Zona: 18 colunas
    Importance: 0.000184
  Predicado: S <= 0.16 (n=326)
    Zona: 18 colunas
    Importance: 0.000119
  Predicado: Rh L + Ar > -0.69 (n=320)
    Zona: 33 colunas
    Importance: 0.003832
  Predicado: Rh L + Ar <= -0.44 (n=166)
    Zona: 33 colunas
    Importance: 0.002998
  Predicado: Rh L + Ar > -0.44 (n=234)
    Zona: 33 colunas
    Importance: 0.004387
  Predicado: Rh L + Ar <= 0.33 (n=242)
    Zona: 33 colunas
    Importance: 0.002802
  Predicado: Rh L + Ar > 0.33 (n=158)
    Zona: 33 colunas
    Importance: 0.005356
  Predicado: Rh L + Ar <= 0.76 (n=324)
    Zona: 33 colunas
    Importance: 0.003330
  Predicado: K > -0.35 (n=315)
    Zona: 16 colunas
    Importance: 0.001547
  Predicado: K <= -0.19 (n=169)
    Zona: 16 colunas
    Importance: 0.001336
  Predicado: K > -0.19 (n=231)
    Zona: 16 colunas
    Importance: 0.001826
  Predicado: K <= -0.01 (n=249)
    Zona: 16 colunas
    Importance: 0.000982
  Predicado: K > -0.01 (n=151)
    Zona: 16 colunas
    Importance: 0.002669
  Predicado: K <= 0.22 (n=320)
    Zona: 16 colunas
    Importance: 0.000967
  Predicado: Ca ka > -1.89 (n=315)
    Zona: 16 colunas
    Importance: 0.046427
  Predicado: Ca ka <= -1.23 (n=169)
    Zona: 16 colunas
    Importance: 0.028804
  Predicado: Ca ka > -1.23 (n=231)
    Zona: 16 colunas
    Importance: 0.056264
  Predicado: Ca ka <= -0.35 (n=249)
    Zona: 16 colunas
    Importance: 0.021323
  Predicado: Ca ka > -0.35 (n=151)
    Zona: 16 colunas
    Importance: 0.083148
  Predicado: Ca ka <= 1.70 (n=323)
    Zona: 16 colunas
    Importance: 0.024828
  Predicado: Ca kb > -0.51 (n=313)
    Zona: 27 colunas
    Importance: 0.002442
  Predicado: Ca kb <= -0.25 (n=162)
    Zona: 27 colunas
    Importance: 0.001877
  Predicado: Ca kb > -0.25 (n=238)
    Zona: 27 colunas
    Importance: 0.002801
  Predicado: Ca kb <= 0.02 (n=249)
    Zona: 27 colunas
    Importance: 0.001450
  Predicado: Ca kb > 0.02 (n=151)
    Zona: 27 colunas
    Importance: 0.004038
  Predicado: Ca kb <= 0.45 (n=324)
    Zona: 27 colunas
    Importance: 0.001487
  Predicado: Ti ka > -1.99 (n=320)
    Zona: 19 colunas
    Importance: 0.038958
  Predicado: Ti ka <= -0.55 (n=161)
    Zona: 19 colunas
    Importance: 0.060199
  Predicado: Ti ka > -0.55 (n=239)
    Zona: 19 colunas
    Importance: 0.041172
  Predicado: Ti ka <= 0.61 (n=244)
    Zona: 19 colunas
    Importance: 0.042914
  Predicado: Ti ka > 0.61 (n=156)
    Zona: 19 colunas
    Importance: 0.058084
  Predicado: Ti ka <= 1.87 (n=325)
    Zona: 19 colunas
    Importance: 0.040444
  Predicado: Ti kb > -1.01 (n=318)
    Zona: 19 colunas
    Importance: 0.004139
  Predicado: Ti kb <= -0.36 (n=163)
    Zona: 19 colunas
    Importance: 0.005832
  Predicado: Ti kb > -0.36 (n=237)
    Zona: 19 colunas
    Importance: 0.004483
  Predicado: Ti kb <= 0.24 (n=245)
    Zona: 19 colunas
    Importance: 0.004290
  Predicado: Ti kb > 0.24 (n=155)
    Zona: 19 colunas
    Importance: 0.006206
  Predicado: Ti kb <= 1.01 (n=323)
    Zona: 19 colunas
    Importance: 0.004141
  Predicado: Cr > -0.67 (n=319)
    Zona: 33 colunas
    Importance: 0.000843
  Predicado: Cr <= -0.21 (n=165)
    Zona: 33 colunas
    Importance: 0.001325
  Predicado: Cr > -0.21 (n=235)
    Zona: 33 colunas
    Importance: 0.000897
  Predicado: Cr <= 0.18 (n=240)
    Zona: 33 colunas
    Importance: 0.001307
  Predicado: Cr > 0.18 (n=160)
    Zona: 33 colunas
    Importance: 0.000723
  Predicado: Cr <= 0.70 (n=324)
    Zona: 33 colunas
    Importance: 0.001139
  Predicado: Mn > -1.21 (n=315)
    Zona: 18 colunas
    Importance: 0.012470
  Predicado: Mn <= -0.74 (n=166)
    Zona: 18 colunas
    Importance: 0.009338
  Predicado: Mn > -0.74 (n=234)
    Zona: 18 colunas
    Importance: 0.014545
  Predicado: Mn <= 0.30 (n=245)
    Zona: 18 colunas
    Importance: 0.007446
  Predicado: Mn > 0.30 (n=155)
    Zona: 18 colunas
    Importance: 0.020188
  Predicado: Mn <= 1.02 (n=325)
    Zona: 18 colunas
    Importance: 0.008356
  Predicado: Fe ka > -9.83 (n=317)
    Zona: 34 colunas
    Importance: 0.341181
  Predicado: Fe ka <= -5.77 (n=166)
    Zona: 34 colunas
    Importance: 0.366779
  Predicado: Fe ka > -5.77 (n=234)
    Zona: 34 colunas
    Importance: 0.374058
  Predicado: Fe ka <= 4.25 (n=243)
    Zona: 34 colunas
    Importance: 0.293272
  Predicado: Fe ka > 4.25 (n=157)
    Zona: 34 colunas
    Importance: 0.491401
  Predicado: Fe ka <= 11.65 (n=320)
    Zona: 34 colunas
    Importance: 0.317388
  Predicado: Fe kb > -3.67 (n=318)
    Zona: 26 colunas
    Importance: 0.041183
  Predicado: Fe kb <= -2.08 (n=165)
    Zona: 26 colunas
    Importance: 0.047081
  Predicado: Fe kb > -2.08 (n=235)
    Zona: 26 colunas
    Importance: 0.044455
  Predicado: Fe kb <= 1.44 (n=241)
    Zona: 26 colunas
    Importance: 0.037302
  Predicado: Fe kb > 1.44 (n=159)
    Zona: 26 colunas
    Importance: 0.058021
  Predicado: Fe kb <= 4.31 (n=321)
    Zona: 26 colunas
    Importance: 0.039651
  Predicado: Ni > -0.28 (n=326)
    Zona: 31 colunas
    Importance: 0.001183
  Predicado: Ni <= -0.06 (n=163)
    Zona: 31 colunas
    Importance: 0.001738
  Predicado: Ni > -0.06 (n=237)
    Zona: 31 colunas
    Importance: 0.001274
  Predicado: Ni <= 0.09 (n=244)
    Zona: 31 colunas
    Importance: 0.001251
  Predicado: Ni > 0.09 (n=156)
    Zona: 31 colunas
    Importance: 0.001795
  Predicado: Ni <= 0.26 (n=322)
    Zona: 31 colunas
    Importance: 0.001195
  Predicado: Cu > -0.46 (n=318)
    Zona: 15 colunas
    Importance: 0.001426
  Predicado: Cu <= -0.21 (n=165)
    Zona: 15 colunas
    Importance: 0.001424
  Predicado: Cu > -0.21 (n=235)
    Zona: 15 colunas
    Importance: 0.001546
  Predicado: Cu <= 0.18 (n=241)
    Zona: 15 colunas
    Importance: 0.001178
  Predicado: Cu > 0.18 (n=159)
    Zona: 15 colunas
    Importance: 0.001978
  Predicado: Cu <= 0.48 (n=321)
    Zona: 15 colunas
    Importance: 0.001251
  Predicado: Zn > -0.31 (n=326)
    Zona: 41 colunas
    Importance: 0.001667
  Predicado: Zn <= -0.08 (n=167)
    Zona: 41 colunas
    Importance: 0.002314
  Predicado: Zn > -0.08 (n=233)
    Zona: 41 colunas
    Importance: 0.001843
  Predicado: Zn <= 0.10 (n=243)
    Zona: 41 colunas
    Importance: 0.001691
  Predicado: Zn > 0.10 (n=157)
    Zona: 41 colunas
    Importance: 0.002579
  Predicado: Zn <= 0.32 (n=326)
    Zona: 41 colunas
    Importance: 0.001658
  Predicado: background1 > -0.46 (n=317)
    Zona: 85 colunas
    Importance: 0.004027
  Predicado: background1 <= -0.15 (n=158)
    Zona: 85 colunas
    Importance: 0.005625
  Predicado: background1 > -0.15 (n=242)
    Zona: 85 colunas
    Importance: 0.004308
  Predicado: background1 <= 0.08 (n=244)
    Zona: 85 colunas
    Importance: 0.003867

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Fe ka > 4.25,Fe ka > 4.25,Fe ka > 4.25,Fe ka > 4.25
1,Fe ka <= -5.77,Fe ka > -5.77,Fe ka > -5.77,Fe ka <= -5.77
2,Fe ka > -5.77,Fe ka <= -5.77,Fe ka <= -5.77,Fe ka > -5.77
3,Fe ka > -9.83,Fe ka > -9.83,Fe ka > -9.83,Fe ka > -9.83
4,Fe ka <= 11.65,Fe ka <= 11.65,Fe ka <= 11.65,Fe ka <= 11.65
...,...,...,...,...
123,S > -0.16,S > -0.16,S > -0.16,S > -0.16
124,S <= 0.04,S <= 0.04,S <= 0.04,S <= 0.04
125,S <= 0.16,S <= 0.16,S <= 0.16,S <= 0.16
126,Class_A,Class_A,Class_A,Class_A
127,Class_B,Class_B,Class_B,Class_B

In [15]:
all_results_pert[0]['pert_results_dict']['Bag_1']

          Predicate  Perturbation
0      Fe ka > 4.25      0.492344
1     Fe ka > -5.77      0.372174
2    Fe ka <= -5.77      0.371452
3     Fe ka > -9.83      0.342019
4    Fe ka <= 11.65      0.315511
..              ...           ...
121       S > -0.07      0.000147
122      S <= -0.07      0.000139
123       S > -0.16      0.000136
124       S <= 0.04      0.000119
125       S <= 0.16      0.000118

[126 rows x 2 columns]

In [16]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > 4.25,8.429654,Fe ka,4.25,>
1,Ca ka > -0.35,1.625056,Ca ka,-0.35,>
2,Ti ka <= -0.55,1.346114,Ti ka,-0.55,<=
3,Fe kb > 1.44,1.269026,Fe kb,1.44,>
4,Mn > 0.30,0.420240,Mn,0.30,>
5,Ti kb > 0.24,0.152530,Ti kb,0.24,>
6,background1 > 0.08,0.146571,background1,0.08,>
7,Al > 0.14,0.144468,Al,0.14,>
8,Rh L + Ar > 0.33,0.138152,Rh L + Ar,0.33,>
9,sum Fe > 0.39,0.104131,sum Fe,0.39,>
10,Ca kb > 0.02,0.078119,Ca kb,0.02,>
11,background2 > 0.08,0.056383,background2,0.08,>
12,Zn > 0.10,0.033707,Zn,0.10,>
13,K > -0.01,0.032747,K,-0.01,>
14,Cu > 0.18,0.027948,Cu,0.18,>
15,Si > 0.21,0.021661,Si,0.21,>
16,Ni <= -0.06,0.018711,Ni,-0.06,<=
17,Fe ka + Ti ka <= -0.06,0.018115,Fe ka + Ti ka,-0.06,<=
18,Cr <= 0.18,0.015545,Cr,0.18,<=
19,P > 0.02,0.009199,P,0.02,>
20,S > 0.04,0.000326,S,0.04,>
21,Class_B,0.000000,None,None,None

In [17]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > 4.25,8.429654,Fe ka,4.25,>,87.045387,38.0,0.001079,Fe ka > 87.045387
1,Fe ka > -5.77,7.076918,Fe ka,-5.77,>,-103.046579,408.0,0.004763,Fe ka > -103.046579
2,Fe ka <= -5.77,6.879467,Fe ka,-5.77,<=,-103.046579,408.0,0.004763,Fe ka <= -103.046579
3,Fe ka > -9.83,5.935921,Fe ka,-9.83,>,-178.952975,247.0,0.001731,Fe ka > -178.952975
4,Fe ka <= 11.65,4.580285,Fe ka,11.65,<=,188.786502,94.0,0.001158,Fe ka <= 188.786502
...,...,...,...,...,...,...,...,...,...
123,S > -0.16,0.000141,S,-0.16,>,-0.124351,326.0,0.000053,S > -0.124351
124,S <= 0.04,0.000096,S,0.04,<=,0.036958,195.0,0.000109,S <= 0.036958
125,S <= 0.16,0.000047,S,0.16,<=,0.132657,399.0,0.002959,S <= 0.132657
126,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
127,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [26]:
import plotly.graph_objects as go

n = 5
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Variância explicada pela PC1: 94.87%

In [19]:
# Permutation importance baseado em mudança nas predições do modelo PLS
# Medimos a média da diferença absoluta entre as predições originais e as predições
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Predições base do modelo PLS
baseline_pred = pls_model.predict(Xcalclass_prep)
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_pred = pls_model.predict(X_perm)
        diffs.append(np.mean(np.abs(baseline_pred - perm_pred)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance': importance_list
})
permutation_df.sort_values(by='Permutation_importance', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance', ascending=False)
permutation_unique_df

   energy  Permutation_importance           Zone
0     6.4                0.061722          Fe ka
1     3.7                0.012005          Ca ka
2    4.52                0.010696          Ti ka
3    7.06                0.007350          Fe kb
4     5.9                0.002887             Mn
5    1.48                0.001273             Al
6    4.94                0.000921          Ti kb
7    4.02                0.000757          Ca kb
8   12.84                0.000626         sum Fe
9    2.62                0.000515      Rh L + Ar
10    3.3                0.000506              K
11   8.06                0.000399             Cu
12   5.42                0.000304             Cr
13   1.72                0.000292             Si
14   2.04                0.000222              P
15   9.26                0.000148    background1
16  10.94                0.000139  Fe ka + Ti ka
17   8.48                0.000113             Zn
18   7.82                0.000109             Ni
19  11.24                0.000098    background2
20   2.54                0.000091              S
21   1.32                0.000002            NaN

In [20]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'VIP_Score': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_Coefficient' : pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,VIP_Score,Reg_Coefficient,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka,Fe ka
1,Fe kb,Ti ka,Ca ka,Ca ka,Ca ka,Fe kb
2,Ti ka,Ca ka,Ti ka,Ti ka,Ti ka,Mn
3,Ca ka,Fe kb,Mn,Fe kb,Fe kb,sum Fe
4,Mn,Mn,Fe kb,Mn,Mn,Ca ka
5,sum Fe,Al,Rh L + Ar,Al,Ti kb,Cr
6,Ti kb,Rh L + Ar,Cr,Ti kb,background1,Si
7,Al,Ca kb,S,Ca kb,Al,Ti kb
8,Si,Ti kb,Al,sum Fe,Rh L + Ar,Rh L + Ar
9,Cr,K,P,Rh L + Ar,sum Fe,Ti ka
10,Rh L + Ar,Cu,NaN,K,Ca kb,Cu
11,Cu,background1,Ca kb,Cu,background2,Al
12,Ca kb,sum Fe,K,Cr,Zn,Ca kb
13,K,Cr,Si,Si,K,background1
14,background1,P,Fe ka + Ti ka,P,Cu,background2
15,P,Zn,sum Fe,background1,Si,K
16,Fe ka + Ti ka,Ni,background2,Fe ka + Ti ka,Ni,Fe ka + Ti ka
17,Zn,background2,Ni,Zn,Fe ka + Ti ka,P
18,Ni,Fe ka + Ti ka,Zn,Ni,Cr,Zn
19,background2,S,Cu,background2,P,Ni
20,S,Si,background1,S,S,S
21,NaN,NaN,Ti kb,NaN,None,None

In [21]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_26016\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

            Method_1          Method_2  RBO_Score
12       Permutation  LRC_perturbation   0.950165
10              Shap  LRC_perturbation   0.910800
9               Shap       Permutation   0.908878
6    Reg_Coefficient       Permutation   0.855490
7    Reg_Coefficient  LRC_perturbation   0.837745
4          VIP_Score    LRC_covariance   0.827178
5    Reg_Coefficient              Shap   0.813930
2          VIP_Score       Permutation   0.796876
3          VIP_Score  LRC_perturbation   0.794954
0          VIP_Score   Reg_Coefficient   0.785613
1          VIP_Score              Shap   0.754878
11              Shap    LRC_covariance   0.657344
13       Permutation    LRC_covariance   0.653512
14  LRC_perturbation    LRC_covariance   0.653512
8    Reg_Coefficient    LRC_covariance   0.649213

In [22]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')