## Loading data

In [6]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/VNIR_databases/soil/plsda/soil_vnir.csv', sep=';') # local copy of Toledo and Guarapuava soil datasets
data = data_complete.loc[:, '400':'2498']


data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '400':'2498'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '400':'2498'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

# vamos converter os espectros de reflectância para absorbância
#Xcalclass = np.log10(1 / Xcalclass)
#Xpredclass = np.log10(1 / Xpredclass)

# savitzky-golay smoothing on the vnir spectra
from scipy.signal import savgol_filter
Xcalclass_prep = pd.DataFrame(savgol_filter(Xcalclass, window_length=11, polyorder=3, deriv=0, axis=1), columns=Xcalclass.columns)
Xpredclass_prep = pd.DataFrame(savgol_filter(Xpredclass, window_length=11, polyorder=3, deriv=0, axis=1), columns=Xpredclass.columns)
Xcalclass_prep, mean_calclass  = prepr.mc(Xcalclass_prep)
Xpredclass_prep = Xpredclass_prep - mean_calclass

from modeling import pls_optimized

# performing PLS-DA with optimized latent variables
plsda_results = pls_optimized(Xcalclass_prep, 
                              ycalclass,
                              LVmax=3,
                              Xpred=Xpredclass_prep,
                              ypred=ypredclass,
                              aim='classification',
                              cv=10)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()
plsda_results[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-26 10:13:36,177 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-26 10:13:36,361 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-26 10:13:36,405 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-26 10:13:36,412 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

,LVs,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy CV,Sensitivity CV,Specificity CV,CM CV,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred,X Cum Exp Var,Y Cum Exp Var,X Ind Exp Var,Y Ind Exp Var
0,1,0.854545,0.000,1.000000,"[[235, 0], [40, 0]]",0.854545,0.0,1.000000,"[[235, 0], [40, 0]]",0.848739,0.0,1.0,"[[101, 0], [18, 0]]",82.518273,2.360363,82.518273,2.360363
1,2,0.854545,0.000,1.000000,"[[235, 0], [40, 0]]",0.850909,0.0,0.995745,"[[234, 1], [40, 0]]",0.848739,0.0,1.0,"[[101, 0], [18, 0]]",88.610581,10.216959,6.092308,7.856595
2,3,0.850909,0.025,0.991489,"[[233, 2], [39, 1]]",0.847273,0.0,0.991489,"[[233, 2], [40, 0]]",0.848739,0.0,1.0,"[[101, 0], [18, 0]]",95.255728,14.420457,6.645147,4.203498

In [7]:
# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

In [8]:
# calculando a covariancia entre cada variável espectral e a predição do modelo PLS-DA
cov_scores = []
y_pred = plsda_results[5].iloc[:,-1].values # using the continuous predictions from LV=3
for col in Xcalclass_prep.columns:
    x_values = Xcalclass_prep[col].values
    covariance = np.cov(x_values, y_pred)[0, 1] # covariance between x and y
    cov_scores.append(covariance)
cov_scores_df = pd.DataFrame(cov_scores, index=Xcalclass_prep.columns, columns=['Covariance'])
cov_scores_df = np.abs(cov_scores_df)
cov_scores_df.plot()

In [10]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [(str(start), start, start + 100) for start in range(400, 2500, 100)]

import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona '400': VE = 98.72%, dim = 51 variáveis
Zona '500': VE = 96.68%, dim = 51 variáveis
Zona '600': VE = 97.35%, dim = 51 variáveis
Zona '700': VE = 99.52%, dim = 51 variáveis
Zona '800': VE = 99.47%, dim = 51 variáveis
Zona '900': VE = 99.77%, dim = 51 variáveis
Zona '1000': VE = 99.87%, dim = 51 variáveis
Zona '1100': VE = 99.92%, dim = 51 variáveis
Zona '1200': VE = 99.97%, dim = 51 variáveis
Zona '1300': VE = 99.93%, dim = 51 variáveis
Zona '1400': VE = 99.97%, dim = 51 variáveis
Zona '1500': VE = 99.98%, dim = 51 variáveis
Zona '1600': VE = 99.98%, dim = 51 variáveis
Zona '1700': VE = 99.97%, dim = 51 variáveis
Zona '1800': VE = 99.89%, dim = 51 variáveis
Zona '1900': VE = 99.96%, dim = 51 variáveis
Zona '2000': VE = 99.98%, dim = 51 variáveis
Zona '2100': VE = 99.74%, dim = 51 variáveis
Zona '2200': VE = 99.78%, dim = 51 variáveis
Zona '2300': VE = 99.90%, dim = 51 variáveis
Zona '2400': VE = 99.88%, dim = 50 variáveis

Scores DataFrame shape: (275, 21)

## VIP, Regression Coefficients e SHAP (como no original)

In [11]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

In [22]:
# shap_global_importance = pd.read_csv('shap_soil_types.csv', sep=';') # loading previously saved shap_unique_df

# # vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
# energy_to_zone_shap = {}
# for zone_name, start, end in spectral_cuts:
#     for i in shap_global_importance['energy']:
#         i_float = float(i)
#         if start <= i_float <= end:
#             energy_to_zone_shap[i] = zone_name
# shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# # agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
# shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
# shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
# shap_unique_df

In [12]:
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred_cont
)

In [13]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.001, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.001

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.001

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.001

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.001

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 137
Removida: 1600 > -0.25 -> 1700 > -0.26 (0.0166) | Mantida: 1700 > -0.26 -> 1600 > -0.25 (0.0321)
Removida: 1400 > -0.24 -> 1700 > -0.26 (0.0153) | Mantida: 1700 > -0.26 -> 1400 > -0.24 (0.0333)
Removida: 1700 > -0.26 -> 1900 > -0.26 (0.0176) | Mantida: 1900 > -0.26 -> 1700 > -0.26 (0.0319)
Removida: 1500 > -0.26 -> 1700 > -0.26 (0.0177) | Mantida: 1700 > -0.26 -> 1500 > -0.26 (0.0444)
Removida: 1400 > -0.24 -> 1600 > -0.25 (0.0179) | Mantida: 1600 > -0.25 -> 1400 > -0.24 (0.0304)
Removida: 1600 > -0.25 -> 2100 > -0.26 (0.0154) | Mantida: 2100 > -0.26 -> 1600 > -0.25 (0.0497)
Removida: 1400 > -0.24 -> 1500 > -0.26 (0.0156) | Mantida: 1500 > -0.26 -> 1400 > -0.24 (0.0313)
Removida: 2200 > -0.25 -> 1500 > -0.26 (0.0159) | Mantida: 1500 > -0.26 -> 2200 > -0.25 (0.0295)
Removida: 1800 > -0.26 -> 1400 > -0.24 (0.0180) | Mantida: 1400 > -0.24 -> 1800 > -0.26 (0.0301)
Removida: 2000 > -0.26 -> 1400 > -0.24 (0.0151) | Mantida: 1400 > -0.24 -> 2000 > -0.26 (0.0166)
Removida: 1800 > -0.26 -> 1900 > -0.26 (0.0169) | Mantida: 1900 > -0.26 -> 1800 > -0.26 (0.0177)
Removida: 2100 > -0.26 -> 1800 > -0.26 (0.0170) | Mantida: 1800 > -0.26 -> 2100 > -0.26 (0.0333)
Removida: 1700 > -0.09 -> 1300 > -0.24 (0.0148) | Mantida: 1300 > -0.24 -> 1700 > -0.09 (0.0156)
Removida: 1900 > -0.26 -> 2000 > -0.26 (0.0135) | Mantida: 2000 > -0.26 -> 1900 > -0.26 (0.0800)
Removida: 1700 > -0.09 -> 1900 > -0.26 (0.0135) | Mantida: 1900 > -0.26 -> 1700 > -0.09 (0.0148)
Removida: 1800 > -0.09 -> 2100 > -0.26 (0.0137) | Mantida: 2100 > -0.26 -> 1800 > -0.09 (0.0143)
Removida: 2100 > -0.26 -> 1700 > -0.09 (0.0135) | Mantida: 1700 > -0.09 -> 2100 > -0.26 (0.0146)
Removida: 1200 > -0.24 -> 2200 > -0.25 (0.0128) | Mantida: 2200 > -0.25 -> 1200 > -0.24 (0.0135)
Removida: 1800 > -0.09 -> 1200 > -0.24 (0.0281) | Mantida: 1200 > -0.24 -> 1800 > -0.09 (0.0298)
Removida: 1600 > -0.09 -> 1200 > -0.24 (0.0151) | Mantida: 1200 > -0.24 -> 1600 > -0.09 (0.0277)
Removida: 1300 > -0.09 -> 1200 > -0.24 (0.0140) | Mantida: 1200 > -0.24 -> 1300 > -0.09 (0.0146)
Removida: 2300 > -0.26 -> 1200 > -0.24 (0.0144) | Mantida: 1200 > -0.24 -> 2300 > -0.26 (0.0149)
Removida: 1800 > -0.09 -> 1700 > -0.09 (0.0149) | Mantida: 1700 > -0.09 -> 1800 > -0.09 (0.0432)
Removida: 2400 > -0.11 -> 2300 > -0.11 (0.0131) | Mantida: 2300 > -0.11 -> 2400 > -0.11 (0.0515)
Removida: 1900 > -0.09 -> 2300 > -0.11 (0.0121) | Mantida: 2300 > -0.11 -> 1900 > -0.09 (0.0389)
Removida: 2300 > -0.11 -> 2100 > -0.10 (0.0141) | Mantida: 2100 > -0.10 -> 2300 > -0.11 (0.0145)
Removida: 2300 > -0.11 -> 1300 > -0.09 (0.0141) | Mantida: 1300 > -0.09 -> 2300 > -0.11 (0.0264)
Removida: 2300 > -0.26 -> 1700 > -0.09 (0.0143) | Mantida: 1700 > -0.09 -> 2300 > -0.26 (0.0158)
Removida: 2300 > -0.26 -> 1600 > -0.09 (0.0155) | Mantida: 1600 > -0.09 -> 2300 > -0.26 (0.0160)
Removida: 2200 > -0.11 -> 1400 > -0.09 (0.0141) | Mantida: 1400 > -0.09 -> 2200 > -0.11 (0.0148)
Removida: 1300 > -0.09 -> 2200 > -0.11 (0.0143) | Mantida: 2200 > -0.11 -> 1300 > -0.09 (0.0264)
Removida: 2100 > -0.10 -> 2400 > -0.27 (0.0148) | Mantida: 2400 > -0.27 -> 2100 > -0.10 (0.0149)
Removida: 2100 > -0.10 -> 1300 > -0.09 (0.0123) | Mantida: 1300 > -0.09 -> 2100 > -0.10 (0.0278)
Removida: 2100 > -0.10 -> 1400 > -0.09 (0.0148) | Mantida: 1400 > -0.09 -> 2100 > -0.10 (0.0280)
Removida: 1800 > 0.06 -> 1100 > -0.23 (0.0131) | Mantida: 1100 > -0.23 -> 1800 > 0.06 (0.0228)
Removida: 2400 > -0.27 -> 1500 > -0.10 (0.0153) | Mantida: 1500 > -0.10 -> 2400 > -0.27 (0.0282)
Removida: 2400 > -0.27 -> 1400 > -0.09 (0.0132) | Mantida: 1400 > -0.09 -> 2400 > -0.27 (0.0135)
Removida: 1500 > -0.10 -> 1600 > -0.09 (0.0160) | Mantida: 1600 > -0.09 -> 1500 > -0.10 (0.0527)
Removida: 1400 > -0.09 -> 1500 > -0.10 (0.0139) | Mantida: 1500 > -0.10 -> 1400 > -0.09 (0.0571)
Removida: 400 <= -0.08 -> 1700 > 0.05 (0.0126) | Mantida: 1700 > 0.05 -> 400 <= -0.08 (0.0229)
Removida: 1700 > 0.05 -> 2000 > -0.10 (0.0127) | Mantida: 2000 > -0.10 -> 1700 > 0.05 (0.0136)
Removida: 1000 > -0.05 -> 400 <= -0.08 (0.0099) | Mantida: 400 <= -0.08 -> 1000 > -0.05 (0.0102)
Removida: 1900 > -0.09 -> 2000 > -0.10 (0.0131) | Mantida: 2000 > -0.10 -> 1900 > -0.09 (0.0136)
Removida: 1200 > -0.08 -> 1900 > -0.09 (0.0237) | Mantida: 1900 > -0.09 -> 1200 > -0.08 (0.0406)
Removida: 1300 > -0.09 -> 2100 > 0.07 (0.0115) | Mantida: 2100 > 0.07 -> 1300 > -0.09 (0.0127)
Removida: 1600 > 0.05 -> 1500 > 0.06 (0.0120) | Mantida: 1500 > 0.06 -> 1600 > 0.05 (0.0477)
Removida: 1100 > -0.23 -> 1500 > 0.06 (0.0118) | Mantida: 1500 > 0.06 -> 1100 > -0.23 (0.0118)
Removida: 2300 > 0.08 -> 1600 > 0.05 (0.0099) | Mantida: 1600 > 0.05 -> 2300 > 0.08 (0.0348)
Removida: 1400 > 0.06 -> 1600 > 0.05 (0.0103) | Mantida: 1600 > 0.05 -> 1400 > 0.06 (0.0361)
Removida: 1600 > 0.05 -> 2200 > 0.08 (0.0099) | Mantida: 2200 > 0.08 -> 1600 > 0.05 (0.0219)
Removida: 2300 > 0.08 -> 2200 > 0.08 (0.0208) | Mantida: 2200 > 0.08 -> 2300 > 0.08 (0.0214)
Removida: 2300 > 0.08 -> 1900 > 0.07 (0.0112) | Mantida: 1900 > 0.07 -> 2300 > 0.08 (0.0120)
Removida: 2000 > 0.07 -> 2300 > 0.08 (0.0123) | Mantida: 2300 > 0.08 -> 2000 > 0.07 (0.0213)
Removida: 2200 > 0.08 -> 1400 > 0.06 (0.0112) | Mantida: 1400 > 0.06 -> 2200 > 0.08 (0.0117)
Removida: 1400 > 0.06 -> 500 <= -0.05 (0.0096) | Mantida: 500 <= -0.05 -> 1400 > 0.06 (0.0102)
Removida: 500 <= -0.05 -> 2400 > 0.09 (0.0095) | Mantida: 2400 > 0.09 -> 500 <= -0.05 (0.0105)
Removida: 500 <= -0.05 -> 1200 > 0.07 (0.0101) | Mantida: 1200 > 0.07 -> 500 <= -0.05 (0.0101)
Removida: 500 <= -0.05 -> 1000 > -0.05 (0.0091) | Mantida: 1000 > -0.05 -> 500 <= -0.05 (0.0094)
Removida: 2000 > 0.07 -> 1900 > 0.07 (0.0092) | Mantida: 1900 > 0.07 -> 2000 > 0.07 (0.0195)
Removida: 1300 > 0.07 -> 1900 > 0.07 (0.0106) | Mantida: 1900 > 0.07 -> 1300 > 0.07 (0.0112)
Removida: 2400 > 0.09 -> 1900 > 0.07 (0.0090) | Mantida: 1900 > 0.07 -> 2400 > 0.09 (0.0105)
Removida: 2000 > 0.07 -> 1100 > -0.23 (0.0102) | Mantida: 1100 > -0.23 -> 2000 > 0.07 (0.0117)
Removida: 1300 > 0.07 -> 2000 > 0.07 (0.0094) | Mantida: 2000 > 0.07 -> 1300 > 0.07 (0.0108)
Removida: 1100 > -0.07 -> 1300 > 0.07 (0.0109) | Mantida: 1300 > 0.07 -> 1100 > -0.07 (0.0110)
Removida: 1100 > 0.06 -> 2400 > 0.09 (0.0105) | Mantida: 2400 > 0.09 -> 1100 > 0.06 (0.0178)
Removida: 1000 > -0.05 -> 2400 > 0.09 (0.0091) | Mantida: 2400 > 0.09 -> 1000 > -0.05 (0.0204)
Removida: 1200 > 0.07 -> 1100 > -0.07 (0.0087) | Mantida: 1100 > -0.07 -> 1200 > 0.07 (0.0089)
Removida: 1100 > 0.06 -> 1100 > -0.07 (0.0096) | Mantida: 1100 > -0.07 -> 1100 > 0.06 (0.0108)
Removida: 1200 > 0.07 -> 1000 > -0.05 (0.0101) | Mantida: 1000 > -0.05 -> 1200 > 0.07 (0.0278)
Removida: 1100 > 0.06 -> 1000 > -0.05 (0.0085) | Mantida: 1000 > -0.05 -> 1100 > 0.06 (0.0094)
Removida: 1000 > -0.20 -> 1100 > 0.06 (0.0095) | Mantida: 1100 > 0.06 -> 1000 > -0.20 (0.0189)
Removida: 1000 > -0.05 -> 400 > -0.25 (0.0079) | Mantida: 400 > -0.25 -> 1000 > -0.05 (0.0167)
Removida: 400 > -0.25 -> 1000 > -0.20 (0.0078) | Mantida: 1000 > -0.20 -> 400 > -0.25 (0.0092)
Removida: 600 <= -0.03 -> 400 > -0.25 (0.0065) | Mantida: 400 > -0.25 -> 600 <= -0.03 (0.0145)
Removida: 400 > -0.25 -> 900 > -0.05 (0.0066) | Mantida: 900 > -0.05 -> 400 > -0.25 (0.0069)
Removida: 600 <= 0.06 -> 700 <= 0.16 (0.0140) | Mantida: 700 <= 0.16 -> 600 <= 0.06 (0.0207)
Removida: 600 <= 0.06 -> 1600 <= 0.26 (0.0070) | Mantida: 1600 <= 0.26 -> 600 <= 0.06 (0.0072)
Removida: 800 <= 0.06 -> 500 > -0.21 (0.0066) | Mantida: 500 > -0.21 -> 800 <= 0.06 (0.0114)
Removida: 700 <= 0.07 -> 500 > -0.21 (0.0056) | Mantida: 500 > -0.21 -> 700 <= 0.07 (0.0121)
Removida: 500 > -0.21 -> 1300 <= 0.25 (0.0050) | Mantida: 1300 <= 0.25 -> 500 > -0.21 (0.0056)
Removida: 1000 > 0.05 -> 900 > -0.05 (0.0138) | Mantida: 900 > -0.05 -> 1000 > 0.05 (0.0200)
Removida: 900 > 0.05 -> 900 > -0.05 (0.0070) | Mantida: 900 > -0.05 -> 900 > 0.05 (0.0073)
Removida: 1000 > 0.05 -> 800 <= 0.06 (0.0060) | Mantida: 800 <= 0.06 -> 1000 > 0.05 (0.0066)
Removida: 1600 <= 0.26 -> 1000 > 0.05 (0.0070) | Mantida: 1000 > 0.05 -> 1600 <= 0.26 (0.0137)
Removida: 700 <= 0.07 -> 800 <= 0.06 (0.0066) | Mantida: 800 <= 0.06 -> 700 <= 0.07 (0.0122)
Removida: 700 <= -0.04 -> 800 <= 0.06 (0.0033) | Mantida: 800 <= 0.06 -> 700 <= -0.04 (0.0057)
Removida: 900 > -0.17 -> 700 <= -0.04 (0.0060) | Mantida: 700 <= -0.04 -> 900 > -0.17 (0.0063)
Removida: 900 > -0.17 -> 900 > 0.05 (0.0054) | Mantida: 900 > 0.05 -> 900 > -0.17 (0.0057)
Removida: 1600 <= 0.26 -> 700 <= 0.07 (0.0056) | Mantida: 700 <= 0.07 -> 1600 <= 0.26 (0.0058)
Removida: 1400 <= 0.25 -> 1600 <= 0.26 (0.0039) | Mantida: 1600 <= 0.26 -> 1400 <= 0.25 (0.0065)
Removida: 1600 <= 0.26 -> 1500 <= 0.26 (0.0065) | Mantida: 1500 <= 0.26 -> 1600 <= 0.26 (0.0066)
Removida: 800 <= -0.05 -> 700 <= 0.07 (0.0056) | Mantida: 700 <= 0.07 -> 800 <= -0.05 (0.0121)
Removida: 1700 <= 0.26 -> 500 <= 0.26 (0.0056) | Mantida: 500 <= 0.26 -> 1700 <= 0.26 (0.0116)
Removida: 400 > 0.14 -> 500 <= 0.26 (0.0045) | Mantida: 500 <= 0.26 -> 400 > 0.14 (0.0049)
Removida: 400 > 0.14 -> 1700 <= 0.26 (0.0055) | Mantida: 1700 <= 0.26 -> 400 > 0.14 (0.0063)
Removida: 1500 <= 0.26 -> 1800 <= 0.26 (0.0068) | Mantida: 1800 <= 0.26 -> 1500 <= 0.26 (0.0104)
Removida: 1400 <= 0.25 -> 1800 <= 0.26 (0.0061) | Mantida: 1800 <= 0.26 -> 1400 <= 0.25 (0.0066)
Removida: 1300 <= 0.25 -> 1800 <= 0.26 (0.0032) | Mantida: 1800 <= 0.26 -> 1300 <= 0.25 (0.0060)
Removida: 1800 <= 0.26 -> 900 > -0.17 (0.0061) | Mantida: 900 > -0.17 -> 1800 <= 0.26 (0.0067)
Removida: 400 <= 0.30 -> 800 > -0.05 (0.0041) | Mantida: 800 > -0.05 -> 400 <= 0.30 (0.0042)
Removida: 1400 <= 0.25 -> 800 <= -0.05 (0.0044) | Mantida: 800 <= -0.05 -> 1400 <= 0.25 (0.0049)
Removida: 1300 <= 0.25 -> 800 <= -0.05 (0.0052) | Mantida: 800 <= -0.05 -> 1300 <= 0.25 (0.0055)
Removida: 800 <= 0.15 -> 1400 <= 0.25 (0.0048) | Mantida: 1400 <= 0.25 -> 800 <= 0.15 (0.0048)
Removida: 900 <= 0.05 -> 800 <= 0.15 (0.0043) | Mantida: 800 <= 0.15 -> 900 <= 0.05 (0.0117)
Removida: 500 > -0.05 -> 900 <= 0.05 (0.0042) | Mantida: 900 <= 0.05 -> 500 > -0.05 (0.0048)
Removida: 900 <= 0.05 -> 1800 <= 0.06 (0.0043) | Mantida: 1800 <= 0.06 -> 900 <= 0.05 (0.0044)
Removida: 500 > -0.05 -> 2300 <= 0.27 (0.0030) | Mantida: 2300 <= 0.27 -> 500 > -0.05 (0.0037)
Removida: 2000 <= 0.25 -> 500 > 0.10 (0.0047) | Mantida: 500 > 0.10 -> 2000 <= 0.25 (0.0098)
Removida: 400 > 0.14 -> 2100 <= 0.25 (0.0043) | Mantida: 2100 <= 0.25 -> 400 > 0.14 (0.0046)
Removida: 2100 <= 0.25 -> 1300 <= 0.25 (0.0042) | Mantida: 1300 <= 0.25 -> 2100 <= 0.25 (0.0055)
Removida: 2100 <= 0.25 -> 2000 <= 0.25 (0.0048) | Mantida: 2000 <= 0.25 -> 2100 <= 0.25 (0.0137)
Removida: 900 <= -0.05 -> 400 <= 0.14 (0.0043) | Mantida: 400 <= 0.14 -> 900 <= -0.05 (0.0050)
Removida: 1800 <= -0.09 -> 400 <= 0.14 (0.0027) | Mantida: 400 <= 0.14 -> 1800 <= -0.09 (0.0056)
Removida: 800 > -0.05 -> 2000 <= 0.25 (0.0037) | Mantida: 2000 <= 0.25 -> 800 > -0.05 (0.0043)
Removida: 1800 <= 0.06 -> 800 > -0.14 (0.0035) | Mantida: 800 > -0.14 -> 1800 <= 0.06 (0.0035)
Removida: 800 > 0.06 -> 900 <= -0.05 (0.0038) | Mantida: 900 <= -0.05 -> 800 > 0.06 (0.0076)
Removida: 1000 <= 0.05 -> 1100 <= -0.07 (0.0034) | Mantida: 1100 <= -0.07 -> 1000 <= 0.05 (0.0039)
Removida: 900 <= 0.16 -> 1000 <= 0.05 (0.0031) | Mantida: 1000 <= 0.05 -> 900 <= 0.16 (0.0033)
Removida: 1000 <= 0.05 -> 1700 <= -0.09 (0.0020) | Mantida: 1700 <= -0.09 -> 1000 <= 0.05 (0.0028)
Removida: 1100 <= -0.07 -> 800 > -0.05 (0.0033) | Mantida: 800 > -0.05 -> 1100 <= -0.07 (0.0039)
Removida: 1100 <= -0.07 -> 1000 <= -0.05 (0.0018) | Mantida: 1000 <= -0.05 -> 1100 <= -0.07 (0.0021)
Removida: 900 <= 0.16 -> 1500 <= 0.06 (0.0029) | Mantida: 1500 <= 0.06 -> 900 <= 0.16 (0.0051)
Removida: 1200 <= 0.25 -> 2300 <= 0.27 (0.0026) | Mantida: 2300 <= 0.27 -> 1200 <= 0.25 (0.0034)
Removida: 2300 <= 0.27 -> 1700 <= -0.09 (0.0018) | Mantida: 1700 <= -0.09 -> 2300 <= 0.27 (0.0021)
Removida: 1000 <= 0.20 -> 1600 <= 0.05 (0.0024) | Mantida: 1600 <= 0.05 -> 1000 <= 0.20 (0.0026)
Removida: 1900 <= 0.07 -> 1000 <= 0.20 (0.0013) | Mantida: 1000 <= 0.20 -> 1900 <= 0.07 (0.0015)
Removida: 1800 <= -0.09 -> 1600 <= 0.05 (0.0024) | Mantida: 1600 <= 0.05 -> 1800 <= -0.09 (0.0027)
Removida: 400 > -0.08 -> 800 > -0.14 (0.0023) | Mantida: 800 > -0.14 -> 400 > -0.08 (0.0033)
Removida: 2400 <= 0.27 -> 2000 <= 0.07 (0.0013) | Mantida: 2000 <= 0.07 -> 2400 <= 0.27 (0.0019)
Removida: 2100 <= -0.10 -> 2400 <= 0.27 (0.0013) | Mantida: 2400 <= 0.27 -> 2100 <= -0.10 (0.0019)
Removida: 2100 <= 0.07 -> 1800 <= -0.09 (0.0016) | Mantida: 1800 <= -0.09 -> 2100 <= 0.07 (0.0030)
Removida: 2000 <= 0.07 -> 1400 <= 0.06 (0.0013) | Mantida: 1400 <= 0.06 -> 2000 <= 0.07 (0.0020)
Removida: 2100 <= -0.10 -> 2000 <= 0.07 (0.0011) | Mantida: 2000 <= 0.07 -> 2100 <= -0.10 (0.0021)
Removida: 2100 <= -0.10 -> 2200 <= 0.08 (0.0017) | Mantida: 2200 <= 0.08 -> 2100 <= -0.10 (0.0023)
Removida: 2200 <= 0.08 -> 2000 <= 0.07 (0.0019) | Mantida: 2000 <= 0.07 -> 2200 <= 0.08 (0.0021)
Removida: 1900 <= 0.07 -> 2200 <= -0.11 (0.0013) | Mantida: 2200 <= -0.11 -> 1900 <= 0.07 (0.0031)
Removida: 1100 <= 0.22 -> 1500 <= -0.10 (0.0012) | Mantida: 1500 <= -0.10 -> 1100 <= 0.22 (0.0016)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 875 | Removidas: 137
Nós predicados: 124
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 138
Removida: 1900 > -0.26 -> 2000 > -0.26 (0.0342) | Mantida: 2000 > -0.26 -> 1900 > -0.26 (0.0691)
Removida: 1600 > -0.25 -> 2000 > -0.26 (0.0169) | Mantida: 2000 > -0.26 -> 1600 > -0.25 (0.0355)
Removida: 1900 > -0.26 -> 1800 > -0.26 (0.0179) | Mantida: 1800 > -0.26 -> 1900 > -0.26 (0.0335)
Removida: 1600 > -0.25 -> 1800 > -0.26 (0.0153) | Mantida: 1800 > -0.26 -> 1600 > -0.25 (0.0184)
Removida: 2100 > -0.26 -> 1800 > -0.26 (0.0362) | Mantida: 1800 > -0.26 -> 2100 > -0.26 (0.0524)
Removida: 1700 > -0.26 -> 1800 > -0.26 (0.0166) | Mantida: 1800 > -0.26 -> 1700 > -0.26 (0.0194)
Removida: 1600 > -0.25 -> 1400 > -0.24 (0.0173) | Mantida: 1400 > -0.24 -> 1600 > -0.25 (0.0487)
Removida: 1800 > -0.09 -> 1400 > -0.24 (0.0166) | Mantida: 1400 > -0.24 -> 1800 > -0.09 (0.0167)
Removida: 1500 > -0.26 -> 1400 > -0.24 (0.0166) | Mantida: 1400 > -0.24 -> 1500 > -0.26 (0.0179)
Removida: 1400 > -0.24 -> 1700 > -0.26 (0.0172) | Mantida: 1700 > -0.26 -> 1400 > -0.24 (0.0182)
Removida: 1500 > -0.26 -> 1700 > -0.26 (0.0148) | Mantida: 1700 > -0.26 -> 1500 > -0.26 (0.0663)
Removida: 1500 > -0.26 -> 2200 > -0.25 (0.0167) | Mantida: 2200 > -0.25 -> 1500 > -0.26 (0.0178)
Removida: 2200 > -0.25 -> 1300 > -0.24 (0.0327) | Mantida: 1300 > -0.24 -> 2200 > -0.25 (0.0328)
Removida: 1300 > -0.24 -> 2300 > -0.26 (0.0322) | Mantida: 2300 > -0.26 -> 1300 > -0.24 (0.0332)
Removida: 1800 > -0.09 -> 2200 > -0.25 (0.0157) | Mantida: 2200 > -0.25 -> 1800 > -0.09 (0.0166)
Removida: 1600 > -0.09 -> 1700 > -0.09 (0.0155) | Mantida: 1700 > -0.09 -> 1600 > -0.09 (0.0156)
Removida: 1800 > -0.09 -> 1500 > -0.10 (0.0152) | Mantida: 1500 > -0.10 -> 1800 > -0.09 (0.0166)
Removida: 1500 > -0.10 -> 1200 > -0.24 (0.0152) | Mantida: 1200 > -0.24 -> 1500 > -0.10 (0.0315)
Removida: 1500 > -0.10 -> 1600 > -0.09 (0.0156) | Mantida: 1600 > -0.09 -> 1500 > -0.10 (0.0463)
Removida: 1600 > -0.09 -> 1200 > -0.24 (0.0141) | Mantida: 1200 > -0.24 -> 1600 > -0.09 (0.0462)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,1900 > -0.26,1600 > -0.25,1600 > -0.09,2000 > -0.26
1,2000 > -0.26,1800 > -0.09,2000 > -0.26,1500 > -0.10
2,2300 > -0.26,2100 > -0.26,1400 > -0.24,1600 > -0.25
3,2100 > -0.26,1700 > -0.26,1700 > -0.26,2300 > -0.26
4,2300 > -0.11,1900 > -0.26,1500 > -0.10,1500 > -0.26
...,...,...,...,...
122,700 > 0.07,600 > -0.14,Class_A,600 > -0.03
123,600 > 0.06,Class_A,Class_B,2000 <= -0.10
124,Class_A,Class_B,NaN,600 > -0.14
125,Class_B,NaN,NaN,Class_A
126,NaN,NaN,NaN,Class_B

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

            Node  Local_Reaching_Centrality  Zone Threshold Operator
0   1600 > -0.25                   2.945111  1600     -0.25        >
1   2000 > -0.26                   2.917649  2000     -0.26        >
2   1700 > -0.26                   2.784295  1700     -0.26        >
3   2100 > -0.26                   2.783132  2100     -0.26        >
4   1900 > -0.26                   2.676332  1900     -0.26        >
5   1500 > -0.10                   2.589583  1500     -0.10        >
6   1800 > -0.09                   2.500467  1800     -0.09        >
7   2300 > -0.26                   2.376945  2300     -0.26        >
8   1400 > -0.24                   2.360981  1400     -0.24        >
9   1300 > -0.24                   2.307949  1300     -0.24        >
10  1200 > -0.24                   2.087739  1200     -0.24        >
11  2400 > -0.11                   2.056144  2400     -0.11        >
12  2200 > -0.11                   2.003917  2200     -0.11        >
13  1100 > -0.23                   1.617980  1100     -0.23        >
14  400 <= -0.08                   1.509673   400     -0.08       <=
15  1000 > -0.20                   1.480540  1000     -0.20        >
16  500 <= -0.05                   1.391088   500     -0.05       <=
17   600 <= 0.14                   1.218904   600      0.14       <=
18   900 > -0.05                   1.185763   900     -0.05        >
19   700 <= 0.16                   1.146575   700      0.16       <=
20   800 <= 0.06                   1.108893   800      0.06       <=
21       Class_A                   0.000000  None      None     None

In [15]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona '400': VE = 98.72%, dim = 51 variáveis
Zona '500': VE = 96.68%, dim = 51 variáveis
Zona '600': VE = 97.35%, dim = 51 variáveis
Zona '700': VE = 99.52%, dim = 51 variáveis
Zona '800': VE = 99.47%, dim = 51 variáveis
Zona '900': VE = 99.77%, dim = 51 variáveis
Zona '1000': VE = 99.87%, dim = 51 variáveis
Zona '1100': VE = 99.92%, dim = 51 variáveis
Zona '1200': VE = 99.97%, dim = 51 variáveis
Zona '1300': VE = 99.93%, dim = 51 variáveis
Zona '1400': VE = 99.97%, dim = 51 variáveis
Zona '1500': VE = 99.98%, dim = 51 variáveis
Zona '1600': VE = 99.98%, dim = 51 variáveis
Zona '1700': VE = 99.97%, dim = 51 variáveis
Zona '1800': VE = 99.89%, dim = 51 variáveis
Zona '1900': VE = 99.96%, dim = 51 variáveis
Zona '2000': VE = 99.98%, dim = 51 variáveis
Zona '2100': VE = 99.74%, dim = 51 variáveis
Zona '2200': VE = 99.78%, dim = 51 variáveis
Zona '2300': VE = 99.90%, dim = 51 variáveis
Zona '2400': VE = 99.88%, dim = 50 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,1600 > -0.25,2.945111,1600,-0.25,>,-0.249737,136.0,0.000263,1600 > -0.249737
1,2000 > -0.26,2.917649,2000,-0.26,>,-0.259451,127.0,0.000550,2000 > -0.259451
2,1700 > -0.26,2.784295,1700,-0.26,>,-0.257439,51.0,0.002561,1700 > -0.257439
3,2100 > -0.26,2.783132,2100,-0.26,>,-0.261575,262.0,0.001556,2100 > -0.261575
4,1900 > -0.26,2.676332,1900,-0.26,>,-0.257487,13.0,0.002507,1900 > -0.257487
...,...,...,...,...,...,...,...,...,...
123,2000 <= -0.10,0.611626,2000,-0.10,<=,-0.100032,135.0,0.000034,2000 <= -0.100032
124,600 > -0.03,0.572012,600,-0.03,>,-0.029653,116.0,0.000346,600 > -0.029653
125,600 > -0.14,0.231932,600,-0.14,>,-0.138320,108.0,0.001680,600 > -0.138320
126,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
127,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [19]:
import plotly.graph_objects as go

n = 5
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona '1500':
  - Dimensão: 51 variáveis espectrais
  - Range de energias: 1500 - 1600
  - Variância explicada pela PC1: 99.98%

In [20]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='regression',
        metric='mean_abs_diff', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): regression
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 126 predicados...
  Predicado: 400 > -0.25 (n=175)
    Zona: 51 colunas
    Importance: 0.006116
  Predicado: 400 <= -0.08 (n=89)
    Zona: 51 colunas
    Importance: 0.011144
  Predicado: 400 > -0.08 (n=131)
    Zona: 51 colunas
    Importance: 0.006530
  Predicado: 400 <= 0.14 (n=131)
    Zona: 51 colunas
    Importance: 0.008382
  Predicado: 400 > 0.14 (n=89)
    Zona: 51 colunas
    Importance: 0.008417
  Predicado: 400 <= 0.30 (n=175)
    Zona: 51 colunas
    Importance: 0.007953
  Predicado: 500 > -0.21 (n=174)
    Zona: 51 colunas
    Importance: 0.026230
  Predicado: 500 <= -0.05 (n=89)
    Zona: 51 colunas
    Importance: 0.048591
  Predicado: 500 > -0.05 (n=131)
    Zona: 51 colunas
    Importance: 0.027468
  Predicado: 500 <= 0.10 (n=129)
    Zona: 51 colunas
    Importance: 0.035595
  Predicado: 500 > 0.10 (n=91)
    Zona: 51 colunas
    Importance: 0.036606
  Predicado: 500 <= 0.26 (n=178)
    Zona: 51 colunas
    Importance: 0.032938
  Predicado: 600 > -0.14 (n=173)
    Zona: 51 colunas
    Importance: 0.034552
  Predicado: 600 <= -0.03 (n=92)
    Zona: 51 colunas
    Importance: 0.064592
  Predicado: 600 > -0.03 (n=128)
    Zona: 51 colunas
    Importance: 0.033971
  Predicado: 600 <= 0.06 (n=134)
    Zona: 51 colunas
    Importance: 0.046727
  Predicado: 600 > 0.06 (n=86)
    Zona: 51 colunas
    Importance: 0.046851
  Predicado: 600 <= 0.14 (n=178)
    Zona: 51 colunas
    Importance: 0.041977
  Predicado: 700 > -0.15 (n=175)
    Zona: 51 colunas
    Importance: 0.052509
  Predicado: 700 <= -0.04 (n=96)
    Zona: 51 colunas
    Importance: 0.096202
  Predicado: 700 > -0.04 (n=124)
    Zona: 51 colunas
    Importance: 0.051203
  Predicado: 700 <= 0.07 (n=133)
    Zona: 51 colunas
    Importance: 0.073413
  Predicado: 700 > 0.07 (n=87)
    Zona: 51 colunas
    Importance: 0.066904
  Predicado: 700 <= 0.16 (n=177)
    Zona: 51 colunas
    Importance: 0.064794
  Predicado: 800 > -0.14 (n=172)
    Zona: 51 colunas
    Importance: 0.029915
  Predicado: 800 <= -0.05 (n=94)
    Zona: 51 colunas
    Importance: 0.051548
  Predicado: 800 > -0.05 (n=126)
    Zona: 51 colunas
    Importance: 0.030453
  Predicado: 800 <= 0.06 (n=133)
    Zona: 51 colunas
    Importance: 0.038704
  Predicado: 800 > 0.06 (n=87)
    Zona: 51 colunas
    Importance: 0.040632
  Predicado: 800 <= 0.15 (n=178)
    Zona: 51 colunas
    Importance: 0.034829
  Predicado: 900 > -0.17 (n=174)
    Zona: 51 colunas
    Importance: 0.025375
  Predicado: 900 <= -0.05 (n=93)
    Zona: 51 colunas
    Importance: 0.040795
  Predicado: 900 > -0.05 (n=127)
    Zona: 51 colunas
    Importance: 0.026611
  Predicado: 900 <= 0.05 (n=134)
    Zona: 51 colunas
    Importance: 0.029939
  Predicado: 900 > 0.05 (n=86)
    Zona: 51 colunas
    Importance: 0.036764
  Predicado: 900 <= 0.16 (n=178)
    Zona: 51 colunas
    Importance: 0.027736
  Predicado: 1000 > -0.20 (n=174)
    Zona: 51 colunas
    Importance: 0.022614
  Predicado: 1000 <= -0.05 (n=94)
    Zona: 51 colunas
    Importance: 0.034946
  Predicado: 1000 > -0.05 (n=126)
    Zona: 51 colunas
    Importance: 0.024092
  Predicado: 1000 <= 0.05 (n=136)
    Zona: 51 colunas
    Importance: 0.025346
  Predicado: 1000 > 0.05 (n=84)
    Zona: 51 colunas
    Importance: 0.034208
  Predicado: 1000 <= 0.20 (n=182)
    Zona: 51 colunas
    Importance: 0.024181
  Predicado: 1100 > -0.23 (n=174)
    Zona: 51 colunas
    Importance: 0.003365
  Predicado: 1100 <= -0.07 (n=91)
    Zona: 51 colunas
    Importance: 0.005304
  Predicado: 1100 > -0.07 (n=129)
    Zona: 51 colunas
    Importance: 0.003522
  Predicado: 1100 <= 0.06 (n=133)
    Zona: 51 colunas
    Importance: 0.003825
  Predicado: 1100 > 0.06 (n=87)
    Zona: 51 colunas
    Importance: 0.004921
  Predicado: 1100 <= 0.22 (n=180)
    Zona: 51 colunas
    Importance: 0.003562
  Predicado: 1200 > -0.24 (n=174)
    Zona: 51 colunas
    Importance: 0.020267
  Predicado: 1200 <= -0.08 (n=93)
    Zona: 51 colunas
    Importance: 0.030385
  Predicado: 1200 > -0.08 (n=127)
    Zona: 51 colunas
    Importance: 0.021372
  Predicado: 1200 <= 0.07 (n=135)
    Zona: 51 colunas
    Importance: 0.022237
  Predicado: 1200 > 0.07 (n=85)
    Zona: 51 colunas
    Importance: 0.029859
  Predicado: 1200 <= 0.25 (n=180)
    Zona: 51 colunas
    Importance: 0.020846
  Predicado: 1300 > -0.24 (n=175)
    Zona: 51 colunas
    Importance: 0.036180
  Predicado: 1300 <= -0.09 (n=92)
    Zona: 51 colunas
    Importance: 0.053092
  Predicado: 1300 > -0.09 (n=128)
    Zona: 51 colunas
    Importance: 0.038191
  Predicado: 1300 <= 0.07 (n=134)
    Zona: 51 colunas
    Importance: 0.038594
  Predicado: 1300 > 0.07 (n=86)
    Zona: 51 colunas
    Importance: 0.053504
  Predicado: 1300 <= 0.25 (n=180)
    Zona: 51 colunas
    Importance: 0.036325
  Predicado: 1400 > -0.24 (n=173)
    Zona: 51 colunas
    Importance: 0.038683
  Predicado: 1400 <= -0.09 (n=93)
    Zona: 51 colunas
    Importance: 0.053926
  Predicado: 1400 > -0.09 (n=127)
    Zona: 51 colunas
    Importance: 0.041834
  Predicado: 1400 <= 0.06 (n=134)
    Zona: 51 colunas
    Importance: 0.039402
  Predicado: 1400 > 0.06 (n=86)
    Zona: 51 colunas
    Importance: 0.058700
  Predicado: 1400 <= 0.25 (n=180)
    Zona: 51 colunas
    Importance: 0.037755
  Predicado: 1500 > -0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.042642
  Predicado: 1500 <= -0.10 (n=93)
    Zona: 51 colunas
    Importance: 0.056889
  Predicado: 1500 > -0.10 (n=127)
    Zona: 51 colunas
    Importance: 0.046791
  Predicado: 1500 <= 0.06 (n=133)
    Zona: 51 colunas
    Importance: 0.041806
  Predicado: 1500 > 0.06 (n=87)
    Zona: 51 colunas
    Importance: 0.065206
  Predicado: 1500 <= 0.26 (n=179)
    Zona: 51 colunas
    Importance: 0.040426
  Predicado: 1600 > -0.25 (n=175)
    Zona: 51 colunas
    Importance: 0.040688
  Predicado: 1600 <= -0.09 (n=92)
    Zona: 51 colunas
    Importance: 0.053851
  Predicado: 1600 > -0.09 (n=128)
    Zona: 51 colunas
    Importance: 0.044842
  Predicado: 1600 <= 0.05 (n=134)
    Zona: 51 colunas
    Importance: 0.039161
  Predicado: 1600 > 0.05 (n=86)
    Zona: 51 colunas
    Importance: 0.063331
  Predicado: 1600 <= 0.26 (n=179)
    Zona: 51 colunas
    Importance: 0.038222
  Predicado: 1700 > -0.26 (n=176)
    Zona: 51 colunas
    Importance: 0.034512
  Predicado: 1700 <= -0.09 (n=91)
    Zona: 51 colunas
    Importance: 0.044930
  Predicado: 1700 > -0.09 (n=129)
    Zona: 51 colunas
    Importance: 0.038205
  Predicado: 1700 <= 0.05 (n=131)
    Zona: 51 colunas
    Importance: 0.032933
  Predicado: 1700 > 0.05 (n=89)
    Zona: 51 colunas
    Importance: 0.052841
  Predicado: 1700 <= 0.26 (n=181)
    Zona: 51 colunas
    Importance: 0.032172
  Predicado: 1800 > -0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.025054
  Predicado: 1800 <= -0.09 (n=92)
    Zona: 51 colunas
    Importance: 0.033858
  Predicado: 1800 > -0.09 (n=128)
    Zona: 51 colunas
    Importance: 0.027422
  Predicado: 1800 <= 0.06 (n=136)
    Zona: 51 colunas
    Importance: 0.024456
  Predicado: 1800 > 0.06 (n=84)
    Zona: 51 colunas
    Importance: 0.039272
  Predicado: 1800 <= 0.26 (n=181)
    Zona: 51 colunas
    Importance: 0.023903
  Predicado: 1900 > -0.26 (n=177)
    Zona: 51 colunas
    Importance: 0.008472
  Predicado: 1900 <= -0.09 (n=90)
    Zona: 51 colunas
    Importance: 0.011592
  Predicado: 1900 > -0.09 (n=130)
    Zona: 51 colunas
    Importance: 0.009202
  Predicado: 1900 <= 0.07 (n=137)
    Zona: 51 colunas
    Importance: 0.008215
  Predicado: 1900 > 0.07 (n=83)
    Zona: 51 colunas
    Importance: 0.013423
  Predicado: 1900 <= 0.25 (n=183)
    Zona: 51 colunas
    Importance: 0.008144
  Predicado: 2000 > -0.26 (n=176)
    Zona: 51 colunas
    Importance: 0.002513
  Predicado: 2000 <= -0.10 (n=88)
    Zona: 51 colunas
    Importance: 0.003498
  Predicado: 2000 > -0.10 (n=132)
    Zona: 51 colunas
    Importance: 0.002691
  Predicado: 2000 <= 0.07 (n=136)
    Zona: 51 colunas
    Importance: 0.002446
  Predicado: 2000 > 0.07 (n=84)
    Zona: 51 colunas
    Importance: 0.003933
  Predicado: 2000 <= 0.25 (n=181)
    Zona: 51 colunas
    Importance: 0.002407
  Predicado: 2100 > -0.26 (n=176)
    Zona: 51 colunas
    Importance: 0.005432
  Predicado: 2100 <= -0.10 (n=89)
    Zona: 51 colunas
    Importance: 0.007314
  Predicado: 2100 > -0.10 (n=131)
    Zona: 51 colunas
    Importance: 0.005838
  Predicado: 2100 <= 0.07 (n=134)
    Zona: 51 colunas
    Importance: 0.005224
  Predicado: 2100 > 0.07 (n=86)
    Zona: 51 colunas
    Importance: 0.008322
  Predicado: 2100 <= 0.25 (n=182)
    Zona: 51 colunas
    Importance: 0.005114
  Predicado: 2200 > -0.25 (n=174)
    Zona: 51 colunas
    Importance: 0.006783
  Predicado: 2200 <= -0.11 (n=84)
    Zona: 51 colunas
    Importance: 0.010382
  Predicado: 2200 > -0.11 (n=136)
    Zona: 51 colunas
    Importance: 0.006950
  Predicado: 2200 <= 0.08 (n=137)
    Zona: 51 colunas
    Importance: 0.007064
  Predicado: 2200 > 0.08 (n=83)
    Zona: 51 colunas
    Importance: 0.010234
  Predicado: 2200 <= 0.25 (n=181)
    Zona: 51 colunas
    Importance: 0.006767
  Predicado: 2300 > -0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.016437
  Predicado: 2300 <= -0.11 (n=87)
    Zona: 51 colunas
    Importance: 0.023806
  Predicado: 2300 > -0.11 (n=133)
    Zona: 51 colunas
    Importance: 0.017168
  Predicado: 2300 <= 0.08 (n=137)
    Zona: 51 colunas
    Importance: 0.016563
  Predicado: 2300 > 0.08 (n=83)
    Zona: 51 colunas
    Importance: 0.025126
  Predicado: 2300 <= 0.27 (n=181)
    Zona: 51 colunas
    Importance: 0.016092
  Predicado: 2400 > -0.27 (n=173)
    Zona: 50 colunas
    Importance: 0.030280
  Predicado: 2400 <= -0.11 (n=89)
    Zona: 50 colunas
    Importance: 0.044205
  Predicado: 2400 > -0.11 (n=131)
    Zona: 50 colunas
    Importance: 0.031875
  Predicado: 2400 <= 0.09 (n=136)
    Zona: 50 colunas
    Importance: 0.031153
  Predicado: 2400 > 0.09 (n=84)
    Zona: 50 colunas
    Importance: 0.046107
  Predicado: 2400 <= 0.27 (n=182)
    Zona: 50 colunas
    Importance: 0.030258

[Bag_2] Processando 126 predicados...
  Predicado: 400 > -0.25 (n=172)
    Zona: 51 colunas
    Importance: 0.006420
  Predicado: 400 <= -0.08 (n=90)
    Zona: 51 colunas
    Importance: 0.011433
  Predicado: 400 > -0.08 (n=130)
    Zona: 51 colunas
    Importance: 0.006867
  Predicado: 400 <= 0.14 (n=127)
    Zona: 51 colunas
    Importance: 0.008793
  Predicado: 400 > 0.14 (n=93)
    Zona: 51 colunas
    Importance: 0.008656
  Predicado: 400 <= 0.30 (n=170)
    Zona: 51 colunas
    Importance: 0.008225
  Predicado: 500 > -0.21 (n=172)
    Zona: 51 colunas
    Importance: 0.027492
  Predicado: 500 <= -0.05 (n=90)
    Zona: 51 colunas
    Importance: 0.049346
  Predicado: 500 > -0.05 (n=130)
    Zona: 51 colunas
    Importance: 0.028959
  Predicado: 500 <= 0.10 (n=128)
    Zona: 51 colunas
    Importance: 0.036577
  Predicado: 500 > 0.10 (n=92)
    Zona: 51 colunas
    Importance: 0.038304
  Predicado: 500 <= 0.26 (n=172)
    Zona: 51 colunas
    Importance: 0.033757
  Predicado: 600 > -0.14 (n=174)
    Zona: 51 colunas
    Importance: 0.033654
  Predicado: 600 <= -0.03 (n=91)
    Zona: 51 colunas
    Importance: 0.063775
  Predicado: 600 > -0.03 (n=129)
    Zona: 51 colunas
    Importance: 0.033489
  Predicado: 600 <= 0.06 (n=133)
    Zona: 51 colunas
    Importance: 0.045934
  Predicado: 600 > 0.06 (n=87)
    Zona: 51 colunas
    Importance: 0.046142
  Predicado: 600 <= 0.14 (n=178)
    Zona: 51 colunas
    Importance: 0.041184
  Predicado: 700 > -0.15 (n=177)
    Zona: 51 colunas
    Importance: 0.050688
  Predicado: 700 <= -0.04 (n=92)
    Zona: 51 colunas
    Importance: 0.096331
  Predicado: 700 > -0.04 (n=128)
    Zona: 51 colunas
    Importance: 0.049313
  Predicado: 700 <= 0.07 (n=137)
    Zona: 51 colunas
    Importance: 0.068970
  Predicado: 700 > 0.07 (n=83)
    Zona: 51 colunas
    Importance: 0.068984
  Predicado: 700 <= 0.16 (n=175)
    Zona: 51 colunas
    Importance: 0.062465
  Predicado: 800 > -0.14 (n=174)
    Zona: 51 colunas
    Importance: 0.030519
  Predicado: 800 <= -0.05 (n=91)
    Zona: 51 colunas
    Importance: 0.051443
  Predicado: 800 > -0.05 (n=129)
    Zona: 51 colunas
    Importance: 0.031274
  Predicado: 800 <= 0.06 (n=132)
    Zona: 51 colunas
    Importance: 0.037749
  Predicado: 800 > 0.06 (n=88)
    Zona: 51 colunas
    Importance: 0.042418
  Predicado: 800 <= 0.15 (n=172)
    Zona: 51 colunas
    Importance: 0.034513
  Predicado: 900 > -0.17 (n=176)
    Zona: 51 colunas
    Importance: 0.026480
  Predicado: 900 <= -0.05 (n=91)
    Zona: 51 colunas
    Importance: 0.040414
  Predicado: 900 > -0.05 (n=129)
    Zona: 51 colunas
    Importance: 0.028115
  Predicado: 900 <= 0.05 (n=130)
    Zona: 51 colunas
    Importance: 0.029863
  Predicado: 900 > 0.05 (n=90)
    Zona: 51 colunas
    Importance: 0.038026
  Predicado: 900 <= 0.16 (n=173)
    Zona: 51 colunas
    Importance: 0.027553
  Predicado: 1000 > -0.20 (n=174)
    Zona: 51 colunas
    Importance: 0.023517
  Predicado: 1000 <= -0.05 (n=91)
    Zona: 51 colunas
    Importance: 0.034616
  Predicado: 1000 > -0.05 (n=129)
    Zona: 51 colunas
    Importance: 0.025425
  Predicado: 1000 <= 0.05 (n=133)
    Zona: 51 colunas
    Importance: 0.025059
  Predicado: 1000 > 0.05 (n=87)
    Zona: 51 colunas
    Importance: 0.035600
  Predicado: 1000 <= 0.20 (n=176)
    Zona: 51 colunas
    Importance: 0.023799
  Predicado: 1100 > -0.23 (n=176)
    Zona: 51 colunas
    Importance: 0.003494
  Predicado: 1100 <= -0.07 (n=89)
    Zona: 51 colunas
    Importance: 0.005199
  Predicado: 1100 > -0.07 (n=131)
    Zona: 51 colunas
    Importance: 0.003715
  Predicado: 1100 <= 0.06 (n=133)
    Zona: 51 colunas
    Importance: 0.003705
  Predicado: 1100 > 0.06 (n=87)
    Zona: 51 colunas
    Importance: 0.005248
  Predicado: 1100 <= 0.22 (n=174)
    Zona: 51 colunas
    Importance: 0.003486
  Predicado: 1200 > -0.24 (n=176)
    Zona: 51 colunas
    Importance: 0.020939
  Predicado: 1200 <= -0.08 (n=90)
    Zona: 51 colunas
    Importance: 0.029820
  Predicado: 1200 > -0.08 (n=130)
    Zona: 51 colunas
    Importance: 0.022244
  Predicado: 1200 <= 0.07 (n=132)
    Zona: 51 colunas
    Importance: 0.021510
  Predicado: 1200 > 0.07 (n=88)
    Zona: 51 colunas
    Importance: 0.031093
  Predicado: 1200 <= 0.25 (n=175)
    Zona: 51 colunas
    Importance: 0.020178
  Predicado: 1300 > -0.24 (n=177)
    Zona: 51 colunas
    Importance: 0.037556
  Predicado: 1300 <= -0.09 (n=87)
    Zona: 51 colunas
    Importance: 0.052920
  Predicado: 1300 > -0.09 (n=133)
    Zona: 51 colunas
    Importance: 0.039597
  Predicado: 1300 <= 0.07 (n=131)
    Zona: 51 colunas
    Importance: 0.037456
  Predicado: 1300 > 0.07 (n=89)
    Zona: 51 colunas
    Importance: 0.055773
  Predicado: 1300 <= 0.25 (n=175)
    Zona: 51 colunas
    Importance: 0.035261
  Predicado: 1400 > -0.24 (n=175)
    Zona: 51 colunas
    Importance: 0.040398
  Predicado: 1400 <= -0.09 (n=86)
    Zona: 51 colunas
    Importance: 0.054744
  Predicado: 1400 > -0.09 (n=134)
    Zona: 51 colunas
    Importance: 0.043099
  Predicado: 1400 <= 0.06 (n=131)
    Zona: 51 colunas
    Importance: 0.038457
  Predicado: 1400 > 0.06 (n=89)
    Zona: 51 colunas
    Importance: 0.061184
  Predicado: 1400 <= 0.25 (n=174)
    Zona: 51 colunas
    Importance: 0.036739
  Predicado: 1500 > -0.26 (n=176)
    Zona: 51 colunas
    Importance: 0.044713
  Predicado: 1500 <= -0.10 (n=87)
    Zona: 51 colunas
    Importance: 0.057543
  Predicado: 1500 > -0.10 (n=133)
    Zona: 51 colunas
    Importance: 0.048492
  Predicado: 1500 <= 0.06 (n=131)
    Zona: 51 colunas
    Importance: 0.040881
  Predicado: 1500 > 0.06 (n=89)
    Zona: 51 colunas
    Importance: 0.068542
  Predicado: 1500 <= 0.26 (n=173)
    Zona: 51 colunas
    Importance: 0.039540
  Predicado: 1600 > -0.25 (n=173)
    Zona: 51 colunas
    Importance: 0.042863
  Predicado: 1600 <= -0.09 (n=87)
    Zona: 51 colunas
    Importance: 0.054495
  Predicado: 1600 > -0.09 (n=133)
    Zona: 51 colunas
    Importance: 0.046739
  Predicado: 1600 <= 0.05 (n=129)
    Zona: 51 colunas
    Importance: 0.039072
  Predicado: 1600 > 0.05 (n=91)
    Zona: 51 colunas
    Importance: 0.065023
  Predicado: 1600 <= 0.26 (n=173)
    Zona: 51 colunas
    Importance: 0.037651
  Predicado: 1700 > -0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.036622
  Predicado: 1700 <= -0.09 (n=85)
    Zona: 51 colunas
    Importance: 0.046344
  Predicado: 1700 > -0.09 (n=135)
    Zona: 51 colunas
    Importance: 0.039643
  Predicado: 1700 <= 0.05 (n=126)
    Zona: 51 colunas
    Importance: 0.033169
  Predicado: 1700 > 0.05 (n=94)
    Zona: 51 colunas
    Importance: 0.054379
  Predicado: 1700 <= 0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.031990
  Predicado: 1800 > -0.26 (n=172)
    Zona: 51 colunas
    Importance: 0.026615
  Predicado: 1800 <= -0.09 (n=88)
    Zona: 51 colunas
    Importance: 0.034557
  Predicado: 1800 > -0.09 (n=132)
    Zona: 51 colunas
    Importance: 0.028802
  Predicado: 1800 <= 0.06 (n=131)
    Zona: 51 colunas
    Importance: 0.024743
  Predicado: 1800 > 0.06 (n=89)
    Zona: 51 colunas
    Importance: 0.040467
  Predicado: 1800 <= 0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.023937
  Predicado: 1900 > -0.26 (n=175)
    Zona: 51 colunas
    Importance: 0.009093
  Predicado: 1900 <= -0.09 (n=88)
    Zona: 51 colunas
    Importance: 0.011809
  Predicado: 1900 > -0.09 (n=132)
    Zona: 51 colunas
    Importance: 0.009816
  Predicado: 1900 <= 0.07 (n=132)
    Zona: 51 colunas
    Importance: 0.008474
  Predicado: 1900 > 0.07 (n=88)
    Zona: 51 colunas
    Importance: 0.013822
  Predicado: 1900 <= 0.25 (n=176)
    Zona: 51 colunas
    Importance: 0.008281
  Predicado: 2000 > -0.26 (n=174)
    Zona: 51 colunas
    Importance: 0.002700
  Predicado: 2000 <= -0.10 (n=86)
    Zona: 51 colunas
    Importance: 0.003566
  Predicado: 2000 > -0.10 (n=134)
    Zona: 51 colunas
    Importance: 0.002875
  Predicado: 2000 <= 0.07 (n=131)
    Zona: 51 colunas
    Importance: 0.002528
  Predicado: 2000 > 0.07 (n=89)
    Zona: 51 colunas
    Importance: 0.004055
  Predicado: 2000 <= 0.25 (n=174)
    Zona: 51 colunas
    Importance: 0.002457
  Predicado: 2100 > -0.26 (n=173)
    Zona: 51 colunas
    Importance: 0.005750
  Predicado: 2100 <= -0.10 (n=86)
    Zona: 51 colunas
    Importance: 0.007459
  Predicado: 2100 > -0.10 (n=134)
    Zona: 51 colunas
    Importance: 0.006180
  Predicado: 2100 <= 0.07 (n=128)
    Zona: 51 colunas
    Importance: 0.005373
  Predicado: 2100 > 0.07 (n=92)
    Zona: 51 colunas
    Importance: 0.008497
  Predicado: 2100 <= 0.25 (n=176)
    Zona: 51 colunas
    Importance: 0.005213
  Predicado: 2200 > -0.25 (n=172)
    Zona: 51 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,700 <= -0.04,1500 > 0.06,1600 > 0.05,700 > 0.07
1,700 <= 0.07,700 <= -0.04,600 <= -0.03,700 <= -0.04
2,1400 > 0.06,700 <= 0.07,700 <= 0.16,1600 > 0.05
3,600 <= -0.03,700 > 0.07,700 <= -0.04,600 <= -0.03
4,700 > 0.07,1600 > 0.05,700 > 0.07,1500 > 0.06
...,...,...,...,...
123,2000 > -0.26,2000 > -0.26,2000 > -0.26,2000 > -0.26
124,2000 <= 0.07,2000 <= 0.07,2000 <= 0.07,2000 <= 0.07
125,2000 <= 0.25,2000 <= 0.25,2000 <= 0.25,2000 <= 0.25
126,Class_A,Class_A,Class_A,Class_A
127,Class_B,Class_B,Class_B,Class_B

In [21]:
all_results_pert[0]['pert_results_dict']['Bag_1']

        Predicate  Perturbation
0    700 <= -0.04      0.096202
1     700 <= 0.07      0.073413
2      700 > 0.07      0.066904
3     1500 > 0.06      0.065206
4     700 <= 0.16      0.064794
..            ...           ...
121  1100 > -0.23      0.003365
122  2000 > -0.10      0.002691
123  2000 > -0.26      0.002513
124  2000 <= 0.07      0.002446
125  2000 <= 0.25      0.002407

[126 rows x 2 columns]

In [22]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

             Node  Local_Reaching_Centrality  Zone Threshold Operator
0    700 <= -0.04                   2.292728   700     -0.04       <=
1     1600 > 0.05                   2.211310  1600      0.05        >
2     1500 > 0.06                   2.179286  1500      0.06        >
3    600 <= -0.03                   2.138556   600     -0.03       <=
4     1400 > 0.06                   1.975489  1400      0.06        >
5     1300 > 0.07                   1.929442  1300      0.07        >
6     1700 > 0.05                   1.780747  1700      0.05        >
7    800 <= -0.05                   1.284515   800     -0.05       <=
8   2400 <= -0.11                   1.260093  2400     -0.11       <=
9    500 <= -0.05                   1.176885   500     -0.05       <=
10    1800 > 0.06                   1.127993  1800      0.06        >
11     900 > 0.05                   1.075027   900      0.05        >
12  1200 <= -0.08                   1.013238  1200     -0.08       <=
13  1000 <= -0.05                   1.012537  1000     -0.05       <=
14    2300 > 0.08                   0.707177  2300      0.08        >
15    1900 > 0.07                   0.230050  1900      0.07        >
16    2200 > 0.08                   0.174271  2200      0.08        >
17   400 <= -0.08                   0.171523   400     -0.08       <=
18    2100 > 0.07                   0.115622  2100      0.07        >
19  1100 <= -0.07                   0.032497  1100     -0.07       <=
20    2000 > 0.07                   0.022205  2000      0.07        >
21        Class_A                   0.000000  None      None     None

In [23]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,700 <= -0.04,2.292728,700,-0.04,<=,-0.039772,98.0,0.000228,700 <= -0.039772
1,1600 > 0.05,2.211310,1600,0.05,>,0.050227,31.0,0.000225,1600 > 0.050227
2,700 > 0.07,2.202305,700,0.07,>,0.069096,38.0,0.000904,700 > 0.069096
3,1500 > 0.06,2.179286,1500,0.06,>,0.063022,12.0,0.003025,1500 > 0.063022
4,600 <= -0.03,2.138556,600,-0.03,<=,-0.029653,116.0,0.000346,600 <= -0.029653
...,...,...,...,...,...,...,...,...,...
123,2000 > -0.26,0.008843,2000,-0.26,>,-0.259451,127.0,0.000550,2000 > -0.259451
124,2000 <= 0.07,0.005572,2000,0.07,<=,0.069416,137.0,0.000594,2000 <= 0.069416
125,2000 <= 0.25,0.002745,2000,0.25,<=,0.253483,207.0,0.003480,2000 <= 0.253483
126,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
127,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

In [25]:
import plotly.graph_objects as go

n = 1
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona '1600':
  - Dimensão: 51 variáveis espectrais
  - Variância explicada pela PC1: 99.98%

In [26]:
# Permutation importance baseado em mudança nas predições do modelo PLS
# Medimos a média da diferença absoluta entre as predições originais e as predições
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Predições base do modelo PLS
baseline_pred = pls_model.predict(Xcalclass_prep)
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_pred = pls_model.predict(X_perm)
        diffs.append(np.mean(np.abs(baseline_pred - perm_pred)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance': importance_list
})
permutation_df.sort_values(by='Permutation_importance', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance', ascending=False)
permutation_unique_df

   energy  Permutation_importance  Zone
0     734                0.002063   700
1     698                0.001885   600
2     534                0.001607   500
3    1542                0.001485  1500
4     802                0.001474   800
5    1612                0.001460  1600
6    1412                0.001421  1400
7    1384                0.001411  1300
8    1702                0.001282  1700
9    2470                0.001222  2400
10   1800                0.001079  1800
11    498                0.001067   400
12   1298                0.001015  1200
13    990                0.000994   900
14   1000                0.000985  1000
15   2204                0.000693  2200
16   2184                0.000691  2100
17   2398                0.000672  2300
18   1100                0.000534  1100
19   1920                0.000509  1900
20   2096                0.000144  2000

In [27]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    #len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'VIP_Score': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_Coefficient' : pad_list(reg_vet_unique_df['Zone'], max_len),
    #'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

   VIP_Score Reg_Coefficient Permutation LRC_perturbation LRC_covariance
0        700             700         700              700           1600
1        500             600         600             1600           2000
2        400             800         500             1500           1700
3        600             500        1500              600           2100
4        800            1400         800             1400           1900
5        900            1300        1600             1300           1500
6       1000            1500        1400             1700           1800
7       2400            1600        1300              800           2300
8       2300             900        1700             2400           1400
9       2200            1000        2400              500           1300
10      1400            1700        1800             1800           1200
11      1500            2400         400              900           2400
12      1300            1200        1200             1200           2200
13      1600            1800         900             1000           1100
14      1900             400        1000             2300            400
15      1100            2200        2200             1900           1000
16      1700            2100        2100             2200            500
17      1800            1100        2300              400            600
18      2100            2300        1100             2100            900
19      2000            1900        1900             1100            700
20      1200            2000        2000             2000            800
21      None            None        None             None           None

In [28]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_22244\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
4   Reg_Coefficient       Permutation   0.856430
1         VIP_Score       Permutation   0.717674
7       Permutation  LRC_perturbation   0.682314
0         VIP_Score   Reg_Coefficient   0.671806
5   Reg_Coefficient  LRC_perturbation   0.652247
2         VIP_Score  LRC_perturbation   0.584158
9  LRC_perturbation    LRC_covariance   0.249069
8       Permutation    LRC_covariance   0.046807
6   Reg_Coefficient    LRC_covariance   0.021826
3         VIP_Score    LRC_covariance   0.003132

In [29]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')