In [4]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

from synthetic import generate_synthetic_spectral_data

config = [
    {
        'nome': 'A',
        'n_amostras': 156,
        'picos': [250, 380, 550, 700, 850],  # 4 picos
        'amp_media': 1.0,
        'amp_std': 0.3,
        'larg_media': 15.0,
        'larg_std': 2.0,
        'ruido_std': 0.04
    },
    {
        'nome': 'B',
        'n_amostras': 146,
        'picos': [50, 250, 380, 550, 850],  # 3 picos (sem pico em 550)
        'amp_media': 1.4,
        'amp_std': 0.5,
        'larg_media': 15.0,
        'larg_std': 1.8,
        'ruido_std': 0.035
    }
]

data_complete = generate_synthetic_spectral_data(
    configuracao_classes=config,
    n_pontos=500,
    x_min=1,
    x_max=1000,
    seed=0
)
# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.iloc[:, 1:], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.iloc[:, 1:], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# Xcalclass_prep = Xcalclass.copy()
# Xpredclass_prep = Xpredclass.copy()

# preprocessings
import preprocessings as prepr  # preprocessing methods
Xcalclass_prep, mean_calclass  = prepr.mc(Xcalclass)
Xpredclass_prep = Xpredclass - mean_calclass

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 11:25:04,413 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 11:25:04,441 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 11:25:04,469 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 11:25:04,483 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [5]:
from modeling import mlp_optimized

mlp_model = mlp_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, 
                          aim='classification', 
                          hidden_layer_sizes=(64,32),
                          activation='tanh',
                          learning_rate='adaptive',
                          max_iter=10,
                          random_state=1)
mlp_model[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,MLP,0.990521,0.980392,1.0,"[[109, 0], [2, 100]]",0.989011,0.977273,1.0,"[[47, 0], [1, 43]]"

## Definição das Zonas Espectrais

In [6]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('F1', 1.0, 100.0),
('background1', 100.0, 200.0),
('F2', 200.0, 300.0),
('background2', 300.0, 330.0),
('F3', 330.0, 430.0),
('background3', 430.0, 500.0),
('F4', 500.0, 600.0),
('background4', 600.0, 660.0),
('F5', 660.0, 750.0),
('background5', 750.0, 815.0),
('F6', 815.0, 890.0),
('background6', 890.0, 1000.0)
]

## SHAP

In [7]:
shap_global_importance = pd.read_csv('shap_synthetic.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

        energy  Mean_Abs_SHAP         Zone
0    51.050100       0.033488           F1
1   697.697395       0.016673           F5
2   855.855711       0.005578           F6
3   261.260521       0.004658           F2
4   371.370741       0.004237           F3
5   563.563126       0.003513           F4
6   137.136273       0.000937  background1
7   625.625251       0.000901  background4
8   973.973948       0.000822  background6
9   781.781563       0.000767  background5
10  327.326653       0.000541  background2
11  433.432866       0.000494  background3

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [8]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'F1': VE = 97.70%, dim = 50 variáveis
Zona 'background1': VE = 4.20%, dim = 50 variáveis
Zona 'F2': VE = 92.76%, dim = 50 variáveis
Zona 'background2': VE = 10.44%, dim = 15 variáveis
Zona 'F3': VE = 92.93%, dim = 50 variáveis
Zona 'background3': VE = 5.32%, dim = 35 variáveis
Zona 'F4': VE = 93.74%, dim = 50 variáveis
Zona 'background4': VE = 8.95%, dim = 30 variáveis
Zona 'F5': VE = 96.69%, dim = 45 variáveis
Zona 'background5': VE = 16.85%, dim = 32 variáveis
Zona 'F6': VE = 93.73%, dim = 38 variáveis
Zona 'background6': VE = 5.17%, dim = 55 variáveis

Scores DataFrame shape: (211, 12)

In [9]:
y_pred = mlp_model[4]['MLP'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [10]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(mlp_model[4]['MLP'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 44
Removida: F1 > -2.43 -> F1 <= 2.88 (2.5467) | Mantida: F1 <= 2.88 -> F1 > -2.43 (3.2693)
Removida: F5 > -1.83 -> F1 > -2.43 (2.2980) | Mantida: F1 > -2.43 -> F5 > -1.83 (3.1656)
Removida: F6 > -1.37 -> F5 > -1.79 (0.3493) | Mantida: F5 > -1.79 -> F6 > -1.37 (1.5271)
Removida: F4 > -0.67 -> F5 > -1.79 (0.3561) | Mantida: F5 > -1.79 -> F4 > -0.67 (1.1689)
Removida: F6 > 0.11 -> F3 > -1.46 (0.2915) | Mantida: F3 > -1.46 -> F6 > 0.11 (0.3191)
Removida: F6 > -0.58 -> F3 > -1.46 (0.2858) | Mantida: F3 > -1.46 -> F6 > -0.58 (0.8623)
Removida: F3 > -1.46 -> F2 > -1.57 (0.3076) | Mantida: F2 > -1.57 -> F3 > -1.46 (0.5874)
Removida: F4 > -1.63 -> F3 > -1.46 (0.3018) | Mantida: F3 > -1.46 -> F4 > -1.63 (0.6298)
Removida: F3 > -1.46 -> F2 > -0.54 (0.2911) | Mantida: F2 > -0.54 -> F3 > -1.46 (0.6071)
Removida: F4 > -0.67 -> F6 > 0.11 (0.3170) | Mantida: F6 > 0.11 -> F4 > -0.67 (0.3215)
Removida: F4 > -1.63 -> F6 > 0.11 (0.2917) | Mantida: F6 > 0.11 -> F4 > -1.63 (0.3302)
Removida: F6 > 0.11 -> F6 > -0.58 (0.5650) | Mantida: F6 > -0.58 -> F6 > 0.11 (0.6043)
Removida: F3 > -0.44 -> F6 > 0.11 (0.2657) | Mantida: F6 > 0.11 -> F3 > -0.44 (0.2990)
Removida: F6 > 0.11 -> F6 > -1.37 (0.3166) | Mantida: F6 > -1.37 -> F6 > 0.11 (0.6384)
Removida: F2 > -1.57 -> F6 > 0.11 (0.2943) | Mantida: F6 > 0.11 -> F2 > -1.57 (0.3048)
Removida: F4 > -0.67 -> F4 > -1.63 (0.6562) | Mantida: F4 > -1.63 -> F4 > -0.67 (1.3543)
Removida: F4 > -0.67 -> F2 > -1.57 (0.3169) | Mantida: F2 > -1.57 -> F4 > -0.67 (0.6487)
Removida: F2 > -0.54 -> F6 > -1.37 (0.3164) | Mantida: F6 > -1.37 -> F2 > -0.54 (0.3545)
Removida: F4 > -1.63 -> F6 > -1.37 (0.3356) | Mantida: F6 > -1.37 -> F4 > -1.63 (0.6705)
Removida: F2 > -1.57 -> F4 > -1.63 (0.2914) | Mantida: F4 > -1.63 -> F2 > -1.57 (0.3223)
Removida: F6 > -0.58 -> F2 > -1.57 (0.2770) | Mantida: F2 > -1.57 -> F6 > -0.58 (0.2898)
Removida: F2 > -0.54 -> F2 > -1.57 (0.6283) | Mantida: F2 > -1.57 -> F2 > -0.54 (0.8956)
Removida: F6 > -0.58 -> F3 > -0.44 (0.5484) | Mantida: F3 > -0.44 -> F6 > -0.58 (0.5600)
Removida: F3 > -0.44 -> F5 <= 0.75 (0.2599) | Mantida: F5 <= 0.75 -> F3 > -0.44 (0.8296)
Removida: F2 > -0.54 -> F5 <= 0.75 (0.2615) | Mantida: F5 <= 0.75 -> F2 > -0.54 (0.5508)
Removida: F5 <= 0.75 -> F1 <= 0.67 (0.5247) | Mantida: F1 <= 0.67 -> F5 <= 0.75 (0.7415)
Removida: F3 > 0.27 -> F1 <= 0.67 (0.4488) | Mantida: F1 <= 0.67 -> F3 > 0.27 (0.8349)
Removida: F2 > 0.21 -> F3 > 0.27 (0.2107) | Mantida: F3 > 0.27 -> F2 > 0.21 (0.7509)
Removida: F2 > 0.21 -> F1 <= 0.67 (0.1917) | Mantida: F1 <= 0.67 -> F2 > 0.21 (0.6379)
Removida: F2 > 0.21 -> F4 > 0.28 (0.1775) | Mantida: F4 > 0.28 -> F2 > 0.21 (0.3420)
Removida: F4 > 0.28 -> F3 <= 1.39 (0.3016) | Mantida: F3 <= 1.39 -> F4 > 0.28 (0.6224)
Removida: F2 <= 1.43 -> F3 <= 1.39 (0.1454) | Mantida: F3 <= 1.39 -> F2 <= 1.43 (0.5998)
Removida: F4 <= 1.58 -> F4 > 0.28 (0.1341) | Mantida: F4 > 0.28 -> F4 <= 1.58 (0.2914)
Removida: F2 <= 1.43 -> F4 > 0.28 (0.2887) | Mantida: F4 > 0.28 -> F2 <= 1.43 (0.2941)
Removida: F4 <= 1.58 -> F2 <= 1.43 (0.2246) | Mantida: F2 <= 1.43 -> F4 <= 1.58 (0.6389)
Removida: F6 <= 1.18 -> F4 <= 1.58 (0.1820) | Mantida: F4 <= 1.58 -> F6 <= 1.18 (0.4930)
Removida: F3 <= 0.27 -> F6 <= 1.18 (0.0685) | Mantida: F6 <= 1.18 -> F3 <= 0.27 (0.1567)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.1840) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.3503)
Removida: F2 <= -0.54 -> F3 <= -0.44 (0.0281) | Mantida: F3 <= -0.44 -> F2 <= -0.54 (0.0513)
Removida: background4 > -0.05 -> background4 > -0.03 (0.0012) | Mantida: background4 > -0.03 -> background4 > -0.05 (0.0024)
Removida: background4 > -0.05 -> F1 > 0.67 (0.0022) | Mantida: F1 > 0.67 -> background4 > -0.05 (0.0233)
Removida: F4 <= 0.28 -> F2 <= 0.21 (0.0394) | Mantida: F2 <= 0.21 -> F4 <= 0.28 (0.0541)
Removida: F6 <= -0.58 -> F2 <= 0.21 (0.0228) | Mantida: F2 <= 0.21 -> F6 <= -0.58 (0.0412)
Removida: F2 <= -0.54 -> F4 <= 0.28 (0.0158) | Mantida: F4 <= 0.28 -> F2 <= -0.54 (0.0185)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 169 | Removidas: 44
Nós predicados: 38
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 39
Removida: F1 <= 2.88 -> F1 > -2.43 (1.6079) | Mantida: F1 > -2.43 -> F1 <= 2.88 (3.3501)
Removida: F1 > -2.43 -> F5 > -1.83 (1.5900) | Mantida: F5 > -1.83 -> F1 > -2.43 (2.9365)
Removida: F4 > -1.63 -> F4 > -0.67 (1.0700) | Mantida: F4 > -0.67 -> F4 > -1.63 (1.0734)
Removida: F4 > -1.63 -> F5 > -1.79 (0.3468) | Mantida: F5 > -1.79 -> F4 > -1.63 (0.3761)
Removida: F3 > -1.46 -> F4 > -0.67 (0.2986) | Mantida: F4 > -0.67 -> F3 > -1.46 (0.3646)
Removida: F6 > -1.37 -> F4 > -0.67 (0.3698) | Mantida: F4 > -0.67 -> F6 > -1.37 (1.0043)
Removida: F4 > -0.67 -> F6 > -0.58 (0.2843) | Mantida: F6 > -0.58 -> F4 > -0.67 (0.2898)
Removida: F6 > 0.11 -> F3 > -1.46 (0.6301) | Mantida: F3 > -1.46 -> F6 > 0.11 (0.6381)
Removida: F2 > -0.54 -> F6 > -1.37 (0.3007) | Mantida: F6 > -1.37 -> F2 > -0.54 (0.6523)
Removida: F2 > -1.57 -> F6 > -1.37 (0.3442) | Mantida: F6 > -1.37 -> F2 > -1.57 (0.9985)
Removida: F3 > -0.44 -> F6 > -0.58 (0.5876) | Mantida: F6 > -0.58 -> F3 > -0.44 (0.8364)
Removida: F3 > -0.44 -> F5 <= 0.75 (0.5264) | Mantida: F5 <= 0.75 -> F3 > -0.44 (0.7986)
Removida: F5 <= 0.75 -> F6 > -0.58 (0.2773) | Mantida: F6 > -0.58 -> F5 <= 0.75 (0.2904)
Removida: F5 <= 0.75 -> F2 > -0.54 (0.2638) | Mantida: F2 > -0.54 -> F5 <= 0.75 (0.8218)
Removida: F1 <= 0.67 -> F3 > 0.27 (0.7059) | Mantida: F3 > 0.27 -> F1 <= 0.67 (1.0693)
Removida: F4 > 0.28 -> F2 > 0.21 (0.3694) | Mantida: F2 > 0.21 -> F4 > 0.28 (0.5509)
Removida: F3 <= 1.39 -> F2 > 0.21 (0.1652) | Mantida: F2 > 0.21 -> F3 <= 1.39 (0.4892)
Removida: F3 <= 1.39 -> F4 > 0.28 (0.1604) | Mantida: F4 > 0.28 -> F3 <= 1.39 (0.4615)
Removida: F4 > 0.28 -> F6 <= 1.18 (0.0979) | Mantida: F6 <= 1.18 -> F4 > 0.28 (0.1010)
Removida: F4 > 0.28 -> F4 <= 1.58 (0.1640) | Mantida: F4 <= 1.58 -> F4 > 0.28 (0.2458)
Removida: F2 <= 1.43 -> F3 <= 1.39 (0.2395) | Mantida: F3 <= 1.39 -> F2 <= 1.43 (0.5120)
Removida: F4 <= 1.58 -> F3 <= 1.39 (0.2377) | Mantida: F3 <= 1.39 -> F4 <= 1.58 (0.3468)
Removida: F6 <= 0.11 -> F6 <= 1.18 (0.1407) | Mantida: F6 <= 1.18 -> F6 <= 0.11 (0.5324)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.1412) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.3119)
Removida: F4 <= -0.67 -> F3 <= 0.27 (0.0684) | Mantida: F3 <= 0.27 -> F4 <= -0.67 (0.1635)
Removida: F3 <= 0.27 -> F4 <= 0.28 (0.0452) | Mantida: F4 <= 0.28 -> F3 <= 0.27 (0.0476)
Removida: F3 <= 0.27 -> F2 <= 0.21 (0.0358) | Mantida: F2 <= 0.21 -> F3 <= 0.27 (0.0575)
Removida: F4 <= -0.67 -> F6 <= -0.58 (0.0352) | Mantida: F6 <= -0.58 -> F4 <= -0.67 (0.0395)
Removida: F6 <= -0.58 -> F2 <= 0.21 (0.0227) | Mantida: F2 <= 0.21 -> F6 <= -0.58 (0.0331)
Removida: background4 > -0.03 -> F6 <= -0.58 (0.0011) | Mantida: F6 <= -0.58 -> background4 > -0.03 (0.0623)
Removida: F6 <= -0.58 -> F3 <= -0.44 (0.0381) | Mantida: F3 <= -0.44 -> F6 <= -0.58 (0.0660)
Removida: F2 <= -0.54 -> F4 <= -0.67 (0.0239) | Mantida: F4 <= -0.67 -> F2 <= -0.54 (0.1019)
Removida: F3 <= -0.44 -> F4 <= -0.67 (0.0231) | Mantida: F4 <= -0.67 -> F3 <= -0.44 (0.0547)
Removida: F4 <= -0.67 -> F2 <= 0.21 (0.0363) | Mantida: F2 <= 0.21 -> F4 <= -0.67 (0.0372)
Removida: F2 <= 0.21 -> F2 <= -0.54 (0.0285) | Mantida: F2 <= -0.54 -> F2 <= 0.21 (0.0359)
Removida: background4 > -0.03 -> F3 <= -0.44 (0.0010) | Mantida: F3 <= -0.44 -> background4 > -0.03 (0.0137)
Removida: background4 > -0.03 -> F1 > 0.67 (0.0012) | Mantida: F1 > 0.67 -> background4 > -0.03 (0.0395)
Removida: background5 > 0.00 -> F1 > 0.67 (0.0019) | Mantida: F1 > 0.67 -> background5 > 0.00 (0.0107)
Removida: background4 > -0.05 -> background5 > 0.00 (0.0024) | Mantida: background5 > 0.00 -> background4 > -0.05 (0.0040)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 178 | Removidas: 39
Nós predicados: 39
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 2
======================================================================


Total de pares bidirecionais encontrados: 41
Removida: F1 > -2.43 -> F1 <= 2.88 (2.5276) | Mantida: F1 <= 2.88 -> F1 > -2.43 (3.1422)
Removida: F5 > -1.83 -> F1 > -2.43 (2.2354) | Mantida: F1 > -2.43 -> F5 > -1.83 (3.1124)
Removida: F6 > -1.37 -> F5 > -1.79 (0.3467) | Mantida: F5 > -1.79 -> F6 > -1.37 (1.4929)
Removida: F2 > -1.57 -> F6 > -1.37 (0.3044) | Mantida: F6 > -1.37 -> F2 > -1.57 (0.6672)
Removida: F6 > -1.37 -> F4 > -1.63 (0.3372) | Mantida: F4 > -1.63 -> F6 > -1.37 (0.6870)
Removida: F6 > 0.11 -> F2 > -1.57 (0.2804) | Mantida: F2 > -1.57 -> F6 > 0.11 (0.6447)
Removida: F4 > -0.67 -> F2 > -1.57 (0.3089) | Mantida: F2 > -1.57 -> F4 > -0.67 (0.9086)
Removida: F2 > -1.57 -> F4 > -1.63 (0.2949) | Mantida: F4 > -1.63 -> F2 > -1.57 (0.3310)
Removida: F2 > -0.54 -> F2 > -1.57 (0.6178) | Mantida: F2 > -1.57 -> F2 > -0.54 (0.6501)
Removida: F2 > -0.54 -> F6 > 0.11 (0.2902) | Mantida: F6 > 0.11 -> F2 > -0.54 (0.6100)
Removida: F6 > 0.11 -> F6 > -0.58 (0.2874) | Mantida: F6 > -0.58 -> F6 > 0.11 (0.5907)
Removida: F6 > 0.11 -> F4 > -1.63 (0.2858) | Mantida: F4 > -1.63 -> F6 > 0.11 (0.3280)
Removida: F4 > -0.67 -> F2 > -0.54 (0.2932) | Mantida: F2 > -0.54 -> F4 > -0.67 (0.9394)
Removida: F2 > -0.54 -> F3 > -1.46 (0.2780) | Mantida: F3 > -1.46 -> F2 > -0.54 (0.2938)
Removida: F6 > -0.58 -> F2 > -0.54 (0.3161) | Mantida: F2 > -0.54 -> F6 > -0.58 (0.5814)
Removida: F2 > -0.54 -> F3 > -0.44 (0.2772) | Mantida: F3 > -0.44 -> F2 > -0.54 (0.2992)
Removida: F4 > -1.63 -> F4 > -0.67 (0.3327) | Mantida: F4 > -0.67 -> F4 > -1.63 (0.9700)
Removida: F3 > -1.46 -> F4 > -0.67 (0.5796) | Mantida: F4 > -0.67 -> F3 > -1.46 (0.6145)
Removida: F5 <= 0.75 -> F6 > -0.58 (0.2903) | Mantida: F6 > -0.58 -> F5 <= 0.75 (0.5512)
Removida: F5 <= 0.75 -> F3 > -1.46 (0.5546) | Mantida: F3 > -1.46 -> F5 <= 0.75 (1.0893)
Removida: F2 > 0.21 -> F1 <= 0.67 (0.2392) | Mantida: F1 <= 0.67 -> F2 > 0.21 (0.7302)
Removida: F3 > 0.27 -> F1 <= 0.67 (0.4366) | Mantida: F1 <= 0.67 -> F3 > 0.27 (0.9369)
Removida: F2 > 0.21 -> F3 > 0.27 (0.5881) | Mantida: F3 > 0.27 -> F2 > 0.21 (1.0393)
Removida: F2 <= 1.43 -> F2 > 0.21 (0.1397) | Mantida: F2 > 0.21 -> F2 <= 1.43 (0.1507)
Removida: F3 <= 1.39 -> F4 > 0.28 (0.2714) | Mantida: F4 > 0.28 -> F3 <= 1.39 (0.4670)
Removida: F6 <= 1.18 -> F4 > 0.28 (0.1169) | Mantida: F4 > 0.28 -> F6 <= 1.18 (0.2271)
Removida: F4 > 0.28 -> F2 <= 1.43 (0.2894) | Mantida: F2 <= 1.43 -> F4 > 0.28 (0.3927)
Removida: F3 <= 1.39 -> F4 <= 1.58 (0.1203) | Mantida: F4 <= 1.58 -> F3 <= 1.39 (0.2447)
Removida: F6 <= 1.18 -> F3 <= 1.39 (0.0764) | Mantida: F3 <= 1.39 -> F6 <= 1.18 (0.1940)
Removida: F2 <= 1.43 -> F4 <= 1.58 (0.2294) | Mantida: F4 <= 1.58 -> F2 <= 1.43 (0.3993)
Removida: F4 <= 1.58 -> F6 <= 1.18 (0.0788) | Mantida: F6 <= 1.18 -> F4 <= 1.58 (0.2156)
Removida: F6 <= 0.11 -> F4 <= 1.58 (0.0831) | Mantida: F4 <= 1.58 -> F6 <= 0.11 (0.1851)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.0689) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.2616)
Removida: F3 <= 0.27 -> F4 <= -0.67 (0.1174) | Mantida: F4 <= -0.67 -> F3 <= 0.27 (0.1498)
Removida: F3 <= -0.44 -> F4 <= -0.67 (0.0253) | Mantida: F4 <= -0.67 -> F3 <= -0.44 (0.0343)
Removida: F4 <= 0.28 -> F6 <= -0.58 (0.0203) | Mantida: F6 <= -0.58 -> F4 <= 0.28 (0.0537)
Removida: background4 > -0.03 -> F1 > 0.67 (0.0023) | Mantida: F1 > 0.67 -> background4 > -0.03 (0.0274)
Removida: background4 > -0.03 -> F2 <= -0.54 (0.0012) | Mantida: F2 <= -0.54 -> background4 > -0.03 (0.0146)
Removida: background4 > -0.05 -> F1 > 0.67 (0.0044) | Mantida: F1 > 0.67 -> background4 > -0.05 (0.0233)
Removida: background4 > -0.05 -> F2 <= -0.54 (0.0011) | Mantida: F2 <= -0.54 -> background4 > -0.05 (0.0126)
Removida: F2 <= -0.54 -> F2 <= 0.21 (0.0217) | Mantida: F2 <= 0.21 -> F2 <= -0.54 (0.0768)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 179 | Removidas: 41
Nós predicados: 37
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 3
======================================================================


Total de pares bidirecionais encontrados: 39
Removida: F1 <= 2.88 -> F1 > -2.43 (1.6132) | Mantida: F1 > -2.43 -> F1 <= 2.88 (6.6058)
Removida: F6 > -1.37 -> F5 > -1.79 (0.3365) | Mantida: F5 > -1.79 -> F6 > -1.37 (1.5423)
Removida: F6 > -1.37 -> F6 > 0.11 (0.3603) | Mantida: F6 > 0.11 -> F6 > -1.37 (0.9618)
Removida: F4 > -0.67 -> F4 > -1.63 (1.0199) | Mantida: F4 > -1.63 -> F4 > -0.67 (1.3772)
Removida: F6 > 0.11 -> F4 > -0.67 (0.6780) | Mantida: F4 > -0.67 -> F6 > 0.11 (1.0288)
Removida: F6 > -0.58 -> F4 > -1.63 (0.3125) | Mantida: F4 > -1.63 -> F6 > -0.58 (0.3247)
Removida: F3 > -1.46 -> F2 > -0.54 (0.2959) | Mantida: F2 > -0.54 -> F3 > -1.46 (0.8975)
Removida: F5 <= 0.75 -> F3 > -1.46 (0.2788) | Mantida: F3 > -1.46 -> F5 <= 0.75 (0.8865)
Removida: F2 > -0.54 -> F2 > -1.57 (0.5680) | Mantida: F2 > -1.57 -> F2 > -0.54 (1.1972)
Removida: F6 > -0.58 -> F2 > -0.54 (0.2931) | Mantida: F2 > -0.54 -> F6 > -0.58 (0.3133)
Removida: F3 > -0.44 -> F2 > -0.54 (0.2881) | Mantida: F2 > -0.54 -> F3 > -0.44 (0.5538)
Removida: F3 > -0.44 -> F2 > -1.57 (0.2818) | Mantida: F2 > -1.57 -> F3 > -0.44 (0.2859)
Removida: F5 <= 0.75 -> F2 > -1.57 (0.2890) | Mantida: F2 > -1.57 -> F5 <= 0.75 (0.5444)
Removida: F5 <= 0.75 -> F3 > -0.44 (0.2807) | Mantida: F3 > -0.44 -> F5 <= 0.75 (0.5281)
Removida: F1 <= 0.67 -> F3 > -0.44 (0.2681) | Mantida: F3 > -0.44 -> F1 <= 0.67 (0.4887)
Removida: F6 > -0.58 -> F5 <= 0.75 (0.5647) | Mantida: F5 <= 0.75 -> F6 > -0.58 (0.8642)
Removida: F3 > 0.27 -> F1 <= 0.67 (0.9066) | Mantida: F1 <= 0.67 -> F3 > 0.27 (1.2030)
Removida: F2 > 0.21 -> F1 <= 0.67 (0.2120) | Mantida: F1 <= 0.67 -> F2 > 0.21 (0.8647)
Removida: F4 > 0.28 -> F2 > 0.21 (0.1713) | Mantida: F2 > 0.21 -> F4 > 0.28 (1.2365)
Removida: F3 <= 1.39 -> F4 > 0.28 (0.1393) | Mantida: F4 > 0.28 -> F3 <= 1.39 (0.7548)
Removida: F4 <= 1.58 -> F3 <= 1.39 (0.1275) | Mantida: F3 <= 1.39 -> F4 <= 1.58 (0.6306)
Removida: F2 <= 1.43 -> F3 <= 1.39 (0.2566) | Mantida: F3 <= 1.39 -> F2 <= 1.43 (0.2627)
Removida: F2 <= 1.43 -> F6 <= 1.18 (0.1021) | Mantida: F6 <= 1.18 -> F2 <= 1.43 (0.2178)
Removida: F6 <= 1.18 -> F4 <= 1.58 (0.0697) | Mantida: F4 <= 1.58 -> F6 <= 1.18 (0.2163)
Removida: F6 <= 1.18 -> F6 <= 0.11 (0.0695) | Mantida: F6 <= 0.11 -> F6 <= 1.18 (0.2970)
Removida: F6 <= 1.18 -> F3 <= 0.27 (0.0713) | Mantida: F3 <= 0.27 -> F6 <= 1.18 (0.0754)
Removida: F2 <= 1.43 -> F4 <= 1.58 (0.2110) | Mantida: F4 <= 1.58 -> F2 <= 1.43 (0.2176)
Removida: F6 <= 0.11 -> F4 <= 1.58 (0.1009) | Mantida: F4 <= 1.58 -> F6 <= 0.11 (0.3712)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.0878) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.2135)
Removida: F4 <= -0.67 -> F3 <= 0.27 (0.0989) | Mantida: F3 <= 0.27 -> F4 <= -0.67 (0.2310)
Removida: F3 <= 0.27 -> F2 <= 0.21 (0.0238) | Mantida: F2 <= 0.21 -> F3 <= 0.27 (0.0486)
Removida: F4 <= -0.67 -> F4 <= 0.28 (0.0196) | Mantida: F4 <= 0.28 -> F4 <= -0.67 (0.0303)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,F1 > -2.47,F1 > -2.47,F1 > -2.47,F1 > -2.47
1,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88,F1 > -2.43
2,F5 > -1.83,F5 > -1.83,F5 > -1.83,F1 <= 2.88
3,F1 > -2.43,F1 > -2.43,F1 > -2.43,F5 > -1.83
4,F5 <= 2.10,F5 <= 2.10,F5 <= 2.10,F5 <= 2.10
5,F5 > -1.79,F2 > -1.57,F5 > -1.79,F5 > -1.79
6,F6 > -1.37,F5 > -1.79,F3 > -1.46,F4 > -0.67
7,F2 > -1.57,F4 > -1.63,F3 > -0.44,F6 > -0.58
8,F2 > -0.54,F3 > -1.46,F4 > -0.67,F6 > 0.11
9,F3 > -0.44,F2 > -0.54,F2 > -1.57,F5 <= 0.75
10,F6 > -0.58,F5 <= 0.75,F6 > -1.37,F2 > -1.57
11,F4 > -1.63,F4 > -0.67,F5 <= 0.75,F3 > -1.46
12,F3 > -1.46,F6 > -1.37,F4 > -1.63,F6 > -1.37
13,F5 <= 0.75,F6 > -0.58,F2 > -0.54,F3 > -0.44
14,F1 <= 0.67,F3 > -0.44,F6 > 0.11,F2 > -0.54
15,F4 > -0.67,F3 > 0.27,F6 > -0.58,F4 > -1.63
16,F6 > 0.11,F6 > 0.11,F1 <= 0.67,F1 <= 0.67
17,F3 > 0.27,F1 <= 0.67,F3 > 0.27,F3 > 0.27
18,F2 > 0.21,F2 > 0.21,F3 <= 1.39,F2 > 0.21
19,F3 <= 1.39,F2 <= 1.43,F2 <= 1.43,F4 > 0.28
20,F2 <= 1.43,F4 > 0.28,F6 <= 1.18,F3 <= 1.39
21,F4 > 0.28,F3 <= 1.39,F4 > 0.28,F2 <= 1.43
22,F4 <= 1.58,F4 <= 1.58,F2 > 0.21,F4 <= 1.58
23,F6 <= 1.18,F6 <= 1.18,F4 <= 1.58,F6 <= 1.18
24,F6 > 1.18,F6 <= 0.11,F6 <= 0.11,F6 <= 0.11
25,F6 <= 0.11,F3 <= 0.27,F3 <= 0.27,F3 <= 0.27
26,F3 <= 0.27,F6 <= -1.37,F4 <= -0.67,F4 <= -0.67
27,F4 <= -0.67,F2 <= 0.21,F2 <= -0.54,F2 <= 0.21
28,F6 <= -0.58,F4 <= 0.28,F2 <= 0.21,F4 <= 0.28
29,F4 <= 0.28,F4 <= -0.67,F4 <= 0.28,F6 <= -0.58
30,F2 <= 0.21,F3 <= -0.44,F3 <= -0.44,F3 <= -0.44
31,F1 > 0.67,background5 > -0.07,F6 <= -0.58,F2 <= -0.54
32,F3 <= -0.44,F2 <= -0.54,F1 > 0.67,background5 > -0.04
33,F2 <= -0.54,F6 <= -0.58,background4 > -0.05,background4 > -0.05
34,background4 > -0.03,background5 > -0.04,background4 > -0.03,background4 > -0.03
35,background4 > -0.05,F1 > 0.67,background5 > -0.04,F1 > 0.67
36,background5 > 0.00,background4 > -0.05,background5 > 0.00,background5 > 0.00
37,background5 > -0.04,background4 > -0.03,Class_A,Class_A
38,Class_A,background5 > 0.00,Class_B,Class_B
39,Class_B,Class_A,NaN,NaN
40,NaN,Class_B,NaN,NaN

In [11]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,F1 > -2.47,6.170546,F1,-2.47,>
1,F5 > -1.83,3.665189,F5,-1.83,>
2,F2 > -1.57,1.010509,F2,-1.57,>
3,F3 > -1.46,0.967540,F3,-1.46,>
4,F4 > -0.67,0.950860,F4,-0.67,>
5,F6 > -1.37,0.948671,F6,-1.37,>
6,background4 > -0.05,0.038514,background4,-0.05,>
7,background5 > -0.04,0.037322,background5,-0.04,>
8,Class_B,0.000000,None,None,None

In [12]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'F1': VE = 97.70%, dim = 50 variáveis
Zona 'background1': VE = 4.20%, dim = 50 variáveis
Zona 'F2': VE = 92.76%, dim = 50 variáveis
Zona 'background2': VE = 10.44%, dim = 15 variáveis
Zona 'F3': VE = 92.93%, dim = 50 variáveis
Zona 'background3': VE = 5.32%, dim = 35 variáveis
Zona 'F4': VE = 93.74%, dim = 50 variáveis
Zona 'background4': VE = 8.95%, dim = 30 variáveis
Zona 'F5': VE = 96.69%, dim = 45 variáveis
Zona 'background5': VE = 16.85%, dim = 32 variáveis
Zona 'F6': VE = 93.73%, dim = 38 variáveis
Zona 'background6': VE = 5.17%, dim = 55 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,F1 > -2.47,6.170546,F1,-2.47,>,-2.469280,70.0,0.000720,F1 > -2.469280
1,F1 <= 2.88,4.592136,F1,2.88,<=,2.877525,163.0,0.002475,F1 <= 2.877525
2,F5 > -1.83,3.665189,F5,-1.83,>,-1.830283,186.0,0.000283,F5 > -1.830283
3,F1 > -2.43,3.597715,F1,-2.43,>,-2.430272,18.0,0.000272,F1 > -2.430272
4,F5 <= 2.10,2.475232,F5,2.10,<=,2.099612,76.0,0.000388,F5 <= 2.099612
5,F5 > -1.79,1.145928,F5,-1.79,>,-1.789303,178.0,0.000697,F5 > -1.789303
6,F2 > -1.57,1.010509,F2,-1.57,>,-1.567476,193.0,0.002524,F2 > -1.567476
7,F3 > -1.46,0.967540,F3,-1.46,>,-1.460111,64.0,0.000111,F3 > -1.460111
8,F4 > -0.67,0.950860,F4,-0.67,>,-0.669382,42.0,0.000618,F4 > -0.669382
9,F6 > -1.37,0.948671,F6,-1.37,>,-1.370060,175.0,0.000060,F6 > -1.370060
10,F3 > -0.44,0.923305,F3,-0.44,>,-0.440007,87.0,0.000007,F3 > -0.440007
11,F5 <= 0.75,0.912683,F5,0.75,<=,0.751483,52.0,0.001483,F5 <= 0.751483
12,F4 > -1.63,0.895228,F4,-1.63,>,-1.631439,56.0,0.001439,F4 > -1.631439
13,F2 > -0.54,0.892574,F2,-0.54,>,-0.539718,77.0,0.000282,F2 > -0.539718
14,F6 > -0.58,0.875180,F6,-0.58,>,-0.579114,144.0,0.000886,F6 > -0.579114
15,F6 > 0.11,0.792333,F6,0.11,>,0.109128,112.0,0.000872,F6 > 0.109128
16,F1 <= 0.67,0.738479,F1,0.67,<=,0.674815,174.0,0.004815,F1 <= 0.674815
17,F3 > 0.27,0.560061,F3,0.27,>,0.271105,58.0,0.001105,F3 > 0.271105
18,F2 > 0.21,0.463906,F2,0.21,>,0.212652,53.0,0.002652,F2 > 0.212652
19,F3 <= 1.39,0.369873,F3,1.39,<=,1.390245,157.0,0.000245,F3 <= 1.390245
20,F4 > 0.28,0.348030,F4,0.28,>,0.282098,26.0,0.002098,F4 > 0.282098
21,F2 <= 1.43,0.344348,F2,1.43,<=,1.431026,104.0,0.001026,F2 <= 1.431026
22,F4 <= 1.58,0.271623,F4,1.58,<=,1.582286,194.0,0.002286,F4 <= 1.582286
23,F6 <= 1.18,0.252854,F6,1.18,<=,1.180851,44.0,0.000851,F6 <= 1.180851
24,F6 > 1.18,0.140472,F6,1.18,>,1.180851,44.0,0.000851,F6 > 1.180851
25,F6 <= 0.11,0.127352,F6,0.11,<=,0.109128,112.0,0.000872,F6 <= 0.109128
26,F3 <= 0.27,0.097682,F3,0.27,<=,0.271105,58.0,0.001105,F3 <= 0.271105
27,F4 <= -0.67,0.081147,F4,-0.67,<=,-0.669382,42.0,0.000618,F4 <= -0.669382
28,F2 <= 0.21,0.061032,F2,0.21,<=,0.212652,53.0,0.002652,F2 <= 0.212652
29,F4 <= 0.28,0.059062,F4,0.28,<=,0.282098,26.0,0.002098,F4 <= 0.282098
30,F6 <= -0.58,0.053753,F6,-0.58,<=,-0.579114,144.0,0.000886,F6 <= -0.579114
31,F3 <= -0.44,0.052751,F3,-0.44,<=,-0.440007,87.0,0.000007,F3 <= -0.440007
32,F2 <= -0.54,0.049840,F2,-0.54,<=,-0.539718,77.0,0.000282,F2 <= -0.539718
33,F6 <= -1.37,0.049171,F6,-1.37,<=,-1.370060,175.0,0.000060,F6 <= -1.370060
34,F1 > 0.67,0.040739,F1,0.67,>,0.674815,174.0,0.004815,F1 > 0.674815
35,background4 > -0.05,0.038514,background4,-0.05,>,-0.050054,197.0,0.000054,background4 > -0.050054
36,background5 > -0.04,0.037322,background5,-0.04,>,-0.039784,30.0,0.000216,background5 > -0.039784
37,background4 > -0.03,0.036206,background4,-0.03,>,-0.029655,61.0,0.000345,background4 > -0.029655
38,background5 > 0.00,0.030416,background5,0.00,>,-0.000664,150.0,0.000664,background5 > -0.000664
39,background5 > -0.07,0.023799,background5,-0.07,>,-0.070634,85.0,0.000634,background5 > -0.070634
40,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
41,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [13]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'F1':
  - Dimensão: 50 variáveis espectrais
  - Range de energias: 1.0 - 99.09819639278558
  - Variância explicada pela PC1: 97.70%

In [14]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=mlp_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=136)
    Zona: 50 colunas
    Importance: 0.164849
  Predicado: F1 <= -2.43 (n=69)
    Zona: 50 colunas
    Importance: 0.006603
  Predicado: F1 > -2.43 (n=99)
    Zona: 50 colunas
    Importance: 0.224251
  Predicado: F1 <= 0.67 (n=100)
    Zona: 50 colunas
    Importance: 0.028474
  Predicado: F1 > 0.67 (n=68)
    Zona: 50 colunas
    Importance: 0.291310
  Predicado: F1 <= 2.88 (n=138)
    Zona: 50 colunas
    Importance: 0.096068
  Predicado: background1 > -0.05 (n=138)
    Zona: 50 colunas
    Importance: 0.000437
  Predicado: background1 <= -0.02 (n=59)
    Zona: 50 colunas
    Importance: 0.000589
  Predicado: background1 > -0.02 (n=109)
    Zona: 50 colunas
    Importance: 0.000446
  Predicado: background1 <= 0.01 (n=101)
    Zona: 50 colunas
    Importance: 0.000572
  Predicado: background1 > 0.01 (n=67)
    Zona: 50 colunas
    Importance: 0.000382
  Predicado: background1 <= 0.05 (n=134)
    Zona: 50 colunas
    Importance: 0.000576
  Predicado: F2 > -1.57 (n=134)
    Zona: 50 colunas
    Importance: 0.010671
  Predicado: F2 <= -0.54 (n=69)
    Zona: 50 colunas
    Importance: 0.018236
  Predicado: F2 > -0.54 (n=99)
    Zona: 50 colunas
    Importance: 0.011389
  Predicado: F2 <= 0.21 (n=100)
    Zona: 50 colunas
    Importance: 0.013808
  Predicado: F2 > 0.21 (n=68)
    Zona: 50 colunas
    Importance: 0.014781
  Predicado: F2 <= 1.43 (n=133)
    Zona: 50 colunas
    Importance: 0.013579
  Predicado: background2 > -0.04 (n=135)
    Zona: 15 colunas
    Importance: 0.000236
  Predicado: background2 <= -0.01 (n=64)
    Zona: 15 colunas
    Importance: 0.000244
  Predicado: background2 > -0.01 (n=104)
    Zona: 15 colunas
    Importance: 0.000238
  Predicado: background2 <= 0.01 (n=93)
    Zona: 15 colunas
    Importance: 0.000235
  Predicado: background2 > 0.01 (n=75)
    Zona: 15 colunas
    Importance: 0.000248
  Predicado: background2 <= 0.04 (n=137)
    Zona: 15 colunas
    Importance: 0.000234
  Predicado: F3 > -1.46 (n=130)
    Zona: 50 colunas
    Importance: 0.010329
  Predicado: F3 <= -0.44 (n=75)
    Zona: 50 colunas
    Importance: 0.015362
  Predicado: F3 > -0.44 (n=93)
    Zona: 50 colunas
    Importance: 0.010742
  Predicado: F3 <= 0.27 (n=105)
    Zona: 50 colunas
    Importance: 0.011316
  Predicado: F3 > 0.27 (n=63)
    Zona: 50 colunas
    Importance: 0.015286
  Predicado: F3 <= 1.39 (n=133)
    Zona: 50 colunas
    Importance: 0.010103
  Predicado: background3 > -0.04 (n=136)
    Zona: 35 colunas
    Importance: 0.000381
  Predicado: background3 <= -0.01 (n=67)
    Zona: 35 colunas
    Importance: 0.000332
  Predicado: background3 > -0.01 (n=101)
    Zona: 35 colunas
    Importance: 0.000380
  Predicado: background3 <= 0.01 (n=100)
    Zona: 35 colunas
    Importance: 0.000338
  Predicado: background3 > 0.01 (n=68)
    Zona: 35 colunas
    Importance: 0.000396
  Predicado: background3 <= 0.04 (n=134)
    Zona: 35 colunas
    Importance: 0.000390
  Predicado: F4 > -1.63 (n=132)
    Zona: 50 colunas
    Importance: 0.012550
  Predicado: F4 <= -0.67 (n=70)
    Zona: 50 colunas
    Importance: 0.011371
  Predicado: F4 > -0.67 (n=98)
    Zona: 50 colunas
    Importance: 0.014607
  Predicado: F4 <= 0.28 (n=102)
    Zona: 50 colunas
    Importance: 0.008686
  Predicado: F4 > 0.28 (n=66)
    Zona: 50 colunas
    Importance: 0.020327
  Predicado: F4 <= 1.58 (n=136)
    Zona: 50 colunas
    Importance: 0.010086
  Predicado: background4 > -0.05 (n=137)
    Zona: 30 colunas
    Importance: 0.000268
  Predicado: background4 <= -0.03 (n=54)
    Zona: 30 colunas
    Importance: 0.000421
  Predicado: background4 > -0.03 (n=114)
    Zona: 30 colunas
    Importance: 0.000229
  Predicado: background4 <= 0.00 (n=97)
    Zona: 30 colunas
    Importance: 0.000335
  Predicado: background4 > 0.00 (n=71)
    Zona: 30 colunas
    Importance: 0.000230
  Predicado: background4 <= 0.04 (n=133)
    Zona: 30 colunas
    Importance: 0.000323
  Predicado: F5 > -1.83 (n=138)
    Zona: 45 colunas
    Importance: 0.041093
  Predicado: F5 <= -1.79 (n=66)
    Zona: 45 colunas
    Importance: 0.031625
  Predicado: F5 > -1.79 (n=102)
    Zona: 45 colunas
    Importance: 0.040666
  Predicado: F5 <= 0.75 (n=101)
    Zona: 45 colunas
    Importance: 0.030154
  Predicado: F5 > 0.75 (n=67)
    Zona: 45 colunas
    Importance: 0.047607
  Predicado: F5 <= 2.10 (n=134)
    Zona: 45 colunas
    Importance: 0.033875
  Predicado: background5 > -0.07 (n=134)
    Zona: 32 colunas
    Importance: 0.000358
  Predicado: background5 <= -0.04 (n=59)
    Zona: 32 colunas
    Importance: 0.000457
  Predicado: background5 > -0.04 (n=109)
    Zona: 32 colunas
    Importance: 0.000286
  Predicado: background5 <= 0.00 (n=95)
    Zona: 32 colunas
    Importance: 0.000414
  Predicado: background5 > 0.00 (n=73)
    Zona: 32 colunas
    Importance: 0.000257
  Predicado: background5 <= 0.06 (n=132)
    Zona: 32 colunas
    Importance: 0.000370
  Predicado: F6 > -1.37 (n=133)
    Zona: 38 colunas
    Importance: 0.009686
  Predicado: F6 <= -0.58 (n=69)
    Zona: 38 colunas
    Importance: 0.018838
  Predicado: F6 > -0.58 (n=99)
    Zona: 38 colunas
    Importance: 0.010213
  Predicado: F6 <= 0.11 (n=107)
    Zona: 38 colunas
    Importance: 0.013185
  Predicado: F6 > 0.11 (n=61)
    Zona: 38 colunas
    Importance: 0.014756
  Predicado: F6 <= 1.18 (n=136)
    Zona: 38 colunas
    Importance: 0.011668
  Predicado: background6 > -0.05 (n=134)
    Zona: 55 colunas
    Importance: 0.000411
  Predicado: background6 <= -0.02 (n=67)
    Zona: 55 colunas
    Importance: 0.000532
  Predicado: background6 > -0.02 (n=101)
    Zona: 55 colunas
    Importance: 0.000459
  Predicado: background6 <= 0.01 (n=99)
    Zona: 55 colunas
    Importance: 0.000455
  Predicado: background6 > 0.01 (n=69)
    Zona: 55 colunas
    Importance: 0.000535
  Predicado: background6 <= 0.04 (n=134)
    Zona: 55 colunas
    Importance: 0.000431

[Bag_2] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=137)
    Zona: 50 colunas
    Importance: 0.153341
  Predicado: F1 <= -2.43 (n=64)
    Zona: 50 colunas
    Importance: 0.006588
  Predicado: F1 > -2.43 (n=104)
    Zona: 50 colunas
    Importance: 0.200246
  Predicado: F1 <= 0.67 (n=101)
    Zona: 50 colunas
    Importance: 0.030206
  Predicado: F1 > 0.67 (n=67)
    Zona: 50 colunas
    Importance: 0.271589
  Predicado: F1 <= 2.88 (n=135)
    Zona: 50 colunas
    Importance: 0.086635
  Predicado: background1 > -0.05 (n=137)
    Zona: 50 colunas
    Importance: 0.000438
  Predicado: background1 <= -0.02 (n=56)
    Zona: 50 colunas
    Importance: 0.000554
  Predicado: background1 > -0.02 (n=112)
    Zona: 50 colunas
    Importance: 0.000435
  Predicado: background1 <= 0.01 (n=96)
    Zona: 50 colunas
    Importance: 0.000573
  Predicado: background1 > 0.01 (n=72)
    Zona: 50 colunas
    Importance: 0.000343
  Predicado: background1 <= 0.05 (n=136)
    Zona: 50 colunas
    Importance: 0.000543
  Predicado: F2 > -1.57 (n=134)
    Zona: 50 colunas
    Importance: 0.012449
  Predicado: F2 <= -0.54 (n=68)
    Zona: 50 colunas
    Importance: 0.016275
  Predicado: F2 > -0.54 (n=100)
    Zona: 50 colunas
    Importance: 0.013996
  Predicado: F2 <= 0.21 (n=100)
    Zona: 50 colunas
    Importance: 0.012331
  Predicado: F2 > 0.21 (n=68)
    Zona: 50 colunas
    Importance: 0.018722
  Predicado: F2 <= 1.43 (n=131)
    Zona: 50 colunas
    Importance: 0.012738
  Predicado: background2 > -0.04 (n=138)
    Zona: 15 colunas
    Importance: 0.000220
  Predicado: background2 <= -0.01 (n=62)
    Zona: 15 colunas
    Importance: 0.000210
  Predicado: background2 > -0.01 (n=106)
    Zona: 15 colunas
    Importance: 0.000213
  Predicado: background2 <= 0.01 (n=87)
    Zona: 15 colunas
    Importance: 0.000223
  Predicado: background2 > 0.01 (n=81)
    Zona: 15 colunas
    Importance: 0.000200
  Predicado: background2 <= 0.04 (n=133)
    Zona: 15 colunas
    Importance: 0.000220
  Predicado: F3 > -1.46 (n=136)
    Zona: 50 colunas
    Importance: 0.009975
  Predicado: F3 <= -0.44 (n=69)
    Zona: 50 colunas
    Importance: 0.013253
  Predicado: F3 > -0.44 (n=99)
    Zona: 50 colunas
    Importance: 0.010209
  Predicado: F3 <= 0.27 (n=99)
    Zona: 50 colunas
    Importance: 0.009631
  Predicado: F3 > 0.27 (n=69)
    Zona: 50 colunas
    Importance: 0.014082
  Predicado: F3 <= 1.39 (n=134)
    Zona: 50 colunas
    Importance: 0.008422
  Predicado: background3 > -0.04 (n=133)
    Zona: 35 colunas
    Importance: 0.000345
  Predicado: background3 <= -0.01 (n=69)
    Zona: 35 colunas
    Importance: 0.000380
  Predicado: background3 > -0.01 (n=99)
    Zona: 35 colunas
    Importance: 0.000316
  Predicado: background3 <= 0.01 (n=100)
    Zona: 35 colunas
    Importance: 0.000369
  Predicado: background3 > 0.01 (n=68)
    Zona: 35 colunas
    Importance: 0.000302
  Predicado: background3 <= 0.04 (n=128)
    Zona: 35 colunas
    Importance: 0.000392
  Predicado: F4 > -1.63 (n=135)
    Zona: 50 colunas
    Importance: 0.011379
  Predicado: F4 <= -0.67 (n=63)
    Zona: 50 colunas
    Importance: 0.012279
  Predicado: F4 > -0.67 (n=105)
    Zona: 50 colunas
    Importance: 0.012647
  Predicado: F4 <= 0.28 (n=99)
    Zona: 50 colunas
    Importance: 0.008720
  Predicado: F4 > 0.28 (n=69)
    Zona: 50 colunas
    Importance: 0.017946
  Predicado: F4 <= 1.58 (n=131)
    Zona: 50 colunas
    Importance: 0.009777
  Predicado: background4 > -0.05 (n=141)
    Zona: 30 colunas
    Importance: 0.000254
  Predicado: background4 <= -0.03 (n=57)
    Zona: 30 colunas
    Importance: 0.000389
  Predicado: background4 > -0.03 (n=111)
    Zona: 30 colunas
    Importance: 0.000230
  Predicado: background4 <= 0.00 (n=99)
    Zona: 30 colunas
    Importance: 0.000320
  Predicado: background4 > 0.00 (n=69)
    Zona: 30 colunas
    Importance: 0.000231
  Predicado: background4 <= 0.04 (n=134)
    Zona: 30 colunas
    Importance: 0.000316
  Predicado: F5 > -1.83 (n=136)
    Zona: 45 colunas
    Importance: 0.041081
  Predicado: F5 <= -1.79 (n=69)
    Zona: 45 colunas
    Importance: 0.025894
  Predicado: F5 > -1.79 (n=99)
    Zona: 45 colunas
    Importance: 0.043310
  Predicado: F5 <= 0.75 (n=101)
    Zona: 45 colunas
    Importance: 0.028269
  Predicado: F5 > 0.75 (n=67)
    Zona: 45 colunas
    Importance: 0.048048
  Predicado: F5 <= 2.10 (n=135)
    Zona: 45 colunas
    Importance: 0.033186
  Predicado: background5 > -0.07 (n=130)
    Zona: 32 colunas
    Importance: 0.000336
  Predicado: background5 <= -0.04 (n=62)
    Zona: 32 colunas
    Importance: 0.000433
  Predicado: background5 > -0.04 (n=106)
    Zona: 32 colunas
    Importance: 0.000256
  Predicado: background5 <= 0.00 (n=103)
    Zona: 32 colunas
    Importance: 0.000349
  Predicado: background5 > 0.00 (n=65)
    Zona: 32 colunas
    Importance: 0.000277
  Predicado: background5 <= 0.06 (n=131)
    Zona: 32 colunas
    Importance: 0.000333
  Predicado: F6 > -1.37 (n=130)
    Zona: 38 colunas
    Importance: 0.010419
  Predicado: F6 <= -0.58 (n=68)
    Zona: 38 colunas
    Importance: 0.015932
  Predicado: F6 > -0.58 (n=100)
    Zona: 38 colunas
    Importance: 0.011357
  Predicado: F6 <= 0.11 (n=100)
    Zona: 38 colunas
    Importance: 0.011990
  Predicado: F6 > 0.11 (n=68)
    Zona: 38 colunas
    Importance: 0.015001
  Predicado: F6 <= 1.18 (n=133)
    Zona: 38 colunas
    Importance: 0.010565
  Predicado: background6 > -0.05 (n=131)
    Zona: 55 colunas
    Importance: 0.000370
  Predicado: background6 <= -0.02 (n=69)
    Zona: 55 colunas
    Importance: 0.000464
  Predicado: background6 > -0.02 (n=99)
    Zona: 55 colunas
    Importance: 0.000403
  Predicado: background6 <= 0.01 (n=108)
    Zona: 55 colunas
    Importance: 0.000402
  Predicado: background6 > 0.01 (n=60)
    Zona: 55 colunas
    Importance: 0.000476
  Predicado: background6 <= 0.04 (n=136)
    Zona: 55 colunas
    Importance: 0.000378

[Bag_3] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=134)
    Zona: 50 colunas
    Importance: 0.154063
  Predicado: F1 <= -2.43 (n=69)
    Zona: 50 colunas
    Importance: 0.005640
  Predicado: F1 > -2.43 (n=99)
    Zona: 50 colunas
    Importance: 0.206573
  Predicado: F1 <= 0.67 (n=104)
    Zona: 50 colunas
    Importance: 0.026982
  Predicado: F1 > 0.67 (n=64)
    Zona: 50 colunas
    Importance: 0.281776
  Predicado: F1 <= 2.88 (n=136)
    Zona: 50 colunas
    Importance: 0.077487
  Predicado: background1 > -0.05 (n=139)
    Zona: 50 colunas
    Importance: 0.000366
  Predicado: background1 <= -0.02 (n=61)
    Zona: 50 colunas
    Importance: 0.000480
  Predicado: background1 > -0.02 (n=107)
    Zona: 50 colunas
    Importance: 0.000350
  Predicado: background1 <= 0.01 (n=104)
    Zona: 50 colunas
    Importance: 0.000467
  Predicado: background1 > 0.01 (n=64)
    Zona: 50 colunas
    Importance: 0.000285
  Predicado: background1 <= 0.05 (n=138)
    Zona: 50 colunas
    Importance: 0.000435
  Predicado: F2 > -1.57 (n=136)
    Zona: 50 colunas
    Importance: 0.011574
  Predicado: F2 <= -0.54 (n=67)
    Zona: 50 colunas
    Importance: 0.016820
  Predicado: F2 > -0.54 (n=101)
    Zona: 50 colunas
    Importance: 0.014034
  Predicado: F2 <= 0.21 (n=101)
    Zona: 50 colunas
    Importance: 0.012227
  Predicado: F2 > 0.21 (n=67)
    Zona: 50 colunas
    Importance: 0.019544
  Predicado: F2 <= 1.43 (n=136)
    Zona: 50 colunas
    Importance: 0.013065
  Predicado: background2 > -0.04 (n=136)
    Zona: 15 colunas
    Importance: 0.000222
  Predicado: background2 <= -0.01 (n=66)
    Zona: 15 colunas
    Importance: 0.000266
  Predicado: background2 > -0.01 (n=102)
    Zona: 15 colunas
    Importance: 0.000207
  Predicado: background2 <= 0.01 (n=94)
    Zona: 15 colunas
    Importance: 0.000242
  Predicado: background2 > 0.01 (n=74)
    Zona: 15 colunas
    Importance: 0.000215
  Predicado: background2 <= 0.04 (n=134)
    Zona: 15 colunas
    Importance: 0.000243
  Predicado: F3 > -1.46 (n=135)
    Zona: 50 colunas
    Importance: 0.007125
  Predicado: F3 <= -0.44 (n=67)
    Zona: 50 colunas
    Importance: 0.011241
  Predicado: F3 > -0.44 (n=101)
    Zona: 50 colunas
    Importance: 0.007501
  Predicado: F3 <= 0.27 (n=103)
    Zona: 50 colunas
    Importance: 0.007891
  Predicado: F3 > 0.27 (n=65)
    Zona: 50 colunas
    Importance: 0.010738
  Predicado: F3 <= 1.39 (n=133)
    Zona: 50 colunas
    Importance: 0.007366
  Predicado: background3 > -0.04 (n=132)
    Zona: 35 colunas
    Importance: 0.000350
  Predicado: background3 <= -0.01 (n=70)
    Zona: 35 colunas
    Importance: 0.000401
  Predicado: background3 > -0.01 (n=98)
    Zona: 35 colunas
    Importance: 0.000316
  Predicado: background3 <= 0.01 (n=98)
    Zona: 35 colunas
    Importance: 0.000407
  Predicado: background3 > 0.01 (n=70)
    Zona: 35 colunas
    Importance: 0.000273
  Predicado: background3 <= 0.04 (n=132)
    Zona: 35 colunas
    Importance: 0.000401
  Predicado: F4 > -1.63 (n=132)
    Zona: 50 colunas
    Importance: 0.008664
  Predicado: F4 <= -0.67 (n=72)
    Zona: 50 colunas
    Importance: 0.011987
  Predicado: F4 > -0.67 (n=96)
    Zona: 50 colunas
    Importance: 0.009847
  Predicado: F4 <= 0.28 (n=106)
    Zona: 50 colunas
    Importance: 0.008947
  Predicado: F4 > 0.28 (n=62)
    Zona: 50 colunas
    Importance: 0.013871
  Predicado: F4 <= 1.58 (n=140)
    Zona: 50 colunas
    Importance: 0.009873
  Predicado: background4 > -0.05 (n=140)
    Zona: 30 colunas
    Importance: 0.000235
  Predicado: background4 <= -0.03 (n=62)
    Zona: 30 colunas
    Importance: 0.000375
  Predicado: background4 > -0.03 (n=106)
    Zona: 30 colunas
    Importance: 0.000204
  Predicado: background4 <= 0.00 (n=100)
    Zona: 30 colunas
    Importance: 0.000325
  Predicado: background4 > 0.00 (n=68)
    Zona: 30 colunas
    Importance: 0.000182
  Predicado: background4 <= 0.04 (n=134)
    Zona: 30 colunas
    Importance: 0.000276
  Predicado: F5 > -1.83 (n=135)
    Zona: 45 colunas
    Importance: 0.038799
  Predicado: F5 <= -1.79 (n=65)
    Zona: 45 colunas
    Importance: 0.024233
  Predicado: F5 > -1.79 (n=103)
    Zona: 45 colunas
    Importance: 0.040086
  Predicado: F5 <= 0.75 (n=98)
    Zona: 45 colunas
    Importance: 0.025846
  Predicado: F5 > 0.75 (n=70)
    Zona: 45 colunas
    Importance: 0.045300
  Predicado: F5 <= 2.10 (n=133)
    Zona: 45 colunas
    Importance: 0.031643
  Predicado: background5 > -0.07 (n=130)
    Zona: 32 colunas
    Importance: 0.000297
  Predicado: background5 <= -0.04 (n=64)
    Zona: 32 colunas
    Importance: 0.000433
  Predicado: background5 > -0.04 (n=104)
    Zona: 32 colunas
    Importance: 0.000205
  Predicado: background5 <= 0.00 (n=104)
    Zona: 32 colunas
    Importance: 0.000353
  Predicado: background5 > 0.00 (n=64)
    Zona: 32 colunas
    Importance: 0.000193
  Predicado: background5 <= 0.06 (n=133)
    Zona: 32 colunas
    Importance: 0.000329
  Predicado: F6 > -1.37 (n=131)
    Zona: 38 colunas
    Importance: 0.009227
  Predicado: F6 <= -0.58 (n=67)
    Zona: 38 colunas
    Importance: 0.018037
  Predicado: F6 > -0.58 (n=101)
    Zona: 38 colunas
    Importance: 0.010588
  Predicado: F6 <= 0.11 (n=101)
    Zona: 38 colunas
    Importance: 0.012797
  Predicado: F6 > 0.11 (n=67)
    Zona: 38 colunas
    Importance: 0.014706
  Predicado: F6 <= 1.18 (n=137)
    Zona: 38 colunas
    Importance: 0.011555
  Predicado: background6 > -0.05 (n=135)
    Zona: 55 colunas
    Importance: 0.000280
  Predicado: background6 <= -0.02 (n=69)
    Zona: 55 colunas
    Importance: 0.000477
  Predicado: background6 > -0.02 (n=99)
    Zona: 55 colunas
    Importance: 0.000305
  Predicado: background6 <= 0.01 (n=101)
    Zona: 55 colunas
    Importance: 0.000440
  Predicado: background6 > 0.01 (n=67)
    Zona: 55 colunas
    Importance: 0.000280
  Predicado: background6 <= 0.04 (n=134)
    Zona: 55 colunas
    Importance: 0.000399

[Bag_4] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=135)
    Zona: 50 colunas
    Importance: 0.146956
  Predicado: F1 <= -2.43 (n=73)
    Zona: 50 colunas
    Importance: 0.006752
  Predicado: F1 > -2.43 (n=95)
    Zona: 50 colunas
    Importance: 0.206539
  Predicado: F1 <= 0.67 (n=104)
    Zona: 50 colunas
    Importance: 0.026305
  Predicado: F1 > 0.67 (n=64)
    Zona: 50 colunas
    Importance: 0.271537
  Predicado: F1 <= 2.88 (n=134)
    Zona: 50 colunas
    Importance: 0.078757
  Predicado: background1 > -0.05 (n=135)
    Zona: 50 colunas
    Importance: 0.000423
  Predicado: background1 <= -0.02 (n=58)
    Zona: 50 colunas
    Importance: 0.000546
  Predicado: background1 > -0.02 (n=110)
    Zona: 50 colunas
    Importance: 0.000424
  Predicado: background1 <= 0.01 (n=98)
    Zona: 50 colunas
    Importance: 0.000569

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,F1 > 0.67,F1 > 0.67,F1 > 0.67,F1 > 0.67
1,F1 > -2.43,F1 > -2.43,F1 > -2.43,F1 > -2.43
2,F1 > -2.47,F1 > -2.47,F1 > -2.47,F1 > -2.47
3,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88
4,F5 > 0.75,F5 > 0.75,F5 > 0.75,F5 > 0.75
...,...,...,...,...
72,background3 > 0.01,background6 > -0.05,Class_A,background3 > 0.04
73,Class_A,background6 > -0.02,Class_B,Class_A
74,Class_B,background1 > 0.01,NaN,Class_B
75,NaN,Class_A,NaN,NaN
76,NaN,Class_B,NaN,NaN

In [15]:
all_results_pert[0]['pert_results_dict']['Bag_1']

              Predicate  Perturbation
0             F1 > 0.67      0.291310
1            F1 > -2.43      0.224251
2            F1 > -2.47      0.164849
3            F1 <= 2.88      0.096068
4             F5 > 0.75      0.047607
..                  ...           ...
67  background2 > -0.04      0.000236
68  background2 <= 0.01      0.000235
69  background2 <= 0.04      0.000234
70   background4 > 0.00      0.000230
71  background4 > -0.03      0.000229

[72 rows x 2 columns]

In [16]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,F1 > 0.67,24.156622,F1,0.67,>
1,F5 > 0.75,3.705659,F5,0.75,>
2,F6 <= -1.37,1.270495,F6,-1.37,<=
3,F4 > 0.28,0.655794,F4,0.28,>
4,F2 > 0.21,0.552760,F2,0.21,>
5,F3 <= -0.44,0.433612,F3,-0.44,<=
6,background5 > -0.07,0.001404,background5,-0.07,>
7,background4 <= 0.00,0.001110,background4,0.00,<=
8,background1 <= -0.02,0.001037,background1,-0.02,<=
9,background6 > 0.01,0.000945,background6,0.01,>
10,background2 <= -0.01,0.000892,background2,-0.01,<=
11,background3 <= -0.01,0.000845,background3,-0.01,<=
12,Class_B,0.000000,None,None,None

In [17]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,F1 > 0.67,24.156622,F1,0.67,>,0.674815,174.0,0.004815,F1 > 0.674815
1,F1 > -2.43,17.040193,F1,-2.43,>,-2.430272,18.0,0.000272,F1 > -2.430272
2,F1 > -2.47,11.286664,F1,-2.47,>,-2.469280,70.0,0.000720,F1 > -2.469280
3,F1 <= 2.88,6.505373,F1,2.88,<=,2.877525,163.0,0.002475,F1 <= 2.877525
4,F5 > 0.75,3.705659,F5,0.75,>,0.751483,52.0,0.001483,F5 > 0.751483
...,...,...,...,...,...,...,...,...,...
73,background2 > 0.01,0.000712,background2,0.01,>,0.010315,102.0,0.000315,background2 > 0.010315
74,background6 > -0.02,0.000687,background6,-0.02,>,-0.019924,140.0,0.000076,background6 > -0.019924
75,background3 > 0.04,0.000324,background3,0.04,>,0.040553,197.0,0.000553,background3 > 0.040553
76,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
77,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [18]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'F1':
  - Dimensão: 50 variáveis espectrais
  - Variância explicada pela PC1: 97.70%

In [19]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = mlp_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = mlp_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

                energy  Permutation_importance_proba         Zone
0   51.050100200400806                      0.003644           F1
1    697.6973947895792                      0.002715           F5
2    855.8557114228457                      0.002258           F6
3    261.2605210420842                      0.001976           F2
4   371.37074148296597                      0.001939           F3
5    563.5631262525051                      0.001909           F4
6   141.14028056112224                      0.000254  background1
7    957.9579158316634                      0.000217  background6
8    789.7895791583167                      0.000214  background5
9    433.4328657314629                      0.000188  background3
10  321.32064128256513                      0.000174  background2
11   655.6553106212425                      0.000163  background4

In [20]:
import numpy as np

max_len = max(
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

           Shap  Permutation LRC_perturbation LRC_covariance
0            F1           F1               F1             F1
1            F5           F5               F5             F5
2            F6           F6               F6             F2
3            F2           F2               F4             F3
4            F3           F3               F2             F4
5            F4           F4               F3             F6
6   background1  background1      background5    background4
7   background4  background6      background4    background5
8   background6  background5      background1           None
9   background5  background3      background6           None
10  background2  background2      background2           None
11  background3  background4      background3           None
12         None         None             None           None

In [21]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_9992\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
0              Shap       Permutation   0.965532
1              Shap  LRC_perturbation   0.921569
3       Permutation  LRC_perturbation   0.917271
2              Shap    LRC_covariance   0.845091
4       Permutation    LRC_covariance   0.842002
5  LRC_perturbation    LRC_covariance   0.822454

In [22]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')