In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
from synthetic import generate_synthetic_spectral_data

config = [
    {
        'nome': 'A',
        'n_amostras': 156,
        'picos': [250, 380, 550, 700, 850],  # 4 picos
        'amp_media': 1.0,
        'amp_std': 0.3,
        'larg_media': 15.0,
        'larg_std': 2.0,
        'ruido_std': 0.04
    },
    {
        'nome': 'B',
        'n_amostras': 146,
        'picos': [50, 250, 380, 550, 850],  # 3 picos (sem pico em 550)
        'amp_media': 1.4,
        'amp_std': 0.5,
        'larg_media': 15.0,
        'larg_std': 1.8,
        'ruido_std': 0.035
    }
]

data_complete = generate_synthetic_spectral_data(
    configuracao_classes=config,
    n_pontos=500,
    x_min=1,
    x_max=1000,
    seed=0
)

import pandas as pd
pd.options.plotting.backend = 'plotly' # setting plotly as the backend for pandas plotting 

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.iloc[:, 1:], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.iloc[:, 1:], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# Xcalclass_prep = Xcalclass.copy()
# Xpredclass_prep = Xpredclass.copy()

# preprocessings
import preprocessings as prepr  # preprocessing methods
Xcalclass_prep, mean_calclass  = prepr.mc(Xcalclass)
Xpredclass_prep = Xpredclass - mean_calclass

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:44:24,754 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:44:24,820 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:44:24,882 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:44:24,910 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[109, 0], [0, 102]]",1.0,1.0,1.0,"[[47, 0], [0, 44]]"

## Definição das Zonas Espectrais

In [3]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('F1', 1.0, 100.0),
('background1', 100.0, 200.0),
('F2', 200.0, 300.0),
('background2', 300.0, 330.0),
('F3', 330.0, 430.0),
('background3', 430.0, 500.0),
('F4', 500.0, 600.0),
('background4', 600.0, 660.0),
('F5', 660.0, 750.0),
('background5', 750.0, 815.0),
('F6', 815.0, 890.0),
('background6', 890.0, 1000.0)
]

## Pvector and SHAP

In [4]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df

                energy   Pvector         Zone
0   49.048096192384776  7.658334           F1
1    701.7014028056112  4.917246           F5
2    847.8476953907816  3.633970           F6
3    379.3787575150301  2.416183           F3
4    549.5490981963928  2.189486           F4
5     249.248496993988  1.759238           F2
6    315.3146292585171  0.374853  background2
7    149.1482965931864  0.360186  background1
8    659.6593186372746  0.357050  background4
9    975.9759519038076  0.296082  background6
10   751.7515030060121  0.290555  background5
11   491.4909819639279  0.216140  background3

In [5]:
shap_global_importance = pd.read_csv('shap_synthetic.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

        energy  Mean_Abs_SHAP         Zone
0    49.048096       0.048546           F1
1   695.695391       0.007130           F5
2   383.382766       0.000692           F3
3   585.585170       0.000627           F4
4   237.236473       0.000543           F2
5   857.857715       0.000526           F6
6   107.106212       0.000512  background1
7   321.320641       0.000289  background2
8   981.981964       0.000281  background6
9   457.456914       0.000255  background3
10  751.751503       0.000237  background5
11  617.617234       0.000000  background4

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'F1': VE = 97.70%, dim = 50 variáveis
Zona 'background1': VE = 4.20%, dim = 50 variáveis
Zona 'F2': VE = 92.76%, dim = 50 variáveis
Zona 'background2': VE = 10.44%, dim = 15 variáveis
Zona 'F3': VE = 92.93%, dim = 50 variáveis
Zona 'background3': VE = 5.32%, dim = 35 variáveis
Zona 'F4': VE = 93.74%, dim = 50 variáveis
Zona 'background4': VE = 8.95%, dim = 30 variáveis
Zona 'F5': VE = 96.69%, dim = 45 variáveis
Zona 'background5': VE = 16.85%, dim = 32 variáveis
Zona 'F6': VE = 93.73%, dim = 38 variáveis
Zona 'background6': VE = 5.17%, dim = 55 variáveis

Scores DataFrame shape: (211, 12)

In [7]:
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(svm_model[4]['SVC'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 39
Removida: F1 <= 2.88 -> F1 > -2.43 (0.8328) | Mantida: F1 > -2.43 -> F1 <= 2.88 (1.6712)
Removida: F1 > -2.43 -> F5 > -1.83 (0.8085) | Mantida: F5 > -1.83 -> F1 > -2.43 (3.9345)
Removida: F5 <= 2.10 -> F1 > -2.43 (1.2900) | Mantida: F1 > -2.43 -> F5 <= 2.10 (3.7906)
Removida: F3 > -1.46 -> F6 > 0.11 (0.2924) | Mantida: F6 > 0.11 -> F3 > -1.46 (0.3274)
Removida: F4 > -1.63 -> F6 > 0.11 (0.3111) | Mantida: F6 > 0.11 -> F4 > -1.63 (0.9222)
Removida: F2 > -1.57 -> F6 > 0.11 (0.2978) | Mantida: F6 > 0.11 -> F2 > -1.57 (0.3122)
Removida: F6 > 0.11 -> F6 > -1.37 (0.3217) | Mantida: F6 > -1.37 -> F6 > 0.11 (0.6632)
Removida: F6 > -0.58 -> F6 > 0.11 (0.2637) | Mantida: F6 > 0.11 -> F6 > -0.58 (0.3100)
Removida: F6 > -1.37 -> F3 > -1.46 (0.3168) | Mantida: F3 > -1.46 -> F6 > -1.37 (0.3214)
Removida: F6 > -0.58 -> F3 > -1.46 (0.2765) | Mantida: F3 > -1.46 -> F6 > -0.58 (0.2851)
Removida: F2 > -1.57 -> F3 > -1.46 (0.5949) | Mantida: F3 > -1.46 -> F2 > -1.57 (0.6515)
Removida: F6 > -1.37 -> F2 > -1.57 (0.2987) | Mantida: F2 > -1.57 -> F6 > -1.37 (0.6253)
Removida: F2 > -0.54 -> F6 > -1.37 (0.3159) | Mantida: F6 > -1.37 -> F2 > -0.54 (0.6538)
Removida: F4 > -0.67 -> F6 > -1.37 (0.3570) | Mantida: F6 > -1.37 -> F4 > -0.67 (0.6273)
Removida: F4 > -1.63 -> F6 > -1.37 (0.3231) | Mantida: F6 > -1.37 -> F4 > -1.63 (0.6674)
Removida: F4 > -0.67 -> F2 > -1.57 (0.6152) | Mantida: F2 > -1.57 -> F4 > -0.67 (0.6253)
Removida: F2 > -0.54 -> F2 > -1.57 (0.3378) | Mantida: F2 > -1.57 -> F2 > -0.54 (0.6132)
Removida: F2 > -1.57 -> F6 > -0.58 (0.2733) | Mantida: F6 > -0.58 -> F2 > -1.57 (0.3024)
Removida: F4 > -0.67 -> F4 > -1.63 (0.3284) | Mantida: F4 > -1.63 -> F4 > -0.67 (1.3306)
Removida: F5 <= 0.75 -> F3 > -0.44 (0.2974) | Mantida: F3 > -0.44 -> F5 <= 0.75 (0.4780)
Removida: F5 <= 0.75 -> F2 > -0.54 (0.2861) | Mantida: F2 > -0.54 -> F5 <= 0.75 (0.2924)
Removida: F6 > -0.58 -> F5 <= 0.75 (0.5680) | Mantida: F5 <= 0.75 -> F6 > -0.58 (0.8558)
Removida: F1 <= 0.67 -> F3 > -0.44 (0.5566) | Mantida: F3 > -0.44 -> F1 <= 0.67 (1.2702)
Removida: F3 > -0.44 -> F6 > -0.58 (0.2644) | Mantida: F6 > -0.58 -> F3 > -0.44 (0.5287)
Removida: F1 <= 0.67 -> F2 > -0.54 (0.2854) | Mantida: F2 > -0.54 -> F1 <= 0.67 (0.5298)
Removida: F2 > 0.21 -> F3 > 0.27 (0.3999) | Mantida: F3 > 0.27 -> F2 > 0.21 (1.5377)
Removida: F4 > 0.28 -> F3 <= 1.39 (0.6087) | Mantida: F3 <= 1.39 -> F4 > 0.28 (0.7508)
Removida: F3 <= 1.39 -> F4 <= 1.58 (0.1242) | Mantida: F4 <= 1.58 -> F3 <= 1.39 (0.1377)
Removida: F4 > 0.28 -> F2 <= 1.43 (0.2782) | Mantida: F2 <= 1.43 -> F4 > 0.28 (0.2795)
Removida: F4 <= 1.58 -> F2 <= 1.43 (0.2257) | Mantida: F2 <= 1.43 -> F4 <= 1.58 (0.7659)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.1950) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.3430)
Removida: F4 <= -0.67 -> F3 <= 0.27 (0.1388) | Mantida: F3 <= 0.27 -> F4 <= -0.67 (0.1702)
Removida: F6 <= 0.11 -> F6 <= 1.18 (0.0474) | Mantida: F6 <= 1.18 -> F6 <= 0.11 (0.4877)
Removida: F4 <= -0.67 -> F6 <= 0.11 (0.0534) | Mantida: F6 <= 0.11 -> F4 <= -0.67 (0.0719)
Removida: F2 <= 0.21 -> F4 <= -0.67 (0.0295) | Mantida: F4 <= -0.67 -> F2 <= 0.21 (0.0704)
Removida: background4 > -0.03 -> F3 <= -0.44 (0.0009) | Mantida: F3 <= -0.44 -> background4 > -0.03 (0.0434)
Removida: F4 <= 0.28 -> F3 <= -0.44 (0.0316) | Mantida: F3 <= -0.44 -> F4 <= 0.28 (0.0503)
Removida: background4 > -0.05 -> background4 > -0.03 (0.0012) | Mantida: background4 > -0.03 -> background4 > -0.05 (0.0095)
Removida: background4 > -0.03 -> F2 <= 0.21 (0.0012) | Mantida: F2 <= 0.21 -> background4 > -0.03 (0.0338)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 157 | Removidas: 39
Nós predicados: 37
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 40
Removida: F1 > -2.43 -> F1 <= 2.88 (0.8754) | Mantida: F1 <= 2.88 -> F1 > -2.43 (3.3694)
Removida: F1 > -2.43 -> F5 > -1.83 (3.1772) | Mantida: F5 > -1.83 -> F1 > -2.43 (3.8932)
Removida: F4 > -1.63 -> F4 > -0.67 (0.3717) | Mantida: F4 > -0.67 -> F4 > -1.63 (1.0169)
Removida: F6 > 0.11 -> F4 > -0.67 (0.3025) | Mantida: F4 > -0.67 -> F6 > 0.11 (0.6120)
Removida: F4 > -0.67 -> F5 > -1.79 (0.3491) | Mantida: F5 > -1.79 -> F4 > -0.67 (0.7883)
Removida: F4 > -0.67 -> F6 > -0.58 (0.2773) | Mantida: F6 > -0.58 -> F4 > -0.67 (0.2796)
Removida: F3 > -1.46 -> F5 <= 0.75 (0.2567) | Mantida: F5 <= 0.75 -> F3 > -1.46 (0.2786)
Removida: F3 > -1.46 -> F6 > -1.37 (0.2966) | Mantida: F6 > -1.37 -> F3 > -1.46 (0.3372)
Removida: F6 > -0.58 -> F3 > -1.46 (0.2828) | Mantida: F3 > -1.46 -> F6 > -0.58 (0.5893)
Removida: F6 > 0.11 -> F5 > -1.79 (0.3279) | Mantida: F5 > -1.79 -> F6 > 0.11 (0.3520)
Removida: F6 > -1.37 -> F5 > -1.79 (0.3646) | Mantida: F5 > -1.79 -> F6 > -1.37 (0.4122)
Removida: F6 > -1.37 -> F6 > 0.11 (0.6335) | Mantida: F6 > 0.11 -> F6 > -1.37 (0.6784)
Removida: F6 > 0.11 -> F6 > -0.58 (0.2716) | Mantida: F6 > -0.58 -> F6 > 0.11 (0.3266)
Removida: F6 > -1.37 -> F2 > -0.54 (0.3155) | Mantida: F2 > -0.54 -> F6 > -1.37 (0.3196)
Removida: F6 > -1.37 -> F2 > -1.57 (0.3213) | Mantida: F2 > -1.57 -> F6 > -1.37 (0.6833)
Removida: F6 > -0.58 -> F3 > -0.44 (0.5239) | Mantida: F3 > -0.44 -> F6 > -0.58 (0.5937)
Removida: F3 > -0.44 -> F1 <= 0.67 (0.4823) | Mantida: F1 <= 0.67 -> F3 > -0.44 (0.5505)
Removida: F5 <= 0.75 -> F3 > -0.44 (0.2661) | Mantida: F3 > -0.44 -> F5 <= 0.75 (0.2701)
Removida: F6 > -0.58 -> F2 > -1.57 (0.2835) | Mantida: F2 > -1.57 -> F6 > -0.58 (0.2855)
Removida: F5 <= 0.75 -> F6 > -0.58 (0.2896) | Mantida: F6 > -0.58 -> F5 <= 0.75 (0.8176)
Removida: F2 > -1.57 -> F2 > -0.54 (0.3099) | Mantida: F2 > -0.54 -> F2 > -1.57 (0.5406)
Removida: F5 <= 0.75 -> F2 > -0.54 (0.5541) | Mantida: F2 > -0.54 -> F5 <= 0.75 (0.5580)
Removida: F1 <= 0.67 -> F5 <= 0.75 (0.2615) | Mantida: F5 <= 0.75 -> F1 <= 0.67 (0.8611)
Removida: F4 > 0.28 -> F2 > 0.21 (0.1818) | Mantida: F2 > 0.21 -> F4 > 0.28 (0.7207)
Removida: F3 <= 1.39 -> F2 > 0.21 (0.1647) | Mantida: F2 > 0.21 -> F3 <= 1.39 (0.4804)
Removida: F2 <= 1.43 -> F4 > 0.28 (0.1449) | Mantida: F4 > 0.28 -> F2 <= 1.43 (0.1568)
Removida: F4 > 0.28 -> F6 <= 1.18 (0.0884) | Mantida: F6 <= 1.18 -> F4 > 0.28 (0.0931)
Removida: F4 <= 1.58 -> F4 > 0.28 (0.2529) | Mantida: F4 > 0.28 -> F4 <= 1.58 (0.2975)
Removida: F2 <= 1.43 -> F3 <= 1.39 (0.1351) | Mantida: F3 <= 1.39 -> F2 <= 1.43 (0.6564)
Removida: F4 <= 1.58 -> F2 <= 1.43 (0.2170) | Mantida: F2 <= 1.43 -> F4 <= 1.58 (0.3739)
Removida: F4 <= 1.58 -> F3 <= 1.39 (0.2398) | Mantida: F3 <= 1.39 -> F4 <= 1.58 (0.3425)
Removida: F6 <= 0.11 -> F6 <= 1.18 (0.2226) | Mantida: F6 <= 1.18 -> F6 <= 0.11 (0.4187)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.1404) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.2945)
Removida: F4 <= -0.67 -> F3 <= 0.27 (0.0669) | Mantida: F3 <= 0.27 -> F4 <= -0.67 (0.1670)
Removida: F4 <= -0.67 -> F6 <= -0.58 (0.0328) | Mantida: F6 <= -0.58 -> F4 <= -0.67 (0.0354)
Removida: F3 <= -0.44 -> F6 <= -0.58 (0.0184) | Mantida: F6 <= -0.58 -> F3 <= -0.44 (0.0556)
Removida: F4 <= 0.28 -> F2 <= 0.21 (0.0227) | Mantida: F2 <= 0.21 -> F4 <= 0.28 (0.0465)
Removida: F3 <= -0.44 -> F2 <= 0.21 (0.0150) | Mantida: F2 <= 0.21 -> F3 <= -0.44 (0.0497)
Removida: F3 <= -0.44 -> F2 <= -0.54 (0.0257) | Mantida: F2 <= -0.54 -> F3 <= -0.44 (0.0355)
Removida: background5 > 0.00 -> background4 > -0.05 (0.0022) | Mantida: background4 > -0.05 -> background5 > 0.00 (0.0022)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 178 | Removidas: 40
Nós predicados: 38
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 2
======================================================================


Total de pares bidirecionais encontrados: 43
Removida: F1 > -2.43 -> F1 <= 2.88 (0.8737) | Mantida: F1 <= 2.88 -> F1 > -2.43 (3.2883)
Removida: F1 > -2.43 -> F5 > -1.83 (3.1435) | Mantida: F5 > -1.83 -> F1 > -2.43 (3.9081)
Removida: F6 > -1.37 -> F5 > -1.79 (0.3462) | Mantida: F5 > -1.79 -> F6 > -1.37 (1.5655)
Removida: F6 > -1.37 -> F6 > 0.11 (0.3153) | Mantida: F6 > 0.11 -> F6 > -1.37 (0.6898)
Removida: F2 > -0.54 -> F6 > -1.37 (0.3174) | Mantida: F6 > -1.37 -> F2 > -0.54 (0.6627)
Removida: F4 > -1.63 -> F6 > -1.37 (0.3520) | Mantida: F6 > -1.37 -> F4 > -1.63 (0.9713)
Removida: F6 > 0.11 -> F2 > -1.57 (0.3129) | Mantida: F2 > -1.57 -> F6 > 0.11 (0.6480)
Removida: F6 > 0.11 -> F2 > -0.54 (0.3316) | Mantida: F2 > -0.54 -> F6 > 0.11 (0.5746)
Removida: F6 > 0.11 -> F5 <= 0.75 (0.2900) | Mantida: F5 <= 0.75 -> F6 > 0.11 (0.6290)
Removida: F3 > -1.46 -> F6 > 0.11 (0.2630) | Mantida: F6 > 0.11 -> F3 > -1.46 (0.3140)
Removida: F2 > -0.54 -> F2 > -1.57 (0.3046) | Mantida: F2 > -1.57 -> F2 > -0.54 (0.6019)
Removida: F2 > -1.57 -> F4 > -0.67 (0.3119) | Mantida: F4 > -0.67 -> F2 > -1.57 (0.3363)
Removida: F2 > -1.57 -> F4 > -1.63 (0.3168) | Mantida: F4 > -1.63 -> F2 > -1.57 (0.6310)
Removida: F4 > -0.67 -> F2 > -0.54 (0.5899) | Mantida: F2 > -0.54 -> F4 > -0.67 (0.9430)
Removida: F4 > -0.67 -> F3 > -1.46 (0.2958) | Mantida: F3 > -1.46 -> F4 > -0.67 (0.5597)
Removida: F4 > -0.67 -> F1 <= 0.67 (0.2561) | Mantida: F1 <= 0.67 -> F4 > -0.67 (0.2923)
Removida: F3 > -1.46 -> F4 > -1.63 (0.3198) | Mantida: F4 > -1.63 -> F3 > -1.46 (1.1561)
Removida: F5 <= 0.75 -> F4 > -1.63 (0.2938) | Mantida: F4 > -1.63 -> F5 <= 0.75 (0.6022)
Removida: F6 > -0.58 -> F3 > -1.46 (0.5340) | Mantida: F3 > -1.46 -> F6 > -0.58 (0.5439)
Removida: F6 > -0.58 -> F1 <= 0.67 (0.8033) | Mantida: F1 <= 0.67 -> F6 > -0.58 (0.8552)
Removida: F1 <= 0.67 -> F5 <= 0.75 (0.2788) | Mantida: F5 <= 0.75 -> F1 <= 0.67 (0.8571)
Removida: F3 > -0.44 -> F1 <= 0.67 (0.2508) | Mantida: F1 <= 0.67 -> F3 > -0.44 (0.7837)
Removida: F3 > -0.44 -> F5 <= 0.75 (0.2620) | Mantida: F5 <= 0.75 -> F3 > -0.44 (0.5473)
Removida: F2 > 0.21 -> F3 > 0.27 (0.5861) | Mantida: F3 > 0.27 -> F2 > 0.21 (1.2939)
Removida: F2 <= 1.43 -> F2 > 0.21 (0.1368) | Mantida: F2 > 0.21 -> F2 <= 1.43 (0.1483)
Removida: F3 <= 1.39 -> F4 > 0.28 (0.1355) | Mantida: F4 > 0.28 -> F3 <= 1.39 (0.4333)
Removida: F4 > 0.28 -> F2 <= 1.43 (0.4027) | Mantida: F2 <= 1.43 -> F4 > 0.28 (0.4917)
Removida: F4 > 0.28 -> F4 <= 1.58 (0.1227) | Mantida: F4 <= 1.58 -> F4 > 0.28 (0.1292)
Removida: F3 <= 1.39 -> F4 <= 1.58 (0.2473) | Mantida: F4 <= 1.58 -> F3 <= 1.39 (0.2498)
Removida: F6 <= 1.18 -> F3 <= 1.39 (0.0674) | Mantida: F3 <= 1.39 -> F6 <= 1.18 (0.3165)
Removida: F4 <= 1.58 -> F2 <= 1.43 (0.2716) | Mantida: F2 <= 1.43 -> F4 <= 1.58 (0.3180)
Removida: F2 <= 1.43 -> F6 <= 1.18 (0.1001) | Mantida: F6 <= 1.18 -> F2 <= 1.43 (0.1131)
Removida: F6 <= 1.18 -> F4 <= 1.58 (0.1157) | Mantida: F4 <= 1.58 -> F6 <= 1.18 (0.1668)
Removida: F6 <= 0.11 -> F4 <= 1.58 (0.0826) | Mantida: F4 <= 1.58 -> F6 <= 0.11 (0.0948)
Removida: F6 <= 0.11 -> F6 <= 1.18 (0.0635) | Mantida: F6 <= 1.18 -> F6 <= 0.11 (0.4302)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.1345) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.3475)
Removida: F4 <= -0.67 -> F3 <= 0.27 (0.0745) | Mantida: F3 <= 0.27 -> F4 <= -0.67 (0.1993)
Removida: F3 <= 0.27 -> F2 <= -0.54 (0.0319) | Mantida: F2 <= -0.54 -> F3 <= 0.27 (0.0387)
Removida: F6 <= -0.58 -> F4 <= -0.67 (0.0528) | Mantida: F4 <= -0.67 -> F6 <= -0.58 (0.1252)
Removida: F2 <= 0.21 -> F6 <= -0.58 (0.0223) | Mantida: F6 <= -0.58 -> F2 <= 0.21 (0.0466)
Removida: F2 <= 0.21 -> F3 <= -0.44 (0.0217) | Mantida: F3 <= -0.44 -> F2 <= 0.21 (0.0430)
Removida: background4 > -0.05 -> background4 > -0.03 (0.0012) | Mantida: background4 > -0.03 -> background4 > -0.05 (0.0099)
Removida: background4 > -0.05 -> background5 > 0.00 (0.0011) | Mantida: background5 > 0.00 -> background4 > -0.05 (0.0042)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 167 | Removidas: 43
Nós predicados: 36
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 3
======================================================================


Total de pares bidirecionais encontrados: 38
Removida: F1 > -2.43 -> F1 <= 2.88 (1.6374) | Mantida: F1 <= 2.88 -> F1 > -2.43 (3.3049)
Removida: F5 > -1.83 -> F1 > -2.43 (3.1090) | Mantida: F1 > -2.43 -> F5 > -1.83 (3.2481)
Removida: F6 > 0.11 -> F5 > -1.79 (0.3191) | Mantida: F5 > -1.79 -> F6 > 0.11 (0.8233)
Removida: F6 > -1.37 -> F4 > -0.67 (0.3317) | Mantida: F4 > -0.67 -> F6 > -1.37 (0.3321)
Removida: F4 > -0.67 -> F6 > 0.11 (0.3294) | Mantida: F6 > 0.11 -> F4 > -0.67 (1.0484)
Removida: F4 > -0.67 -> F4 > -1.63 (0.5935) | Mantida: F4 > -1.63 -> F4 > -0.67 (0.9751)
Removida: F6 > 0.11 -> F4 > -1.63 (0.6680) | Mantida: F4 > -1.63 -> F6 > 0.11 (0.7015)
Removida: F3 > -1.46 -> F4 > -1.63 (0.2995) | Mantida: F4 > -1.63 -> F3 > -1.46 (0.6198)
Removida: F4 > -1.63 -> F5 <= 0.75 (0.2896) | Mantida: F5 <= 0.75 -> F4 > -1.63 (0.2968)
Removida: F3 > -1.46 -> F2 > -0.54 (0.2944) | Mantida: F2 > -0.54 -> F3 > -1.46 (0.6262)
Removida: F1 <= 0.67 -> F3 > -1.46 (0.2849) | Mantida: F3 > -1.46 -> F1 <= 0.67 (0.5583)
Removida: F2 > -0.54 -> F2 > -1.57 (0.5685) | Mantida: F2 > -1.57 -> F2 > -0.54 (0.6100)
Removida: F5 <= 0.75 -> F2 > -0.54 (0.2836) | Mantida: F2 > -0.54 -> F5 <= 0.75 (0.3079)
Removida: F2 > -0.54 -> F6 > -0.58 (0.5622) | Mantida: F6 > -0.58 -> F2 > -0.54 (0.5873)
Removida: F5 <= 0.75 -> F2 > -1.57 (0.3068) | Mantida: F2 > -1.57 -> F5 <= 0.75 (0.5619)
Removida: F3 > -0.44 -> F5 <= 0.75 (0.5280) | Mantida: F5 <= 0.75 -> F3 > -0.44 (0.5959)
Removida: F3 > -0.44 -> F1 <= 0.67 (0.2609) | Mantida: F1 <= 0.67 -> F3 > -0.44 (0.5343)
Removida: F6 > -0.58 -> F3 > 0.27 (0.2230) | Mantida: F3 > 0.27 -> F6 > -0.58 (0.2693)
Removida: F2 > 0.21 -> F3 > 0.27 (0.2109) | Mantida: F3 > 0.27 -> F2 > 0.21 (1.6722)
Removida: F1 <= 0.67 -> F6 > -0.58 (0.5560) | Mantida: F6 > -0.58 -> F1 <= 0.67 (0.8031)
Removida: F3 <= 1.39 -> F4 > 0.28 (0.4239) | Mantida: F4 > 0.28 -> F3 <= 1.39 (0.5968)
Removida: F2 <= 1.43 -> F4 > 0.28 (0.1514) | Mantida: F4 > 0.28 -> F2 <= 1.43 (0.3829)
Removida: F2 <= 1.43 -> F3 <= 1.39 (0.2433) | Mantida: F3 <= 1.39 -> F2 <= 1.43 (0.4855)
Removida: F4 <= 1.58 -> F3 <= 1.39 (0.1280) | Mantida: F3 <= 1.39 -> F4 <= 1.58 (0.3306)
Removida: F2 <= 1.43 -> F4 <= 1.58 (0.2004) | Mantida: F4 <= 1.58 -> F2 <= 1.43 (0.2197)
Removida: F6 <= 1.18 -> F6 <= 0.11 (0.1653) | Mantida: F6 <= 0.11 -> F6 <= 1.18 (0.3994)
Removida: F3 <= 0.27 -> F6 <= 0.11 (0.1369) | Mantida: F6 <= 0.11 -> F3 <= 0.27 (0.1560)
Removida: F6 <= 0.11 -> F4 <= -0.67 (0.0728) | Mantida: F4 <= -0.67 -> F6 <= 0.11 (0.0771)
Removida: F4 <= -0.67 -> F6 <= 1.18 (0.0559) | Mantida: F6 <= 1.18 -> F4 <= -0.67 (0.1953)
Removida: F4 <= -0.67 -> F3 <= 0.27 (0.1001) | Mantida: F3 <= 0.27 -> F4 <= -0.67 (0.1593)
Removida: F2 <= 0.21 -> F6 <= -0.58 (0.0191) | Mantida: F6 <= -0.58 -> F2 <= 0.21 (0.0955)
Removida: F2 <= -0.54 -> F2 <= 0.21 (0.0230) | Mantida: F2 <= 0.21 -> F2 <= -0.54 (0.0405)
Removida: F4 <= 0.28 -> F2 <= 0.21 (0.0166) | Mantida: F2 <= 0.21 -> F4 <= 0.28 (0.0233)
Removida: background4 > -0.03 -> background4 > -0.05 (0.0043) | Mantida: background4 > -0.05 -> background4 > -0.03 (0.0059)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,F1 > -2.47,F1 > -2.47,F1 > -2.47,F1 > -2.47
1,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88
2,F5 > -1.83,F5 > -1.83,F5 > -1.83,F5 > -1.83
3,F1 > -2.43,F1 > -2.43,F1 > -2.43,F1 > -2.43
4,F5 <= 2.10,F5 <= 2.10,F5 <= 2.10,F5 <= 2.10
5,F3 > -0.44,F6 > 0.11,F5 > -1.79,F5 > -1.79
6,F5 > -1.79,F3 > -0.44,F4 > -1.63,F6 > -1.37
7,F4 > -1.63,F3 > 0.27,F2 > -0.54,F6 > -0.58
8,F4 > -0.67,F4 > -0.67,F1 <= 0.67,F6 > 0.11
9,F3 > -1.46,F1 <= 0.67,F4 > -0.67,F3 > -1.46
10,F6 > -1.37,F5 > -1.79,F5 <= 0.75,F3 > 0.27
11,F2 > -0.54,F6 > -1.37,F6 > 0.11,F4 > -0.67
12,F2 > -1.57,F2 > -1.57,F6 > -1.37,F1 <= 0.67
13,F6 > 0.11,F4 > -1.63,F3 > -1.46,F5 <= 0.75
14,F5 <= 0.75,F6 > -0.58,F3 > -0.44,F2 > -1.57
15,F1 <= 0.67,F2 > -0.54,F2 > -1.57,F2 > -0.54
16,F3 > 0.27,F5 <= 0.75,F6 > -0.58,F4 > -1.63
17,F6 > -0.58,F3 > -1.46,F3 > 0.27,F3 > -0.44
18,F3 <= 1.39,F3 <= 1.39,F2 > 0.21,F2 > 0.21
19,F2 > 0.21,F4 > 0.28,F2 <= 1.43,F4 > 0.28
20,F2 <= 1.43,F2 <= 1.43,F4 > 0.28,F3 <= 1.39
21,F4 <= 1.58,F2 > 0.21,F6 <= 1.18,F6 <= 0.11
22,F4 > 0.28,F6 <= 1.18,F3 <= 1.39,F4 <= 1.58
23,F6 <= 1.18,F4 <= 1.58,F6 <= 0.11,F6 <= 1.18
24,F6 > 1.18,F6 <= 0.11,F4 <= 1.58,F2 <= 1.43
25,F6 <= 0.11,F3 <= 0.27,F4 <= -0.67,F3 <= 0.27
26,F3 <= 0.27,F6 <= -1.37,F3 <= 0.27,F4 <= -0.67
27,F4 <= -0.67,F4 <= 0.28,F2 <= 0.21,F6 <= -0.58
28,F2 <= 0.21,F4 <= -0.67,F2 <= -0.54,F4 <= 0.28
29,F4 <= 0.28,F2 <= 0.21,F4 <= 0.28,F2 <= 0.21
30,F3 <= -0.44,background5 > -0.04,F6 <= -0.58,F3 <= -0.44
31,F6 <= -0.58,F3 <= -0.44,F3 <= -0.44,F2 <= -0.54
32,F2 <= -0.54,F6 <= -0.58,background5 > -0.04,background5 > 0.00
33,background4 > -0.05,F2 <= -0.54,background4 > -0.05,background4 > -0.05
34,background4 > -0.03,background5 > 0.00,background4 > -0.03,background4 > -0.03
35,background5 > 0.00,background4 > -0.05,background5 > 0.00,background5 > -0.04
36,background5 > -0.04,background4 > -0.03,Class_A,Class_A
37,Class_A,background5 > -0.07,Class_B,Class_B
38,Class_B,Class_A,NaN,NaN
39,NaN,Class_B,NaN,NaN

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,F1 > -2.47,6.393797,F1,-2.47,>
1,F5 > -1.83,3.277862,F5,-1.83,>
2,F6 > -1.37,0.913422,F6,-1.37,>
3,F4 > -1.63,0.905974,F4,-1.63,>
4,F3 > -0.44,0.878801,F3,-0.44,>
5,F2 > -0.54,0.857832,F2,-0.54,>
6,background5 > 0.00,0.025506,background5,0.00,>
7,background4 > -0.05,0.024050,background4,-0.05,>
8,Class_B,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'F1': VE = 97.70%, dim = 50 variáveis
Zona 'background1': VE = 4.20%, dim = 50 variáveis
Zona 'F2': VE = 92.76%, dim = 50 variáveis
Zona 'background2': VE = 10.44%, dim = 15 variáveis
Zona 'F3': VE = 92.93%, dim = 50 variáveis
Zona 'background3': VE = 5.32%, dim = 35 variáveis
Zona 'F4': VE = 93.74%, dim = 50 variáveis
Zona 'background4': VE = 8.95%, dim = 30 variáveis
Zona 'F5': VE = 96.69%, dim = 45 variáveis
Zona 'background5': VE = 16.85%, dim = 32 variáveis
Zona 'F6': VE = 93.73%, dim = 38 variáveis
Zona 'background6': VE = 5.17%, dim = 55 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,F1 > -2.47,6.393797,F1,-2.47,>,-2.469280,70.0,0.000720,F1 > -2.469280
1,F1 <= 2.88,4.302241,F1,2.88,<=,2.877525,163.0,0.002475,F1 <= 2.877525
2,F5 > -1.83,3.277862,F5,-1.83,>,-1.830283,186.0,0.000283,F5 > -1.830283
3,F1 > -2.43,3.057715,F1,-2.43,>,-2.430272,18.0,0.000272,F1 > -2.430272
4,F5 <= 2.10,2.369149,F5,2.10,<=,2.099612,76.0,0.000388,F5 <= 2.099612
5,F5 > -1.79,1.091374,F5,-1.79,>,-1.789303,178.0,0.000697,F5 > -1.789303
6,F6 > -1.37,0.913422,F6,-1.37,>,-1.370060,175.0,0.000060,F6 > -1.370060
7,F4 > -1.63,0.905974,F4,-1.63,>,-1.631439,56.0,0.001439,F4 > -1.631439
8,F6 > 0.11,0.887900,F6,0.11,>,0.109128,112.0,0.000872,F6 > 0.109128
9,F4 > -0.67,0.881768,F4,-0.67,>,-0.669382,42.0,0.000618,F4 > -0.669382
10,F3 > -0.44,0.878801,F3,-0.44,>,-0.440007,87.0,0.000007,F3 > -0.440007
11,F1 <= 0.67,0.862929,F1,0.67,<=,0.674815,174.0,0.004815,F1 <= 0.674815
12,F2 > -0.54,0.857832,F2,-0.54,>,-0.539718,77.0,0.000282,F2 > -0.539718
13,F5 <= 0.75,0.845436,F5,0.75,<=,0.751483,52.0,0.001483,F5 <= 0.751483
14,F3 > -1.46,0.841952,F3,-1.46,>,-1.460111,64.0,0.000111,F3 > -1.460111
15,F2 > -1.57,0.825353,F2,-1.57,>,-1.567476,193.0,0.002524,F2 > -1.567476
16,F6 > -0.58,0.776782,F6,-0.58,>,-0.579114,144.0,0.000886,F6 > -0.579114
17,F3 > 0.27,0.721547,F3,0.27,>,0.271105,58.0,0.001105,F3 > 0.271105
18,F2 > 0.21,0.390572,F2,0.21,>,0.212652,53.0,0.002652,F2 > 0.212652
19,F3 <= 1.39,0.361374,F3,1.39,<=,1.390245,157.0,0.000245,F3 <= 1.390245
20,F4 > 0.28,0.340912,F4,0.28,>,0.282098,26.0,0.002098,F4 > 0.282098
21,F2 <= 1.43,0.312907,F2,1.43,<=,1.431026,104.0,0.001026,F2 <= 1.431026
22,F6 <= 1.18,0.239778,F6,1.18,<=,1.180851,44.0,0.000851,F6 <= 1.180851
23,F4 <= 1.58,0.235630,F4,1.58,<=,1.582286,194.0,0.002286,F4 <= 1.582286
24,F6 > 1.18,0.125052,F6,1.18,>,1.180851,44.0,0.000851,F6 > 1.180851
25,F6 <= 0.11,0.112175,F6,0.11,<=,0.109128,112.0,0.000872,F6 <= 0.109128
26,F3 <= 0.27,0.076600,F3,0.27,<=,0.271105,58.0,0.001105,F3 <= 0.271105
27,F4 <= -0.67,0.062724,F4,-0.67,<=,-0.669382,42.0,0.000618,F4 <= -0.669382
28,F6 <= -1.37,0.056755,F6,-1.37,<=,-1.370060,175.0,0.000060,F6 <= -1.370060
29,F4 <= 0.28,0.047588,F4,0.28,<=,0.282098,26.0,0.002098,F4 <= 0.282098
30,F2 <= 0.21,0.043851,F2,0.21,<=,0.212652,53.0,0.002652,F2 <= 0.212652
31,F6 <= -0.58,0.040982,F6,-0.58,<=,-0.579114,144.0,0.000886,F6 <= -0.579114
32,F3 <= -0.44,0.038586,F3,-0.44,<=,-0.440007,87.0,0.000007,F3 <= -0.440007
33,F2 <= -0.54,0.038067,F2,-0.54,<=,-0.539718,77.0,0.000282,F2 <= -0.539718
34,background5 > 0.00,0.025506,background5,0.00,>,-0.000664,150.0,0.000664,background5 > -0.000664
35,background4 > -0.05,0.024050,background4,-0.05,>,-0.050054,197.0,0.000054,background4 > -0.050054
36,background5 > -0.04,0.020175,background5,-0.04,>,-0.039784,30.0,0.000216,background5 > -0.039784
37,background4 > -0.03,0.014009,background4,-0.03,>,-0.029655,61.0,0.000345,background4 > -0.029655
38,background5 > -0.07,0.000080,background5,-0.07,>,-0.070634,85.0,0.000634,background5 > -0.070634
39,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
40,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'F1':
  - Dimensão: 50 variáveis espectrais
  - Range de energias: 1.0 - 99.09819639278558
  - Variância explicada pela PC1: 97.70%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 72 | Descartados: 24
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 73 | Descartados: 23
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=136)
    Zona: 50 colunas
    Importance: 0.175772
  Predicado: F1 <= -2.43 (n=69)
    Zona: 50 colunas
    Importance: 0.004079
  Predicado: F1 > -2.43 (n=99)
    Zona: 50 colunas
    Importance: 0.240275
  Predicado: F1 <= 0.67 (n=100)
    Zona: 50 colunas
    Importance: 0.041687
  Predicado: F1 > 0.67 (n=68)
    Zona: 50 colunas
    Importance: 0.292646
  Predicado: F1 <= 2.88 (n=138)
    Zona: 50 colunas
    Importance: 0.107266
  Predicado: background1 > -0.05 (n=138)
    Zona: 50 colunas
    Importance: 0.000094
  Predicado: background1 <= -0.02 (n=59)
    Zona: 50 colunas
    Importance: 0.000079
  Predicado: background1 > -0.02 (n=109)
    Zona: 50 colunas
    Importance: 0.000098
  Predicado: background1 <= 0.01 (n=101)
    Zona: 50 colunas
    Importance: 0.000075
  Predicado: background1 > 0.01 (n=67)
    Zona: 50 colunas
    Importance: 0.000116
  Predicado: background1 <= 0.05 (n=134)
    Zona: 50 colunas
    Importance: 0.000089
  Predicado: F2 > -1.57 (n=134)
    Zona: 50 colunas
    Importance: 0.002742
  Predicado: F2 <= -0.54 (n=69)
    Zona: 50 colunas
    Importance: 0.002882
  Predicado: F2 > -0.54 (n=99)
    Zona: 50 colunas
    Importance: 0.003349
  Predicado: F2 <= 0.21 (n=100)
    Zona: 50 colunas
    Importance: 0.002167
  Predicado: F2 > 0.21 (n=68)
    Zona: 50 colunas
    Importance: 0.004614
  Predicado: F2 <= 1.43 (n=133)
    Zona: 50 colunas
    Importance: 0.002954
  Predicado: background2 > -0.04 (n=135)
    Zona: 15 colunas
    Importance: 0.000032
  Predicado: background2 <= -0.01 (n=64)
    Zona: 15 colunas
    Importance: 0.000046
  Predicado: background2 > -0.01 (n=104)
    Zona: 15 colunas
    Importance: 0.000028
  Predicado: background2 <= 0.01 (n=93)
    Zona: 15 colunas
    Importance: 0.000038
  Predicado: background2 > 0.01 (n=75)
    Zona: 15 colunas
    Importance: 0.000031
  Predicado: background2 <= 0.04 (n=137)
    Zona: 15 colunas
    Importance: 0.000032
  Predicado: F3 > -1.46 (n=130)
    Zona: 50 colunas
    Importance: 0.002975
  Predicado: F3 <= -0.44 (n=75)
    Zona: 50 colunas
    Importance: 0.002895
  Predicado: F3 > -0.44 (n=93)
    Zona: 50 colunas
    Importance: 0.003393
  Predicado: F3 <= 0.27 (n=105)
    Zona: 50 colunas
    Importance: 0.002170
  Predicado: F3 > 0.27 (n=63)
    Zona: 50 colunas
    Importance: 0.004838
  Predicado: F3 <= 1.39 (n=133)
    Zona: 50 colunas
    Importance: 0.002126
  Predicado: background3 > -0.04 (n=136)
    Zona: 35 colunas
    Importance: 0.000059
  Predicado: background3 <= -0.01 (n=67)
    Zona: 35 colunas
    Importance: 0.000046
  Predicado: background3 > -0.01 (n=101)
    Zona: 35 colunas
    Importance: 0.000064
  Predicado: background3 <= 0.01 (n=100)
    Zona: 35 colunas
    Importance: 0.000059
  Predicado: background3 > 0.01 (n=68)
    Zona: 35 colunas
    Importance: 0.000054
  Predicado: background3 <= 0.04 (n=134)
    Zona: 35 colunas
    Importance: 0.000056
  Predicado: F4 > -1.63 (n=132)
    Zona: 50 colunas
    Importance: 0.002051
  Predicado: F4 <= -0.67 (n=70)
    Zona: 50 colunas
    Importance: 0.002075
  Predicado: F4 > -0.67 (n=98)
    Zona: 50 colunas
    Importance: 0.002462
  Predicado: F4 <= 0.28 (n=102)
    Zona: 50 colunas
    Importance: 0.001514
  Predicado: F4 > 0.28 (n=66)
    Zona: 50 colunas
    Importance: 0.003517
  Predicado: F4 <= 1.58 (n=136)
    Zona: 50 colunas
    Importance: 0.001538
  Predicado: background4 > -0.05 (n=137)
    Zona: 30 colunas
    Importance: 0.000058
  Predicado: background4 <= -0.03 (n=54)
    Zona: 30 colunas
    Importance: 0.000062
  Predicado: background4 > -0.03 (n=114)
    Zona: 30 colunas
    Importance: 0.000059
  Predicado: background4 <= 0.00 (n=97)
    Zona: 30 colunas
    Importance: 0.000057
  Predicado: background4 > 0.00 (n=71)
    Zona: 30 colunas
    Importance: 0.000064
  Predicado: background4 <= 0.04 (n=133)
    Zona: 30 colunas
    Importance: 0.000056
  Predicado: F5 > -1.83 (n=138)
    Zona: 45 colunas
    Importance: 0.023471
  Predicado: F5 <= -1.79 (n=66)
    Zona: 45 colunas
    Importance: 0.011696
  Predicado: F5 > -1.79 (n=102)
    Zona: 45 colunas
    Importance: 0.026034
  Predicado: F5 <= 0.75 (n=101)
    Zona: 45 colunas
    Importance: 0.015470
  Predicado: F5 > 0.75 (n=67)
    Zona: 45 colunas
    Importance: 0.027834
  Predicado: F5 <= 2.10 (n=134)
    Zona: 45 colunas
    Importance: 0.018726
  Predicado: background5 > -0.07 (n=134)
    Zona: 32 colunas
    Importance: 0.000067
  Predicado: background5 <= -0.04 (n=59)
    Zona: 32 colunas
    Importance: 0.000063
  Predicado: background5 > -0.04 (n=109)
    Zona: 32 colunas
    Importance: 0.000073
  Predicado: background5 <= 0.00 (n=95)
    Zona: 32 colunas
    Importance: 0.000074
  Predicado: background5 > 0.00 (n=73)
    Zona: 32 colunas
    Importance: 0.000063
  Predicado: background5 <= 0.06 (n=132)
    Zona: 32 colunas
    Importance: 0.000065
  Predicado: F6 > -1.37 (n=133)
    Zona: 38 colunas
    Importance: 0.002002
  Predicado: F6 <= -0.58 (n=69)
    Zona: 38 colunas
    Importance: 0.004839
  Predicado: F6 > -0.58 (n=99)
    Zona: 38 colunas
    Importance: 0.002191
  Predicado: F6 <= 0.11 (n=107)
    Zona: 38 colunas
    Importance: 0.003238
  Predicado: F6 > 0.11 (n=61)
    Zona: 38 colunas
    Importance: 0.003350
  Predicado: F6 <= 1.18 (n=136)
    Zona: 38 colunas
    Importance: 0.002953
  Predicado: background6 > -0.05 (n=134)
    Zona: 55 colunas
    Importance: 0.000088
  Predicado: background6 <= -0.02 (n=67)
    Zona: 55 colunas
    Importance: 0.000118
  Predicado: background6 > -0.02 (n=101)
    Zona: 55 colunas
    Importance: 0.000093
  Predicado: background6 <= 0.01 (n=99)
    Zona: 55 colunas
    Importance: 0.000111
  Predicado: background6 > 0.01 (n=69)
    Zona: 55 colunas
    Importance: 0.000091
  Predicado: background6 <= 0.04 (n=134)
    Zona: 55 colunas
    Importance: 0.000101

[Bag_2] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=137)
    Zona: 50 colunas
    Importance: 0.163777
  Predicado: F1 <= -2.43 (n=64)
    Zona: 50 colunas
    Importance: 0.003744
  Predicado: F1 > -2.43 (n=104)
    Zona: 50 colunas
    Importance: 0.214817
  Predicado: F1 <= 0.67 (n=101)
    Zona: 50 colunas
    Importance: 0.043549
  Predicado: F1 > 0.67 (n=67)
    Zona: 50 colunas
    Importance: 0.271376
  Predicado: F1 <= 2.88 (n=135)
    Zona: 50 colunas
    Importance: 0.097592
  Predicado: background1 > -0.05 (n=137)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 <= -0.02 (n=56)
    Zona: 50 colunas
    Importance: 0.000073
  Predicado: background1 > -0.02 (n=112)
    Zona: 50 colunas
    Importance: 0.000097
  Predicado: background1 <= 0.01 (n=96)
    Zona: 50 colunas
    Importance: 0.000072
  Predicado: background1 > 0.01 (n=72)
    Zona: 50 colunas
    Importance: 0.000112
  Predicado: background1 <= 0.05 (n=136)
    Zona: 50 colunas
    Importance: 0.000086
  Predicado: F2 > -1.57 (n=134)
    Zona: 50 colunas
    Importance: 0.003036
  Predicado: F2 <= -0.54 (n=68)
    Zona: 50 colunas
    Importance: 0.002069
  Predicado: F2 > -0.54 (n=100)
    Zona: 50 colunas
    Importance: 0.003694
  Predicado: F2 <= 0.21 (n=100)
    Zona: 50 colunas
    Importance: 0.001595
  Predicado: F2 > 0.21 (n=68)
    Zona: 50 colunas
    Importance: 0.005157
  Predicado: F2 <= 1.43 (n=131)
    Zona: 50 colunas
    Importance: 0.002582
  Predicado: background2 > -0.04 (n=138)
    Zona: 15 colunas
    Importance: 0.000034
  Predicado: background2 <= -0.01 (n=62)
    Zona: 15 colunas
    Importance: 0.000039
  Predicado: background2 > -0.01 (n=106)
    Zona: 15 colunas
    Importance: 0.000030
  Predicado: background2 <= 0.01 (n=87)
    Zona: 15 colunas
    Importance: 0.000035
  Predicado: background2 > 0.01 (n=81)
    Zona: 15 colunas
    Importance: 0.000032
  Predicado: background2 <= 0.04 (n=133)
    Zona: 15 colunas
    Importance: 0.000029
  Predicado: F3 > -1.46 (n=136)
    Zona: 50 colunas
    Importance: 0.002929
  Predicado: F3 <= -0.44 (n=69)
    Zona: 50 colunas
    Importance: 0.003227
  Predicado: F3 > -0.44 (n=99)
    Zona: 50 colunas
    Importance: 0.003303
  Predicado: F3 <= 0.27 (n=99)
    Zona: 50 colunas
    Importance: 0.002361
  Predicado: F3 > 0.27 (n=69)
    Zona: 50 colunas
    Importance: 0.004579
  Predicado: F3 <= 1.39 (n=134)
    Zona: 50 colunas
    Importance: 0.002278
  Predicado: background3 > -0.04 (n=133)
    Zona: 35 colunas
    Importance: 0.000057
  Predicado: background3 <= -0.01 (n=69)
    Zona: 35 colunas
    Importance: 0.000051
  Predicado: background3 > -0.01 (n=99)
    Zona: 35 colunas
    Importance: 0.000061
  Predicado: background3 <= 0.01 (n=100)
    Zona: 35 colunas
    Importance: 0.000060
  Predicado: background3 > 0.01 (n=68)
    Zona: 35 colunas
    Importance: 0.000053
  Predicado: background3 <= 0.04 (n=128)
    Zona: 35 colunas
    Importance: 0.000056
  Predicado: F4 > -1.63 (n=135)
    Zona: 50 colunas
    Importance: 0.001953
  Predicado: F4 <= -0.67 (n=63)
    Zona: 50 colunas
    Importance: 0.002178
  Predicado: F4 > -0.67 (n=105)
    Zona: 50 colunas
    Importance: 0.002262
  Predicado: F4 <= 0.28 (n=99)
    Zona: 50 colunas
    Importance: 0.001517
  Predicado: F4 > 0.28 (n=69)
    Zona: 50 colunas
    Importance: 0.003255
  Predicado: F4 <= 1.58 (n=131)
    Zona: 50 colunas
    Importance: 0.001431
  Predicado: background4 > -0.05 (n=141)
    Zona: 30 colunas
    Importance: 0.000057
  Predicado: background4 <= -0.03 (n=57)
    Zona: 30 colunas
    Importance: 0.000055
  Predicado: background4 > -0.03 (n=111)
    Zona: 30 colunas
    Importance: 0.000063
  Predicado: background4 <= 0.00 (n=99)
    Zona: 30 colunas
    Importance: 0.000054
  Predicado: background4 > 0.00 (n=69)
    Zona: 30 colunas
    Importance: 0.000068
  Predicado: background4 <= 0.04 (n=134)
    Zona: 30 colunas
    Importance: 0.000056
  Predicado: F5 > -1.83 (n=136)
    Zona: 45 colunas
    Importance: 0.024186
  Predicado: F5 <= -1.79 (n=69)
    Zona: 45 colunas
    Importance: 0.012468
  Predicado: F5 > -1.79 (n=99)
    Zona: 45 colunas
    Importance: 0.027044
  Predicado: F5 <= 0.75 (n=101)
    Zona: 45 colunas
    Importance: 0.016762
  Predicado: F5 > 0.75 (n=67)
    Zona: 45 colunas
    Importance: 0.027533
  Predicado: F5 <= 2.10 (n=135)
    Zona: 45 colunas
    Importance: 0.019958
  Predicado: background5 > -0.07 (n=130)
    Zona: 32 colunas
    Importance: 0.000070
  Predicado: background5 <= -0.04 (n=62)
    Zona: 32 colunas
    Importance: 0.000054
  Predicado: background5 > -0.04 (n=106)
    Zona: 32 colunas
    Importance: 0.000076
  Predicado: background5 <= 0.00 (n=103)
    Zona: 32 colunas
    Importance: 0.000067
  Predicado: background5 > 0.00 (n=65)
    Zona: 32 colunas
    Importance: 0.000068
  Predicado: background5 <= 0.06 (n=131)
    Zona: 32 colunas
    Importance: 0.000061
  Predicado: F6 > -1.37 (n=130)
    Zona: 38 colunas
    Importance: 0.002547
  Predicado: F6 <= -0.58 (n=68)
    Zona: 38 colunas
    Importance: 0.002934
  Predicado: F6 > -0.58 (n=100)
    Zona: 38 colunas
    Importance: 0.002808
  Predicado: F6 <= 0.11 (n=100)
    Zona: 38 colunas
    Importance: 0.002103
  Predicado: F6 > 0.11 (n=68)
    Zona: 38 colunas
    Importance: 0.003971
  Predicado: F6 <= 1.18 (n=133)
    Zona: 38 colunas
    Importance: 0.002097
  Predicado: background6 > -0.05 (n=131)
    Zona: 55 colunas
    Importance: 0.000089
  Predicado: background6 <= -0.02 (n=69)
    Zona: 55 colunas
    Importance: 0.000101
  Predicado: background6 > -0.02 (n=99)
    Zona: 55 colunas
    Importance: 0.000094
  Predicado: background6 <= 0.01 (n=108)
    Zona: 55 colunas
    Importance: 0.000098
  Predicado: background6 > 0.01 (n=60)
    Zona: 55 colunas
    Importance: 0.000094
  Predicado: background6 <= 0.04 (n=136)
    Zona: 55 colunas
    Importance: 0.000092

[Bag_3] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=134)
    Zona: 50 colunas
    Importance: 0.163831
  Predicado: F1 <= -2.43 (n=69)
    Zona: 50 colunas
    Importance: 0.004144
  Predicado: F1 > -2.43 (n=99)
    Zona: 50 colunas
    Importance: 0.220536
  Predicado: F1 <= 0.67 (n=104)
    Zona: 50 colunas
    Importance: 0.040734
  Predicado: F1 > 0.67 (n=64)
    Zona: 50 colunas
    Importance: 0.279416
  Predicado: F1 <= 2.88 (n=136)
    Zona: 50 colunas
    Importance: 0.088324
  Predicado: background1 > -0.05 (n=139)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 <= -0.02 (n=61)
    Zona: 50 colunas
    Importance: 0.000080
  Predicado: background1 > -0.02 (n=107)
    Zona: 50 colunas
    Importance: 0.000095
  Predicado: background1 <= 0.01 (n=104)
    Zona: 50 colunas
    Importance: 0.000076
  Predicado: background1 > 0.01 (n=64)
    Zona: 50 colunas
    Importance: 0.000111
  Predicado: background1 <= 0.05 (n=138)
    Zona: 50 colunas
    Importance: 0.000085
  Predicado: F2 > -1.57 (n=136)
    Zona: 50 colunas
    Importance: 0.002611
  Predicado: F2 <= -0.54 (n=67)
    Zona: 50 colunas
    Importance: 0.002763
  Predicado: F2 > -0.54 (n=101)
    Zona: 50 colunas
    Importance: 0.003289
  Predicado: F2 <= 0.21 (n=101)
    Zona: 50 colunas
    Importance: 0.001977
  Predicado: F2 > 0.21 (n=67)
    Zona: 50 colunas
    Importance: 0.004741
  Predicado: F2 <= 1.43 (n=136)
    Zona: 50 colunas
    Importance: 0.002792
  Predicado: background2 > -0.04 (n=136)
    Zona: 15 colunas
    Importance: 0.000033
  Predicado: background2 <= -0.01 (n=66)
    Zona: 15 colunas
    Importance: 0.000043
  Predicado: background2 > -0.01 (n=102)
    Zona: 15 colunas
    Importance: 0.000029
  Predicado: background2 <= 0.01 (n=94)
    Zona: 15 colunas
    Importance: 0.000036
  Predicado: background2 > 0.01 (n=74)
    Zona: 15 colunas
    Importance: 0.000032
  Predicado: background2 <= 0.04 (n=134)
    Zona: 15 colunas
    Importance: 0.000031
  Predicado: F3 > -1.46 (n=135)
    Zona: 50 colunas
    Importance: 0.003000
  Predicado: F3 <= -0.44 (n=67)
    Zona: 50 colunas
    Importance: 0.002693
  Predicado: F3 > -0.44 (n=101)
    Zona: 50 colunas
    Importance: 0.003633
  Predicado: F3 <= 0.27 (n=103)
    Zona: 50 colunas
    Importance: 0.001891
  Predicado: F3 > 0.27 (n=65)
    Zona: 50 colunas
    Importance: 0.005424
  Predicado: F3 <= 1.39 (n=133)
    Zona: 50 colunas
    Importance: 0.001954
  Predicado: background3 > -0.04 (n=132)
    Zona: 35 colunas
    Importance: 0.000056
  Predicado: background3 <= -0.01 (n=70)
    Zona: 35 colunas
    Importance: 0.000047
  Predicado: background3 > -0.01 (n=98)
    Zona: 35 colunas
    Importance: 0.000061
  Predicado: background3 <= 0.01 (n=98)
    Zona: 35 colunas
    Importance: 0.000058
  Predicado: background3 > 0.01 (n=70)
    Zona: 35 colunas
    Importance: 0.000050
  Predicado: background3 <= 0.04 (n=132)
    Zona: 35 colunas
    Importance: 0.000055
  Predicado: F4 > -1.63 (n=132)
    Zona: 50 colunas
    Importance: 0.001619
  Predicado: F4 <= -0.67 (n=72)
    Zona: 50 colunas
    Importance: 0.001821
  Predicado: F4 > -0.67 (n=96)
    Zona: 50 colunas
    Importance: 0.001976
  Predicado: F4 <= 0.28 (n=106)
    Zona: 50 colunas
    Importance: 0.001355
  Predicado: F4 > 0.28 (n=62)
    Zona: 50 colunas
    Importance: 0.002857
  Predicado: F4 <= 1.58 (n=140)
    Zona: 50 colunas
    Importance: 0.001368
  Predicado: background4 > -0.05 (n=140)
    Zona: 30 colunas
    Importance: 0.000054
  Predicado: background4 <= -0.03 (n=62)
    Zona: 30 colunas
    Importance: 0.000062
  Predicado: background4 > -0.03 (n=106)
    Zona: 30 colunas
    Importance: 0.000056
  Predicado: background4 <= 0.00 (n=100)
    Zona: 30 colunas
    Importance: 0.000058
  Predicado: background4 > 0.00 (n=68)
    Zona: 30 colunas
    Importance: 0.000058
  Predicado: background4 <= 0.04 (n=134)
    Zona: 30 colunas
    Importance: 0.000055
  Predicado: F5 > -1.83 (n=135)
    Zona: 45 colunas
    Importance: 0.023650
  Predicado: F5 <= -1.79 (n=65)
    Zona: 45 colunas
    Importance: 0.012280
  Predicado: F5 > -1.79 (n=103)
    Zona: 45 colunas
    Importance: 0.025336
  Predicado: F5 <= 0.75 (n=98)
    Zona: 45 colunas
    Importance: 0.016347
  Predicado: F5 > 0.75 (n=70)
    Zona: 45 colunas
    Importance: 0.025798
  Predicado: F5 <= 2.10 (n=133)
    Zona: 45 colunas
    Importance: 0.019709
  Predicado: background5 > -0.07 (n=130)
    Zona: 32 colunas
    Importance: 0.000066
  Predicado: background5 <= -0.04 (n=64)
    Zona: 32 colunas
    Importance: 0.000056
  Predicado: background5 > -0.04 (n=104)
    Zona: 32 colunas
    Importance: 0.000072
  Predicado: background5 <= 0.00 (n=104)
    Zona: 32 colunas
    Importance: 0.000068
  Predicado: background5 > 0.00 (n=64)
    Zona: 32 colunas
    Importance: 0.000061
  Predicado: background5 <= 0.06 (n=133)
    Zona: 32 colunas
    Importance: 0.000062
  Predicado: F6 > -1.37 (n=131)
    Zona: 38 colunas
    Importance: 0.002293
  Predicado: F6 <= -0.58 (n=67)
    Zona: 38 colunas
    Importance: 0.005018
  Predicado: F6 > -0.58 (n=101)
    Zona: 38 colunas
    Importance: 0.002565
  Predicado: F6 <= 0.11 (n=101)
    Zona: 38 colunas
    Importance: 0.003435
  Predicado: F6 > 0.11 (n=67)
    Zona: 38 colunas
    Importance: 0.003706
  Predicado: F6 <= 1.18 (n=137)
    Zona: 38 colunas
    Importance: 0.003061
  Predicado: background6 > -0.05 (n=135)
    Zona: 55 colunas
    Importance: 0.000082
  Predicado: background6 <= -0.02 (n=69)
    Zona: 55 colunas
    Importance: 0.000105
  Predicado: background6 > -0.02 (n=99)
    Zona: 55 colunas
    Importance: 0.000088
  Predicado: background6 <= 0.01 (n=101)
    Zona: 55 colunas
    Importance: 0.000104
  Predicado: background6 > 0.01 (n=67)
    Zona: 55 colunas
    Importance: 0.000080
  Predicado: background6 <= 0.04 (n=134)
    Zona: 55 colunas
    Importance: 0.000095

[Bag_4] Processando 72 predicados...
  Predicado: F1 > -2.47 (n=135)
    Zona: 50 colunas
    Importance: 0.158157
  Predicado: F1 <= -2.43 (n=73)
    Zona: 50 colunas
    Importance: 0.004180
  Predicado: F1 > -2.43 (n=95)
    Zona: 50 colunas
    Importance: 0.223380
  Predicado: F1 <= 0.67 (n=104)
    Zona: 50 colunas
    Importance: 0.036174
  Predicado: F1 > 0.67 (n=64)
    Zona: 50 colunas
    Importance: 0.277564
  Predicado: F1 <= 2.88 (n=134)
    Zona: 50 colunas
    Importance: 0.087683
  Predicado: background1 > -0.05 (n=135)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 <= -0.02 (n=58)
    Zona: 50 colunas
    Importance: 0.000085
  Predicado: background1 > -0.02 (n=110)
    Zona: 50 colunas
    Importance: 0.000091
  Predicado: background1 <= 0.01 (n=98)
    Zona: 50 colunas
    Importance: 0.000079

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,F1 > 0.67,F1 > 0.67,F1 > 0.67,F1 > 0.67
1,F1 > -2.43,F1 > -2.43,F1 > -2.43,F1 > -2.43
2,F1 > -2.47,F1 > -2.47,F1 > -2.47,F1 > -2.47
3,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88,F1 <= 2.88
4,F1 <= 0.67,F1 <= 0.67,F1 <= 0.67,F1 <= 0.67
...,...,...,...,...
72,background2 > -0.01,background2 <= 0.01,Class_A,background2 > -0.01
73,Class_A,background2 > -0.01,Class_B,Class_A
74,Class_B,background2 <= 0.04,NaN,Class_B
75,NaN,Class_A,NaN,NaN
76,NaN,Class_B,NaN,NaN

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

              Predicate  Perturbation
0             F1 > 0.67      0.292646
1            F1 > -2.43      0.240275
2            F1 > -2.47      0.175772
3            F1 <= 2.88      0.107266
4            F1 <= 0.67      0.041687
..                  ...           ...
67  background2 <= 0.01      0.000038
68  background2 > -0.04      0.000032
69  background2 <= 0.04      0.000032
70   background2 > 0.01      0.000031
71  background2 > -0.01      0.000028

[72 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,F1 > 0.67,19.440156,F1,0.67,>
1,F5 > 0.75,2.696398,F5,0.75,>
2,F2 > 0.21,0.171930,F2,0.21,>
3,F3 > 0.27,0.154941,F3,0.27,>
4,F6 <= -0.58,0.149346,F6,-0.58,<=
5,F4 > 0.28,0.115418,F4,0.28,>
6,background5 > -0.04,0.000343,background5,-0.04,>
7,background1 > 0.01,0.000286,background1,0.01,>
8,background6 <= -0.02,0.000282,background6,-0.02,<=
9,background4 > 0.00,0.000217,background4,0.00,>
10,background3 > -0.04,0.000202,background3,-0.04,>
11,background2 <= -0.01,0.000063,background2,-0.01,<=
12,Class_B,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,F1 > 0.67,19.440156,F1,0.67,>,0.674815,174.0,0.004815,F1 > 0.674815
1,F1 > -2.43,13.983183,F1,-2.43,>,-2.430272,18.0,0.000272,F1 > -2.430272
2,F1 > -2.47,9.304690,F1,-2.47,>,-2.469280,70.0,0.000720,F1 > -2.469280
3,F1 <= 2.88,5.574682,F1,2.88,<=,2.877525,163.0,0.002475,F1 <= 2.877525
4,F1 <= 0.67,3.377137,F1,0.67,<=,0.674815,174.0,0.004815,F1 <= 0.674815
...,...,...,...,...,...,...,...,...,...
73,background2 > 0.01,0.000034,background2,0.01,>,0.010315,102.0,0.000315,background2 > 0.010315
74,background2 <= 0.04,0.000029,background2,0.04,<=,0.040212,99.0,0.000212,background2 <= 0.040212
75,background2 > -0.01,0.000025,background2,-0.01,>,-0.009990,140.0,0.000010,background2 > -0.009990
76,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
77,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [23]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'F1':
  - Dimensão: 50 variáveis espectrais
  - Variância explicada pela PC1: 97.70%

In [17]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

                energy  Permutation_importance_proba         Zone
0   49.048096192384776                      0.003977           F1
1    699.6993987975952                      0.001333           F5
2    847.8476953907816                      0.000629           F6
3    379.3787575150301                      0.000530           F3
4    549.5490981963928                      0.000513           F4
5     249.248496993988                      0.000449           F2
6   109.10821643286573                      0.000011  background1
7    315.3146292585171                      0.000010  background2
8    791.7915831663327                      0.000010  background5
9    659.6593186372746                      0.000008  background4
10   911.9118236472947                      0.000008  background6
11   441.4408817635271                      0.000006  background3

In [18]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

    SVM_pvector         Shap  Permutation LRC_perturbation LRC_covariance
0            F1           F1           F1               F1             F1
1            F5           F5           F5               F5             F5
2            F6           F3           F6               F2             F6
3            F3           F4           F3               F3             F4
4            F4           F2           F4               F6             F3
5            F2           F6           F2               F4             F2
6   background2  background1  background1      background5    background5
7   background1  background2  background2      background1    background4
8   background4  background6  background5      background6           None
9   background6  background3  background4      background4           None
10  background5  background5  background6      background3           None
11  background3  background4  background3      background2           None
12         None         None         None             None           None

In [19]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_3556\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
1       SVM_pvector       Permutation   0.963578
3       SVM_pvector    LRC_covariance   0.905408
8       Permutation    LRC_covariance   0.905408
4              Shap       Permutation   0.878279
0       SVM_pvector              Shap   0.874447
7       Permutation  LRC_perturbation   0.871359
5              Shap  LRC_perturbation   0.870148
2       SVM_pvector  LRC_perturbation   0.869437
6              Shap    LRC_covariance   0.842002
9  LRC_perturbation    LRC_covariance   0.824408

In [20]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')