In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil/plsda/soil.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.32':'13.1']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.32':'13.1'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.32':'13.1'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:18:56,957 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:18:56,967 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:18:56,983 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:18:56,993 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import mlp_optimized

mlp_model = mlp_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, 
                          aim='classification', 
                          hidden_layer_sizes=(64,32),
                          activation='tanh',
                          learning_rate='adaptive',
                          max_iter=10,
                          random_state=1)
mlp_model[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,MLP,0.824324,0.859155,0.792208,"[[61, 16], [10, 61]]",0.765625,0.83871,0.69697,"[[23, 10], [5, 26]]"

## Definição das Zonas Espectrais

In [3]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.37),
('Ti ka', 4.37, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('background1', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background2', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background3', 11.14, 12.55),
('sum Fe' , 12.55, 13.1)
]

## SHAP

In [5]:
shap_global_importance = pd.read_csv('shap_soil.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP           Zone
0     6.52       0.024400          Fe ka
1     3.68       0.020931          Ca ka
2     4.52       0.016328          Ti ka
3     5.88       0.006197             Mn
4     7.06       0.003586          Fe kb
5     3.30       0.002263              K
6     1.74       0.001054             Si
7     3.98       0.000359          Ca kb
8     1.48       0.000266             Al
9    12.84       0.000226         sum Fe
10    9.94       0.000212    background2
11    4.86       0.000136          Ti kb
12    1.86       0.000131              P
13    2.98       0.000073      Rh L + Ar
14   10.72       0.000069  Fe ka + Ti ka
15    5.38       0.000066             Cr
16    8.12       0.000028             Cu
17   11.64       0.000010    background3
18    1.32       0.000000            NaN
19    2.20       0.000000              S
20    7.32       0.000000    background1

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Al': VE = 79.34%, dim = 15 variáveis
Zona 'Si': VE = 91.83%, dim = 12 variáveis
Zona 'P': VE = 62.02%, dim = 17 variáveis
Zona 'S': VE = 36.84%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 42.17%, dim = 33 variáveis
Zona 'K': VE = 83.48%, dim = 16 variáveis
Zona 'Ca ka': VE = 99.02%, dim = 16 variáveis
Zona 'Ca kb': VE = 74.05%, dim = 27 variáveis
Zona 'Ti ka': VE = 89.48%, dim = 19 variáveis
Zona 'Ti kb': VE = 82.21%, dim = 19 variáveis
Zona 'Cr': VE = 53.41%, dim = 33 variáveis
Zona 'Mn': VE = 91.12%, dim = 18 variáveis
Zona 'Fe ka': VE = 56.98%, dim = 34 variáveis
Zona 'Fe kb': VE = 55.98%, dim = 26 variáveis
Zona 'background1': VE = 32.70%, dim = 31 variáveis
Zona 'Cu': VE = 53.86%, dim = 15 variáveis
Zona 'background2': VE = 26.43%, dim = 125 variáveis
Zona 'Fe ka + Ti ka': VE = 34.74%, dim = 23 variáveis
Zona 'background3': VE = 18.96%, dim = 71 variáveis
Zona 'sum Fe': VE = 55.82%, dim = 28 variáveis

Scores DataFrame shape: (148, 20)

In [7]:
y_pred = mlp_model[4]['MLP'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(mlp_model[4]['MLP'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 123 | Descartados: 37
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 122 | Descartados: 38
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 123 | Descartados: 37
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 122 | Descartados: 38
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 86
Removida: Ca ka > -0.36 -> Fe ka > 0.86 (0.5107) | Mantida: Fe ka > 0.86 -> Ca ka > -0.36 (1.1020)
Removida: Fe ka > -0.43 -> Ca ka > -0.36 (0.0941) | Mantida: Ca ka > -0.36 -> Fe ka > -0.43 (1.1462)
Removida: Ti ka > 0.93 -> Fe ka > -0.43 (0.1198) | Mantida: Fe ka > -0.43 -> Ti ka > 0.93 (0.3122)
Removida: Fe ka > -2.66 -> Fe ka > -0.43 (0.1194) | Mantida: Fe ka > -0.43 -> Fe ka > -2.66 (0.3382)
Removida: Ti ka > 0.93 -> Ca ka <= 1.21 (0.2731) | Mantida: Ca ka <= 1.21 -> Ti ka > 0.93 (0.4334)
Removida: Fe ka > -2.66 -> Ti ka > 0.93 (0.1806) | Mantida: Ti ka > 0.93 -> Fe ka > -2.66 (0.4411)
Removida: Ti ka > 0.93 -> Fe ka <= 0.86 (0.1053) | Mantida: Fe ka <= 0.86 -> Ti ka > 0.93 (0.1544)
Removida: Ca ka <= 1.21 -> Fe ka > -2.66 (0.3015) | Mantida: Fe ka > -2.66 -> Ca ka <= 1.21 (0.3825)
Removida: Fe ka <= 0.86 -> Ti ka > -1.78 (0.0289) | Mantida: Ti ka > -1.78 -> Fe ka <= 0.86 (0.1991)
Removida: Ti ka > -0.57 -> Ti ka > -1.78 (0.0572) | Mantida: Ti ka > -1.78 -> Ti ka > -0.57 (0.1951)
Removida: Mn > -0.65 -> Fe ka <= 0.86 (0.0900) | Mantida: Fe ka <= 0.86 -> Mn > -0.65 (0.1152)
Removida: Fe kb > 0.40 -> Mn > -0.65 (0.0501) | Mantida: Mn > -0.65 -> Fe kb > 0.40 (0.0951)
Removida: Ca kb > -0.37 -> Mn > -0.65 (0.0732) | Mantida: Mn > -0.65 -> Ca kb > -0.37 (0.0969)
Removida: Ca kb > -0.23 -> Mn > -0.65 (0.0627) | Mantida: Mn > -0.65 -> Ca kb > -0.23 (0.0852)
Removida: Fe kb > 0.40 -> Ca kb > -0.37 (0.0550) | Mantida: Ca kb > -0.37 -> Fe kb > 0.40 (0.0687)
Removida: Fe ka <= 2.21 -> Fe kb > 0.40 (0.0504) | Mantida: Fe kb > 0.40 -> Fe ka <= 2.21 (0.0969)
Removida: Ca kb > -0.37 -> Fe ka <= 2.21 (0.0728) | Mantida: Fe ka <= 2.21 -> Ca kb > -0.37 (0.1718)
Removida: Ca kb > -0.23 -> Ti ka > -0.57 (0.0645) | Mantida: Ti ka > -0.57 -> Ca kb > -0.23 (0.0846)
Removida: Fe ka <= -0.43 -> Ca kb > -0.23 (0.0502) | Mantida: Ca kb > -0.23 -> Fe ka <= -0.43 (0.0706)
Removida: Fe ka <= -0.43 -> Ti ka > -0.57 (0.0587) | Mantida: Ti ka > -0.57 -> Fe ka <= -0.43 (0.0706)
Removida: Fe ka <= -0.43 -> Ca ka <= -0.36 (0.0310) | Mantida: Ca ka <= -0.36 -> Fe ka <= -0.43 (0.0526)
Removida: Fe ka <= -0.43 -> K > -0.20 (0.0331) | Mantida: K > -0.20 -> Fe ka <= -0.43 (0.0460)
Removida: K > -0.38 -> Mn > -0.38 (0.0497) | Mantida: Mn > -0.38 -> K > -0.38 (0.0681)
Removida: K > -0.20 -> Mn > -0.38 (0.0458) | Mantida: Mn > -0.38 -> K > -0.20 (0.0524)
Removida: Si > -0.20 -> Ti ka <= -0.57 (0.0369) | Mantida: Ti ka <= -0.57 -> Si > -0.20 (0.0456)
Removida: K > -0.38 -> Si > 0.13 (0.0567) | Mantida: Si > 0.13 -> K > -0.38 (0.0624)
Removida: K > -0.38 -> Si > -0.66 (0.1170) | Mantida: Si > -0.66 -> K > -0.38 (0.1201)
Removida: Si > 0.13 -> Si > -0.66 (0.1069) | Mantida: Si > -0.66 -> Si > 0.13 (0.1208)
Removida: Fe kb > -0.07 -> Si > -0.66 (0.0401) | Mantida: Si > -0.66 -> Fe kb > -0.07 (0.1167)
Removida: Ca ka <= -0.36 -> K > -0.20 (0.0545) | Mantida: K > -0.20 -> Ca ka <= -0.36 (0.0968)
Removida: Ca kb > -0.04 -> K > -0.20 (0.0442) | Mantida: K > -0.20 -> Ca kb > -0.04 (0.0474)
Removida: Al <= -0.09 -> Mn > -0.15 (0.0203) | Mantida: Mn > -0.15 -> Al <= -0.09 (0.0265)
Removida: Si > -0.20 -> Ti kb > 0.26 (0.0312) | Mantida: Ti kb > 0.26 -> Si > -0.20 (0.0372)
Removida: K > 0.02 -> Si > -0.20 (0.0389) | Mantida: Si > -0.20 -> K > 0.02 (0.0398)
Removida: sum Fe <= 0.31 -> K > 0.02 (0.0240) | Mantida: K > 0.02 -> sum Fe <= 0.31 (0.0359)
Removida: sum Fe <= 0.31 -> Al > -0.33 (0.0461) | Mantida: Al > -0.33 -> sum Fe <= 0.31 (0.0660)
Removida: Al > -0.33 -> K > 0.02 (0.0373) | Mantida: K > 0.02 -> Al > -0.33 (0.0718)
Removida: Al > -0.33 -> Ti kb > -0.16 (0.0315) | Mantida: Ti kb > -0.16 -> Al > -0.33 (0.0367)
Removida: Fe kb > -1.03 -> Al > -0.33 (0.0245) | Mantida: Al > -0.33 -> Fe kb > -1.03 (0.0352)
Removida: S > -0.06 -> Ti kb > -0.16 (0.0073) | Mantida: Ti kb > -0.16 -> S > -0.06 (0.0154)
Removida: Fe kb <= 0.40 -> Ti kb > -0.16 (0.0208) | Mantida: Ti kb > -0.16 -> Fe kb <= 0.40 (0.0303)
Removida: sum Fe > -0.31 -> P > -0.24 (0.0202) | Mantida: P > -0.24 -> sum Fe > -0.31 (0.0212)
Removida: Fe kb > -1.03 -> Fe kb <= -0.07 (0.0149) | Mantida: Fe kb <= -0.07 -> Fe kb > -1.03 (0.0206)
Removida: Fe kb <= 0.40 -> Al <= 0.16 (0.0203) | Mantida: Al <= 0.16 -> Fe kb <= 0.40 (0.0561)
Removida: Fe kb <= 0.40 -> Ca kb <= 0.29 (0.0134) | Mantida: Ca kb <= 0.29 -> Fe kb <= 0.40 (0.0152)
Removida: Al <= 0.16 -> sum Fe > -0.31 (0.0291) | Mantida: sum Fe > -0.31 -> Al <= 0.16 (0.0788)
Removida: sum Fe > -0.31 -> Fe kb <= 0.95 (0.0196) | Mantida: Fe kb <= 0.95 -> sum Fe > -0.31 (0.0210)
Removida: Cr > -0.28 -> Al <= 0.16 (0.0201) | Mantida: Al <= 0.16 -> Cr > -0.28 (0.1039)
Removida: sum Fe <= 0.13 -> Cr > -0.28 (0.0175) | Mantida: Cr > -0.28 -> sum Fe <= 0.13 (0.0182)
Removida: sum Fe <= 0.13 -> Al > -0.09 (0.0167) | Mantida: Al > -0.09 -> sum Fe <= 0.13 (0.0254)
Removida: Al <= -0.09 -> sum Fe <= 0.13 (0.0238) | Mantida: sum Fe <= 0.13 -> Al <= -0.09 (0.0328)
Removida: Cr <= 0.28 -> Al <= -0.09 (0.0137) | Mantida: Al <= -0.09 -> Cr <= 0.28 (0.0229)
Removida: Cr <= 0.28 -> Ti kb > -0.63 (0.0151) | Mantida: Ti kb > -0.63 -> Cr <= 0.28 (0.0225)
Removida: Cr <= 0.28 -> Al > -0.09 (0.0348) | Mantida: Al > -0.09 -> Cr <= 0.28 (0.0448)
Removida: Al > -0.09 -> Mn <= -0.38 (0.0183) | Mantida: Mn <= -0.38 -> Al > -0.09 (0.0239)
Removida: P > -0.17 -> Al > -0.09 (0.0146) | Mantida: Al > -0.09 -> P > -0.17 (0.0208)
Removida: Cr > 0.04 -> K <= 0.39 (0.0130) | Mantida: K <= 0.39 -> Cr > 0.04 (0.0178)
Removida: sum Fe > -0.04 -> K <= 0.39 (0.0120) | Mantida: K <= 0.39 -> sum Fe > -0.04 (0.0184)
Removida: K <= 0.39 -> Ca kb <= 0.29 (0.0125) | Mantida: Ca kb <= 0.29 -> K <= 0.39 (0.0168)
Removida: background2 <= 0.25 -> Cr > -0.12 (0.0062) | Mantida: Cr > -0.12 -> background2 <= 0.25 (0.0107)
Removida: background2 <= 0.12 -> background2 <= 0.25 (0.0060) | Mantida: background2 <= 0.25 -> background2 <= 0.12 (0.0076)
Removida: background2 <= 0.25 -> Cr <= 0.04 (0.0059) | Mantida: Cr <= 0.04 -> background2 <= 0.25 (0.0138)
Removida: Cr > -0.12 -> Ca kb <= 0.29 (0.0118) | Mantida: Ca kb <= 0.29 -> Cr > -0.12 (0.0151)
Removida: background2 <= 0.12 -> Ca kb <= 0.29 (0.0048) | Mantida: Ca kb <= 0.29 -> background2 <= 0.12 (0.0137)
Removida: Cr <= 0.04 -> Fe kb <= 0.95 (0.0136) | Mantida: Fe kb <= 0.95 -> Cr <= 0.04 (0.0148)
Removida: S > -0.06 -> Cr <= 0.04 (0.0149) | Mantida: Cr <= 0.04 -> S > -0.06 (0.0216)
Removida: Cr > -0.12 -> Si <= 0.69 (0.0123) | Mantida: Si <= 0.69 -> Cr > -0.12 (0.0203)
Removida: sum Fe > -0.04 -> Cr > 0.04 (0.0111) | Mantida: Cr > 0.04 -> sum Fe > -0.04 (0.0113)
Removida: sum Fe > -0.04 -> Ti ka <= 0.93 (0.0105) | Mantida: Ti ka <= 0.93 -> sum Fe > -0.04 (0.0186)
Removida: background2 > 0.12 -> P <= 0.28 (0.0033) | Mantida: P <= 0.28 -> background2 > 0.12 (0.0067)
Removida: S > -0.13 -> Rh L + Ar <= -0.05 (0.0069) | Mantida: Rh L + Ar <= -0.05 -> S > -0.13 (0.0147)
Removida: Rh L + Ar <= -0.05 -> sum Fe > 0.13 (0.0079) | Mantida: sum Fe > 0.13 -> Rh L + Ar <= -0.05 (0.0202)
Removida: background2 > -0.06 -> background1 <= 0.16 (0.0038) | Mantida: background1 <= 0.16 -> background2 > -0.06 (0.0043)
Removida: S > 0.03 -> background2 > -0.06 (0.0043) | Mantida: background2 > -0.06 -> S > 0.03 (0.0049)
Removida: background3 <= 0.18 -> sum Fe <= -0.04 (0.0030) | Mantida: sum Fe <= -0.04 -> background3 <= 0.18 (0.0083)
Removida: S > 0.03 -> sum Fe <= -0.04 (0.0061) | Mantida: sum Fe <= -0.04 -> S > 0.03 (0.0173)
Removida: sum Fe <= -0.04 -> background1 <= -0.03 (0.0081) | Mantida: background1 <= -0.03 -> sum Fe <= -0.04 (0.0091)
Removida: background3 <= 0.18 -> background1 <= 0.05 (0.0023) | Mantida: background1 <= 0.05 -> background3 <= 0.18 (0.0044)
Removida: background3 <= 0.18 -> sum Fe > 0.13 (0.0022) | Mantida: sum Fe > 0.13 -> background3 <= 0.18 (0.0092)
Removida: S > 0.03 -> background1 <= 0.05 (0.0051) | Mantida: background1 <= 0.05 -> S > 0.03 (0.0092)
Removida: background1 <= 0.05 -> sum Fe > 0.13 (0.0083) | Mantida: sum Fe > 0.13 -> background1 <= 0.05 (0.0156)
Removida: background1 <= 0.05 -> background1 <= 0.16 (0.0043) | Mantida: background1 <= 0.16 -> background1 <= 0.05 (0.0045)
Removida: background1 <= 0.05 -> P <= 0.28 (0.0035) | Mantida: P <= 0.28 -> background1 <= 0.05 (0.0083)
Removida: Rh L + Ar <= 0.09 -> P <= 0.28 (0.0053) | Mantida: P <= 0.28 -> Rh L + Ar <= 0.09 (0.0081)
Removida: Rh L + Ar <= 0.23 -> Rh L + Ar <= 0.09 (0.0045) | Mantida: Rh L + Ar <= 0.09 -> Rh L + Ar <= 0.23 (0.0048)
Removida: background2 <= -0.06 -> background1 <= 0.16 (0.0047) | Mantida: background1 <= 0.16 -> background2 <= -0.06 (0.0084)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 648 | Removidas: 86
Nós predicados: 90
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 79
Removida: Fe ka > 0.86 -> Ca ka > -1.02 (0.1654) | Mantida: Ca ka > -1.02 -> Fe ka > 0.86 (2.1457)
Removida: Ca ka > -0.36 -> Fe ka > 0.86 (0.4897) | Mantida: Fe ka > 0.86 -> Ca ka > -0.36 (0.6196)
Removida: Fe ka > -0.43 -> Ca ka > -0.36 (0.1079) | Mantida: Ca ka > -0.36 -> Fe ka > -0.43 (1.0359)
Removida: Ca ka > -0.36 -> Ti ka > 0.93 (0.1603) | Mantida: Ti ka > 0.93 -> Ca ka > -0.36 (0.1677)
Removida: Ca ka <= 1.21 -> Fe ka > -0.43 (0.1448) | Mantida: Fe ka > -0.43 -> Ca ka <= 1.21 (0.2743)
Removida: Fe ka > -2.66 -> Fe ka > -0.43 (0.1085) | Mantida: Fe ka > -0.43 -> Fe ka > -2.66 (0.4128)
Removida: Ti ka > 0.93 -> Ca ka <= 1.21 (0.2964) | Mantida: Ca ka <= 1.21 -> Ti ka > 0.93 (0.5686)
Removida: Fe ka > -2.66 -> Ti ka > -1.78 (0.1308) | Mantida: Ti ka > -1.78 -> Fe ka > -2.66 (0.2281)
Removida: Ca kb > -0.37 -> Mn > -0.65 (0.0687) | Mantida: Mn > -0.65 -> Ca kb > -0.37 (0.1745)
Removida: Ca kb > -0.23 -> Mn > -0.65 (0.0540) | Mantida: Mn > -0.65 -> Ca kb > -0.23 (0.0827)
Removida: Fe kb > 0.40 -> Mn > -0.65 (0.0466) | Mantida: Mn > -0.65 -> Fe kb > 0.40 (0.0863)
Removida: Ti ka > -0.57 -> Mn > -0.65 (0.1093) | Mantida: Mn > -0.65 -> Ti ka > -0.57 (0.2767)
Removida: Fe kb > 0.40 -> Ca kb > -0.23 (0.0501) | Mantida: Ca kb > -0.23 -> Fe kb > 0.40 (0.0714)
Removida: Fe ka <= 2.21 -> Mn > -0.38 (0.0356) | Mantida: Mn > -0.38 -> Fe ka <= 2.21 (0.0530)
Removida: Ti ka > -0.57 -> Si > -0.20 (0.0437) | Mantida: Si > -0.20 -> Ti ka > -0.57 (0.0448)
Removida: Si > -0.66 -> Al <= 0.37 (0.0659) | Mantida: Al <= 0.37 -> Si > -0.66 (0.0899)
Removida: Fe kb > -0.07 -> Si > -0.66 (0.0353) | Mantida: Si > -0.66 -> Fe kb > -0.07 (0.0642)
Removida: K > -0.38 -> Si > 0.13 (0.0581) | Mantida: Si > 0.13 -> K > -0.38 (0.0647)
Removida: Fe kb > 0.40 -> Mn > -0.38 (0.0467) | Mantida: Mn > -0.38 -> Fe kb > 0.40 (0.0828)
Removida: Fe ka <= 0.86 -> Ti ka > -1.78 (0.0845) | Mantida: Ti ka > -1.78 -> Fe ka <= 0.86 (0.2822)
Removida: Fe kb > -0.07 -> K > -0.38 (0.0389) | Mantida: K > -0.38 -> Fe kb > -0.07 (0.0557)
Removida: K > -0.38 -> Mn > -0.38 (0.0508) | Mantida: Mn > -0.38 -> K > -0.38 (0.0681)
Removida: Fe ka <= -0.43 -> K > -0.38 (0.0414) | Mantida: K > -0.38 -> Fe ka <= -0.43 (0.0594)
Removida: Fe kb > -0.07 -> K > -0.20 (0.0371) | Mantida: K > -0.20 -> Fe kb > -0.07 (0.1496)
Removida: K > -0.20 -> Si > -0.20 (0.0494) | Mantida: Si > -0.20 -> K > -0.20 (0.0553)
Removida: Ca kb > -0.04 -> Si > -0.20 (0.0374) | Mantida: Si > -0.20 -> Ca kb > -0.04 (0.0546)
Removida: Al <= 0.37 -> Si > -0.20 (0.0957) | Mantida: Si > -0.20 -> Al <= 0.37 (0.1131)
Removida: Mn > -0.38 -> Ca kb > -0.04 (0.0380) | Mantida: Ca kb > -0.04 -> Mn > -0.38 (0.0446)
Removida: sum Fe <= 0.31 -> Ca kb > -0.04 (0.0222) | Mantida: Ca kb > -0.04 -> sum Fe <= 0.31 (0.0294)
Removida: K > 0.02 -> Al <= 0.37 (0.0474) | Mantida: Al <= 0.37 -> K > 0.02 (0.0494)
Removida: K > 0.02 -> Ca ka <= -0.36 (0.0342) | Mantida: Ca ka <= -0.36 -> K > 0.02 (0.0511)
Removida: Fe kb > -1.03 -> Ca ka <= -0.36 (0.0233) | Mantida: Ca ka <= -0.36 -> Fe kb > -1.03 (0.0573)
Removida: K > 0.02 -> Al > -0.33 (0.0382) | Mantida: Al > -0.33 -> K > 0.02 (0.0691)
Removida: sum Fe <= 0.31 -> K > 0.02 (0.0227) | Mantida: K > 0.02 -> sum Fe <= 0.31 (0.0393)
Removida: K > 0.02 -> Fe kb > -1.03 (0.0374) | Mantida: Fe kb > -1.03 -> K > 0.02 (0.0575)
Removida: sum Fe <= 0.31 -> Al > -0.33 (0.0924) | Mantida: Al > -0.33 -> sum Fe <= 0.31 (0.0991)
Removida: sum Fe <= 0.31 -> Fe kb > -1.03 (0.0228) | Mantida: Fe kb > -1.03 -> sum Fe <= 0.31 (0.0471)
Removida: Ti kb <= 0.72 -> Ti kb > 0.26 (0.0303) | Mantida: Ti kb > 0.26 -> Ti kb <= 0.72 (0.0309)
Removida: sum Fe > -0.31 -> Al <= -0.09 (0.0190) | Mantida: Al <= -0.09 -> sum Fe > -0.31 (0.0296)
Removida: Mn <= 0.64 -> Mn > -0.15 (0.0294) | Mantida: Mn > -0.15 -> Mn <= 0.64 (0.0332)
Removida: Cr > -0.28 -> P > -0.17 (0.0156) | Mantida: P > -0.17 -> Cr > -0.28 (0.0199)
Removida: P > -0.17 -> Fe kb <= -0.07 (0.0180) | Mantida: Fe kb <= -0.07 -> P > -0.17 (0.0189)
Removida: Cr <= 0.28 -> Cr > -0.28 (0.0165) | Mantida: Cr > -0.28 -> Cr <= 0.28 (0.0182)
Removida: Fe kb <= -0.07 -> Al > -0.09 (0.0170) | Mantida: Al > -0.09 -> Fe kb <= -0.07 (0.0233)
Removida: background2 <= 0.12 -> Al > -0.09 (0.0078) | Mantida: Al > -0.09 -> background2 <= 0.12 (0.0202)
Removida: Al > -0.09 -> sum Fe <= 0.13 (0.0221) | Mantida: sum Fe <= 0.13 -> Al > -0.09 (0.0311)
Removida: Al > -0.09 -> Ti kb > -0.63 (0.0244) | Mantida: Ti kb > -0.63 -> Al > -0.09 (0.0245)
Removida: Cr <= 0.28 -> sum Fe <= 0.13 (0.0331) | Mantida: sum Fe <= 0.13 -> Cr <= 0.28 (0.0338)
Removida: sum Fe <= 0.13 -> Fe kb <= 0.95 (0.0162) | Mantida: Fe kb <= 0.95 -> sum Fe <= 0.13 (0.0374)
Removida: Al <= -0.09 -> Ti kb > -0.16 (0.0210) | Mantida: Ti kb > -0.16 -> Al <= -0.09 (0.0254)
Removida: background2 <= 0.25 -> Cr <= 0.04 (0.0058) | Mantida: Cr <= 0.04 -> background2 <= 0.25 (0.0265)
Removida: Cr <= 0.04 -> Ca kb <= 0.29 (0.0111) | Mantida: Ca kb <= 0.29 -> Cr <= 0.04 (0.0163)
Removida: background2 <= 0.25 -> Ti kb <= 0.72 (0.0057) | Mantida: Ti kb <= 0.72 -> background2 <= 0.25 (0.0197)
Removida: background2 <= 0.25 -> sum Fe > -0.04 (0.0063) | Mantida: sum Fe > -0.04 -> background2 <= 0.25 (0.0129)
Removida: Ti kb <= 0.72 -> Ti ka <= 1.88 (0.0110) | Mantida: Ti ka <= 1.88 -> Ti kb <= 0.72 (0.0117)
Removida: Rh L + Ar <= -0.05 -> Ti kb <= 0.72 (0.0078) | Mantida: Ti kb <= 0.72 -> Rh L + Ar <= -0.05 (0.0168)
Removida: Ca kb <= 0.29 -> Mn <= -0.38 (0.0171) | Mantida: Mn <= -0.38 -> Ca kb <= 0.29 (0.0188)
Removida: K <= 0.39 -> Mn <= -0.38 (0.0138) | Mantida: Mn <= -0.38 -> K <= 0.39 (0.0382)
Removida: Cr > 0.04 -> Ca kb <= 0.29 (0.0122) | Mantida: Ca kb <= 0.29 -> Cr > 0.04 (0.0149)
Removida: Rh L + Ar <= -0.05 -> Ca kb <= 0.29 (0.0084) | Mantida: Ca kb <= 0.29 -> Rh L + Ar <= -0.05 (0.0138)
Removida: sum Fe > -0.04 -> Cr > 0.04 (0.0127) | Mantida: Cr > 0.04 -> sum Fe > -0.04 (0.0362)
Removida: Rh L + Ar <= -0.05 -> sum Fe > -0.04 (0.0082) | Mantida: sum Fe > -0.04 -> Rh L + Ar <= -0.05 (0.0114)
Removida: S > 0.03 -> S > -0.06 (0.0063) | Mantida: S > -0.06 -> S > 0.03 (0.0064)
Removida: Cr > -0.12 -> sum Fe > -0.04 (0.0096) | Mantida: sum Fe > -0.04 -> Cr > -0.12 (0.0249)
Removida: sum Fe <= -0.04 -> K <= 0.39 (0.0113) | Mantida: K <= 0.39 -> sum Fe <= -0.04 (0.0131)
Removida: S > -0.13 -> S > 0.03 (0.0062) | Mantida: S > 0.03 -> S > -0.13 (0.0172)
Removida: S > 0.03 -> Ti kb > -0.63 (0.0064) | Mantida: Ti kb > -0.63 -> S > 0.03 (0.0136)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ca ka > -1.73,Ca ka > -1.73,Ca ka > -1.73,Ca ka > -1.73
1,Ca ka > -1.02,Ca ka > -1.02,Ca ka > -1.02,Ca ka > -1.02
2,Fe ka > 0.86,Ca ka > -0.36,Fe ka > 0.86,Fe ka > 0.86
3,Ca ka > -0.36,Fe ka > 0.86,Fe ka > -0.43,Ca ka > -0.36
4,Fe ka > -2.66,Fe ka > -0.43,Fe ka > -2.66,Ca ka <= 1.21
...,...,...,...,...
90,Class_A,Class_B,P <= 0.28,background2 > -0.06
91,Class_B,NaN,Si <= -0.66,Fe ka + Ti ka > -0.15
92,NaN,NaN,Fe ka + Ti ka > -0.15,Class_A
93,NaN,NaN,Class_A,Class_B
94,NaN,NaN,Class_B,NaN

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -1.73,19.005937,Ca ka,-1.73,>
1,Fe ka > 0.86,5.611314,Fe ka,0.86,>
2,Ti ka > 0.93,2.385289,Ti ka,0.93,>
3,Ca kb > -0.37,2.126591,Ca kb,-0.37,>
4,Mn > -0.65,1.635937,Mn,-0.65,>
5,K > -0.38,1.516626,K,-0.38,>
6,Fe kb > 0.40,1.490815,Fe kb,0.40,>
7,Si > -0.66,1.465682,Si,-0.66,>
8,Al <= 0.37,1.379312,Al,0.37,<=
9,sum Fe <= 0.31,0.901311,sum Fe,0.31,<=
10,Ti kb > 0.26,0.875212,Ti kb,0.26,>
11,Fe ka + Ti ka <= 0.16,0.792347,Fe ka + Ti ka,0.16,<=
12,P > -0.24,0.761268,P,-0.24,>
13,Cr <= 0.28,0.671774,Cr,0.28,<=
14,background2 <= 0.12,0.639695,background2,0.12,<=
15,S > -0.13,0.626022,S,-0.13,>
16,background1 <= 0.05,0.564276,background1,0.05,<=
17,Rh L + Ar <= 0.23,0.553065,Rh L + Ar,0.23,<=
18,background3 <= 0.18,0.506977,background3,0.18,<=
19,Cu > 0.06,0.461123,Cu,0.06,>
20,Class_A,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Al': VE = 89.82%, dim = 15 variáveis
Zona 'Si': VE = 95.22%, dim = 12 variáveis
Zona 'P': VE = 61.00%, dim = 17 variáveis
Zona 'S': VE = 42.01%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 51.54%, dim = 33 variáveis
Zona 'K': VE = 88.55%, dim = 16 variáveis
Zona 'Ca ka': VE = 99.40%, dim = 16 variáveis
Zona 'Ca kb': VE = 72.71%, dim = 27 variáveis
Zona 'Ti ka': VE = 93.59%, dim = 19 variáveis
Zona 'Ti kb': VE = 88.32%, dim = 19 variáveis
Zona 'Cr': VE = 56.23%, dim = 33 variáveis
Zona 'Mn': VE = 93.26%, dim = 18 variáveis
Zona 'Fe ka': VE = 58.12%, dim = 34 variáveis
Zona 'Fe kb': VE = 55.52%, dim = 26 variáveis
Zona 'background1': VE = 34.82%, dim = 31 variáveis
Zona 'Cu': VE = 55.93%, dim = 15 variáveis
Zona 'background2': VE = 26.61%, dim = 125 variáveis
Zona 'Fe ka + Ti ka': VE = 39.81%, dim = 23 variáveis
Zona 'background3': VE = 19.45%, dim = 71 variáveis
Zona 'sum Fe': VE = 69.07%, dim = 28 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -1.73,19.005937,Ca ka,-1.73,>,-2.806273,140.0,0.001954,Ca ka > -2.806273
1,Ca ka > -1.02,10.098925,Ca ka,-1.02,>,-1.635267,143.0,0.000757,Ca ka > -1.635267
2,Fe ka > 0.86,5.611314,Fe ka,0.86,>,55.595005,114.0,0.001174,Fe ka > 55.595005
3,Ca ka > -0.36,3.825583,Ca ka,-0.36,>,-0.641296,49.0,0.004141,Ca ka > -0.641296
4,Fe ka > -0.43,3.343724,Fe ka,-0.43,>,-54.402608,14.0,0.002481,Fe ka > -54.402608
...,...,...,...,...,...,...,...,...,...
94,background3 <= 0.04,0.367233,background3,0.04,<=,0.036170,57.0,0.000169,background3 <= 0.036170
95,Mn <= -0.15,0.308549,Mn,-0.15,<=,-0.357226,56.0,0.003096,Mn <= -0.357226
96,Fe ka + Ti ka > -0.15,0.128245,Fe ka + Ti ka,-0.15,>,-0.137035,129.0,0.007042,Fe ka + Ti ka > -0.137035
97,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
98,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ca ka':
  - Dimensão: 16 variáveis espectrais
  - Range de energias: 3.54 - 3.84
  - Variância explicada pela PC1: 99.40%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=mlp_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 123 | Descartados: 37
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 122 | Descartados: 38
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 123 predicados...
  Predicado: Al > -0.33 (n=93)
    Zona: 15 colunas
    Importance: 0.009087
  Predicado: Al <= -0.09 (n=49)
    Zona: 15 colunas
    Importance: 0.012581
  Predicado: Al > -0.09 (n=69)
    Zona: 15 colunas
    Importance: 0.009107
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.009354
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.012355
  Predicado: Al <= 0.37 (n=96)
    Zona: 15 colunas
    Importance: 0.009150
  Predicado: Si > -0.66 (n=94)
    Zona: 12 colunas
    Importance: 0.006920
  Predicado: Si <= -0.20 (n=44)
    Zona: 12 colunas
    Importance: 0.009988
  Predicado: Si > -0.20 (n=74)
    Zona: 12 colunas
    Importance: 0.007583
  Predicado: Si <= 0.13 (n=66)
    Zona: 12 colunas
    Importance: 0.007353
  Predicado: Si > 0.13 (n=52)
    Zona: 12 colunas
    Importance: 0.009910
  Predicado: Si <= 0.69 (n=94)
    Zona: 12 colunas
    Importance: 0.006945
  Predicado: P <= -0.24 (n=29)
    Zona: 17 colunas
    Importance: 0.007853
  Predicado: P > -0.24 (n=89)
    Zona: 17 colunas
    Importance: 0.007419
  Predicado: P <= -0.17 (n=52)
    Zona: 17 colunas
    Importance: 0.005944
  Predicado: P > -0.17 (n=66)
    Zona: 17 colunas
    Importance: 0.008772
  Predicado: P <= 0.01 (n=71)
    Zona: 17 colunas
    Importance: 0.005149
  Predicado: P > 0.01 (n=47)
    Zona: 17 colunas
    Importance: 0.011116
  Predicado: P <= 0.28 (n=94)
    Zona: 17 colunas
    Importance: 0.005351
  Predicado: S <= -0.13 (n=29)
    Zona: 18 colunas
    Importance: 0.003158
  Predicado: S > -0.13 (n=89)
    Zona: 18 colunas
    Importance: 0.002685
  Predicado: S <= -0.06 (n=51)
    Zona: 18 colunas
    Importance: 0.003237
  Predicado: S > -0.06 (n=67)
    Zona: 18 colunas
    Importance: 0.002470
  Predicado: S <= 0.03 (n=73)
    Zona: 18 colunas
    Importance: 0.003020
  Predicado: S > 0.03 (n=45)
    Zona: 18 colunas
    Importance: 0.002448
  Predicado: S <= 0.12 (n=93)
    Zona: 18 colunas
    Importance: 0.002707
  Predicado: Rh L + Ar > -0.25 (n=95)
    Zona: 33 colunas
    Importance: 0.003732
  Predicado: Rh L + Ar <= -0.05 (n=45)
    Zona: 33 colunas
    Importance: 0.004514
  Predicado: Rh L + Ar > -0.05 (n=73)
    Zona: 33 colunas
    Importance: 0.003798
  Predicado: Rh L + Ar <= 0.09 (n=73)
    Zona: 33 colunas
    Importance: 0.004076
  Predicado: Rh L + Ar > 0.09 (n=45)
    Zona: 33 colunas
    Importance: 0.004063
  Predicado: Rh L + Ar <= 0.23 (n=96)
    Zona: 33 colunas
    Importance: 0.003870
  Predicado: K > -0.38 (n=94)
    Zona: 16 colunas
    Importance: 0.014742
  Predicado: K <= -0.20 (n=50)
    Zona: 16 colunas
    Importance: 0.016751
  Predicado: K > -0.20 (n=68)
    Zona: 16 colunas
    Importance: 0.016370
  Predicado: K <= 0.02 (n=72)
    Zona: 16 colunas
    Importance: 0.013057
  Predicado: K > 0.02 (n=46)
    Zona: 16 colunas
    Importance: 0.021970
  Predicado: K <= 0.39 (n=96)
    Zona: 16 colunas
    Importance: 0.013065
  Predicado: Ca ka > -1.73 (n=94)
    Zona: 16 colunas
    Importance: 0.064499
  Predicado: Ca ka <= -1.02 (n=49)
    Zona: 16 colunas
    Importance: 0.049806
  Predicado: Ca ka > -1.02 (n=69)
    Zona: 16 colunas
    Importance: 0.075472
  Predicado: Ca ka <= -0.36 (n=69)
    Zona: 16 colunas
    Importance: 0.037836
  Predicado: Ca ka > -0.36 (n=49)
    Zona: 16 colunas
    Importance: 0.102804
  Predicado: Ca ka <= 1.21 (n=92)
    Zona: 16 colunas
    Importance: 0.043363
  Predicado: Ca kb > -0.37 (n=93)
    Zona: 27 colunas
    Importance: 0.009664
  Predicado: Ca kb <= -0.23 (n=48)
    Zona: 27 colunas
    Importance: 0.011499
  Predicado: Ca kb > -0.23 (n=70)
    Zona: 27 colunas
    Importance: 0.010553
  Predicado: Ca kb <= -0.04 (n=71)
    Zona: 27 colunas
    Importance: 0.008706
  Predicado: Ca kb > -0.04 (n=47)
    Zona: 27 colunas
    Importance: 0.014309
  Predicado: Ca kb <= 0.29 (n=92)
    Zona: 27 colunas
    Importance: 0.009052
  Predicado: Ti ka > -1.78 (n=94)
    Zona: 19 colunas
    Importance: 0.029982
  Predicado: Ti ka <= -0.57 (n=52)
    Zona: 19 colunas
    Importance: 0.048231
  Predicado: Ti ka > -0.57 (n=66)
    Zona: 19 colunas
    Importance: 0.032734
  Predicado: Ti ka <= 0.93 (n=74)
    Zona: 19 colunas
    Importance: 0.035893
  Predicado: Ti ka > 0.93 (n=44)
    Zona: 19 colunas
    Importance: 0.045736
  Predicado: Ti ka <= 1.88 (n=97)
    Zona: 19 colunas
    Importance: 0.033981
  Predicado: Ti kb > -0.63 (n=94)
    Zona: 19 colunas
    Importance: 0.009305
  Predicado: Ti kb <= -0.16 (n=53)
    Zona: 19 colunas
    Importance: 0.015986
  Predicado: Ti kb > -0.16 (n=65)
    Zona: 19 colunas
    Importance: 0.009440
  Predicado: Ti kb <= 0.26 (n=76)
    Zona: 19 colunas
    Importance: 0.012467
  Predicado: Ti kb > 0.26 (n=42)
    Zona: 19 colunas
    Importance: 0.012223
  Predicado: Ti kb <= 0.72 (n=97)
    Zona: 19 colunas
    Importance: 0.011801
  Predicado: Cr > -0.28 (n=92)
    Zona: 33 colunas
    Importance: 0.007428
  Predicado: Cr <= -0.12 (n=48)
    Zona: 33 colunas
    Importance: 0.008485
  Predicado: Cr > -0.12 (n=70)
    Zona: 33 colunas
    Importance: 0.008285
  Predicado: Cr <= 0.04 (n=73)
    Zona: 33 colunas
    Importance: 0.007077
  Predicado: Cr > 0.04 (n=45)
    Zona: 33 colunas
    Importance: 0.010458
  Predicado: Cr <= 0.28 (n=94)
    Zona: 33 colunas
    Importance: 0.006655
  Predicado: Mn > -0.65 (n=99)
    Zona: 18 colunas
    Importance: 0.026263
  Predicado: Mn <= -0.38 (n=45)
    Zona: 18 colunas
    Importance: 0.023148
  Predicado: Mn > -0.38 (n=73)
    Zona: 18 colunas
    Importance: 0.031395
  Predicado: Mn <= -0.15 (n=68)
    Zona: 18 colunas
    Importance: 0.017194
  Predicado: Mn > -0.15 (n=50)
    Zona: 18 colunas
    Importance: 0.043287
  Predicado: Mn <= 0.64 (n=94)
    Zona: 18 colunas
    Importance: 0.017534
  Predicado: Fe ka > -2.66 (n=92)
    Zona: 34 colunas
    Importance: 0.068703
  Predicado: Fe ka <= -0.43 (n=50)
    Zona: 34 colunas
    Importance: 0.076068
  Predicado: Fe ka > -0.43 (n=68)
    Zona: 34 colunas
    Importance: 0.068028
  Predicado: Fe ka <= 0.86 (n=73)
    Zona: 34 colunas
    Importance: 0.068498
  Predicado: Fe ka > 0.86 (n=45)
    Zona: 34 colunas
    Importance: 0.076198
  Predicado: Fe ka <= 2.21 (n=91)
    Zona: 34 colunas
    Importance: 0.068369
  Predicado: Fe kb > -1.03 (n=92)
    Zona: 26 colunas
    Importance: 0.017450
  Predicado: Fe kb <= -0.07 (n=49)
    Zona: 26 colunas
    Importance: 0.017748
  Predicado: Fe kb > -0.07 (n=69)
    Zona: 26 colunas
    Importance: 0.017541
  Predicado: Fe kb <= 0.40 (n=75)
    Zona: 26 colunas
    Importance: 0.016580
  Predicado: Fe kb > 0.40 (n=43)
    Zona: 26 colunas
    Importance: 0.019454
  Predicado: Fe kb <= 0.95 (n=91)
    Zona: 26 colunas
    Importance: 0.016628
  Predicado: background1 <= -0.16 (n=29)
    Zona: 31 colunas
    Importance: 0.002851
  Predicado: background1 > -0.16 (n=89)
    Zona: 31 colunas
    Importance: 0.002759
  Predicado: background1 <= -0.03 (n=47)
    Zona: 31 colunas
    Importance: 0.002750
  Predicado: background1 > -0.03 (n=71)
    Zona: 31 colunas
    Importance: 0.002802
  Predicado: background1 <= 0.05 (n=70)
    Zona: 31 colunas
    Importance: 0.002653
  Predicado: background1 > 0.05 (n=48)
    Zona: 31 colunas
    Importance: 0.002969
  Predicado: background1 <= 0.16 (n=95)
    Zona: 31 colunas
    Importance: 0.002748
  Predicado: Cu > -0.18 (n=93)
    Zona: 15 colunas
    Importance: 0.005378
  Predicado: Cu <= -0.06 (n=46)
    Zona: 15 colunas
    Importance: 0.006884
  Predicado: Cu > -0.06 (n=72)
    Zona: 15 colunas
    Importance: 0.005900
  Predicado: Cu <= 0.06 (n=68)
    Zona: 15 colunas
    Importance: 0.005424
  Predicado: Cu > 0.06 (n=50)
    Zona: 15 colunas
    Importance: 0.007451
  Predicado: Cu <= 0.15 (n=91)
    Zona: 15 colunas
    Importance: 0.004897
  Predicado: background2 > -0.29 (n=91)
    Zona: 125 colunas
    Importance: 0.008078
  Predicado: background2 <= -0.06 (n=47)
    Zona: 125 colunas
    Importance: 0.009246
  Predicado: background2 > -0.06 (n=71)
    Zona: 125 colunas
    Importance: 0.008804
  Predicado: background2 <= 0.12 (n=71)
    Zona: 125 colunas
    Importance: 0.009438
  Predicado: background2 > 0.12 (n=47)
    Zona: 125 colunas
    Importance: 0.008289
  Predicado: background2 <= 0.25 (n=95)
    Zona: 125 colunas
    Importance: 0.009252
  Predicado: Fe ka + Ti ka > -0.15 (n=94)
    Zona: 23 colunas
    Importance: 0.002762
  Predicado: Fe ka + Ti ka <= -0.04 (n=48)
    Zona: 23 colunas
    Importance: 0.003197
  Predicado: Fe ka + Ti ka > -0.04 (n=70)
    Zona: 23 colunas
    Importance: 0.002951
  Predicado: Fe ka + Ti ka <= 0.06 (n=70)
    Zona: 23 colunas
    Importance: 0.003136
  Predicado: Fe ka + Ti ka > 0.06 (n=48)
    Zona: 23 colunas
    Importance: 0.002928
  Predicado: Fe ka + Ti ka <= 0.16 (n=98)
    Zona: 23 colunas
    Importance: 0.003101
  Predicado: background3 > -0.17 (n=91)
    Zona: 71 colunas
    Importance: 0.007232
  Predicado: background3 <= -0.04 (n=50)
    Zona: 71 colunas
    Importance: 0.009613
  Predicado: background3 > -0.04 (n=68)
    Zona: 71 colunas
    Importance: 0.008171
  Predicado: background3 <= 0.04 (n=70)
    Zona: 71 colunas
    Importance: 0.008286
  Predicado: background3 > 0.04 (n=48)
    Zona: 71 colunas
    Importance: 0.009506
  Predicado: background3 <= 0.18 (n=96)
    Zona: 71 colunas
    Importance: 0.007979
  Predicado: sum Fe > -0.31 (n=94)
    Zona: 28 colunas
    Importance: 0.009372
  Predicado: sum Fe <= -0.04 (n=48)
    Zona: 28 colunas
    Importance: 0.014855
  Predicado: sum Fe > -0.04 (n=70)
    Zona: 28 colunas
    Importance: 0.008987
  Predicado: sum Fe <= 0.13 (n=74)
    Zona: 28 colunas
    Importance: 0.011201
  Predicado: sum Fe > 0.13 (n=44)
    Zona: 28 colunas
    Importance: 0.011664
  Predicado: sum Fe <= 0.31 (n=97)
    Zona: 28 colunas
    Importance: 0.010799

[Bag_2] Processando 120 predicados...
  Predicado: Al > -0.33 (n=95)
    Zona: 15 colunas
    Importance: 0.009851
  Predicado: Al <= -0.09 (n=49)
    Zona: 15 colunas
    Importance: 0.011985
  Predicado: Al > -0.09 (n=69)
    Zona: 15 colunas
    Importance: 0.009999
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.008914
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.013709
  Predicado: Al <= 0.37 (n=93)
    Zona: 15 colunas
    Importance: 0.008922
  Predicado: Si > -0.66 (n=96)
    Zona: 12 colunas
    Importance: 0.007146
  Predicado: Si <= -0.20 (n=48)
    Zona: 12 colunas
    Importance: 0.008891
  Predicado: Si > -0.20 (n=70)
    Zona: 12 colunas
    Importance: 0.007992
  Predicado: Si <= 0.13 (n=73)
    Zona: 12 colunas
    Importance: 0.006638
  Predicado: Si > 0.13 (n=45)
    Zona: 12 colunas
    Importance: 0.011148
  Predicado: Si <= 0.69 (n=93)
    Zona: 12 colunas
    Importance: 0.006326
  Predicado: P > -0.24 (n=95)
    Zona: 17 colunas
    Importance: 0.007364
  Predicado: P <= -0.17 (n=45)
    Zona: 17 colunas
    Importance: 0.006307
  Predicado: P > -0.17 (n=73)
    Zona: 17 colunas
    Importance: 0.008344
  Predicado: P <= 0.01 (n=72)
    Zona: 17 colunas
    Importance: 0.005337
  Predicado: P > 0.01 (n=46)
    Zona: 17 colunas
    Importance: 0.011058
  Predicado: P <= 0.28 (n=91)
    Zona: 17 colunas
    Importance: 0.005326
  Predicado: S > -0.13 (n=91)
    Zona: 18 colunas
    Importance: 0.002777
  Predicado: S <= -0.06 (n=50)
    Zona: 18 colunas
    Importance: 0.003274
  Predicado: S > -0.06 (n=68)
    Zona: 18 colunas
    Importance: 0.002487
  Predicado: S <= 0.03 (n=73)
    Zona: 18 colunas
    Importance: 0.003105
  Predicado: S > 0.03 (n=45)
    Zona: 18 colunas
    Importance: 0.002360
  Predicado: S <= 0.12 (n=91)
    Zona: 18 colunas
    Importance: 0.002865
  Predicado: Rh L + Ar > -0.25 (n=97)
    Zona: 33 colunas
    Importance: 0.003551
  Predicado: Rh L + Ar <= -0.05 (n=42)
    Zona: 33 colunas
    Importance: 0.004103
  Predicado: Rh L + Ar > -0.05 (n=76)
    Zona: 33 colunas
    Importance: 0.003709
  Predicado: Rh L + Ar <= 0.09 (n=68)
    Zona: 33 colunas
    Importance: 0.003701
  Predicado: Rh L + Ar > 0.09 (n=50)
    Zona: 33 colunas
    Importance: 0.004050
  Predicado: Rh L + Ar <= 0.23 (n=93)
    Zona: 33 colunas
    Importance: 0.003535
  Predicado: K > -0.38 (n=94)
    Zona: 16 colunas
    Importance: 0.015532
  Predicado: K <= -0.20 (n=45)
    Zona: 16 colunas
    Importance: 0.017452
  Predicado: K > -0.20 (n=73)
    Zona: 16 colunas
    Importance: 0.017172
  Predicado: K <= 0.02 (n=69)
    Zona: 16 colunas
    Importance: 0.012990
  Predicado: K > 0.02 (n=49)
    Zona: 16 colunas
    Importance: 0.023319
  Predicado: K <= 0.39 (n=93)
    Zona: 16 colunas
    Importance: 0.013074
  Predicado: Ca ka > -1.73 (n=92)
    Zona: 16 colunas
    Importance: 0.066310
  Predicado: Ca ka <= -1.02 (n=48)
    Zona: 16 colunas
    Importance: 0.051204
  Predicado: Ca ka > -1.02 (n=70)
    Zona: 16 colunas
    Importance: 0.077273
  Predicado: Ca ka <= -0.36 (n=71)
    Zona: 16 colunas
    Importance: 0.037555
  Predicado: Ca ka > -0.36 (n=47)
    Zona: 16 colunas
    Importance: 0.110649
  Predicado: Ca ka <= 1.21 (n=91)
    Zona: 16 colunas
    Importance: 0.042013
  Predicado: Ca kb > -0.37 (n=94)
    Zona: 27 colunas
    Importance: 0.010354
  Predicado: Ca kb <= -0.23 (n=48)
    Zona: 27 colunas
    Importance: 0.011721
  Predicado: Ca kb > -0.23 (n=70)
    Zona: 27 colunas
    Importance: 0.011172
  Predicado: Ca kb <= -0.04 (n=71)
    Zona: 27 colunas
    Importance: 0.008985
  Predicado: Ca kb > -0.04 (n=47)
    Zona: 27 colunas
    Importance: 0.015036
  Predicado: Ca kb <= 0.29 (n=90)
    Zona: 27 colunas
    Importance: 0.009118
  Predicado: Ti ka > -1.78 (n=99)
    Zona: 19 colunas
    Importance: 0.031533
  Predicado: Ti ka <= -0.57 (n=42)
    Zona: 19 colunas
    Importance: 0.046653
  Predicado: Ti ka > -0.57 (n=76)
    Zona: 19 colunas
    Importance: 0.033472
  Predicado: Ti ka <= 0.93 (n=67)
    Zona: 19 colunas
    Importance: 0.031673
  Predicado: Ti ka > 0.93 (n=51)
    Zona: 19 colunas
    Importance: 0.046690
  Predicado: Ti ka <= 1.88 (n=91)
    Zona: 19 colunas
    Importance: 0.030565
  Predicado: Ti kb > -0.63 (n=97)
    Zona: 19 colunas
    Importance: 0.010159
  Predicado: Ti kb <= -0.16 (n=44)
    Zona: 19 colunas
    Importance: 0.015202
  Predicado: Ti kb > -0.16 (n=74)
    Zona: 19 colunas
    Importance: 0.010325
  Predicado: Ti kb <= 0.26 (n=68)
    Zona: 19 colunas
    Importance: 0.011673
  Predicado: Ti kb > 0.26 (n=50)
    Zona: 19 colunas
    Importance: 0.012785
  Predicado: Ti kb <= 0.72 (n=92)
    Zona: 19 colunas
    Importance: 0.011156
  Predicado: Cr > -0.28 (n=94)
    Zona: 33 colunas
    Importance: 0.006791
  Predicado: Cr <= -0.12 (n=47)
    Zona: 33 colunas
    Importance: 0.009251
  Predicado: Cr > -0.12 (n=71)
    Zona: 33 colunas
    Importance: 0.007204
  Predicado: Cr <= 0.04 (n=73)
    Zona: 33 colunas
    Importance: 0.007461
  Predicado: Cr > 0.04 (n=45)
    Zona: 33 colunas
    Importance: 0.008924
  Predicado: Cr <= 0.28 (n=98)
    Zona: 33 colunas
    Importance: 0.007031
  Predicado: Mn > -0.65 (n=93)
    Zona: 18 colunas
    Importance: 0.027171
  Predicado: Mn <= -0.38 (n=47)
    Zona: 18 colunas
    Importance: 0.024772
  Predicado: Mn > -0.38 (n=71)
    Zona: 18 colunas
    Importance: 0.031698
  Predicado: Mn <= -0.15 (n=72)
    Zona: 18 colunas
    Importance: 0.017907
  Predicado: Mn > -0.15 (n=46)
    Zona: 18 colunas
    Importance: 0.046207
  Predicado: Mn <= 0.64 (n=95)
    Zona: 18 colunas
    Importance: 0.018788
  Predicado: Fe ka > -2.66 (n=93)
    Zona: 34 colunas
    Importance: 0.068083
  Predicado: Fe ka <= -0.43 (n=45)
    Zona: 34 colunas
    Importance: 0.068947
  Predicado: Fe ka > -0.43 (n=73)
    Zona: 34 colunas
    Importance: 0.069965
  Predicado: Fe ka <= 0.86 (n=68)
    Zona: 34 colunas
    Importance: 0.061946
  Predicado: Fe ka > 0.86 (n=50)
    Zona: 34 colunas
    Importance: 0.079955
  Predicado: Fe ka <= 2.21 (n=93)
    Zona: 34 colunas
    Importance: 0.066033
  Predicado: Fe kb > -1.03 (n=94)
    Zona: 26 colunas
    Importance: 0.017260
  Predicado: Fe kb <= -0.07 (n=45)
    Zona: 26 colunas
    Importance: 0.017275
  Predicado: Fe kb > -0.07 (n=73)
    Zona: 26 colunas
    Importance: 0.017434
  Predicado: Fe kb <= 0.40 (n=69)
    Zona: 26 colunas
    Importance: 0.015561
  Predicado: Fe kb > 0.40 (n=49)
    Zona: 26 colunas
    Importance: 0.019925
  Predicado: Fe kb <= 0.95 (n=93)
    Zona: 26 colunas
    Importance: 0.016469
  Predicado: background1 > -0.16 (n=91)
    Zona: 31 colunas
    Importance: 0.002976
  Predicado: background1 <= -0.03 (n=50)
    Zona: 31 colunas
    Importance: 0.002918
  Predicado: background1 > -0.03 (n=68)
    Zona: 31 colunas
    Importance: 0.003031
  Predicado: background1 <= 0.05 (n=76)
    Zona: 31 colunas
    Importance: 0.002837
  Predicado: background1 > 0.05 (n=42)
    Zona: 31 colunas
    Importance: 0.003248
  Predicado: background1 <= 0.16 (n=96)
    Zona: 31 colunas
    Importance: 0.002756
  Predicado: Cu > -0.18 (n=93)
    Zona: 15 colunas
    Importance: 0.004935
  Predicado: Cu <= -0.06 (n=49)
    Zona: 15 colunas
    Importance: 0.006763
  Predicado: Cu > -0.06 (n=69)
    Zona: 15 colunas
    Importance: 0.005688
  Predicado: Cu <= 0.06 (n=72)
    Zona: 15 colunas
    Importance: 0.005262
  Predicado: Cu > 0.06 (n=46)
    Zona: 15 colunas
    Importance: 0.007500
  Predicado: Cu <= 0.15 (n=95)
    Zona: 15 colunas
    Importance: 0.004893
  Predicado: background2 > -0.29 (n=93)
    Zona: 125 colunas
    Importance: 0.008291
  Predicado: background2 <= -0.06 (n=50)
    Zona: 125 colunas
    Importance: 0.009389
  Predicado: background2 > -0.06 (n=68)
    Zona: 125 colunas
    Importance: 0.009271
  Predicado: background2 <= 0.12 (n=73)
    Zona: 125 colunas
    Importance: 0.009828
  Predicado: background2 > 0.12 (n=45)
    Zona: 125 colunas
    Importance: 0.008499
  Predicado: background2 <= 0.25 (n=94)
    Zona: 125 colunas
    Importance: 0.009749
  Predicado: Fe ka + Ti ka > -0.15 (n=96)
    Zona: 23 colunas
    Importance: 0.002844
  Predicado: Fe ka + Ti ka <= -0.04 (n=44)
    Zona: 23 colunas
    Importance: 0.003341
  Predicado: Fe ka + Ti ka > -0.04 (n=74)
    Zona: 23 colunas
    Importance: 0.002863
  Predicado: Fe ka + Ti ka <= 0.06 (n=68)
    Zona: 23 colunas
    Importance: 0.003262
  Predicado: Fe ka + Ti ka > 0.06 (n=50)
    Zona: 23 colunas
    Importance: 0.002741
  Predicado: Fe ka + Ti ka <= 0.16 (n=92)
    Zona: 23 colunas
    Importance: 0.003147
  Predicado: background3 > -0.17 (n=91)
    Zona: 71 colunas
    Importance: 0.007220

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka > -0.36,Ca ka > -0.36,Ca ka > -0.36,Ca ka > -0.36
1,Ca ka > -1.02,Fe ka > 0.86,Fe ka <= -0.43,Fe ka <= -0.43
2,Fe ka > 0.86,Ca ka > -1.02,Fe ka > 0.86,Fe ka > -0.43
3,Ca ka > -1.73,Fe ka <= -0.43,Fe ka <= 2.21,Fe ka <= 0.86
4,Fe ka > -0.43,Fe ka > -0.43,Fe ka > -2.66,Ca ka > -1.73
...,...,...,...,...
124,Fe ka + Ti ka > 0.06,NaN,Fe ka + Ti ka > -0.15,S > 0.03
125,background1 <= -0.16,NaN,Class_A,Class_A
126,S > 0.03,NaN,Class_B,Class_B
127,Class_A,NaN,NaN,NaN
128,Class_B,NaN,NaN,NaN

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

               Predicate  Perturbation
0          Ca ka > -0.36      0.102804
1           Fe ka > 0.86      0.076198
2         Fe ka <= -0.43      0.076068
3          Ca ka > -1.02      0.075472
4          Fe ka > -2.66      0.068703
..                   ...           ...
118            S <= 0.12      0.002707
119            S > -0.13      0.002685
120  background1 <= 0.05      0.002653
121            S > -0.06      0.002470
122             S > 0.03      0.002448

[123 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -0.36,7.119731,Ca ka,-0.36,>
1,Fe ka <= -0.43,5.690224,Fe ka,-0.43,<=
2,Mn > 0.64,4.642038,Mn,0.64,>
3,Ti ka <= -0.57,4.388663,Ti ka,-0.57,<=
4,K > 0.02,1.249261,K,0.02,>
5,Ti kb <= -0.63,1.129048,Ti kb,-0.63,<=
6,Fe kb > 0.40,1.029286,Fe kb,0.40,>
7,Ca kb > -0.04,0.599724,Ca kb,-0.04,>
8,sum Fe <= -0.04,0.589987,sum Fe,-0.04,<=
9,Si <= -0.66,0.559322,Si,-0.66,<=
10,Al <= -0.09,0.553489,Al,-0.09,<=
11,background3 <= -0.17,0.489907,background3,-0.17,<=
12,P > 0.01,0.487479,P,0.01,>
13,background2 <= -0.29,0.432857,background2,-0.29,<=
14,Cr > 0.04,0.414401,Cr,0.04,>
15,Cu > 0.06,0.394850,Cu,0.06,>
16,Rh L + Ar <= -0.05,0.074894,Rh L + Ar,-0.05,<=
17,Fe ka + Ti ka <= -0.04,0.023705,Fe ka + Ti ka,-0.04,<=
18,S <= -0.06,0.021839,S,-0.06,<=
19,background1 > -0.16,0.018221,background1,-0.16,>
20,Class_A,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -0.36,7.119731,Ca ka,-0.36,>,-0.641296,49.0,0.004141,Ca ka > -0.641296
1,Fe ka <= -0.43,5.690224,Fe ka,-0.43,<=,-54.402608,14.0,0.002481,Fe ka <= -54.402608
2,Fe ka > -0.43,5.531878,Fe ka,-0.43,>,-54.402608,14.0,0.002481,Fe ka > -54.402608
3,Fe ka <= 2.21,5.485551,Fe ka,2.21,<=,-52.027383,10.0,0.025269,Fe ka <= -52.027383
4,Fe ka > 0.86,5.466023,Fe ka,0.86,>,55.595005,114.0,0.001174,Fe ka > 55.595005
...,...,...,...,...,...,...,...,...,...
131,S > 0.12,0.015043,S,0.12,>,0.092267,45.0,0.001052,S > 0.092267
132,background1 <= -0.16,0.013470,background1,-0.16,<=,-0.141474,2.0,0.000536,background1 <= -0.141474
133,S > 0.03,0.008707,S,0.03,>,0.015843,130.0,0.000535,S > 0.015843
134,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
135,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

In [16]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ca ka':
  - Dimensão: 16 variáveis espectrais
  - Variância explicada pela PC1: 99.40%

In [18]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = mlp_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = mlp_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba           Zone
0    6.52                      0.033639          Fe ka
1    4.52                      0.028431          Ti ka
2    3.68                      0.019257          Ca ka
3    5.88                      0.010159             Mn
4    7.06                      0.009119          Fe kb
5    1.74                      0.005880             Si
6     3.3                      0.005805              K
7    3.98                      0.004433          Ca kb
8    1.48                      0.003900             Al
9   12.74                      0.003704         sum Fe
10   4.86                      0.003684          Ti kb
11   2.02                      0.003353              P
12   5.38                      0.003285             Cr
13   9.94                      0.002688    background2
14   8.02                      0.002174             Cu
15   2.86                      0.002060      Rh L + Ar
16  10.72                      0.001911  Fe ka + Ti ka
17    7.5                      0.001734    background1
18  12.54                      0.001728    background3
19   2.42                      0.001600              S
20   1.32                      0.000969            NaN

In [20]:
import numpy as np

max_len = max(
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

             Shap    Permutation LRC_perturbation LRC_covariance
0           Fe ka          Fe ka            Ca ka          Ca ka
1           Ca ka          Ti ka            Fe ka          Fe ka
2           Ti ka          Ca ka               Mn          Ti ka
3              Mn             Mn            Ti ka          Ca kb
4           Fe kb          Fe kb                K             Mn
5               K             Si            Ti kb              K
6              Si              K            Fe kb          Fe kb
7           Ca kb          Ca kb            Ca kb             Si
8              Al             Al           sum Fe             Al
9          sum Fe         sum Fe               Si         sum Fe
10    background2          Ti kb               Al          Ti kb
11          Ti kb              P      background3  Fe ka + Ti ka
12              P             Cr                P              P
13      Rh L + Ar    background2      background2             Cr
14  Fe ka + Ti ka             Cu               Cr    background2
15             Cr      Rh L + Ar               Cu              S
16             Cu  Fe ka + Ti ka        Rh L + Ar    background1
17    background3    background1    Fe ka + Ti ka      Rh L + Ar
18            NaN    background3                S    background3
19              S              S      background1             Cu
20    background1            NaN             None           None

In [21]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_11404\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
5  LRC_perturbation    LRC_covariance   0.861034
0              Shap       Permutation   0.858349
2              Shap    LRC_covariance   0.618176
1              Shap  LRC_perturbation   0.586759
4       Permutation    LRC_covariance   0.504772
3       Permutation  LRC_perturbation   0.473355

In [22]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')