In [87]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/soil/plsda/soil.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.32':'13.1']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.32':'13.1'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.32':'13.1'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-08 16:39:49,646 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-08 16:39:49,655 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-08 16:39:49,680 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

2026-02-08 16:39:49,688 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning:

'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.

In [88]:
# PLS-DA with optimized latent variables
from modeling import pls_optimized

plsda_results = pls_optimized(
    Xcalclass_prep, 
    ycalclass,
    LVmax=4,
    Xpred=Xpredclass_prep,
    ypred=ypredclass,
    aim='classification',
    cv=10
)

# Convenience references used later
pls_model = plsda_results[3]               # fitted PLS model
vip_scores_mat = plsda_results[4]          # VIP scores matrix (features × LV)
y_pred_cont = plsda_results[5].iloc[:, -1] # continuous predictions for Xcalclass (used for MI/Cov)

# plotando o vip scores rapidamente
vip_scores_mat.T.plot()

## Definição das Zonas Espectrais

In [89]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Al', 1.33, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.19),
('S', 2.19, 2.55),
('Rh L + Ar', 2.55, 3.21),
('K', 3.21, 3.53),
('Ca ka', 3.53, 3.84),
('Ca kb', 3.84, 4.37),
('Ti ka', 4.37, 4.75),
('Ti kb', 4.75, 5.12),
('Cr', 5.12, 5.77),
('Mn', 5.77, 6.13),
('Fe ka', 6.13, 6.80),
('Fe kb', 6.80, 7.30),
('background1', 7.30, 7.91),
('Cu', 7.91, 8.20),
('background2', 8.20, 10.69),
('Fe ka + Ti ka', 10.69, 11.14),
('background3', 11.14, 12.55),
('sum Fe' , 12.55, 13.1)
]

## VIP, Regression Coefficients e SHAP (como no original)

In [90]:
# VIP scores por energia
vip_scores_df = pd.DataFrame({
    'energy': vip_scores_mat.T.index,
    'VIP_Score': vip_scores_mat.T.iloc[:,0].values
})
vip_scores_df = vip_scores_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in vip_scores_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
vip_scores_df['Zone'] = vip_scores_df['energy'].map(energy_to_zone_vip)
vip_scores_unique_df = vip_scores_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
vip_scores_unique_df = vip_scores_unique_df.sort_values(by='VIP_Score', ascending=False).reset_index(drop=True)

# Coeficientes de regressão do PLS
reg_vet = pd.DataFrame(pls_model.coef_, columns=pls_model.feature_names_in_).T
reg_vet.insert(0, 'energy', reg_vet.index)
reg_vet = reg_vet.reset_index(drop=True)
reg_vet.columns = ['energy','Reg_coef']
reg_vet['Abs_Reg_coef'] = reg_vet['Reg_coef'].abs()
reg_vet = reg_vet.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)
energy_to_zone_reg = {}
for zone_name, start, end in spectral_cuts:
    for e in reg_vet['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_reg[e] = zone_name
reg_vet['Zone'] = reg_vet['energy'].map(energy_to_zone_reg)
reg_vet_unique_df = reg_vet.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
reg_vet_unique_df = reg_vet_unique_df.sort_values(by='Abs_Reg_coef', ascending=False).reset_index(drop=True)

In [91]:
shap_global_importance = pd.read_csv('shap_soil.csv', sep=';') # loading previously saved shap_unique_df

# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df = shap_unique_df.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP           Zone
0     3.70       0.027751          Ca ka
1     6.42       0.013531          Fe ka
2     5.90       0.012230             Mn
3     1.74       0.010560             Si
4     4.46       0.006195          Ti ka
5     7.02       0.000310          Fe kb
6     5.02       0.000083          Ti kb
7     1.46       0.000082             Al
8     3.32       0.000021              K
9     2.02       0.000021              P
10   10.70       0.000000  Fe ka + Ti ka
11    1.32       0.000000            NaN
12    2.22       0.000000              S
13    4.36       0.000000          Ca kb
14    2.90       0.000000      Rh L + Ar
15    9.32       0.000000    background2
16   12.62       0.000000         sum Fe
17   12.02       0.000000    background3
18    7.78       0.000000    background1
19    8.18       0.000000             Cu
20    5.32       0.000000             Cr

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [92]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Al': VE = 79.34%, dim = 15 variáveis
Zona 'Si': VE = 91.83%, dim = 12 variáveis
Zona 'P': VE = 62.02%, dim = 17 variáveis
Zona 'S': VE = 36.84%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 42.17%, dim = 33 variáveis
Zona 'K': VE = 83.48%, dim = 16 variáveis
Zona 'Ca ka': VE = 99.02%, dim = 16 variáveis
Zona 'Ca kb': VE = 74.05%, dim = 27 variáveis
Zona 'Ti ka': VE = 89.48%, dim = 19 variáveis
Zona 'Ti kb': VE = 82.21%, dim = 19 variáveis
Zona 'Cr': VE = 53.41%, dim = 33 variáveis
Zona 'Mn': VE = 91.12%, dim = 18 variáveis
Zona 'Fe ka': VE = 56.98%, dim = 34 variáveis
Zona 'Fe kb': VE = 55.98%, dim = 26 variáveis
Zona 'background1': VE = 32.70%, dim = 31 variáveis
Zona 'Cu': VE = 53.86%, dim = 15 variáveis
Zona 'background2': VE = 26.43%, dim = 125 variáveis
Zona 'Fe ka + Ti ka': VE = 34.74%, dim = 23 variáveis
Zona 'background3': VE = 18.96%, dim = 71 variáveis
Zona 'sum Fe': VE = 55.82%, dim = 28 variáveis

Scores DataFrame shape: (148, 20)

In [93]:
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred_cont
)

In [94]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 123 | Descartados: 37
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 122 | Descartados: 38
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 123 | Descartados: 37
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 122 | Descartados: 38
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 94
Removida: Ca ka > -1.73 -> Ca ka > -0.36 (0.7862) | Mantida: Ca ka > -0.36 -> Ca ka > -1.73 (4.5083)
Removida: Ca ka > -1.02 -> Ca ka > -1.73 (1.4677) | Mantida: Ca ka > -1.73 -> Ca ka > -1.02 (4.3441)
Removida: Fe ka > 0.86 -> Ca ka > -1.02 (0.2032) | Mantida: Ca ka > -1.02 -> Fe ka > 0.86 (4.9999)
Removida: Ti ka > 0.93 -> Fe ka > -0.43 (0.2101) | Mantida: Fe ka > -0.43 -> Ti ka > 0.93 (0.4986)
Removida: Ti ka > 0.93 -> Fe ka > -2.66 (0.7153) | Mantida: Fe ka > -2.66 -> Ti ka > 0.93 (0.7719)
Removida: Ti ka > -0.57 -> Ti ka > -1.78 (0.2992) | Mantida: Ti ka > -1.78 -> Ti ka > -0.57 (0.5237)
Removida: Ca kb > -0.04 -> Ti ka > -1.78 (0.1228) | Mantida: Ti ka > -1.78 -> Ca kb > -0.04 (0.1695)
Removida: Ca ka <= 1.21 -> Ti ka > -1.78 (0.1484) | Mantida: Ti ka > -1.78 -> Ca ka <= 1.21 (0.2757)
Removida: Ca kb > -0.23 -> Ti ka > -0.57 (0.1332) | Mantida: Ti ka > -0.57 -> Ca kb > -0.23 (0.1593)
Removida: Mn > -0.38 -> Ti ka > -0.57 (0.1186) | Mantida: Ti ka > -0.57 -> Mn > -0.38 (0.1298)
Removida: Ti ka > -0.57 -> Mn > -0.65 (0.1261) | Mantida: Mn > -0.65 -> Ti ka > -0.57 (0.1434)
Removida: Ti ka > -0.57 -> Ca ka <= 1.21 (0.1361) | Mantida: Ca ka <= 1.21 -> Ti ka > -0.57 (0.3088)
Removida: Ca kb > -0.23 -> Ca kb > -0.04 (0.3877) | Mantida: Ca kb > -0.04 -> Ca kb > -0.23 (0.3896)
Removida: Ca kb > -0.37 -> Ca kb > -0.23 (0.1935) | Mantida: Ca kb > -0.23 -> Ca kb > -0.37 (0.3844)
Removida: Ca ka <= 1.21 -> Mn > -0.65 (0.1566) | Mantida: Mn > -0.65 -> Ca ka <= 1.21 (0.5918)
Removida: Mn > -0.65 -> Ti ka <= -0.57 (0.1387) | Mantida: Ti ka <= -0.57 -> Mn > -0.65 (0.1450)
Removida: Ti ka <= 1.88 -> Ca ka <= 1.21 (0.1407) | Mantida: Ca ka <= 1.21 -> Ti ka <= 1.88 (0.1409)
Removida: Ti ka <= -0.57 -> Fe kb > 0.40 (0.2071) | Mantida: Fe kb > 0.40 -> Ti ka <= -0.57 (0.2226)
Removida: Ti ka <= 0.93 -> Fe kb > 0.40 (0.1160) | Mantida: Fe kb > 0.40 -> Ti ka <= 0.93 (0.1288)
Removida: Fe kb > 0.40 -> Mn > -0.15 (0.0716) | Mantida: Mn > -0.15 -> Fe kb > 0.40 (0.1139)
Removida: Ti ka <= -0.57 -> Ti ka <= 1.88 (0.1077) | Mantida: Ti ka <= 1.88 -> Ti ka <= -0.57 (0.2398)
Removida: Mn > -0.38 -> Mn > -0.15 (0.1983) | Mantida: Mn > -0.15 -> Mn > -0.38 (0.4723)
Removida: Si > -0.66 -> Mn > -0.15 (0.1003) | Mantida: Mn > -0.15 -> Si > -0.66 (0.1011)
Removida: Mn > -0.15 -> Ti ka <= 0.93 (0.0814) | Mantida: Ti ka <= 0.93 -> Mn > -0.15 (0.1868)
Removida: Ti ka <= 0.93 -> Ti ka <= 1.88 (0.0764) | Mantida: Ti ka <= 1.88 -> Ti ka <= 0.93 (0.1959)
Removida: Fe kb > -0.07 -> Ti ka <= 0.93 (0.0540) | Mantida: Ti ka <= 0.93 -> Fe kb > -0.07 (0.0934)
Removida: Fe kb > -0.07 -> Si > -0.66 (0.0948) | Mantida: Si > -0.66 -> Fe kb > -0.07 (0.0967)
Removida: Si > 0.13 -> K > -0.20 (0.0567) | Mantida: K > -0.20 -> Si > 0.13 (0.0636)
Removida: Fe kb > -1.03 -> Si > 0.13 (0.0492) | Mantida: Si > 0.13 -> Fe kb > -1.03 (0.1684)
Removida: Ca ka <= -0.36 -> K > -0.38 (0.1596) | Mantida: K > -0.38 -> Ca ka <= -0.36 (0.2546)
Removida: Fe kb > -1.03 -> Ca ka <= -0.36 (0.0947) | Mantida: Ca ka <= -0.36 -> Fe kb > -1.03 (0.1367)
Removida: K > -0.38 -> Ti kb > 0.26 (0.0546) | Mantida: Ti kb > 0.26 -> K > -0.38 (0.0611)
Removida: K > -0.20 -> Al <= 0.37 (0.0555) | Mantida: Al <= 0.37 -> K > -0.20 (0.1697)
Removida: Ti kb > 0.26 -> K > -0.20 (0.0983) | Mantida: K > -0.20 -> Ti kb > 0.26 (0.0994)
Removida: Ti kb > 0.26 -> Si <= 0.13 (0.0487) | Mantida: Si <= 0.13 -> Ti kb > 0.26 (0.0569)
Removida: Ti kb > 0.26 -> K > 0.02 (0.0457) | Mantida: K > 0.02 -> Ti kb > 0.26 (0.0488)
Removida: Ti kb > -0.16 -> K > 0.02 (0.0837) | Mantida: K > 0.02 -> Ti kb > -0.16 (0.0844)
Removida: K > -0.20 -> Si > -0.20 (0.0512) | Mantida: Si > -0.20 -> K > -0.20 (0.0612)
Removida: K > 0.02 -> K > -0.20 (0.0479) | Mantida: K > -0.20 -> K > 0.02 (0.0529)
Removida: Fe kb > -1.03 -> Si > -0.20 (0.0417) | Mantida: Si > -0.20 -> Fe kb > -1.03 (0.1162)
Removida: Si > -0.20 -> Si <= 0.69 (0.0439) | Mantida: Si <= 0.69 -> Si > -0.20 (0.0545)
Removida: Ti kb <= 0.26 -> K > 0.02 (0.0460) | Mantida: K > 0.02 -> Ti kb <= 0.26 (0.0480)
Removida: K > 0.02 -> Ti kb <= -0.16 (0.0439) | Mantida: Ti kb <= -0.16 -> K > 0.02 (0.0444)
Removida: Al > -0.33 -> K > 0.02 (0.0380) | Mantida: K > 0.02 -> Al > -0.33 (0.0442)
Removida: Al <= 0.16 -> Ti kb > -0.63 (0.0406) | Mantida: Ti kb > -0.63 -> Al <= 0.16 (0.0867)
Removida: Ti kb <= -0.16 -> Ti kb <= 0.26 (0.0308) | Mantida: Ti kb <= 0.26 -> Ti kb <= -0.16 (0.0425)
Removida: Al <= 0.16 -> Ti kb <= -0.16 (0.0282) | Mantida: Ti kb <= -0.16 -> Al <= 0.16 (0.0412)
Removida: Al > -0.33 -> Al <= 0.16 (0.0379) | Mantida: Al <= 0.16 -> Al > -0.33 (0.0754)
Removida: Al <= -0.09 -> sum Fe <= 0.31 (0.0342) | Mantida: sum Fe <= 0.31 -> Al <= -0.09 (0.0413)
Removida: Al > -0.33 -> sum Fe <= 0.31 (0.0324) | Mantida: sum Fe <= 0.31 -> Al > -0.33 (0.0425)
Removida: P > -0.24 -> Al > -0.33 (0.0245) | Mantida: Al > -0.33 -> P > -0.24 (0.0593)
Removida: Cr > -0.28 -> P > -0.24 (0.0190) | Mantida: P > -0.24 -> Cr > -0.28 (0.0212)
Removida: P > -0.24 -> Ca ka <= -1.02 (0.0230) | Mantida: Ca ka <= -1.02 -> P > -0.24 (0.0322)
Removida: sum Fe > -0.31 -> Al <= -0.09 (0.0216) | Mantida: Al <= -0.09 -> sum Fe > -0.31 (0.0266)
Removida: Fe kb <= 0.95 -> Si <= -0.20 (0.0078) | Mantida: Si <= -0.20 -> Fe kb <= 0.95 (0.0126)
Removida: sum Fe > -0.31 -> Cr > -0.28 (0.0194) | Mantida: Cr > -0.28 -> sum Fe > -0.31 (0.0333)
Removida: sum Fe <= 0.13 -> sum Fe > -0.31 (0.0193) | Mantida: sum Fe > -0.31 -> sum Fe <= 0.13 (0.0555)
Removida: sum Fe <= 0.13 -> Cr > -0.28 (0.0176) | Mantida: Cr > -0.28 -> sum Fe <= 0.13 (0.0181)
Removida: Ca kb <= 0.29 -> Ca ka <= -1.02 (0.0200) | Mantida: Ca ka <= -1.02 -> Ca kb <= 0.29 (0.0586)
Removida: S > -0.06 -> Ca kb <= 0.29 (0.0084) | Mantida: Ca kb <= 0.29 -> S > -0.06 (0.0179)
Removida: Cr <= 0.28 -> Ca kb <= 0.29 (0.0145) | Mantida: Ca kb <= 0.29 -> Cr <= 0.28 (0.0210)
Removida: Ca kb <= 0.29 -> Al > -0.09 (0.0165) | Mantida: Al > -0.09 -> Ca kb <= 0.29 (0.0251)
Removida: Cr <= 0.04 -> Ca kb <= 0.29 (0.0142) | Mantida: Ca kb <= 0.29 -> Cr <= 0.04 (0.0187)
Removida: Cr <= 0.28 -> K <= 0.39 (0.0115) | Mantida: K <= 0.39 -> Cr <= 0.28 (0.0231)
Removida: S > -0.06 -> K <= 0.39 (0.0082) | Mantida: K <= 0.39 -> S > -0.06 (0.0200)
Removida: Al > -0.09 -> Cr <= 0.28 (0.0172) | Mantida: Cr <= 0.28 -> Al > -0.09 (0.0276)
Removida: background2 <= 0.12 -> S > -0.06 (0.0060) | Mantida: S > -0.06 -> background2 <= 0.12 (0.0088)
Removida: background2 <= 0.25 -> background2 <= 0.12 (0.0068) | Mantida: background2 <= 0.12 -> background2 <= 0.25 (0.0134)
Removida: background2 <= 0.25 -> sum Fe > -0.04 (0.0041) | Mantida: sum Fe > -0.04 -> background2 <= 0.25 (0.0135)
Removida: background3 <= 0.18 -> sum Fe > -0.04 (0.0035) | Mantida: sum Fe > -0.04 -> background3 <= 0.18 (0.0111)
Removida: sum Fe > -0.04 -> P <= 0.28 (0.0101) | Mantida: P <= 0.28 -> sum Fe > -0.04 (0.0126)
Removida: Cr <= 0.04 -> P > 0.01 (0.0111) | Mantida: P > 0.01 -> Cr <= 0.04 (0.0311)
Removida: S > -0.13 -> Cr <= 0.04 (0.0077) | Mantida: Cr <= 0.04 -> S > -0.13 (0.0110)
Removida: S > -0.06 -> S > -0.13 (0.0078) | Mantida: S > -0.13 -> S > -0.06 (0.0086)
Removida: S > -0.06 -> P > -0.17 (0.0084) | Mantida: P > -0.17 -> S > -0.06 (0.0143)
Removida: S > -0.13 -> Fe kb <= 0.40 (0.0070) | Mantida: Fe kb <= 0.40 -> S > -0.13 (0.0106)
Removida: P > -0.17 -> Al > -0.09 (0.0129) | Mantida: Al > -0.09 -> P > -0.17 (0.0457)
Removida: P > -0.17 -> P > 0.01 (0.0130) | Mantida: P > 0.01 -> P > -0.17 (0.0140)
Removida: Cr > 0.04 -> sum Fe <= -0.04 (0.0096) | Mantida: sum Fe <= -0.04 -> Cr > 0.04 (0.0106)
Removida: Cr > 0.04 -> Al > 0.16 (0.0060) | Mantida: Al > 0.16 -> Cr > 0.04 (0.0249)
Removida: background1 <= -0.03 -> background1 <= 0.05 (0.0057) | Mantida: background1 <= 0.05 -> background1 <= -0.03 (0.0228)
Removida: S > 0.03 -> background1 <= 0.05 (0.0052) | Mantida: background1 <= 0.05 -> S > 0.03 (0.0056)
Removida: background1 <= 0.05 -> background3 <= 0.18 (0.0045) | Mantida: background3 <= 0.18 -> background1 <= 0.05 (0.0106)
Removida: background3 <= 0.18 -> Mn <= -0.38 (0.0026) | Mantida: Mn <= -0.38 -> background3 <= 0.18 (0.0168)
Removida: background3 <= 0.18 -> Mn <= -0.15 (0.0030) | Mantida: Mn <= -0.15 -> background3 <= 0.18 (0.0140)
Removida: Rh L + Ar <= -0.05 -> sum Fe > 0.13 (0.0106) | Mantida: sum Fe > 0.13 -> Rh L + Ar <= -0.05 (0.0162)
Removida: Cr > -0.12 -> sum Fe > 0.13 (0.0059) | Mantida: sum Fe > 0.13 -> Cr > -0.12 (0.0059)
Removida: background1 > -0.16 -> sum Fe > 0.13 (0.0035) | Mantida: sum Fe > 0.13 -> background1 > -0.16 (0.0075)
Removida: background1 <= 0.16 -> Rh L + Ar <= -0.05 (0.0042) | Mantida: Rh L + Ar <= -0.05 -> background1 <= 0.16 (0.0051)
Removida: S > 0.03 -> Cr > -0.12 (0.0062) | Mantida: Cr > -0.12 -> S > 0.03 (0.0076)
Removida: background2 <= -0.06 -> Cr > -0.12 (0.0036) | Mantida: Cr > -0.12 -> background2 <= -0.06 (0.0087)
Removida: S > 0.03 -> Mn <= -0.15 (0.0062) | Mantida: Mn <= -0.15 -> S > 0.03 (0.0136)
Removida: S > 0.03 -> Al > 0.16 (0.0061) | Mantida: Al > 0.16 -> S > 0.03 (0.0134)
Removida: background2 <= -0.06 -> Mn <= -0.15 (0.0034) | Mantida: Mn <= -0.15 -> background2 <= -0.06 (0.0135)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 619 | Removidas: 94
Nós predicados: 92
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 96
Removida: Ca ka > -1.02 -> Ca ka > -0.36 (0.3202) | Mantida: Ca ka > -0.36 -> Ca ka > -1.02 (2.4681)
Removida: Fe ka > -0.43 -> Ca ka > -0.36 (0.4600) | Mantida: Ca ka > -0.36 -> Fe ka > -0.43 (0.5498)
Removida: Ti ka > 0.93 -> Ca ka > -0.36 (0.2702) | Mantida: Ca ka > -0.36 -> Ti ka > 0.93 (0.2889)
Removida: Ca ka > -1.02 -> Ca ka > -1.73 (2.1821) | Mantida: Ca ka > -1.73 -> Ca ka > -1.02 (2.3977)
Removida: Fe ka > 0.86 -> Ca ka > -1.02 (0.6144) | Mantida: Ca ka > -1.02 -> Fe ka > 0.86 (2.2400)
Removida: Fe ka > 0.86 -> Ti ka > 0.93 (0.2310) | Mantida: Ti ka > 0.93 -> Fe ka > 0.86 (0.2524)
Removida: Fe ka > -2.66 -> Fe ka > -0.43 (0.1750) | Mantida: Fe ka > -0.43 -> Fe ka > -2.66 (0.6476)
Removida: Fe ka > -0.43 -> Ti ka > 0.93 (0.1645) | Mantida: Ti ka > 0.93 -> Fe ka > -0.43 (0.2143)
Removida: Fe ka > -2.66 -> Ca kb > -0.04 (0.1507) | Mantida: Ca kb > -0.04 -> Fe ka > -2.66 (0.2735)
Removida: Ca kb > -0.04 -> Ti ka <= -0.57 (0.0457) | Mantida: Ti ka <= -0.57 -> Ca kb > -0.04 (0.1673)
Removida: Ca kb > -0.04 -> Al <= 0.37 (0.0436) | Mantida: Al <= 0.37 -> Ca kb > -0.04 (0.0545)
Removida: Ti ka <= -0.57 -> Mn > -0.65 (0.1371) | Mantida: Mn > -0.65 -> Ti ka <= -0.57 (0.1418)
Removida: Ca kb > -0.23 -> Ti ka > -0.57 (0.1263) | Mantida: Ti ka > -0.57 -> Ca kb > -0.23 (0.1558)
Removida: Ca kb > -0.37 -> Ca kb > -0.23 (0.0618) | Mantida: Ca kb > -0.23 -> Ca kb > -0.37 (0.2620)
Removida: Fe kb > -0.07 -> Ca kb > -0.23 (0.0525) | Mantida: Ca kb > -0.23 -> Fe kb > -0.07 (0.0592)
Removida: Ti ka > -0.57 -> Ti ka > -1.78 (0.4988) | Mantida: Ti ka > -1.78 -> Ti ka > -0.57 (0.6678)
Removida: Ti ka <= -0.57 -> Ti ka > -0.57 (0.1358) | Mantida: Ti ka > -0.57 -> Ti ka <= -0.57 (0.1811)
Removida: Ca kb > -0.37 -> Ca ka <= 1.21 (0.1221) | Mantida: Ca ka <= 1.21 -> Ca kb > -0.37 (0.1520)
Removida: Ca kb > -0.37 -> Si > 0.13 (0.0665) | Mantida: Si > 0.13 -> Ca kb > -0.37 (0.0839)
Removida: Fe kb > -0.07 -> Ca kb > -0.37 (0.0526) | Mantida: Ca kb > -0.37 -> Fe kb > -0.07 (0.0767)
Removida: Fe kb > 0.40 -> Ca ka <= 1.21 (0.0784) | Mantida: Ca ka <= 1.21 -> Fe kb > 0.40 (0.1349)
Removida: Mn > -0.38 -> Ti ka > -1.78 (0.1060) | Mantida: Ti ka > -1.78 -> Mn > -0.38 (0.1326)
Removida: Mn > -0.38 -> Mn > -0.15 (0.1221) | Mantida: Mn > -0.15 -> Mn > -0.38 (0.3398)
Removida: Ti ka <= 1.88 -> Mn > -0.38 (0.1095) | Mantida: Mn > -0.38 -> Ti ka <= 1.88 (0.2221)
Removida: Mn > -0.38 -> Ti ka <= 0.93 (0.1108) | Mantida: Ti ka <= 0.93 -> Mn > -0.38 (0.1118)
Removida: Fe kb > 0.40 -> Mn > -0.15 (0.0605) | Mantida: Mn > -0.15 -> Fe kb > 0.40 (0.2288)
Removida: Ti ka <= 1.88 -> Fe kb > 0.40 (0.1273) | Mantida: Fe kb > 0.40 -> Ti ka <= 1.88 (0.1294)
Removida: Fe kb > 0.40 -> Si > -0.66 (0.1312) | Mantida: Si > -0.66 -> Fe kb > 0.40 (0.2088)
Removida: Si > -0.66 -> Ti ka <= 1.88 (0.0934) | Mantida: Ti ka <= 1.88 -> Si > -0.66 (0.2180)
Removida: Fe kb > -0.07 -> Ti ka <= 1.88 (0.0487) | Mantida: Ti ka <= 1.88 -> Fe kb > -0.07 (0.0882)
Removida: Ti ka <= 0.93 -> Ti ka <= 1.88 (0.0853) | Mantida: Ti ka <= 1.88 -> Ti ka <= 0.93 (0.0853)
Removida: Fe kb > -0.07 -> Si > -0.66 (0.0498) | Mantida: Si > -0.66 -> Fe kb > -0.07 (0.1891)
Removida: Si > -0.66 -> Ti ka <= 0.93 (0.1961) | Mantida: Ti ka <= 0.93 -> Si > -0.66 (0.2147)
Removida: Si > -0.20 -> Si > 0.13 (0.0882) | Mantida: Si > 0.13 -> Si > -0.20 (0.2473)
Removida: Ti ka <= -0.57 -> Fe ka <= 0.86 (0.0478) | Mantida: Fe ka <= 0.86 -> Ti ka <= -0.57 (0.0538)
Removida: Ti ka <= 0.93 -> Ca ka <= -0.36 (0.0824) | Mantida: Ca ka <= -0.36 -> Ti ka <= 0.93 (0.1503)
Removida: Ca ka <= -0.36 -> Si > -0.20 (0.0637) | Mantida: Si > -0.20 -> Ca ka <= -0.36 (0.0765)
Removida: K > -0.38 -> Ca ka <= -0.36 (0.0641) | Mantida: Ca ka <= -0.36 -> K > -0.38 (0.0708)
Removida: Fe kb > -1.03 -> K > -0.38 (0.0445) | Mantida: K > -0.38 -> Fe kb > -1.03 (0.1216)
Removida: K > -0.20 -> K > -0.38 (0.0748) | Mantida: K > -0.38 -> K > -0.20 (0.1284)
Removida: K > -0.20 -> Fe kb > -1.03 (0.0641) | Mantida: Fe kb > -1.03 -> K > -0.20 (0.0803)
Removida: Fe kb > -1.03 -> Ti kb <= 0.72 (0.0378) | Mantida: Ti kb <= 0.72 -> Fe kb > -1.03 (0.0561)
Removida: Al <= 0.37 -> K > -0.20 (0.1154) | Mantida: K > -0.20 -> Al <= 0.37 (0.1689)
Removida: Ti kb > 0.26 -> Al <= 0.37 (0.0585) | Mantida: Al <= 0.37 -> Ti kb > 0.26 (0.1535)
Removida: Al <= 0.37 -> Ti kb <= 0.72 (0.0508) | Mantida: Ti kb <= 0.72 -> Al <= 0.37 (0.0665)
Removida: K > 0.02 -> Ti kb > 0.26 (0.0451) | Mantida: Ti kb > 0.26 -> K > 0.02 (0.0516)
Removida: K > 0.02 -> Al <= 0.16 (0.0428) | Mantida: Al <= 0.16 -> K > 0.02 (0.0429)
Removida: K > 0.02 -> Ti kb <= 0.26 (0.0437) | Mantida: Ti kb <= 0.26 -> K > 0.02 (0.0460)
Removida: Ti kb > -0.16 -> K > 0.02 (0.0517) | Mantida: K > 0.02 -> Ti kb > -0.16 (0.0619)
Removida: Ti kb > -0.63 -> K > 0.02 (0.0448) | Mantida: K > 0.02 -> Ti kb > -0.63 (0.0862)
Removida: Fe ka <= 2.21 -> Al <= 0.16 (0.0339) | Mantida: Al <= 0.16 -> Fe ka <= 2.21 (0.0397)
Removida: Fe ka <= 2.21 -> Al <= -0.09 (0.0303) | Mantida: Al <= -0.09 -> Fe ka <= 2.21 (0.0395)
Removida: Fe ka <= 2.21 -> Ti kb <= 0.26 (0.0270) | Mantida: Ti kb <= 0.26 -> Fe ka <= 2.21 (0.0443)
Removida: Mn <= 0.64 -> Al <= 0.16 (0.0327) | Mantida: Al <= 0.16 -> Mn <= 0.64 (0.0393)
Removida: Ti kb <= -0.16 -> Al <= 0.16 (0.0327) | Mantida: Al <= 0.16 -> Ti kb <= -0.16 (0.0399)
Removida: sum Fe > -0.31 -> Mn <= 0.64 (0.0183) | Mantida: Mn <= 0.64 -> sum Fe > -0.31 (0.0346)
Removida: sum Fe <= 0.31 -> Mn <= 0.64 (0.0172) | Mantida: Mn <= 0.64 -> sum Fe <= 0.31 (0.0347)
Removida: Mn <= 0.64 -> Ti kb > -0.63 (0.0305) | Mantida: Ti kb > -0.63 -> Mn <= 0.64 (0.0323)
Removida: sum Fe <= 0.31 -> Al > -0.33 (0.0208) | Mantida: Al > -0.33 -> sum Fe <= 0.31 (0.0821)
Removida: Al > -0.33 -> Si <= 0.13 (0.0344) | Mantida: Si <= 0.13 -> Al > -0.33 (0.0384)
Removida: Ti kb <= 0.26 -> Ti kb > -0.63 (0.0337) | Mantida: Ti kb > -0.63 -> Ti kb <= 0.26 (0.0468)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ca ka > -1.73,Ca ka > -0.36,Ca ka > -1.73,Ca ka > -0.36
1,Ca ka > -0.36,Ca ka > -1.73,Ca ka > -1.02,Ca ka > -1.73
2,Ca ka > -1.02,Ca ka > -1.02,Ca ka > -0.36,Fe ka > -0.43
3,Fe ka > 0.86,Fe ka > 0.86,Fe ka > 0.86,Ca ka > -1.02
4,Fe ka > -0.43,Fe ka > -0.43,Ca kb > -0.37,Fe ka > -2.66
...,...,...,...,...
96,NaN,NaN,Cr <= -0.12,background2 > 0.12
97,NaN,NaN,Rh L + Ar <= 0.23,K <= 0.02
98,NaN,NaN,background3 <= -0.04,Ca kb <= -0.04
99,NaN,NaN,Class_A,Class_A
100,NaN,NaN,Class_B,Class_B

In [95]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -1.73,11.435302,Ca ka,-1.73,>
1,Fe ka > 0.86,4.800227,Fe ka,0.86,>
2,Ti ka > 0.93,2.650134,Ti ka,0.93,>
3,Mn > -0.65,2.592024,Mn,-0.65,>
4,Ca kb > -0.37,2.578133,Ca kb,-0.37,>
5,Si > -0.66,1.584730,Si,-0.66,>
6,Fe kb > 0.40,1.580886,Fe kb,0.40,>
7,K > -0.38,1.247210,K,-0.38,>
8,Al <= 0.37,1.233161,Al,0.37,<=
9,Ti kb > 0.26,1.186732,Ti kb,0.26,>
10,sum Fe > -0.31,0.769974,sum Fe,-0.31,>
11,P > -0.24,0.748408,P,-0.24,>
12,Cr <= 0.04,0.705243,Cr,0.04,<=
13,S > -0.06,0.664246,S,-0.06,>
14,background2 > -0.29,0.663196,background2,-0.29,>
15,background1 <= 0.05,0.632967,background1,0.05,<=
16,background3 <= 0.18,0.626349,background3,0.18,<=
17,Rh L + Ar > 0.09,0.607509,Rh L + Ar,0.09,>
18,Cu > 0.06,0.557348,Cu,0.06,>
19,Fe ka + Ti ka <= 0.16,0.499227,Fe ka + Ti ka,0.16,<=
20,Class_A,0.000000,None,None,None

In [96]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Al': VE = 89.82%, dim = 15 variáveis
Zona 'Si': VE = 95.22%, dim = 12 variáveis
Zona 'P': VE = 61.00%, dim = 17 variáveis
Zona 'S': VE = 42.01%, dim = 18 variáveis
Zona 'Rh L + Ar': VE = 51.54%, dim = 33 variáveis
Zona 'K': VE = 88.55%, dim = 16 variáveis
Zona 'Ca ka': VE = 99.40%, dim = 16 variáveis
Zona 'Ca kb': VE = 72.71%, dim = 27 variáveis
Zona 'Ti ka': VE = 93.59%, dim = 19 variáveis
Zona 'Ti kb': VE = 88.32%, dim = 19 variáveis
Zona 'Cr': VE = 56.23%, dim = 33 variáveis
Zona 'Mn': VE = 93.26%, dim = 18 variáveis
Zona 'Fe ka': VE = 58.12%, dim = 34 variáveis
Zona 'Fe kb': VE = 55.52%, dim = 26 variáveis
Zona 'background1': VE = 34.82%, dim = 31 variáveis
Zona 'Cu': VE = 55.93%, dim = 15 variáveis
Zona 'background2': VE = 26.61%, dim = 125 variáveis
Zona 'Fe ka + Ti ka': VE = 39.81%, dim = 23 variáveis
Zona 'background3': VE = 19.45%, dim = 71 variáveis
Zona 'sum Fe': VE = 69.07%, dim = 28 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -1.73,11.435302,Ca ka,-1.73,>,-2.806273,140.0,0.001954,Ca ka > -2.806273
1,Ca ka > -0.36,11.146522,Ca ka,-0.36,>,-0.641296,49.0,0.004141,Ca ka > -0.641296
2,Ca ka > -1.02,8.941993,Ca ka,-1.02,>,-1.635267,143.0,0.000757,Ca ka > -1.635267
3,Fe ka > 0.86,4.800227,Fe ka,0.86,>,55.595005,114.0,0.001174,Fe ka > 55.595005
4,Fe ka > -0.43,4.167810,Fe ka,-0.43,>,-54.402608,14.0,0.002481,Fe ka > -54.402608
...,...,...,...,...,...,...,...,...,...
100,K <= 0.02,0.359152,K,0.02,<=,0.001685,19.0,0.000477,K <= 0.001685
101,background3 <= 0.04,0.347558,background3,0.04,<=,0.036170,57.0,0.000169,background3 <= 0.036170
102,background3 <= -0.04,0.000197,background3,-0.04,<=,-0.027035,120.0,0.000368,background3 <= -0.027035
103,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
104,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [97]:
import plotly.graph_objects as go

n = 62
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'background2':
  - Dimensão: 125 variáveis espectrais
  - Range de energias: 8.2 - 10.68
  - Variância explicada pela PC1: 26.61%

In [98]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE
y_pred_conticted_numeric = pd.Series(y_pred_cont) # predições numéricas do modelo

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred_conticted_numeric,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=pls_model,
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='regression',
        metric='mean_abs_diff', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 123 | Descartados: 37
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 122 | Descartados: 38
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 120 | Descartados: 40
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 121 | Descartados: 39
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): regression
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: mean_abs_diff
Total de folds: 10


[Bag_1] Processando 123 predicados...
  Predicado: Al > -0.33 (n=93)
    Zona: 15 colunas
    Importance: 0.005999
  Predicado: Al <= -0.09 (n=49)
    Zona: 15 colunas
    Importance: 0.011131
  Predicado: Al > -0.09 (n=69)
    Zona: 15 colunas
    Importance: 0.006196
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.008062
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.008521
  Predicado: Al <= 0.37 (n=96)
    Zona: 15 colunas
    Importance: 0.007459
  Predicado: Si > -0.66 (n=94)
    Zona: 12 colunas
    Importance: 0.059900
  Predicado: Si <= -0.20 (n=44)
    Zona: 12 colunas
    Importance: 0.087200
  Predicado: Si > -0.20 (n=74)
    Zona: 12 colunas
    Importance: 0.064652
  Predicado: Si <= 0.13 (n=66)
    Zona: 12 colunas
    Importance: 0.061259
  Predicado: Si > 0.13 (n=52)
    Zona: 12 colunas
    Importance: 0.088038
  Predicado: Si <= 0.69 (n=94)
    Zona: 12 colunas
    Importance: 0.055999
  Predicado: P <= -0.24 (n=29)
    Zona: 17 colunas
    Importance: 0.003744
  Predicado: P > -0.24 (n=89)
    Zona: 17 colunas
    Importance: 0.003923
  Predicado: P <= -0.17 (n=52)
    Zona: 17 colunas
    Importance: 0.002999
  Predicado: P > -0.17 (n=66)
    Zona: 17 colunas
    Importance: 0.004572
  Predicado: P <= 0.01 (n=71)
    Zona: 17 colunas
    Importance: 0.002821
  Predicado: P > 0.01 (n=47)
    Zona: 17 colunas
    Importance: 0.005477
  Predicado: P <= 0.28 (n=94)
    Zona: 17 colunas
    Importance: 0.002867
  Predicado: S <= -0.13 (n=29)
    Zona: 18 colunas
    Importance: 0.003209
  Predicado: S > -0.13 (n=89)
    Zona: 18 colunas
    Importance: 0.001984
  Predicado: S <= -0.06 (n=51)
    Zona: 18 colunas
    Importance: 0.002447
  Predicado: S > -0.06 (n=67)
    Zona: 18 colunas
    Importance: 0.002161
  Predicado: S <= 0.03 (n=73)
    Zona: 18 colunas
    Importance: 0.001935
  Predicado: S > 0.03 (n=45)
    Zona: 18 colunas
    Importance: 0.002852
  Predicado: S <= 0.12 (n=93)
    Zona: 18 colunas
    Importance: 0.001816
  Predicado: Rh L + Ar > -0.25 (n=95)
    Zona: 33 colunas
    Importance: 0.002249
  Predicado: Rh L + Ar <= -0.05 (n=45)
    Zona: 33 colunas
    Importance: 0.002326
  Predicado: Rh L + Ar > -0.05 (n=73)
    Zona: 33 colunas
    Importance: 0.002378
  Predicado: Rh L + Ar <= 0.09 (n=73)
    Zona: 33 colunas
    Importance: 0.002303
  Predicado: Rh L + Ar > 0.09 (n=45)
    Zona: 33 colunas
    Importance: 0.002447
  Predicado: Rh L + Ar <= 0.23 (n=96)
    Zona: 33 colunas
    Importance: 0.002328
  Predicado: K > -0.38 (n=94)
    Zona: 16 colunas
    Importance: 0.009290
  Predicado: K <= -0.20 (n=50)
    Zona: 16 colunas
    Importance: 0.008552
  Predicado: K > -0.20 (n=68)
    Zona: 16 colunas
    Importance: 0.010748
  Predicado: K <= 0.02 (n=72)
    Zona: 16 colunas
    Importance: 0.006478
  Predicado: K > 0.02 (n=46)
    Zona: 16 colunas
    Importance: 0.015046
  Predicado: K <= 0.39 (n=96)
    Zona: 16 colunas
    Importance: 0.006652
  Predicado: Ca ka > -1.73 (n=94)
    Zona: 16 colunas
    Importance: 0.140496
  Predicado: Ca ka <= -1.02 (n=49)
    Zona: 16 colunas
    Importance: 0.086335
  Predicado: Ca ka > -1.02 (n=69)
    Zona: 16 colunas
    Importance: 0.169248
  Predicado: Ca ka <= -0.36 (n=69)
    Zona: 16 colunas
    Importance: 0.065025
  Predicado: Ca ka > -0.36 (n=49)
    Zona: 16 colunas
    Importance: 0.233097
  Predicado: Ca ka <= 1.21 (n=92)
    Zona: 16 colunas
    Importance: 0.070927
  Predicado: Ca kb > -0.37 (n=93)
    Zona: 27 colunas
    Importance: 0.007788
  Predicado: Ca kb <= -0.23 (n=48)
    Zona: 27 colunas
    Importance: 0.005543
  Predicado: Ca kb > -0.23 (n=70)
    Zona: 27 colunas
    Importance: 0.009187
  Predicado: Ca kb <= -0.04 (n=71)
    Zona: 27 colunas
    Importance: 0.004101
  Predicado: Ca kb > -0.04 (n=47)
    Zona: 27 colunas
    Importance: 0.013148
  Predicado: Ca kb <= 0.29 (n=92)
    Zona: 27 colunas
    Importance: 0.004423
  Predicado: Ti ka > -1.78 (n=94)
    Zona: 19 colunas
    Importance: 0.033079
  Predicado: Ti ka <= -0.57 (n=52)
    Zona: 19 colunas
    Importance: 0.032993
  Predicado: Ti ka > -0.57 (n=66)
    Zona: 19 colunas
    Importance: 0.035451
  Predicado: Ti ka <= 0.93 (n=74)
    Zona: 19 colunas
    Importance: 0.034173
  Predicado: Ti ka > 0.93 (n=44)
    Zona: 19 colunas
    Importance: 0.034695
  Predicado: Ti ka <= 1.88 (n=97)
    Zona: 19 colunas
    Importance: 0.034228
  Predicado: Ti kb > -0.63 (n=94)
    Zona: 19 colunas
    Importance: 0.004619
  Predicado: Ti kb <= -0.16 (n=53)
    Zona: 19 colunas
    Importance: 0.004719
  Predicado: Ti kb > -0.16 (n=65)
    Zona: 19 colunas
    Importance: 0.004779
  Predicado: Ti kb <= 0.26 (n=76)
    Zona: 19 colunas
    Importance: 0.004465
  Predicado: Ti kb > 0.26 (n=42)
    Zona: 19 colunas
    Importance: 0.005272
  Predicado: Ti kb <= 0.72 (n=97)
    Zona: 19 colunas
    Importance: 0.004856
  Predicado: Cr > -0.28 (n=92)
    Zona: 33 colunas
    Importance: 0.001423
  Predicado: Cr <= -0.12 (n=48)
    Zona: 33 colunas
    Importance: 0.001797
  Predicado: Cr > -0.12 (n=70)
    Zona: 33 colunas
    Importance: 0.001474
  Predicado: Cr <= 0.04 (n=73)
    Zona: 33 colunas
    Importance: 0.001426
  Predicado: Cr > 0.04 (n=45)
    Zona: 33 colunas
    Importance: 0.001896
  Predicado: Cr <= 0.28 (n=94)
    Zona: 33 colunas
    Importance: 0.001369
  Predicado: Mn > -0.65 (n=99)
    Zona: 18 colunas
    Importance: 0.072800
  Predicado: Mn <= -0.38 (n=45)
    Zona: 18 colunas
    Importance: 0.057075
  Predicado: Mn > -0.38 (n=73)
    Zona: 18 colunas
    Importance: 0.086738
  Predicado: Mn <= -0.15 (n=68)
    Zona: 18 colunas
    Importance: 0.039931
  Predicado: Mn > -0.15 (n=50)
    Zona: 18 colunas
    Importance: 0.123699
  Predicado: Mn <= 0.64 (n=94)
    Zona: 18 colunas
    Importance: 0.042034
  Predicado: Fe ka > -2.66 (n=92)
    Zona: 34 colunas
    Importance: 0.059210
  Predicado: Fe ka <= -0.43 (n=50)
    Zona: 34 colunas
    Importance: 0.070222
  Predicado: Fe ka > -0.43 (n=68)
    Zona: 34 colunas
    Importance: 0.060901
  Predicado: Fe ka <= 0.86 (n=73)
    Zona: 34 colunas
    Importance: 0.063571
  Predicado: Fe ka > 0.86 (n=45)
    Zona: 34 colunas
    Importance: 0.066927
  Predicado: Fe ka <= 2.21 (n=91)
    Zona: 34 colunas
    Importance: 0.061827
  Predicado: Fe kb > -1.03 (n=92)
    Zona: 26 colunas
    Importance: 0.013855
  Predicado: Fe kb <= -0.07 (n=49)
    Zona: 26 colunas
    Importance: 0.013874
  Predicado: Fe kb > -0.07 (n=69)
    Zona: 26 colunas
    Importance: 0.013451
  Predicado: Fe kb <= 0.40 (n=75)
    Zona: 26 colunas
    Importance: 0.013295
  Predicado: Fe kb > 0.40 (n=43)
    Zona: 26 colunas
    Importance: 0.014206
  Predicado: Fe kb <= 0.95 (n=91)
    Zona: 26 colunas
    Importance: 0.013881
  Predicado: background1 <= -0.16 (n=29)
    Zona: 31 colunas
    Importance: 0.001834
  Predicado: background1 > -0.16 (n=89)
    Zona: 31 colunas
    Importance: 0.001141
  Predicado: background1 <= -0.03 (n=47)
    Zona: 31 colunas
    Importance: 0.001405
  Predicado: background1 > -0.03 (n=71)
    Zona: 31 colunas
    Importance: 0.001249
  Predicado: background1 <= 0.05 (n=70)
    Zona: 31 colunas
    Importance: 0.001256
  Predicado: background1 > 0.05 (n=48)
    Zona: 31 colunas
    Importance: 0.001392
  Predicado: background1 <= 0.16 (n=95)
    Zona: 31 colunas
    Importance: 0.001283
  Predicado: Cu > -0.18 (n=93)
    Zona: 15 colunas
    Importance: 0.001806
  Predicado: Cu <= -0.06 (n=46)
    Zona: 15 colunas
    Importance: 0.002217
  Predicado: Cu > -0.06 (n=72)
    Zona: 15 colunas
    Importance: 0.001976
  Predicado: Cu <= 0.06 (n=68)
    Zona: 15 colunas
    Importance: 0.001696
  Predicado: Cu > 0.06 (n=50)
    Zona: 15 colunas
    Importance: 0.002578
  Predicado: Cu <= 0.15 (n=91)
    Zona: 15 colunas
    Importance: 0.001632
  Predicado: background2 > -0.29 (n=91)
    Zona: 125 colunas
    Importance: 0.004721
  Predicado: background2 <= -0.06 (n=47)
    Zona: 125 colunas
    Importance: 0.006754
  Predicado: background2 > -0.06 (n=71)
    Zona: 125 colunas
    Importance: 0.005243
  Predicado: background2 <= 0.12 (n=71)
    Zona: 125 colunas
    Importance: 0.005360
  Predicado: background2 > 0.12 (n=47)
    Zona: 125 colunas
    Importance: 0.006578
  Predicado: background2 <= 0.25 (n=95)
    Zona: 125 colunas
    Importance: 0.005214
  Predicado: Fe ka + Ti ka > -0.15 (n=94)
    Zona: 23 colunas
    Importance: 0.001080
  Predicado: Fe ka + Ti ka <= -0.04 (n=48)
    Zona: 23 colunas
    Importance: 0.001738
  Predicado: Fe ka + Ti ka > -0.04 (n=70)
    Zona: 23 colunas
    Importance: 0.001159
  Predicado: Fe ka + Ti ka <= 0.06 (n=70)
    Zona: 23 colunas
    Importance: 0.001416
  Predicado: Fe ka + Ti ka > 0.06 (n=48)
    Zona: 23 colunas
    Importance: 0.001362
  Predicado: Fe ka + Ti ka <= 0.16 (n=98)
    Zona: 23 colunas
    Importance: 0.001276
  Predicado: background3 > -0.17 (n=91)
    Zona: 71 colunas
    Importance: 0.003850
  Predicado: background3 <= -0.04 (n=50)
    Zona: 71 colunas
    Importance: 0.005443
  Predicado: background3 > -0.04 (n=68)
    Zona: 71 colunas
    Importance: 0.004397
  Predicado: background3 <= 0.04 (n=70)
    Zona: 71 colunas
    Importance: 0.004313
  Predicado: background3 > 0.04 (n=48)
    Zona: 71 colunas
    Importance: 0.005610
  Predicado: background3 <= 0.18 (n=96)
    Zona: 71 colunas
    Importance: 0.004345
  Predicado: sum Fe > -0.31 (n=94)
    Zona: 28 colunas
    Importance: 0.002605
  Predicado: sum Fe <= -0.04 (n=48)
    Zona: 28 colunas
    Importance: 0.004460
  Predicado: sum Fe > -0.04 (n=70)
    Zona: 28 colunas
    Importance: 0.002657
  Predicado: sum Fe <= 0.13 (n=74)
    Zona: 28 colunas
    Importance: 0.003350
  Predicado: sum Fe > 0.13 (n=44)
    Zona: 28 colunas
    Importance: 0.003459
  Predicado: sum Fe <= 0.31 (n=97)
    Zona: 28 colunas
    Importance: 0.003119

[Bag_2] Processando 120 predicados...
  Predicado: Al > -0.33 (n=95)
    Zona: 15 colunas
    Importance: 0.006544
  Predicado: Al <= -0.09 (n=49)
    Zona: 15 colunas
    Importance: 0.010502
  Predicado: Al > -0.09 (n=69)
    Zona: 15 colunas
    Importance: 0.006940
  Predicado: Al <= 0.16 (n=71)
    Zona: 15 colunas
    Importance: 0.007633
  Predicado: Al > 0.16 (n=47)
    Zona: 15 colunas
    Importance: 0.009607
  Predicado: Al <= 0.37 (n=93)
    Zona: 15 colunas
    Importance: 0.007189
  Predicado: Si > -0.66 (n=96)
    Zona: 12 colunas
    Importance: 0.060237
  Predicado: Si <= -0.20 (n=48)
    Zona: 12 colunas
    Importance: 0.076679
  Predicado: Si > -0.20 (n=70)
    Zona: 12 colunas
    Importance: 0.066816
  Predicado: Si <= 0.13 (n=73)
    Zona: 12 colunas
    Importance: 0.053628
  Predicado: Si > 0.13 (n=45)
    Zona: 12 colunas
    Importance: 0.098732
  Predicado: Si <= 0.69 (n=93)
    Zona: 12 colunas
    Importance: 0.050183
  Predicado: P > -0.24 (n=95)
    Zona: 17 colunas
    Importance: 0.003865
  Predicado: P <= -0.17 (n=45)
    Zona: 17 colunas
    Importance: 0.003003
  Predicado: P > -0.17 (n=73)
    Zona: 17 colunas
    Importance: 0.004336
  Predicado: P <= 0.01 (n=72)
    Zona: 17 colunas
    Importance: 0.002720
  Predicado: P > 0.01 (n=46)
    Zona: 17 colunas
    Importance: 0.005562
  Predicado: P <= 0.28 (n=91)
    Zona: 17 colunas
    Importance: 0.002662
  Predicado: S > -0.13 (n=91)
    Zona: 18 colunas
    Importance: 0.001917
  Predicado: S <= -0.06 (n=50)
    Zona: 18 colunas
    Importance: 0.002406
  Predicado: S > -0.06 (n=68)
    Zona: 18 colunas
    Importance: 0.002094
  Predicado: S <= 0.03 (n=73)
    Zona: 18 colunas
    Importance: 0.001865
  Predicado: S > 0.03 (n=45)
    Zona: 18 colunas
    Importance: 0.002812
  Predicado: S <= 0.12 (n=91)
    Zona: 18 colunas
    Importance: 0.001737
  Predicado: Rh L + Ar > -0.25 (n=97)
    Zona: 33 colunas
    Importance: 0.002255
  Predicado: Rh L + Ar <= -0.05 (n=42)
    Zona: 33 colunas
    Importance: 0.002208
  Predicado: Rh L + Ar > -0.05 (n=76)
    Zona: 33 colunas
    Importance: 0.002443
  Predicado: Rh L + Ar <= 0.09 (n=68)
    Zona: 33 colunas
    Importance: 0.002285
  Predicado: Rh L + Ar > 0.09 (n=50)
    Zona: 33 colunas
    Importance: 0.002460
  Predicado: Rh L + Ar <= 0.23 (n=93)
    Zona: 33 colunas
    Importance: 0.002270
  Predicado: K > -0.38 (n=94)
    Zona: 16 colunas
    Importance: 0.009821
  Predicado: K <= -0.20 (n=45)
    Zona: 16 colunas
    Importance: 0.008853
  Predicado: K > -0.20 (n=73)
    Zona: 16 colunas
    Importance: 0.011085
  Predicado: K <= 0.02 (n=69)
    Zona: 16 colunas
    Importance: 0.006374
  Predicado: K > 0.02 (n=49)
    Zona: 16 colunas
    Importance: 0.015668
  Predicado: K <= 0.39 (n=93)
    Zona: 16 colunas
    Importance: 0.006617
  Predicado: Ca ka > -1.73 (n=92)
    Zona: 16 colunas
    Importance: 0.144804
  Predicado: Ca ka <= -1.02 (n=48)
    Zona: 16 colunas
    Importance: 0.086517
  Predicado: Ca ka > -1.02 (n=70)
    Zona: 16 colunas
    Importance: 0.172917
  Predicado: Ca ka <= -0.36 (n=71)
    Zona: 16 colunas
    Importance: 0.063208
  Predicado: Ca ka > -0.36 (n=47)
    Zona: 16 colunas
    Importance: 0.250409
  Predicado: Ca ka <= 1.21 (n=91)
    Zona: 16 colunas
    Importance: 0.068923
  Predicado: Ca kb > -0.37 (n=94)
    Zona: 27 colunas
    Importance: 0.008185
  Predicado: Ca kb <= -0.23 (n=48)
    Zona: 27 colunas
    Importance: 0.005488
  Predicado: Ca kb > -0.23 (n=70)
    Zona: 27 colunas
    Importance: 0.009774
  Predicado: Ca kb <= -0.04 (n=71)
    Zona: 27 colunas
    Importance: 0.004062
  Predicado: Ca kb > -0.04 (n=47)
    Zona: 27 colunas
    Importance: 0.014024
  Predicado: Ca kb <= 0.29 (n=90)
    Zona: 27 colunas
    Importance: 0.004433
  Predicado: Ti ka > -1.78 (n=99)
    Zona: 19 colunas
    Importance: 0.032612
  Predicado: Ti ka <= -0.57 (n=42)
    Zona: 19 colunas
    Importance: 0.033988
  Predicado: Ti ka > -0.57 (n=76)
    Zona: 19 colunas
    Importance: 0.033984
  Predicado: Ti ka <= 0.93 (n=67)
    Zona: 19 colunas
    Importance: 0.034263
  Predicado: Ti ka > 0.93 (n=51)
    Zona: 19 colunas
    Importance: 0.033621
  Predicado: Ti ka <= 1.88 (n=91)
    Zona: 19 colunas
    Importance: 0.033670
  Predicado: Ti kb > -0.63 (n=97)
    Zona: 19 colunas
    Importance: 0.004735
  Predicado: Ti kb <= -0.16 (n=44)
    Zona: 19 colunas
    Importance: 0.004953
  Predicado: Ti kb > -0.16 (n=74)
    Zona: 19 colunas
    Importance: 0.004810
  Predicado: Ti kb <= 0.26 (n=68)
    Zona: 19 colunas
    Importance: 0.004616
  Predicado: Ti kb > 0.26 (n=50)
    Zona: 19 colunas
    Importance: 0.005200
  Predicado: Ti kb <= 0.72 (n=92)
    Zona: 19 colunas
    Importance: 0.004862
  Predicado: Cr > -0.28 (n=94)
    Zona: 33 colunas
    Importance: 0.001313
  Predicado: Cr <= -0.12 (n=47)
    Zona: 33 colunas
    Importance: 0.001618
  Predicado: Cr > -0.12 (n=71)
    Zona: 33 colunas
    Importance: 0.001393
  Predicado: Cr <= 0.04 (n=73)
    Zona: 33 colunas
    Importance: 0.001284
  Predicado: Cr > 0.04 (n=45)
    Zona: 33 colunas
    Importance: 0.001805
  Predicado: Cr <= 0.28 (n=98)
    Zona: 33 colunas
    Importance: 0.001216
  Predicado: Mn > -0.65 (n=93)
    Zona: 18 colunas
    Importance: 0.072932
  Predicado: Mn <= -0.38 (n=47)
    Zona: 18 colunas
    Importance: 0.058833
  Predicado: Mn > -0.38 (n=71)
    Zona: 18 colunas
    Importance: 0.085099
  Predicado: Mn <= -0.15 (n=72)
    Zona: 18 colunas
    Importance: 0.040762
  Predicado: Mn > -0.15 (n=46)
    Zona: 18 colunas
    Importance: 0.127657
  Predicado: Mn <= 0.64 (n=95)
    Zona: 18 colunas
    Importance: 0.043734
  Predicado: Fe ka > -2.66 (n=93)
    Zona: 34 colunas
    Importance: 0.061024
  Predicado: Fe ka <= -0.43 (n=45)
    Zona: 34 colunas
    Importance: 0.067490
  Predicado: Fe ka > -0.43 (n=73)
    Zona: 34 colunas
    Importance: 0.062231
  Predicado: Fe ka <= 0.86 (n=68)
    Zona: 34 colunas
    Importance: 0.058249
  Predicado: Fe ka > 0.86 (n=50)
    Zona: 34 colunas
    Importance: 0.072379
  Predicado: Fe ka <= 2.21 (n=93)
    Zona: 34 colunas
    Importance: 0.057920
  Predicado: Fe kb > -1.03 (n=94)
    Zona: 26 colunas
    Importance: 0.013405
  Predicado: Fe kb <= -0.07 (n=45)
    Zona: 26 colunas
    Importance: 0.013499
  Predicado: Fe kb > -0.07 (n=73)
    Zona: 26 colunas
    Importance: 0.013147
  Predicado: Fe kb <= 0.40 (n=69)
    Zona: 26 colunas
    Importance: 0.012400
  Predicado: Fe kb > 0.40 (n=49)
    Zona: 26 colunas
    Importance: 0.014522
  Predicado: Fe kb <= 0.95 (n=93)
    Zona: 26 colunas
    Importance: 0.013001
  Predicado: background1 > -0.16 (n=91)
    Zona: 31 colunas
    Importance: 0.001148
  Predicado: background1 <= -0.03 (n=50)
    Zona: 31 colunas
    Importance: 0.001363
  Predicado: background1 > -0.03 (n=68)
    Zona: 31 colunas
    Importance: 0.001239
  Predicado: background1 <= 0.05 (n=76)
    Zona: 31 colunas
    Importance: 0.001211
  Predicado: background1 > 0.05 (n=42)
    Zona: 31 colunas
    Importance: 0.001437
  Predicado: background1 <= 0.16 (n=96)
    Zona: 31 colunas
    Importance: 0.001198
  Predicado: Cu > -0.18 (n=93)
    Zona: 15 colunas
    Importance: 0.001791
  Predicado: Cu <= -0.06 (n=49)
    Zona: 15 colunas
    Importance: 0.002143
  Predicado: Cu > -0.06 (n=69)
    Zona: 15 colunas
    Importance: 0.002005
  Predicado: Cu <= 0.06 (n=72)
    Zona: 15 colunas
    Importance: 0.001655
  Predicado: Cu > 0.06 (n=46)
    Zona: 15 colunas
    Importance: 0.002700
  Predicado: Cu <= 0.15 (n=95)
    Zona: 15 colunas
    Importance: 0.001613
  Predicado: background2 > -0.29 (n=93)
    Zona: 125 colunas
    Importance: 0.004816
  Predicado: background2 <= -0.06 (n=50)
    Zona: 125 colunas
    Importance: 0.006277
  Predicado: background2 > -0.06 (n=68)
    Zona: 125 colunas
    Importance: 0.005577
  Predicado: background2 <= 0.12 (n=73)
    Zona: 125 colunas
    Importance: 0.005272
  Predicado: background2 > 0.12 (n=45)
    Zona: 125 colunas
    Importance: 0.006850
  Predicado: background2 <= 0.25 (n=94)
    Zona: 125 colunas
    Importance: 0.005078
  Predicado: Fe ka + Ti ka > -0.15 (n=96)
    Zona: 23 colunas
    Importance: 0.001171
  Predicado: Fe ka + Ti ka <= -0.04 (n=44)
    Zona: 23 colunas
    Importance: 0.001737
  Predicado: Fe ka + Ti ka > -0.04 (n=74)
    Zona: 23 colunas
    Importance: 0.001245
  Predicado: Fe ka + Ti ka <= 0.06 (n=68)
    Zona: 23 colunas
    Importance: 0.001386
  Predicado: Fe ka + Ti ka > 0.06 (n=50)
    Zona: 23 colunas
    Importance: 0.001487
  Predicado: Fe ka + Ti ka <= 0.16 (n=92)
    Zona: 23 colunas
    Importance: 0.001283
  Predicado: background3 > -0.17 (n=91)
    Zona: 71 colunas
    Importance: 0.003722

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka > -0.36,Ca ka > -0.36,Ca ka > -0.36,Ca ka > -0.36
1,Ca ka > -1.02,Mn > -0.15,Ca ka > -1.02,Mn > 0.64
2,Ca ka > -1.73,Ca ka > -1.02,Mn > -0.15,Ca ka > -1.02
3,Mn > -0.15,Ca ka > -1.73,Si > 0.13,Ca ka > -1.73
4,Mn > -0.38,Si > 0.13,Ca ka > -1.73,Mn > -0.15
...,...,...,...,...
124,Fe ka + Ti ka > -0.04,NaN,Fe ka + Ti ka > -0.15,Fe ka + Ti ka > -0.15
125,background1 <= 0.16,NaN,Class_A,Class_A
126,Fe ka + Ti ka > -0.15,NaN,Class_B,Class_B
127,Class_A,NaN,NaN,NaN
128,Class_B,NaN,NaN,NaN

In [99]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                 Predicate  Perturbation
0            Ca ka > -0.36      0.233097
1            Ca ka > -1.02      0.169248
2            Ca ka > -1.73      0.140496
3               Mn > -0.15      0.123699
4                Si > 0.13      0.088038
..                     ...           ...
118    background1 <= 0.05      0.001256
119    background1 > -0.03      0.001249
120  Fe ka + Ti ka > -0.04      0.001159
121    background1 > -0.16      0.001141
122  Fe ka + Ti ka > -0.15      0.001080

[123 rows x 2 columns]

In [100]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -0.36,9.738977,Ca ka,-0.36,>
1,Mn > 0.64,8.149500,Mn,0.64,>
2,Si > 0.13,3.827714,Si,0.13,>
3,Fe ka <= -2.66,2.928575,Fe ka,-2.66,<=
4,Ti ka > 0.93,0.730139,Ti ka,0.93,>
5,Fe kb <= -0.07,0.398422,Fe kb,-0.07,<=
6,K > 0.02,0.367059,K,0.02,>
7,Al <= -0.09,0.347074,Al,-0.09,<=
8,Ca kb > -0.04,0.309303,Ca kb,-0.04,>
9,background2 <= -0.29,0.243803,background2,-0.29,<=
10,background3 <= -0.17,0.179245,background3,-0.17,<=
11,Ti kb <= 0.72,0.090495,Ti kb,0.72,<=
12,P > 0.01,0.081051,P,0.01,>
13,sum Fe <= -0.04,0.074109,sum Fe,-0.04,<=
14,S > 0.12,0.062444,S,0.12,>
15,Cu <= -0.18,0.030255,Cu,-0.18,<=
16,Rh L + Ar > 0.09,0.020595,Rh L + Ar,0.09,>
17,Cr <= -0.28,0.019353,Cr,-0.28,<=
18,Fe ka + Ti ka <= -0.04,0.018300,Fe ka + Ti ka,-0.04,<=
19,background1 <= -0.16,0.015031,background1,-0.16,<=
20,Class_B,0.000000,None,None,None

In [101]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -0.36,9.738977,Ca ka,-0.36,>,-0.641296,49.0,0.004141,Ca ka > -0.641296
1,Mn > 0.64,8.149500,Mn,0.64,>,1.293607,104.0,0.014336,Mn > 1.293607
2,Ca ka > -1.02,6.401255,Ca ka,-1.02,>,-1.635267,143.0,0.000757,Ca ka > -1.635267
3,Ca ka > -1.73,5.019360,Ca ka,-1.73,>,-2.806273,140.0,0.001954,Ca ka > -2.806273
4,Mn > -0.15,4.895011,Mn,-0.15,>,-0.357226,56.0,0.003096,Mn > -0.357226
...,...,...,...,...,...,...,...,...,...
131,Fe ka + Ti ka > -0.04,0.007072,Fe ka + Ti ka,-0.04,>,-0.040286,48.0,0.000022,Fe ka + Ti ka > -0.040286
132,background1 > -0.16,0.006099,background1,-0.16,>,-0.141474,2.0,0.000536,background1 > -0.141474
133,Fe ka + Ti ka > -0.15,0.003055,Fe ka + Ti ka,-0.15,>,-0.137035,129.0,0.007042,Fe ka + Ti ka > -0.137035
134,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
135,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [102]:
import plotly.graph_objects as go

n = 1
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Mn':
  - Dimensão: 18 variáveis espectrais
  - Variância explicada pela PC1: 93.26%

In [103]:
# Permutation importance baseado em mudança nas predições do modelo PLS
# Medimos a média da diferença absoluta entre as predições originais e as predições
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Predições base do modelo PLS
baseline_pred = pls_model.predict(Xcalclass_prep)
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_pred = pls_model.predict(X_perm)
        diffs.append(np.mean(np.abs(baseline_pred - perm_pred)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance': importance_list
})
permutation_df.sort_values(by='Permutation_importance', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance', ascending=False)
permutation_unique_df

   energy  Permutation_importance           Zone
0     3.7                0.033093          Ca ka
1    1.74                0.020366             Si
2    6.42                0.019398          Fe ka
3     5.9                0.018689             Mn
4    4.46                0.018559          Ti ka
5    7.02                0.005123          Fe kb
6    1.48                0.003036             Al
7    5.02                0.002826          Ti kb
8     3.3                0.002801              K
9       4                0.002580          Ca kb
10   2.02                0.002075              P
11  12.84                0.001843         sum Fe
12   2.28                0.000937              S
13   8.04                0.000855             Cu
14   2.68                0.000754      Rh L + Ar
15   9.38                0.000725    background2
16   5.22                0.000703             Cr
17    7.4                0.000666    background1
18  12.12                0.000576    background3
19   10.9                0.000479  Fe ka + Ti ka
20   1.32                0.000231            NaN

In [104]:
import numpy as np

max_len = max(
    len(vip_scores_unique_df['Zone']),
    len(reg_vet_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'VIP_Score': pad_list(vip_scores_unique_df['Zone'], max_len),
    'Reg_Coefficient' : pad_list(reg_vet_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,VIP_Score,Reg_Coefficient,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Ca ka,Mn,Ca ka,Ca ka,Ca ka,Ca ka
1,Fe ka,Si,Fe ka,Si,Mn,Fe ka
2,Mn,Ca ka,Mn,Fe ka,Si,Ti ka
3,Si,Ti ka,Si,Mn,Fe ka,Mn
4,Fe kb,Fe ka,Ti ka,Ti ka,Ti ka,Ca kb
5,Ca kb,P,Fe kb,Fe kb,Fe kb,Si
6,Ti ka,K,Ti kb,Al,K,Fe kb
7,Al,Al,Al,Ti kb,Al,K
8,K,Ca kb,K,K,Ca kb,Al
9,sum Fe,sum Fe,P,Ca kb,background2,Ti kb
10,P,Ti kb,Fe ka + Ti ka,P,background3,sum Fe
11,Ti kb,background2,NaN,sum Fe,Ti kb,P
12,Cr,S,S,S,P,Cr
13,S,Fe kb,Ca kb,Cu,sum Fe,S
14,background2,Rh L + Ar,Rh L + Ar,Rh L + Ar,S,background2
15,Rh L + Ar,background3,background2,background2,Cu,background1
16,background3,Cu,sum Fe,Cr,Rh L + Ar,background3
17,Cu,background1,background3,background1,Cr,Rh L + Ar
18,background1,Cr,background1,background3,Fe ka + Ti ka,Cu
19,Fe ka + Ti ka,Fe ka + Ti ka,Cu,Fe ka + Ti ka,background1,Fe ka + Ti ka
20,NaN,NaN,Cr,NaN,None,None

In [105]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_22248\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

            Method_1          Method_2  RBO_Score
1          VIP_Score              Shap   0.936470
11              Shap    LRC_covariance   0.859867
4          VIP_Score    LRC_covariance   0.855513
9               Shap       Permutation   0.811500
12       Permutation  LRC_perturbation   0.806490
10              Shap  LRC_perturbation   0.805279
3          VIP_Score  LRC_perturbation   0.785602
2          VIP_Score       Permutation   0.783680
13       Permutation    LRC_covariance   0.756078
14  LRC_perturbation    LRC_covariance   0.710877
7    Reg_Coefficient  LRC_perturbation   0.520151
6    Reg_Coefficient       Permutation   0.461099
5    Reg_Coefficient              Shap   0.356099
0          VIP_Score   Reg_Coefficient   0.336421
8    Reg_Coefficient    LRC_covariance   0.294614

In [106]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')