In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/milk/plsda/milk.csv', sep=';') # local copy of Toledo 2022 dataset
data = data_complete.loc[:, '2.66':'22.62']

# Creating a new column 'Class' based on the condition of the samples in the 'Type' column being 'Authentic'
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '2.66':'22.62'], test_size=0.30) # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '2.66':'22.62'], test_size=0.30) # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True) # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0]) # creating the target variable for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0]) # creating the target variable for prediction set

# preprocessings
import preprocessings as prepr # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:42:19,008 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:42:19,042 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:42:19,112 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:42:19,212 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,0.970149,0.994048,0.93,"[[93, 7], [1, 167]]",0.843478,0.847222,0.837209,"[[36, 7], [11, 61]]"

## Definição das Zonas Espectrais

In [3]:
# establishing spectral cuts based on expert knowledge of XRF spectra
spectral_cuts = [
('Ag La', 2.66, 3.10),
('Ag Lb', 3.10, 3.46),
('Ca', 3.46, 3.92),
('background', 3.92, 6.12),
('Fe', 6.12, 6.68),
('Cu', 6.70, 8.37),
('Zn', 8.37, 9.10),
('Bremsstrahlung', 9.10, 20.06),
('Ag compton', 20.06, 21.62),
('Ag ka', 21.48, 22.62)
]

## Pvector and SHAP

In [4]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df

  energy    Pvector            Zone
0  22.23  72.456491           Ag ka
1   2.99  54.182196           Ag La
2   8.75  43.305839              Zn
3   3.22  41.848390           Ag Lb
4  17.99  38.304185  Bremsstrahlung
5   6.42  36.324355              Fe
6  21.41  29.586439      Ag compton
7   4.81  26.811026      background
8   3.89  26.299280              Ca
9   7.80  23.374915              Cu

In [5]:
shap_global_importance = pd.read_csv('shap_milk.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

   energy  Mean_Abs_SHAP            Zone
0    2.99       0.029420           Ag La
1   22.23       0.017223           Ag ka
2    3.20       0.011185           Ag Lb
3   17.99       0.001372  Bremsstrahlung
4    8.73       0.001075              Zn
5   21.41       0.000739      Ag compton
6    6.35       0.000516              Fe
7    3.89       0.000282              Ca
8    8.21       0.000146              Cu
9    5.45       0.000120      background

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Ag La': VE = 84.62%, dim = 18 variáveis
Zona 'Ag Lb': VE = 86.51%, dim = 15 variáveis
Zona 'Ca': VE = 21.64%, dim = 19 variáveis
Zona 'background': VE = 3.44%, dim = 87 variáveis
Zona 'Fe': VE = 12.88%, dim = 23 variáveis
Zona 'Cu': VE = 9.26%, dim = 66 variáveis
Zona 'Zn': VE = 17.17%, dim = 29 variáveis
Zona 'Bremsstrahlung': VE = 30.64%, dim = 429 variáveis
Zona 'Ag compton': VE = 52.31%, dim = 62 variáveis
Zona 'Ag ka': VE = 76.93%, dim = 45 variáveis

Scores DataFrame shape: (268, 10)

In [7]:
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(svm_model[4]['SVC'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 62
Removida: Ag Lb <= 2.36 -> Ag La <= 7.76 (5.8990) | Mantida: Ag La <= 7.76 -> Ag Lb <= 2.36 (23.3772)
Removida: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= 9.64 (0.9251) | Mantida: Bremsstrahlung <= 9.64 -> Bremsstrahlung <= 4.15 (1.4597)
Removida: Ag compton <= 6.52 -> Bremsstrahlung <= 4.15 (0.3764) | Mantida: Bremsstrahlung <= 4.15 -> Ag compton <= 6.52 (0.4336)
Removida: Bremsstrahlung <= 9.64 -> Ag ka > -7.06 (0.5450) | Mantida: Ag ka > -7.06 -> Bremsstrahlung <= 9.64 (0.7324)
Removida: Bremsstrahlung <= -1.54 -> Ag compton <= 6.52 (0.5105) | Mantida: Ag compton <= 6.52 -> Bremsstrahlung <= -1.54 (0.7718)
Removida: Ag ka <= 20.95 -> Ag ka <= -7.06 (0.5856) | Mantida: Ag ka <= -7.06 -> Ag ka <= 20.95 (0.8923)
Removida: Bremsstrahlung > -9.06 -> Ag ka <= -7.06 (0.4964) | Mantida: Ag ka <= -7.06 -> Bremsstrahlung > -9.06 (0.7780)
Removida: Ag ka <= -7.06 -> Ag ka > -11.59 (0.5804) | Mantida: Ag ka > -11.59 -> Ag ka <= -7.06 (0.9612)
Removida: Ag compton <= 6.52 -> Bremsstrahlung > -9.06 (0.4107) | Mantida: Bremsstrahlung > -9.06 -> Ag compton <= 6.52 (0.5319)
Removida: Ag ka <= 20.95 -> Ag ka > -7.06 (0.7711) | Mantida: Ag ka > -7.06 -> Ag ka <= 20.95 (2.0963)
Removida: Bremsstrahlung > -9.06 -> Ag compton <= 2.96 (0.2259) | Mantida: Ag compton <= 2.96 -> Bremsstrahlung > -9.06 (0.5968)
Removida: Bremsstrahlung > -9.06 -> Ag ka > -11.59 (0.1521) | Mantida: Ag ka > -11.59 -> Bremsstrahlung > -9.06 (0.6921)
Removida: Bremsstrahlung > -1.54 -> Ag ka > -11.59 (0.2093) | Mantida: Ag ka > -11.59 -> Bremsstrahlung > -1.54 (1.4680)
Removida: Ag compton > -6.71 -> Ag ka > -11.59 (0.2799) | Mantida: Ag ka > -11.59 -> Ag compton > -6.71 (0.3490)
Removida: Bremsstrahlung > -1.54 -> Ag compton <= 2.96 (0.1858) | Mantida: Ag compton <= 2.96 -> Bremsstrahlung > -1.54 (0.3022)
Removida: Ag compton <= 2.96 -> Bremsstrahlung > 4.15 (0.2772) | Mantida: Bremsstrahlung > 4.15 -> Ag compton <= 2.96 (0.7001)
Removida: Ag compton <= -1.09 -> Ag compton > -6.71 (0.6650) | Mantida: Ag compton > -6.71 -> Ag compton <= -1.09 (1.0554)
Removida: Ag compton > -1.09 -> Ag compton <= -1.09 (0.1689) | Mantida: Ag compton <= -1.09 -> Ag compton > -1.09 (0.2007)
Removida: Ag Lb > 2.36 -> Ag La > 2.70 (0.5062) | Mantida: Ag La > 2.70 -> Ag Lb > 2.36 (1.5051)
Removida: Ag compton > -1.09 -> Ag Lb > 2.36 (0.4413) | Mantida: Ag Lb > 2.36 -> Ag compton > -1.09 (0.9091)
Removida: Cu > 0.32 -> Ag La > -18.52 (0.0111) | Mantida: Ag La > -18.52 -> Cu > 0.32 (0.1600)
Removida: Ag La > -18.52 -> Ag ka > 5.37 (0.1466) | Mantida: Ag ka > 5.37 -> Ag La > -18.52 (0.1483)
Removida: Cu > 0.32 -> Ca <= -0.68 (0.0126) | Mantida: Ca <= -0.68 -> Cu > 0.32 (0.0276)
Removida: Fe > -1.18 -> Cu > 0.32 (0.0156) | Mantida: Cu > 0.32 -> Fe > -1.18 (0.0188)
Removida: Cu > 0.32 -> Fe > 0.31 (0.0093) | Mantida: Fe > 0.31 -> Cu > 0.32 (0.0128)
Removida: Zn > 0.56 -> Ca <= -0.68 (0.0184) | Mantida: Ca <= -0.68 -> Zn > 0.56 (0.0225)
Removida: Ca > -0.68 -> Ca <= -0.68 (0.0189) | Mantida: Ca <= -0.68 -> Ca > -0.68 (0.0206)
Removida: Zn > 0.56 -> Ag Lb > -15.87 (0.0138) | Mantida: Ag Lb > -15.87 -> Zn > 0.56 (0.1627)
Removida: Zn > 0.56 -> Fe > -0.36 (0.0159) | Mantida: Fe > -0.36 -> Zn > 0.56 (0.0204)
Removida: Ca > 0.46 -> Ag compton > 2.96 (0.0209) | Mantida: Ag compton > 2.96 -> Ca > 0.46 (0.0541)
Removida: Fe > 0.31 -> Ca > 0.46 (0.0147) | Mantida: Ca > 0.46 -> Fe > 0.31 (0.0436)
Removida: Ca > 0.46 -> Ca <= 0.46 (0.0167) | Mantida: Ca <= 0.46 -> Ca > 0.46 (0.0202)
Removida: Ca > -1.79 -> Ca > 0.46 (0.0186) | Mantida: Ca > 0.46 -> Ca > -1.79 (0.0432)
Removida: Cu > -1.74 -> Zn <= 1.56 (0.0026) | Mantida: Zn <= 1.56 -> Cu > -1.74 (0.0055)
Removida: Cu > -1.74 -> Cu > -0.64 (0.0055) | Mantida: Cu > -0.64 -> Cu > -1.74 (0.0063)
Removida: Fe > -0.36 -> Ca > -1.79 (0.0114) | Mantida: Ca > -1.79 -> Fe > -0.36 (0.0167)
Removida: Ca > -1.79 -> Ca <= 1.81 (0.0196) | Mantida: Ca <= 1.81 -> Ca > -1.79 (0.0221)
Removida: Fe > -0.36 -> Ag Lb > -15.87 (0.0072) | Mantida: Ag Lb > -15.87 -> Fe > -0.36 (0.0655)
Removida: Ca <= 1.81 -> Ca <= 0.46 (0.0191) | Mantida: Ca <= 0.46 -> Ca <= 1.81 (0.0761)
Removida: Ca <= 0.46 -> Ag Lb > 6.48 (0.0164) | Mantida: Ag Lb > 6.48 -> Ca <= 0.46 (0.0607)
Removida: Ca <= 1.81 -> Ag La > 7.76 (0.0156) | Mantida: Ag La > 7.76 -> Ca <= 1.81 (0.0431)
Removida: background > -0.46 -> Ag La > 7.76 (0.0020) | Mantida: Ag La > 7.76 -> background > -0.46 (0.0460)
Removida: Zn <= 1.56 -> Ag La > 7.76 (0.0068) | Mantida: Ag La > 7.76 -> Zn <= 1.56 (0.0293)
Removida: Zn <= -0.39 -> Cu <= 1.92 (0.0032) | Mantida: Cu <= 1.92 -> Zn <= -0.39 (0.0045)
Removida: background <= 1.29 -> Cu <= 1.92 (0.0017) | Mantida: Cu <= 1.92 -> background <= 1.29 (0.0035)
Removida: Cu > -0.64 -> Fe <= 1.20 (0.0021) | Mantida: Fe <= 1.20 -> Cu > -0.64 (0.0042)
Removida: background <= 1.29 -> Cu > -0.64 (0.0015) | Mantida: Cu > -0.64 -> background <= 1.29 (0.0081)
Removida: Zn > -0.39 -> Cu <= -0.64 (0.0026) | Mantida: Cu <= -0.64 -> Zn > -0.39 (0.0029)
Removida: Cu <= 0.32 -> Cu <= -0.64 (0.0035) | Mantida: Cu <= -0.64 -> Cu <= 0.32 (0.0051)
Removida: Cu <= -0.64 -> Zn <= 1.56 (0.0027) | Mantida: Zn <= 1.56 -> Cu <= -0.64 (0.0047)
Removida: background > -1.23 -> Ag Lb > 6.48 (0.0020) | Mantida: Ag Lb > 6.48 -> background > -1.23 (0.1303)
Removida: background > -1.23 -> Zn <= 0.56 (0.0019) | Mantida: Zn <= 0.56 -> background > -1.23 (0.0063)
Removida: background > -0.46 -> Zn > -1.47 (0.0039) | Mantida: Zn > -1.47 -> background > -0.46 (0.0103)
Removida: background > -0.46 -> Zn <= 0.56 (0.0018) | Mantida: Zn <= 0.56 -> background > -0.46 (0.0092)
Removida: background > -0.46 -> Cu <= 0.32 (0.0007) | Mantida: Cu <= 0.32 -> background > -0.46 (0.0051)
Removida: background > 0.40 -> Zn <= 1.56 (0.0014) | Mantida: Zn <= 1.56 -> background > 0.40 (0.0074)
Removida: background <= 0.40 -> Zn <= 1.56 (0.0010) | Mantida: Zn <= 1.56 -> background <= 0.40 (0.0050)
Removida: background > 0.40 -> Zn <= 0.56 (0.0024) | Mantida: Zn <= 0.56 -> background > 0.40 (0.0078)
Removida: background > 0.40 -> Fe <= 1.20 (0.0029) | Mantida: Fe <= 1.20 -> background > 0.40 (0.0042)
Removida: background <= 1.29 -> Zn <= 0.56 (0.0014) | Mantida: Zn <= 0.56 -> background <= 1.29 (0.0052)
Removida: Cu <= 0.32 -> Zn > -1.47 (0.0020) | Mantida: Zn > -1.47 -> Cu <= 0.32 (0.0090)
Removida: Zn > -0.39 -> Ag Lb > -15.87 (0.0024) | Mantida: Ag Lb > -15.87 -> Zn > -0.39 (0.0148)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 386 | Removidas: 62
Nós predicados: 60
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 73
Removida: Ag Lb <= 2.36 -> Ag La <= 7.76 (2.9910) | Mantida: Ag La <= 7.76 -> Ag Lb <= 2.36 (26.6188)
Removida: Ag ka <= -7.06 -> Ag ka <= 20.95 (0.3022) | Mantida: Ag ka <= 20.95 -> Ag ka <= -7.06 (0.8951)
Removida: Bremsstrahlung <= 9.64 -> Ag ka <= -7.06 (0.5570) | Mantida: Ag ka <= -7.06 -> Bremsstrahlung <= 9.64 (1.4016)
Removida: Bremsstrahlung <= 4.15 -> Ag ka <= -7.06 (0.5714) | Mantida: Ag ka <= -7.06 -> Bremsstrahlung <= 4.15 (0.9224)
Removida: Ag compton <= 6.52 -> Ag ka <= -7.06 (0.3787) | Mantida: Ag ka <= -7.06 -> Ag compton <= 6.52 (0.6504)
Removida: Ag ka > -7.06 -> Ag ka > -11.59 (0.8506) | Mantida: Ag ka > -11.59 -> Ag ka > -7.06 (0.8781)
Removida: Ag compton <= 2.96 -> Ag ka > -11.59 (0.2890) | Mantida: Ag ka > -11.59 -> Ag compton <= 2.96 (0.4312)
Removida: Bremsstrahlung <= 9.64 -> Ag ka > -11.59 (0.2513) | Mantida: Ag ka > -11.59 -> Bremsstrahlung <= 9.64 (0.6897)
Removida: Ag compton <= 6.52 -> Ag ka > -11.59 (0.3787) | Mantida: Ag ka > -11.59 -> Ag compton <= 6.52 (0.5619)
Removida: Bremsstrahlung <= -1.54 -> Ag ka > -7.06 (0.4103) | Mantida: Ag ka > -7.06 -> Bremsstrahlung <= -1.54 (0.7986)
Removida: Bremsstrahlung > -9.06 -> Ag ka > -7.06 (0.4502) | Mantida: Ag ka > -7.06 -> Bremsstrahlung > -9.06 (0.4957)
Removida: Bremsstrahlung <= 4.15 -> Ag ka > -7.06 (0.2518) | Mantida: Ag ka > -7.06 -> Bremsstrahlung <= 4.15 (1.5270)
Removida: Ag compton <= 6.52 -> Ag ka > -7.06 (0.4161) | Mantida: Ag ka > -7.06 -> Ag compton <= 6.52 (0.6263)
Removida: Bremsstrahlung <= 9.64 -> Bremsstrahlung <= -1.54 (0.2640) | Mantida: Bremsstrahlung <= -1.54 -> Bremsstrahlung <= 9.64 (0.8153)
Removida: Bremsstrahlung <= -1.54 -> Bremsstrahlung <= 4.15 (0.3099) | Mantida: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= -1.54 (0.5822)
Removida: Bremsstrahlung <= -1.54 -> Ag compton <= 6.52 (0.2562) | Mantida: Ag compton <= 6.52 -> Bremsstrahlung <= -1.54 (0.8309)
Removida: Bremsstrahlung <= -1.54 -> Ag ka <= 20.95 (0.2592) | Mantida: Ag ka <= 20.95 -> Bremsstrahlung <= -1.54 (1.7642)
Removida: Bremsstrahlung <= 9.64 -> Bremsstrahlung <= 4.15 (0.5492) | Mantida: Bremsstrahlung <= 4.15 -> Bremsstrahlung <= 9.64 (0.5855)
Removida: Ag compton <= 6.52 -> Ag ka <= 20.95 (0.8011) | Mantida: Ag ka <= 20.95 -> Ag compton <= 6.52 (1.2885)
Removida: Bremsstrahlung > -9.06 -> Ag compton <= 6.52 (0.2294) | Mantida: Ag compton <= 6.52 -> Bremsstrahlung > -9.06 (0.7391)
Removida: Bremsstrahlung > -9.06 -> Ag compton <= 2.96 (0.2287) | Mantida: Ag compton <= 2.96 -> Bremsstrahlung > -9.06 (0.3428)
Removida: Bremsstrahlung > -1.54 -> Ag compton <= 2.96 (0.1734) | Mantida: Ag compton <= 2.96 -> Bremsstrahlung > -1.54 (0.8361)
Removida: Ag compton > -6.71 -> Bremsstrahlung > -1.54 (0.2137) | Mantida: Bremsstrahlung > -1.54 -> Ag compton > -6.71 (0.2889)
Removida: Bremsstrahlung > 4.15 -> Bremsstrahlung > -1.54 (0.1704) | Mantida: Bremsstrahlung > -1.54 -> Bremsstrahlung > 4.15 (0.3457)
Removida: Bremsstrahlung > -1.54 -> Ag compton <= -1.09 (0.1515) | Mantida: Ag compton <= -1.09 -> Bremsstrahlung > -1.54 (0.2672)
Removida: Ag compton <= 2.96 -> Bremsstrahlung > 4.15 (0.5763) | Mantida: Bremsstrahlung > 4.15 -> Ag compton <= 2.96 (0.6549)
Removida: Ag compton > -6.71 -> Ag compton <= 2.96 (0.2807) | Mantida: Ag compton <= 2.96 -> Ag compton > -6.71 (0.2933)
Removida: Bremsstrahlung > 4.15 -> Ag compton <= -1.09 (0.1504) | Mantida: Ag compton <= -1.09 -> Bremsstrahlung > 4.15 (0.2174)
Removida: Ag compton > -6.71 -> Ag compton <= -1.09 (0.4390) | Mantida: Ag compton <= -1.09 -> Ag compton > -6.71 (1.1698)
Removida: Ag Lb > 2.36 -> Ag La > 2.70 (0.5182) | Mantida: Ag La > 2.70 -> Ag Lb > 2.36 (0.7761)
Removida: Ag compton > -1.09 -> Ag Lb > 2.36 (0.4305) | Mantida: Ag Lb > 2.36 -> Ag compton > -1.09 (0.9180)
Removida: Ag compton > -1.09 -> Ag La > 2.70 (0.1394) | Mantida: Ag La > 2.70 -> Ag compton > -1.09 (0.7682)
Removida: Ag compton > -1.09 -> Ag ka > 5.37 (0.0956) | Mantida: Ag ka > 5.37 -> Ag compton > -1.09 (0.3788)
Removida: Ca <= -0.68 -> Ag La > -18.52 (0.0209) | Mantida: Ag La > -18.52 -> Ca <= -0.68 (0.0990)
Removida: Fe > -1.18 -> Ca <= -0.68 (0.0167) | Mantida: Ca <= -0.68 -> Fe > -1.18 (0.0291)
Removida: Fe > -1.18 -> Ca > -0.68 (0.0114) | Mantida: Ca > -0.68 -> Fe > -1.18 (0.0216)
Removida: Fe > 0.31 -> Fe > -1.18 (0.0113) | Mantida: Fe > -1.18 -> Fe > 0.31 (0.0415)
Removida: Fe > -1.18 -> Ca > 0.46 (0.0164) | Mantida: Ca > 0.46 -> Fe > -1.18 (0.0202)
Removida: Ca <= 1.81 -> Ca <= -0.68 (0.0226) | Mantida: Ca <= -0.68 -> Ca <= 1.81 (0.0238)
Removida: Ca <= -0.68 -> Zn > 0.56 (0.0248) | Mantida: Zn > 0.56 -> Ca <= -0.68 (0.0309)
Removida: Ca <= 0.46 -> Ca > 0.46 (0.0260) | Mantida: Ca > 0.46 -> Ca <= 0.46 (0.0655)
Removida: Cu > 0.32 -> Fe > 0.31 (0.0104) | Mantida: Fe > 0.31 -> Cu > 0.32 (0.0155)
Removida: Cu > 0.32 -> Ag compton > 2.96 (0.0123) | Mantida: Ag compton > 2.96 -> Cu > 0.32 (0.0895)
Removida: Fe > 0.31 -> Ca > -1.79 (0.0144) | Mantida: Ca > -1.79 -> Fe > 0.31 (0.0185)
Removida: Fe > -0.36 -> Zn > 0.56 (0.0137) | Mantida: Zn > 0.56 -> Fe > -0.36 (0.0182)
Removida: Fe > -0.36 -> Ca <= 0.46 (0.0087) | Mantida: Ca <= 0.46 -> Fe > -0.36 (0.0185)
Removida: Fe > -0.36 -> Ag Lb > -15.87 (0.0106) | Mantida: Ag Lb > -15.87 -> Fe > -0.36 (0.0581)
Removida: Zn > 0.56 -> Ca > -1.79 (0.0178) | Mantida: Ca > -1.79 -> Zn > 0.56 (0.0423)
Removida: Ca <= 1.81 -> Zn > 0.56 (0.0103) | Mantida: Zn > 0.56 -> Ca <= 1.81 (0.0191)
Removida: background > -1.23 -> Zn > 0.56 (0.0030) | Mantida: Zn > 0.56 -> background > -1.23 (0.0144)
Removida: Ag compton > 2.96 -> Ag Lb > -15.87 (0.0409) | Mantida: Ag Lb > -15.87 -> Ag compton > 2.96 (0.2081)
Removida: Ca > -0.68 -> Ca <= 1.81 (0.0161) | Mantida: Ca <= 1.81 -> Ca > -0.68 (0.0451)
Removida: background > -1.23 -> Ca <= 0.46 (0.0024) | Mantida: Ca <= 0.46 -> background > -1.23 (0.0136)
Removida: Cu <= 0.32 -> Ca <= 1.81 (0.0053) | Mantida: Ca <= 1.81 -> Cu <= 0.32 (0.0138)
Removida: background > 0.40 -> Cu <= 0.32 (0.0012) | Mantida: Cu <= 0.32 -> background > 0.40 (0.0051)
Removida: Cu <= 0.32 -> Ag La > 7.76 (0.0051) | Mantida: Ag La > 7.76 -> Cu <= 0.32 (0.0338)
Removida: background > 0.40 -> Zn <= -0.39 (0.0021) | Mantida: Zn <= -0.39 -> background > 0.40 (0.0050)
Removida: background > -0.46 -> Zn <= 0.56 (0.0019) | Mantida: Zn <= 0.56 -> background > -0.46 (0.0078)
Removida: background > -0.46 -> Ag Lb > 6.48 (0.0028) | Mantida: Ag Lb > 6.48 -> background > -0.46 (0.0691)
Removida: background > -0.46 -> Zn > -1.47 (0.0021) | Mantida: Zn > -1.47 -> background > -0.46 (0.0075)
Removida: Zn <= 0.56 -> Ag La > 7.76 (0.0107) | Mantida: Ag La > 7.76 -> Zn <= 0.56 (0.0385)
Removida: Zn > -0.39 -> Zn <= 1.56 (0.0054) | Mantida: Zn <= 1.56 -> Zn > -0.39 (0.0061)
Removida: Fe <= 0.31 -> Zn <= 1.56 (0.0016) | Mantida: Zn <= 1.56 -> Fe <= 0.31 (0.0049)
Removida: Cu > -0.64 -> Zn > -0.39 (0.0032) | Mantida: Zn > -0.39 -> Cu > -0.64 (0.0053)
Removida: Cu > -0.64 -> Cu > -1.74 (0.0032) | Mantida: Cu > -1.74 -> Cu > -0.64 (0.0125)
Removida: background <= 1.29 -> Zn > -1.47 (0.0018) | Mantida: Zn > -1.47 -> background <= 1.29 (0.0102)
Removida: Fe <= -0.36 -> Zn <= -0.39 (0.0039) | Mantida: Zn <= -0.39 -> Fe <= -0.36 (0.0063)
Removida: background <= 0.40 -> Zn <= -0.39 (0.0005) | Mantida: Zn <= -0.39 -> background <= 0.40 (0.0040)
Removida: background <= 0.40 -> Cu <= -0.64 (0.0008) | Mantida: Cu <= -0.64 -> background <= 0.40 (0.0040)
Removida: background <= 1.29 -> Cu > -0.64 (0.0014) | Mantida: Cu > -0.64 -> background <= 1.29 (0.0078)
Removida: background <= 1.29 -> Ag Lb > 6.48 (0.0033) | Mantida: Ag Lb > 6.48 -> background <= 1.29 (0.0332)
Removida: Fe <= 0.31 -> Fe <= -0.36 (0.0026) | Mantida: Fe <= -0.36 -> Fe <= 0.31 (0.0039)
Removida: background <= 0.40 -> Fe <= -0.36 (0.0006) | Mantida: Fe <= -0.36 -> background <= 0.40 (0.0018)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 392 | Removidas: 73
Nós predicados: 60
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 2
======================================================================


Total de pares bidirecionais encontrados: 72
Removida: Ag La <= 7.76 -> Ag La <= 2.70 (3.1529) | Mantida: Ag La <= 2.70 -> Ag La <= 7.76 (29.6066)
Removida: Bremsstrahlung > -9.06 -> Ag compton <= 6.52 (0.8030) | Mantida: Ag compton <= 6.52 -> Bremsstrahlung > -9.06 (1.0960)
Removida: Ag ka > -11.59 -> Bremsstrahlung > -9.06 (0.6780) | Mantida: Bremsstrahlung > -9.06 -> Ag ka > -11.59 (0.7334)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70
1,Ag La <= 7.76,Ag La <= 7.76,Ag La <= 7.76,Ag La <= 7.76
2,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36
3,Ag Lb <= 6.48,Ag Lb <= 6.48,Ag Lb <= 6.48,Ag Lb <= 6.48
4,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 9.01
...,...,...,...,...
57,background <= -0.46,background > 0.40,background <= 1.29,Fe <= -0.36
58,background <= 0.40,Cu > -0.64,Zn <= 0.56,Fe <= 1.20
59,Cu <= -0.64,Cu <= -0.64,background <= 0.40,Fe <= 0.31
60,Class_A,Class_A,Class_A,Class_A
61,Class_B,Class_B,Class_B,Class_B

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ag La <= 2.70,22.172710,Ag La,2.70,<=
1,Ag Lb <= 2.36,16.674586,Ag Lb,2.36,<=
2,Ag ka <= 5.37,1.632236,Ag ka,5.37,<=
3,Bremsstrahlung <= 9.64,0.941964,Bremsstrahlung,9.64,<=
4,Ag compton <= 6.52,0.893456,Ag compton,6.52,<=
5,Ca <= 0.46,0.226601,Ca,0.46,<=
6,Zn <= 1.56,0.207514,Zn,1.56,<=
7,Cu > -1.74,0.199377,Cu,-1.74,>
8,background <= 1.29,0.192872,background,1.29,<=
9,Fe > -0.36,0.191654,Fe,-0.36,>
10,Class_B,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Ag La': VE = 91.39%, dim = 18 variáveis
Zona 'Ag Lb': VE = 90.27%, dim = 15 variáveis
Zona 'Ca': VE = 27.70%, dim = 19 variáveis
Zona 'background': VE = 3.72%, dim = 87 variáveis
Zona 'Fe': VE = 14.68%, dim = 23 variáveis
Zona 'Cu': VE = 15.48%, dim = 66 variáveis
Zona 'Zn': VE = 21.60%, dim = 29 variáveis
Zona 'Bremsstrahlung': VE = 38.87%, dim = 429 variáveis
Zona 'Ag compton': VE = 52.69%, dim = 62 variáveis
Zona 'Ag ka': VE = 80.83%, dim = 45 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ag La <= 2.70,22.172710,Ag La,2.70,<=,34.935039,86.0,0.021418,Ag La <= 34.935039
1,Ag La <= 7.76,19.357224,Ag La,7.76,<=,105.814886,78.0,0.002963,Ag La <= 105.814886
2,Ag Lb <= 2.36,16.674586,Ag Lb,2.36,<=,30.578162,0.0,0.008013,Ag Lb <= 30.578162
3,Ag Lb <= 6.48,13.467024,Ag Lb,6.48,<=,75.496450,98.0,0.013050,Ag Lb <= 75.496450
4,Ag La <= 9.01,9.754684,Ag La,9.01,<=,126.903607,239.0,0.004801,Ag La <= 126.903607
...,...,...,...,...,...,...,...,...,...
57,background <= 0.40,0.150688,background,0.40,<=,4.852293,186.0,0.003287,background <= 4.852293
58,Fe <= 0.31,0.143087,Fe,0.31,<=,3.353626,32.0,0.003765,Fe <= 3.353626
59,Cu <= -0.64,0.139218,Cu,-0.64,<=,-1.435498,17.0,0.000042,Cu <= -1.435498
60,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
61,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ag La':
  - Dimensão: 18 variáveis espectrais
  - Range de energias: 2.66 - 3.10
  - Variância explicada pela PC1: 91.39%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 60 | Descartados: 20
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 60 predicados...
  Predicado: Ag La > -18.52 (n=176)
    Zona: 18 colunas
    Importance: 0.058394
  Predicado: Ag La <= 2.70 (n=81)
    Zona: 18 colunas
    Importance: 0.289430
  Predicado: Ag La > 2.70 (n=133)
    Zona: 18 colunas
    Importance: 0.032110
  Predicado: Ag La <= 7.76 (n=130)
    Zona: 18 colunas
    Importance: 0.187870
  Predicado: Ag La > 7.76 (n=84)
    Zona: 18 colunas
    Importance: 0.039184
  Predicado: Ag La <= 9.01 (n=171)
    Zona: 18 colunas
    Importance: 0.151268
  Predicado: Ag Lb > -15.87 (n=173)
    Zona: 15 colunas
    Importance: 0.040460
  Predicado: Ag Lb <= 2.36 (n=82)
    Zona: 15 colunas
    Importance: 0.216438
  Predicado: Ag Lb > 2.36 (n=132)
    Zona: 15 colunas
    Importance: 0.027509
  Predicado: Ag Lb <= 6.48 (n=129)
    Zona: 15 colunas
    Importance: 0.142517
  Predicado: Ag Lb > 6.48 (n=85)
    Zona: 15 colunas
    Importance: 0.035230
  Predicado: Ag Lb <= 8.04 (n=170)
    Zona: 15 colunas
    Importance: 0.114055
  Predicado: Ca > -1.79 (n=172)
    Zona: 19 colunas
    Importance: 0.004625
  Predicado: Ca <= -0.68 (n=85)
    Zona: 19 colunas
    Importance: 0.005512
  Predicado: Ca > -0.68 (n=129)
    Zona: 19 colunas
    Importance: 0.004959
  Predicado: Ca <= 0.46 (n=128)
    Zona: 19 colunas
    Importance: 0.004884
  Predicado: Ca > 0.46 (n=86)
    Zona: 19 colunas
    Importance: 0.005618
  Predicado: Ca <= 1.81 (n=175)
    Zona: 19 colunas
    Importance: 0.004696
  Predicado: background > -1.23 (n=175)
    Zona: 87 colunas
    Importance: 0.014765
  Predicado: background <= -0.46 (n=84)
    Zona: 87 colunas
    Importance: 0.011561
  Predicado: background > -0.46 (n=130)
    Zona: 87 colunas
    Importance: 0.014935
  Predicado: background <= 0.40 (n=127)
    Zona: 87 colunas
    Importance: 0.012796
  Predicado: background > 0.40 (n=87)
    Zona: 87 colunas
    Importance: 0.014800
  Predicado: background <= 1.29 (n=172)
    Zona: 87 colunas
    Importance: 0.014373
  Predicado: Fe > -1.18 (n=173)
    Zona: 23 colunas
    Importance: 0.005918
  Predicado: Fe <= -0.36 (n=81)
    Zona: 23 colunas
    Importance: 0.006248
  Predicado: Fe > -0.36 (n=133)
    Zona: 23 colunas
    Importance: 0.006087
  Predicado: Fe <= 0.31 (n=122)
    Zona: 23 colunas
    Importance: 0.005669
  Predicado: Fe > 0.31 (n=92)
    Zona: 23 colunas
    Importance: 0.006783
  Predicado: Fe <= 1.20 (n=167)
    Zona: 23 colunas
    Importance: 0.005393
  Predicado: Cu > -1.74 (n=167)
    Zona: 66 colunas
    Importance: 0.009868
  Predicado: Cu <= -0.64 (n=86)
    Zona: 66 colunas
    Importance: 0.009647
  Predicado: Cu > -0.64 (n=128)
    Zona: 66 colunas
    Importance: 0.010424
  Predicado: Cu <= 0.32 (n=125)
    Zona: 66 colunas
    Importance: 0.010285
  Predicado: Cu > 0.32 (n=89)
    Zona: 66 colunas
    Importance: 0.009868
  Predicado: Cu <= 1.92 (n=167)
    Zona: 66 colunas
    Importance: 0.010436
  Predicado: Zn > -1.47 (n=174)
    Zona: 29 colunas
    Importance: 0.008608
  Predicado: Zn <= -0.39 (n=82)
    Zona: 29 colunas
    Importance: 0.007200
  Predicado: Zn > -0.39 (n=132)
    Zona: 29 colunas
    Importance: 0.008669
  Predicado: Zn <= 0.56 (n=130)
    Zona: 29 colunas
    Importance: 0.007110
  Predicado: Zn > 0.56 (n=84)
    Zona: 29 colunas
    Importance: 0.009647
  Predicado: Zn <= 1.56 (n=171)
    Zona: 29 colunas
    Importance: 0.007186
  Predicado: Bremsstrahlung > -9.06 (n=170)
    Zona: 429 colunas
    Importance: 0.081718
  Predicado: Bremsstrahlung <= -1.54 (n=84)
    Zona: 429 colunas
    Importance: 0.123205
  Predicado: Bremsstrahlung > -1.54 (n=130)
    Zona: 429 colunas
    Importance: 0.064980
  Predicado: Bremsstrahlung <= 4.15 (n=127)
    Zona: 429 colunas
    Importance: 0.100793
  Predicado: Bremsstrahlung > 4.15 (n=87)
    Zona: 429 colunas
    Importance: 0.068919
  Predicado: Bremsstrahlung <= 9.64 (n=166)
    Zona: 429 colunas
    Importance: 0.094130
  Predicado: Ag compton > -6.71 (n=174)
    Zona: 62 colunas
    Importance: 0.018133
  Predicado: Ag compton <= -1.09 (n=83)
    Zona: 62 colunas
    Importance: 0.021794
  Predicado: Ag compton > -1.09 (n=131)
    Zona: 62 colunas
    Importance: 0.017902
  Predicado: Ag compton <= 2.96 (n=127)
    Zona: 62 colunas
    Importance: 0.019990
  Predicado: Ag compton > 2.96 (n=87)
    Zona: 62 colunas
    Importance: 0.018568
  Predicado: Ag compton <= 6.52 (n=168)
    Zona: 62 colunas
    Importance: 0.018805
  Predicado: Ag ka > -11.59 (n=174)
    Zona: 45 colunas
    Importance: 0.075852
  Predicado: Ag ka <= -7.06 (n=85)
    Zona: 45 colunas
    Importance: 0.107659
  Predicado: Ag ka > -7.06 (n=129)
    Zona: 45 colunas
    Importance: 0.072167
  Predicado: Ag ka <= 5.37 (n=126)
    Zona: 45 colunas
    Importance: 0.088126
  Predicado: Ag ka > 5.37 (n=88)
    Zona: 45 colunas
    Importance: 0.083599
  Predicado: Ag ka <= 20.95 (n=168)
    Zona: 45 colunas
    Importance: 0.083795

[Bag_2] Processando 60 predicados...
  Predicado: Ag La > -18.52 (n=170)
    Zona: 18 colunas
    Importance: 0.053884
  Predicado: Ag La <= 2.70 (n=87)
    Zona: 18 colunas
    Importance: 0.298066
  Predicado: Ag La > 2.70 (n=127)
    Zona: 18 colunas
    Importance: 0.030717
  Predicado: Ag La <= 7.76 (n=132)
    Zona: 18 colunas
    Importance: 0.203484
  Predicado: Ag La > 7.76 (n=82)
    Zona: 18 colunas
    Importance: 0.036254
  Predicado: Ag La <= 9.01 (n=175)
    Zona: 18 colunas
    Importance: 0.161114
  Predicado: Ag Lb > -15.87 (n=171)
    Zona: 15 colunas
    Importance: 0.044632
  Predicado: Ag Lb <= 2.36 (n=87)
    Zona: 15 colunas
    Importance: 0.220896
  Predicado: Ag Lb > 2.36 (n=127)
    Zona: 15 colunas
    Importance: 0.025578
  Predicado: Ag Lb <= 6.48 (n=131)
    Zona: 15 colunas
    Importance: 0.151264
  Predicado: Ag Lb > 6.48 (n=83)
    Zona: 15 colunas
    Importance: 0.031936
  Predicado: Ag Lb <= 8.04 (n=174)
    Zona: 15 colunas
    Importance: 0.119713
  Predicado: Ca > -1.79 (n=165)
    Zona: 19 colunas
    Importance: 0.004647
  Predicado: Ca <= -0.68 (n=83)
    Zona: 19 colunas
    Importance: 0.005245
  Predicado: Ca > -0.68 (n=131)
    Zona: 19 colunas
    Importance: 0.004888
  Predicado: Ca <= 0.46 (n=128)
    Zona: 19 colunas
    Importance: 0.004844
  Predicado: Ca > 0.46 (n=86)
    Zona: 19 colunas
    Importance: 0.005299
  Predicado: Ca <= 1.81 (n=173)
    Zona: 19 colunas
    Importance: 0.004642
  Predicado: background > -1.23 (n=168)
    Zona: 87 colunas
    Importance: 0.013589
  Predicado: background <= -0.46 (n=89)
    Zona: 87 colunas
    Importance: 0.010935
  Predicado: background > -0.46 (n=125)
    Zona: 87 colunas
    Importance: 0.014027
  Predicado: background <= 0.40 (n=126)
    Zona: 87 colunas
    Importance: 0.011430
  Predicado: background > 0.40 (n=88)
    Zona: 87 colunas
    Importance: 0.014619
  Predicado: background <= 1.29 (n=172)
    Zona: 87 colunas
    Importance: 0.012930
  Predicado: Fe > -1.18 (n=169)
    Zona: 23 colunas
    Importance: 0.005899
  Predicado: Fe <= -0.36 (n=87)
    Zona: 23 colunas
    Importance: 0.005552
  Predicado: Fe > -0.36 (n=127)
    Zona: 23 colunas
    Importance: 0.006348
  Predicado: Fe <= 0.31 (n=127)
    Zona: 23 colunas
    Importance: 0.005601
  Predicado: Fe > 0.31 (n=87)
    Zona: 23 colunas
    Importance: 0.006642
  Predicado: Fe <= 1.20 (n=169)
    Zona: 23 colunas
    Importance: 0.005313
  Predicado: Cu > -1.74 (n=166)
    Zona: 66 colunas
    Importance: 0.009270
  Predicado: Cu <= -0.64 (n=90)
    Zona: 66 colunas
    Importance: 0.007757
  Predicado: Cu > -0.64 (n=124)
    Zona: 66 colunas
    Importance: 0.010519
  Predicado: Cu <= 0.32 (n=129)
    Zona: 66 colunas
    Importance: 0.009259
  Predicado: Cu > 0.32 (n=85)
    Zona: 66 colunas
    Importance: 0.009507
  Predicado: Cu <= 1.92 (n=170)
    Zona: 66 colunas
    Importance: 0.009963
  Predicado: Zn > -1.47 (n=169)
    Zona: 29 colunas
    Importance: 0.008216
  Predicado: Zn <= -0.39 (n=86)
    Zona: 29 colunas
    Importance: 0.005980
  Predicado: Zn > -0.39 (n=128)
    Zona: 29 colunas
    Importance: 0.008740
  Predicado: Zn <= 0.56 (n=132)
    Zona: 29 colunas
    Importance: 0.006716
  Predicado: Zn > 0.56 (n=82)
    Zona: 29 colunas
    Importance: 0.009104
  Predicado: Zn <= 1.56 (n=169)
    Zona: 29 colunas
    Importance: 0.007231
  Predicado: Bremsstrahlung > -9.06 (n=173)
    Zona: 429 colunas
    Importance: 0.076070
  Predicado: Bremsstrahlung <= -1.54 (n=87)
    Zona: 429 colunas
    Importance: 0.118676
  Predicado: Bremsstrahlung > -1.54 (n=127)
    Zona: 429 colunas
    Importance: 0.059336
  Predicado: Bremsstrahlung <= 4.15 (n=134)
    Zona: 429 colunas
    Importance: 0.097553
  Predicado: Bremsstrahlung > 4.15 (n=80)
    Zona: 429 colunas
    Importance: 0.059855
  Predicado: Bremsstrahlung <= 9.64 (n=170)
    Zona: 429 colunas
    Importance: 0.089847
  Predicado: Ag compton > -6.71 (n=171)
    Zona: 62 colunas
    Importance: 0.017785
  Predicado: Ag compton <= -1.09 (n=84)
    Zona: 62 colunas
    Importance: 0.022599
  Predicado: Ag compton > -1.09 (n=130)
    Zona: 62 colunas
    Importance: 0.017231
  Predicado: Ag compton <= 2.96 (n=130)
    Zona: 62 colunas
    Importance: 0.020197
  Predicado: Ag compton > 2.96 (n=84)
    Zona: 62 colunas
    Importance: 0.018010
  Predicado: Ag compton <= 6.52 (n=173)
    Zona: 62 colunas
    Importance: 0.018997
  Predicado: Ag ka > -11.59 (n=169)
    Zona: 45 colunas
    Importance: 0.082031
  Predicado: Ag ka <= -7.06 (n=84)
    Zona: 45 colunas
    Importance: 0.114114
  Predicado: Ag ka > -7.06 (n=130)
    Zona: 45 colunas
    Importance: 0.081981
  Predicado: Ag ka <= 5.37 (n=125)
    Zona: 45 colunas
    Importance: 0.093997
  Predicado: Ag ka > 5.37 (n=89)
    Zona: 45 colunas
    Importance: 0.095432
  Predicado: Ag ka <= 20.95 (n=166)
    Zona: 45 colunas
    Importance: 0.088100

[Bag_3] Processando 60 predicados...
  Predicado: Ag La > -18.52 (n=174)
    Zona: 18 colunas
    Importance: 0.057894
  Predicado: Ag La <= 2.70 (n=84)
    Zona: 18 colunas
    Importance: 0.280691
  Predicado: Ag La > 2.70 (n=130)
    Zona: 18 colunas
    Importance: 0.030888
  Predicado: Ag La <= 7.76 (n=128)
    Zona: 18 colunas
    Importance: 0.191507
  Predicado: Ag La > 7.76 (n=86)
    Zona: 18 colunas
    Importance: 0.035821
  Predicado: Ag La <= 9.01 (n=169)
    Zona: 18 colunas
    Importance: 0.153059
  Predicado: Ag Lb > -15.87 (n=173)
    Zona: 15 colunas
    Importance: 0.042576
  Predicado: Ag Lb <= 2.36 (n=84)
    Zona: 15 colunas
    Importance: 0.205944
  Predicado: Ag Lb > 2.36 (n=130)
    Zona: 15 colunas
    Importance: 0.028093
  Predicado: Ag Lb <= 6.48 (n=127)
    Zona: 15 colunas
    Importance: 0.139897
  Predicado: Ag Lb > 6.48 (n=87)
    Zona: 15 colunas
    Importance: 0.036603
  Predicado: Ag Lb <= 8.04 (n=169)
    Zona: 15 colunas
    Importance: 0.111112
  Predicado: Ca > -1.79 (n=171)
    Zona: 19 colunas
    Importance: 0.004674
  Predicado: Ca <= -0.68 (n=79)
    Zona: 19 colunas
    Importance: 0.005437
  Predicado: Ca > -0.68 (n=135)
    Zona: 19 colunas
    Importance: 0.005076
  Predicado: Ca <= 0.46 (n=126)
    Zona: 19 colunas
    Importance: 0.004821
  Predicado: Ca > 0.46 (n=88)
    Zona: 19 colunas
    Importance: 0.005765
  Predicado: Ca <= 1.81 (n=170)
    Zona: 19 colunas
    Importance: 0.004527
  Predicado: background > -1.23 (n=169)
    Zona: 87 colunas
    Importance: 0.013736
  Predicado: background <= -0.46 (n=89)
    Zona: 87 colunas
    Importance: 0.012063
  Predicado: background > -0.46 (n=125)
    Zona: 87 colunas
    Importance: 0.013499
  Predicado: background <= 0.40 (n=133)
    Zona: 87 colunas
    Importance: 0.012826
  Predicado: background > 0.40 (n=81)
    Zona: 87 colunas
    Importance: 0.013026
  Predicado: background <= 1.29 (n=174)
    Zona: 87 colunas
    Importance: 0.013730
  Predicado: Fe > -1.18 (n=174)
    Zona: 23 colunas
    Importance: 0.005676
  Predicado: Fe <= -0.36 (n=76)
    Zona: 23 colunas
    Importance: 0.005456
  Predicado: Fe > -0.36 (n=138)
    Zona: 23 colunas
    Importance: 0.006266
  Predicado: Fe <= 0.31 (n=124)
    Zona: 23 colunas
    Importance: 0.005441
  Predicado: Fe > 0.31 (n=90)
    Zona: 23 colunas
    Importance: 0.006717
  Predicado: Fe <= 1.20 (n=170)
    Zona: 23 colunas
    Importance: 0.005216
  Predicado: Cu > -1.74 (n=173)
    Zona: 66 colunas
    Importance: 0.010153
  Predicado: Cu <= -0.64 (n=84)
    Zona: 66 colunas
    Importance: 0.008588
  Predicado: Cu > -0.64 (n=130)
    Zona: 66 colunas
    Importance: 0.011282
  Predicado: Cu <= 0.32 (n=125)
    Zona: 66 colunas
    Importance: 0.010090
  Predicado: Cu > 0.32 (n=89)
    Zona: 66 colunas
    Importance: 0.010413
  Predicado: Cu <= 1.92 (n=171)
    Zona: 66 colunas
    Importance: 0.010593
  Predicado: Zn > -1.47 (n=170)
    Zona: 29 colunas
    Importance: 0.008076
  Predicado: Zn <= -0.39 (n=89)
    Zona: 29 colunas
    Importance: 0.005798
  Predicado: Zn > -0.39 (n=125)
    Zona: 29 colunas
    Importance: 0.008993
  Predicado: Zn <= 0.56 (n=130)
    Zona: 29 colunas
    Importance: 0.006685
  Predicado: Zn > 0.56 (n=84)
    Zona: 29 colunas
    Importance: 0.009181
  Predicado: Zn <= 1.56 (n=173)
    Zona: 29 colunas
    Importance: 0.006669
  Predicado: Bremsstrahlung > -9.06 (n=167)
    Zona: 429 colunas
    Importance: 0.077060
  Predicado: Bremsstrahlung <= -1.54 (n=84)
    Zona: 429 colunas
    Importance: 0.113126
  Predicado: Bremsstrahlung > -1.54 (n=130)
    Zona: 429 colunas
    Importance: 0.065601
  Predicado: Bremsstrahlung <= 4.15 (n=129)
    Zona: 429 colunas
    Importance: 0.093413
  Predicado: Bremsstrahlung > 4.15 (n=85)
    Zona: 429 colunas
    Importance: 0.070358
  Predicado: Bremsstrahlung <= 9.64 (n=173)
    Zona: 429 colunas
    Importance: 0.088371
  Predicado: Ag compton > -6.71 (n=170)
    Zona: 62 colunas
    Importance: 0.017838
  Predicado: Ag compton <= -1.09 (n=89)
    Zona: 62 colunas
    Importance: 0.020896
  Predicado: Ag compton > -1.09 (n=125)
    Zona: 62 colunas
    Importance: 0.017209
  Predicado: Ag compton <= 2.96 (n=132)
    Zona: 62 colunas
    Importance: 0.018379
  Predicado: Ag compton > 2.96 (n=82)
    Zona: 62 colunas
    Importance: 0.019327
  Predicado: Ag compton <= 6.52 (n=172)
    Zona: 62 colunas
    Importance: 0.017884
  Predicado: Ag ka > -11.59 (n=168)
    Zona: 45 colunas
    Importance: 0.083102
  Predicado: Ag ka <= -7.06 (n=91)
    Zona: 45 colunas
    Importance: 0.107674
  Predicado: Ag ka > -7.06 (n=123)
    Zona: 45 colunas
    Importance: 0.082882
  Predicado: Ag ka <= 5.37 (n=131)
    Zona: 45 colunas
    Importance: 0.089738
  Predicado: Ag ka > 5.37 (n=83)
    Zona: 45 colunas
    Importance: 0.099242
  Predicado: Ag ka <= 20.95 (n=173)
    Zona: 45 colunas
    Importance: 0.084547

[Bag_4] Processando 60 predicados...
  Predicado: Ag La > -18.52 (n=172)
    Zona: 18 colunas
    Importance: 0.058413
  Predicado: Ag La <= 2.70 (n=86)
    Zona: 18 colunas
    Importance: 0.286122
  Predicado: Ag La > 2.70 (n=128)
    Zona: 18 colunas
    Importance: 0.033757
  Predicado: Ag La <= 7.76 (n=128)
    Zona: 18 colunas
    Importance: 0.199381
  Predicado: Ag La > 7.76 (n=86)
    Zona: 18 colunas
    Importance: 0.039612
  Predicado: Ag La <= 9.01 (n=172)
    Zona: 18 colunas
    Importance: 0.157427
  Predicado: Ag Lb > -15.87 (n=168)
    Zona: 15 colunas
    Importance: 0.040000
  Predicado: Ag Lb <= 2.36 (n=88)
    Zona: 15 colunas
    Importance: 0.208755
  Predicado: Ag Lb > 2.36 (n=126)
    Zona: 15 colunas
    Importance: 0.029981
  Predicado: Ag Lb <= 6.48 (n=128)
    Zona: 15 colunas
    Importance: 0.147860
  Predicado: Ag Lb > 6.48 (n=86)
    Zona: 15 colunas
    Importance: 0.037464
  Predicado: Ag Lb <= 8.04 (n=167)
    Zona: 15 colunas
    Importance: 0.118800
  Predicado: Ca > -1.79 (n=165)
    Zona: 19 colunas
    Importance: 0.005218
  Predicado: Ca <= -0.68 (n=90)
    Zona: 19 colunas
    Importance: 0.005489
  Predicado: Ca > -0.68 (n=124)
    Zona: 19 colunas
    Importance: 0.005664
  Predicado: Ca <= 0.46 (n=129)
    Zona: 19 colunas
    Importance: 0.005082
  Predicado: Ca > 0.46 (n=85)
    Zona: 19 colunas
    Importance: 0.006363
  Predicado: Ca <= 1.81 (n=171)
    Zona: 19 colunas
    Importance: 0.004813
  Predicado: background > -1.23 (n=170)
    Zona: 87 colunas
    Importance: 0.015045
  Predicado: background <= -0.46 (n=85)
    Zona: 87 colunas
    Importance: 0.011536
  Predicado: background > -0.46 (n=129)
    Zona: 87 colunas
    Importance: 0.015285
  Predicado: background <= 0.40 (n=127)
    Zona: 87 colunas
    Importance: 0.013117
  Predicado: background > 0.40 (n=87)
    Zona: 87 colunas
    Importance: 0.014787
  Predicado: background <= 1.29 (n=171)
    Zona: 87 colunas
    Importance: 0.014057
  Predicado: Fe > -1.18 (n=173)
    Zona: 23 colunas
    Importance: 0.006088
  Predicado: Fe <= -0.36 (n=82)
    Zona: 23 colunas
    Importance: 0.005932
  Predicado: Fe > -0.36 (n=132)
    Zona: 23 colunas
    Importance: 0.006396
  Predicado: Fe <= 0.31 (n=128)
    Zona: 23 colunas
    Importance: 0.005501
  Predicado: Fe > 0.31 (n=86)
    Zona: 23 colunas
    Importance: 0.007286
  Predicado: Fe <= 1.20 (n=169)
    Zona: 23 colunas
    Importance: 0.005270
  Predicado: Cu > -1.74 (n=169)
    Zona: 66 colunas
    Importance: 0.010138
  Predicado: Cu <= -0.64 (n=89)
    Zona: 66 colunas
    Importance: 0.009156
  Predicado: Cu > -0.64 (n=125)
    Zona: 66 colunas
    Importance: 0.011282
  Predicado: Cu <= 0.32 (n=128)
    Zona: 66 colunas
    Importance: 0.009924
  Predicado: Cu > 0.32 (n=86)
    Zona: 66 colunas
    Importance: 0.011105
  Predicado: Cu <= 1.92 (n=170)
    Zona: 66 colunas
    Importance: 0.010675
  Predicado: Zn > -1.47 (n=170)
    Zona: 29 colunas
    Importance: 0.008955
  Predicado: Zn <= -0.39 (n=86)
    Zona: 29 colunas
    Importance: 0.006529
  Predicado: Zn > -0.39 (n=128)
    Zona: 29 colunas
    Importance: 0.009146
  Predicado: Zn <= 0.56 (n=132)
    Zona: 29 colunas
    Importance: 0.006999
  Predicado: Zn > 0.56 (n=82)
    Zona: 29 colunas
    Importance: 0.009858
  Predicado: Zn <= 1.56 (n=172)
    Zona: 29 colunas
    Importance: 0.007214
  Predicado: Bremsstrahlung > -9.06 (n=173)
    Zona: 429 colunas
    Importance: 0.076134
  Predicado: Bremsstrahlung <= -1.54 (n=84)
    Zona: 429 colunas
    Importance: 0.111943
  Predicado: Bremsstrahlung > -1.54 (n=130)
    Zona: 429 colunas
    Importance: 0.065397
  Predicado: Bremsstrahlung <= 4.15 (n=130)
    Zona: 429 colunas
    Importance: 0.094417
  Predicado: Bremsstrahlung > 4.15 (n=84)
    Zona: 429 colunas
    Importance: 0.067031
  Predicado: Bremsstrahlung <= 9.64 (n=174)
    Zona: 429 colunas
    Importance: 0.088250

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70,Ag La <= 2.70
1,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36,Ag Lb <= 2.36
2,Ag La <= 7.76,Ag La <= 7.76,Ag La <= 7.76,Ag La <= 7.76
3,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 9.01,Ag La <= 9.01
4,Ag Lb <= 6.48,Ag Lb <= 6.48,Ag Lb <= 6.48,Ag Lb <= 6.48
...,...,...,...,...
57,Fe <= -0.36,Ca > -0.68,Ca <= 0.46,Ca <= 0.46
58,Zn <= 0.56,Fe <= 1.20,Ca > -1.79,Ca > -1.79
59,Ca <= 1.81,Fe <= 0.31,Ca <= 1.81,Ca <= 1.81
60,Class_A,Class_A,Class_A,Class_A
61,Class_B,Class_B,Class_B,Class_B

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                  Predicate  Perturbation
0             Ag La <= 2.70      0.289430
1             Ag Lb <= 2.36      0.216438
2             Ag La <= 7.76      0.187870
3             Ag La <= 9.01      0.151268
4             Ag Lb <= 6.48      0.142517
5   Bremsstrahlung <= -1.54      0.123205
6             Ag Lb <= 8.04      0.114055
7            Ag ka <= -7.06      0.107659
8    Bremsstrahlung <= 4.15      0.100793
9    Bremsstrahlung <= 9.64      0.094130
10            Ag ka <= 5.37      0.088126
11           Ag ka <= 20.95      0.083795
12             Ag ka > 5.37      0.083599
13   Bremsstrahlung > -9.06      0.081718
14           Ag ka > -11.59      0.075852
15            Ag ka > -7.06      0.072167
16    Bremsstrahlung > 4.15      0.068919
17   Bremsstrahlung > -1.54      0.064980
18           Ag La > -18.52      0.058394
19           Ag Lb > -15.87      0.040460
20             Ag La > 7.76      0.039184
21             Ag Lb > 6.48      0.035230
22             Ag La > 2.70      0.032110
23             Ag Lb > 2.36      0.027509
24      Ag compton <= -1.09      0.021794
25       Ag compton <= 2.96      0.019990
26       Ag compton <= 6.52      0.018805
27        Ag compton > 2.96      0.018568
28       Ag compton > -6.71      0.018133
29       Ag compton > -1.09      0.017902
30       background > -0.46      0.014935
31        background > 0.40      0.014800
32       background > -1.23      0.014765
33       background <= 1.29      0.014373
34       background <= 0.40      0.012796
35      background <= -0.46      0.011561
36               Cu <= 1.92      0.010436
37               Cu > -0.64      0.010424
38               Cu <= 0.32      0.010285
39               Cu > -1.74      0.009868
40                Cu > 0.32      0.009868
41              Cu <= -0.64      0.009647
42                Zn > 0.56      0.009647
43               Zn > -0.39      0.008669
44               Zn > -1.47      0.008608
45              Zn <= -0.39      0.007200
46               Zn <= 1.56      0.007186
47               Zn <= 0.56      0.007110
48                Fe > 0.31      0.006783
49              Fe <= -0.36      0.006248
50               Fe > -0.36      0.006087
51               Fe > -1.18      0.005918
52               Fe <= 0.31      0.005669
53                Ca > 0.46      0.005618
54              Ca <= -0.68      0.005512
55               Fe <= 1.20      0.005393
56               Ca > -0.68      0.004959
57               Ca <= 0.46      0.004884
58               Ca <= 1.81      0.004696
59               Ca > -1.79      0.004625

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ag La <= 2.70,6.687719,Ag La,2.70,<=
1,Ag Lb <= 2.36,5.267929,Ag Lb,2.36,<=
2,Bremsstrahlung <= -1.54,1.552834,Bremsstrahlung,-1.54,<=
3,Ag ka <= -7.06,1.547798,Ag ka,-7.06,<=
4,Ag compton <= -1.09,0.191063,Ag compton,-1.09,<=
5,Zn > 0.56,0.017833,Zn,0.56,>
6,background > -1.23,0.016647,background,-1.23,>
7,Cu > -0.64,0.016340,Cu,-0.64,>
8,Ca <= -0.68,0.006738,Ca,-0.68,<=
9,Fe > 0.31,0.006703,Fe,0.31,>
10,Class_A,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ag La <= 2.70,6.687719,Ag La,2.70,<=,34.935039,86.0,0.021418,Ag La <= 34.935039
1,Ag Lb <= 2.36,5.267929,Ag Lb,2.36,<=,30.578162,0.0,0.008013,Ag Lb <= 30.578162
2,Ag La <= 7.76,4.210716,Ag La,7.76,<=,105.814886,78.0,0.002963,Ag La <= 105.814886
3,Ag La <= 9.01,3.130528,Ag La,9.01,<=,126.903607,239.0,0.004801,Ag La <= 126.903607
4,Ag Lb <= 6.48,2.141540,Ag Lb,6.48,<=,75.496450,98.0,0.013050,Ag Lb <= 75.496450
...,...,...,...,...,...,...,...,...,...
57,Ca <= 0.46,0.004840,Ca,0.46,<=,3.531024,28.0,0.010826,Ca <= 3.531024
58,Ca > -1.79,0.004289,Ca,-1.79,>,-9.483856,153.0,0.012409,Ca > -9.483856
59,Ca <= 1.81,0.002665,Ca,1.81,<=,-2.575534,222.0,0.044016,Ca <= -2.575534
60,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
61,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

In [16]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ag La':
  - Dimensão: 18 variáveis espectrais
  - Variância explicada pela PC1: 91.39%

In [17]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

  energy  Permutation_importance_proba            Zone
0  22.23                      0.025466           Ag ka
1   3.02                      0.017941           Ag La
2   3.17                      0.010048           Ag Lb
3   8.73                      0.003896              Zn
4  17.99                      0.003754  Bremsstrahlung
5  21.41                      0.003501      Ag compton
6   6.35                      0.003248              Fe
7   7.80                      0.002201              Cu
8   3.89                      0.002154              Ca
9   4.84                      0.001934      background

In [18]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Ag ka,Ag La,Ag ka,Ag La,Ag La
1,Ag La,Ag ka,Ag La,Ag Lb,Ag Lb
2,Zn,Ag Lb,Ag Lb,Bremsstrahlung,Ag ka
3,Ag Lb,Bremsstrahlung,Zn,Ag ka,Bremsstrahlung
4,Bremsstrahlung,Zn,Bremsstrahlung,Ag compton,Ag compton
5,Fe,Ag compton,Ag compton,Zn,Ca
6,Ag compton,Fe,Fe,background,Zn
7,background,Ca,Cu,Cu,Cu
8,Ca,Cu,Ca,Ca,background
9,Cu,background,background,Fe,Fe
10,None,None,None,None,None

In [19]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_21700\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
1       SVM_pvector       Permutation   0.909339
9  LRC_perturbation    LRC_covariance   0.906219
6              Shap    LRC_covariance   0.833891
5              Shap  LRC_perturbation   0.790206
4              Shap       Permutation   0.642939
0       SVM_pvector              Shap   0.583614
8       Permutation    LRC_covariance   0.508166
7       Permutation  LRC_perturbation   0.467569
3       SVM_pvector    LRC_covariance   0.447674
2       SVM_pvector  LRC_perturbation   0.410166

In [20]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')