In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/forage/plsda/forage.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '1.4':'20.81']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '1.4':'20.81'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '1.4':'20.81'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:39:40,361 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:39:40,374 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:39:40,410 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-08 19:39:40,469 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import svm_optimized

svm_model = svm_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, aim='classification', kernel='rbf')
svm_model[0]

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,SVC,1.0,1.0,1.0,"[[40, 0], [0, 95]]",1.0,1.0,1.0,"[[18, 0], [0, 42]]"

## Definição das Zonas Espectrais

In [3]:
spectral_cuts = [
('Al', 1.40, 1.63),
('Si', 1.63, 1.86),
('P', 1.86, 2.16),
('S', 2.16, 2.44),
('Rh L + Ar', 2.44, 3.10),
('K', 3.10, 3.46),
('Ca ka', 3.46, 3.86),
('Ca kb', 3.86, 4.16),
('background1', 4.14, 4.37),
('Ti ka', 4.37, 4.66),
('Ti kb', 4.66, 5.08),
('background2', 5.08, 5.72),
('Mn', 5.72, 6.10),
('Fe ka', 6.10, 6.76),
('Fe kb', 6.76, 7.20),
('Ni', 7.20, 7.69),
('background3', 7.69, 13.10),
('sum Fe' , 13.10, 13.63),
('background4', 13.63, 18.0),
('Compton scattering', 18.0, 19.70),
('Rayleight scattering', 19.70, 20.81)
]

## Pvector and SHAP

In [4]:
X_sv = svm_model[3].support_vectors_            # shape (n_SV, n_features)
alpha_dual = svm_model[3].dual_coef_.ravel()    # shape (n_SV,)

# Calculando os coeficientes p usando os vetores de suporte e os multiplicadores de Lagrange
pvetor = pd.DataFrame({'energia' : Xcalclass.columns,
                       'importance': (X_sv.T) @ alpha_dual})
pvetor['importance'] = np.abs(pvetor['importance'])
pvector_df = pd.DataFrame({
    'energy': pvetor['energia'],
    'Pvector': pvetor['importance'].values
})
pvector_df = pvector_df.sort_values(by='Pvector', ascending=False).reset_index(drop=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in pvector_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
pvector_df['Zone'] = pvector_df['energy'].map(energy_to_zone_vip)
pvector_unique_df = pvector_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
pvector_unique_df

   energy    Pvector                  Zone
0    6.42  29.020377                 Fe ka
1     3.7  21.276746                 Ca ka
2    1.74  20.460692                    Si
3    3.34  12.997443                     K
4    4.02   7.862402                 Ca kb
5    4.52   7.835278                 Ti ka
6    7.08   7.213706                 Fe kb
7    2.62   5.597003             Rh L + Ar
8    1.86   3.167416                     P
9    2.28   2.214821                     S
10  13.41   2.154293                sum Fe
11   1.62   2.151909                    Al
12   4.94   2.032520                 Ti kb
13   7.54   1.425007                    Ni
14   5.92   1.240119                    Mn
15  19.39   1.124331    Compton scattering
16  11.95   1.122248           background3
17  20.31   0.974562  Rayleight scattering
18  15.41   0.831623           background4
19   4.14   0.743773           background1
20   5.12   0.699431           background2

In [5]:
shap_global_importance = pd.read_csv('shap_forage.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP                  Zone
0     1.74       0.040840                    Si
1     3.70       0.033018                 Ca ka
2     6.42       0.029003                 Fe ka
3     3.36       0.005098                     K
4    13.65       0.000478           background4
5     2.64       0.000472             Rh L + Ar
6     7.97       0.000445           background3
7    19.45       0.000360    Compton scattering
8     2.32       0.000263                     S
9    13.61       0.000000                sum Fe
10    1.40       0.000000                    Al
11   20.27       0.000000  Rayleight scattering
12    5.10       0.000000           background2
13    4.86       0.000000                 Ti kb
14    4.24       0.000000           background1
15    4.38       0.000000                 Ti ka
16    6.00       0.000000                    Mn
17    2.14       0.000000                     P
18    3.86       0.000000                 Ca kb
19    6.76       0.000000                 Fe kb
20    7.38       0.000000                    Ni

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Al': VE = 92.81%, dim = 12 variáveis
Zona 'Si': VE = 99.42%, dim = 12 variáveis
Zona 'P': VE = 94.16%, dim = 16 variáveis
Zona 'S': VE = 89.31%, dim = 15 variáveis
Zona 'Rh L + Ar': VE = 95.85%, dim = 34 variáveis
Zona 'K': VE = 98.44%, dim = 19 variáveis
Zona 'Ca ka': VE = 89.46%, dim = 21 variáveis
Zona 'Ca kb': VE = 97.67%, dim = 16 variáveis
Zona 'background1': VE = 53.72%, dim = 12 variáveis
Zona 'Ti ka': VE = 98.15%, dim = 15 variáveis
Zona 'Ti kb': VE = 76.25%, dim = 22 variáveis
Zona 'background2': VE = 66.63%, dim = 33 variáveis
Zona 'Mn': VE = 94.16%, dim = 20 variáveis
Zona 'Fe ka': VE = 99.38%, dim = 34 variáveis
Zona 'Fe kb': VE = 94.04%, dim = 23 variáveis
Zona 'Ni': VE = 77.76%, dim = 25 variáveis
Zona 'background3': VE = 84.69%, dim = 271 variáveis
Zona 'sum Fe': VE = 88.47%, dim = 27 variáveis
Zona 'background4': VE = 87.92%, dim = 219 variáveis
Zona 'Compton scattering': VE = 88.73%, dim = 85 variáveis
Zona 'Rayleight scattering': VE = 84.40%, dim = 56 variáveis

Scores DataFrame shape: (135, 21)

In [7]:
y_pred = svm_model[4]['SVC'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(svm_model[4]['SVC'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 128 | Descartados: 40
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 109
Removida: Si > -1.67 -> Si > -2.51 (3.8458) | Mantida: Si > -2.51 -> Si > -1.67 (5.1915)
Removida: Si > -2.51 -> Ca ka <= 3.95 (2.5976) | Mantida: Ca ka <= 3.95 -> Si > -2.51 (4.8597)
Removida: K > -6.69 -> Si > -2.51 (1.3609) | Mantida: Si > -2.51 -> K > -6.69 (2.5823)
Removida: Ca ka <= 3.95 -> Si > -1.67 (2.3154) | Mantida: Si > -1.67 -> Ca ka <= 3.95 (2.5714)
Removida: Si > -1.67 -> K > -6.69 (1.2761) | Mantida: K > -6.69 -> Si > -1.67 (3.8834)
Removida: K > -6.69 -> Ca ka <= 3.95 (2.7450) | Mantida: Ca ka <= 3.95 -> K > -6.69 (4.7092)
Removida: Ca ka <= 1.77 -> K <= 6.26 (3.0400) | Mantida: K <= 6.26 -> Ca ka <= 1.77 (4.3852)
Removida: K > -1.46 -> K <= 6.26 (1.9652) | Mantida: K <= 6.26 -> K > -1.46 (4.0224)
Removida: Si > -0.72 -> K > -1.46 (1.6608) | Mantida: K > -1.46 -> Si > -0.72 (4.5527)
Removida: Si > -0.72 -> K <= 6.26 (0.9583) | Mantida: K <= 6.26 -> Si > -0.72 (1.8463)
Removida: Ca ka <= -1.50 -> Ca ka > -4.65 (1.0042) | Mantida: Ca ka > -4.65 -> Ca ka <= -1.50 (1.5739)
Removida: Ca kb <= 1.58 -> Ca ka <= -1.50 (0.5047) | Mantida: Ca ka <= -1.50 -> Ca kb <= 1.58 (0.9953)
Removida: Fe kb > -0.91 -> Ca ka <= -1.50 (0.4992) | Mantida: Ca ka <= -1.50 -> Fe kb > -0.91 (0.5020)
Removida: Ca ka <= -1.50 -> Ti ka > -0.70 (0.5202) | Mantida: Ti ka > -0.70 -> Ca ka <= -1.50 (2.2448)
Removida: Ca kb <= 1.58 -> Fe kb > -0.91 (0.4937) | Mantida: Fe kb > -0.91 -> Ca kb <= 1.58 (1.0405)
Removida: Ca kb <= 1.58 -> Rh L + Ar > -0.16 (0.5497) | Mantida: Rh L + Ar > -0.16 -> Ca kb <= 1.58 (1.0418)
Removida: Ca kb <= 1.58 -> Ti ka > -0.86 (0.5437) | Mantida: Ti ka > -0.86 -> Ca kb <= 1.58 (0.5640)
Removida: Ti ka > -0.70 -> Rh L + Ar > -0.16 (0.5484) | Mantida: Rh L + Ar > -0.16 -> Ti ka > -0.70 (0.6239)
Removida: Rh L + Ar > -0.77 -> Ti ka > -0.70 (0.5386) | Mantida: Ti ka > -0.70 -> Rh L + Ar > -0.77 (0.5953)
Removida: Ti ka > -0.86 -> Fe kb > -0.63 (1.6242) | Mantida: Fe kb > -0.63 -> Ti ka > -0.86 (2.1355)
Removida: Fe kb > -0.44 -> Ti ka > -0.86 (0.4991) | Mantida: Ti ka > -0.86 -> Fe kb > -0.44 (0.5628)
Removida: Rh L + Ar > -0.16 -> Rh L + Ar > -0.77 (0.5375) | Mantida: Rh L + Ar > -0.77 -> Rh L + Ar > -0.16 (1.1483)
Removida: Fe kb > -0.91 -> Rh L + Ar > -0.77 (0.4328) | Mantida: Rh L + Ar > -0.77 -> Fe kb > -0.91 (0.4363)
Removida: Fe kb > -0.44 -> Fe kb > -0.91 (0.4618) | Mantida: Fe kb > -0.91 -> Fe kb > -0.44 (0.9566)
Removida: Rh L + Ar > -0.77 -> Ca kb <= 0.62 (0.4372) | Mantida: Ca kb <= 0.62 -> Rh L + Ar > -0.77 (0.4538)
Removida: Ti ka > -0.52 -> Fe kb > -0.44 (0.9372) | Mantida: Fe kb > -0.44 -> Ti ka > -0.52 (1.4449)
Removida: K <= 2.15 -> Ti ka > -0.52 (0.4692) | Mantida: Ti ka > -0.52 -> K <= 2.15 (0.4820)
Removida: Rh L + Ar > -1.66 -> Ti ka > -0.52 (0.4492) | Mantida: Ti ka > -0.52 -> Rh L + Ar > -1.66 (0.4515)
Removida: background4 > 0.14 -> Rh L + Ar > -1.66 (0.3374) | Mantida: Rh L + Ar > -1.66 -> background4 > 0.14 (1.4517)
Removida: Fe kb > -0.44 -> Rh L + Ar > -1.66 (0.3732) | Mantida: Rh L + Ar > -1.66 -> Fe kb > -0.44 (0.4404)
Removida: background4 > -0.62 -> K <= 2.15 (0.2153) | Mantida: K <= 2.15 -> background4 > -0.62 (1.0478)
Removida: Fe ka <= 1.10 -> background4 > -0.62 (0.3002) | Mantida: background4 > -0.62 -> Fe ka <= 1.10 (0.5430)
Removida: Ca kb > -1.81 -> Fe ka <= 1.10 (0.2306) | Mantida: Fe ka <= 1.10 -> Ca kb > -1.81 (0.4646)
Removida: Compton scattering > 0.05 -> Fe ka <= 1.10 (0.2609) | Mantida: Fe ka <= 1.10 -> Compton scattering > 0.05 (0.7938)
Removida: background4 > -1.28 -> Fe ka <= 1.10 (0.2538) | Mantida: Fe ka <= 1.10 -> background4 > -1.28 (0.2908)
Removida: background4 > -0.62 -> K > 2.15 (0.2605) | Mantida: K > 2.15 -> background4 > -0.62 (0.3551)
Removida: Compton scattering > 0.05 -> background4 > -0.62 (0.4426) | Mantida: background4 > -0.62 -> Compton scattering > 0.05 (0.4835)
Removida: Rayleight scattering > 0.03 -> K > 2.15 (0.1644) | Mantida: K > 2.15 -> Rayleight scattering > 0.03 (0.2229)
Removida: K > 2.15 -> Ca kb <= -0.59 (0.2672) | Mantida: Ca kb <= -0.59 -> K > 2.15 (0.4636)
Removida: Compton scattering > -0.40 -> Compton scattering > 0.05 (0.2365) | Mantida: Compton scattering > 0.05 -> Compton scattering > -0.40 (0.5623)
Removida: Compton scattering > 0.05 -> Ca kb > -1.81 (0.2375) | Mantida: Ca kb > -1.81 -> Compton scattering > 0.05 (0.2475)
Removida: Compton scattering > -0.40 -> Ca kb <= -0.59 (0.4533) | Mantida: Ca kb <= -0.59 -> Compton scattering > -0.40 (0.5042)
Removida: Ca kb > -1.81 -> Ca kb <= -0.59 (0.2578) | Mantida: Ca kb <= -0.59 -> Ca kb > -1.81 (0.4759)
Removida: Ca kb > -1.81 -> Compton scattering > -0.40 (0.2418) | Mantida: Compton scattering > -0.40 -> Ca kb > -1.81 (0.6161)
Removida: Ca kb > -1.81 -> background4 > -1.28 (0.2271) | Mantida: background4 > -1.28 -> Ca kb > -1.81 (0.4613)
Removida: Rayleight scattering > 0.03 -> background4 > -1.28 (0.1693) | Mantida: background4 > -1.28 -> Rayleight scattering > 0.03 (0.3401)
Removida: Rayleight scattering > 0.03 -> Compton scattering > -0.88 (0.1689) | Mantida: Compton scattering > -0.88 -> Rayleight scattering > 0.03 (0.4840)
Removida: Rayleight scattering > 0.03 -> Rayleight scattering > -0.25 (0.1164) | Mantida: Rayleight scattering > -0.25 -> Rayleight scattering > 0.03 (0.1581)
Removida: Al > -0.68 -> Rayleight scattering > 0.03 (0.1293) | Mantida: Rayleight scattering > 0.03 -> Al > -0.68 (0.4149)
Removida: sum Fe > -0.28 -> Rayleight scattering > 0.03 (0.3118) | Mantida: Rayleight scattering > 0.03 -> sum Fe > -0.28 (0.3123)
Removida: Compton scattering > -0.88 -> sum Fe > -0.28 (0.1611) | Mantida: sum Fe > -0.28 -> Compton scattering > -0.88 (0.2633)
Removida: Compton scattering > -0.88 -> Al > -0.68 (0.1370) | Mantida: Al > -0.68 -> Compton scattering > -0.88 (0.1432)
Removida: sum Fe > -0.28 -> Rayleight scattering > -0.25 (0.1598) | Mantida: Rayleight scattering > -0.25 -> sum Fe > -0.28 (0.2464)
Removida: sum Fe > -0.28 -> sum Fe > 0.07 (0.1659) | Mantida: sum Fe > 0.07 -> sum Fe > -0.28 (0.4525)
Removida: sum Fe > 0.07 -> Rayleight scattering > -0.25 (0.3098) | Mantida: Rayleight scattering > -0.25 -> sum Fe > 0.07 (0.4193)
Removida: sum Fe > 0.07 -> Al > -0.68 (0.1485) | Mantida: Al > -0.68 -> sum Fe > 0.07 (0.2942)
Removida: Rayleight scattering > -0.50 -> Al > -0.68 (0.1388) | Mantida: Al > -0.68 -> Rayleight scattering > -0.50 (0.4488)
Removida: Rayleight scattering > -0.50 -> Ti kb > -0.32 (0.0957) | Mantida: Ti kb > -0.32 -> Rayleight scattering > -0.50 (0.0960)
Removida: K <= -1.46 -> Al > -0.19 (0.1264) | Mantida: Al > -0.19 -> K <= -1.46 (0.2379)
Removida: Ti kb > -0.14 -> K <= -1.46 (0.0877) | Mantida: K <= -1.46 -> Ti kb > -0.14 (0.1061)
Removida: Al > -0.19 -> sum Fe > -0.60 (0.1136) | Mantida: sum Fe > -0.60 -> Al > -0.19 (0.4486)
Removida: Ti kb > -0.14 -> Al > -0.19 (0.0856) | Mantida: Al > -0.19 -> Ti kb > -0.14 (0.2045)
Removida: Ti kb > -0.32 -> Al > -0.19 (0.1950) | Mantida: Al > -0.19 -> Ti kb > -0.32 (0.2436)
Removida: Ti kb > -0.32 -> sum Fe > -0.60 (0.0735) | Mantida: sum Fe > -0.60 -> Ti kb > -0.32 (0.2506)
Removida: Ti kb > -0.32 -> Al <= 0.62 (0.0824) | Mantida: Al <= 0.62 -> Ti kb > -0.32 (0.1876)
Removida: Mn > 0.23 -> Al <= 0.62 (0.0958) | Mantida: Al <= 0.62 -> Mn > 0.23 (0.1968)
Removida: Ti kb > -0.32 -> P > -1.23 (0.0791) | Mantida: P > -1.23 -> Ti kb > -0.32 (0.1385)
Removida: P > 0.08 -> P > -1.23 (0.0421) | Mantida: P > -1.23 -> P > 0.08 (0.2663)
Removida: P <= -0.59 -> P > 0.08 (0.0490) | Mantida: P > 0.08 -> P <= -0.59 (0.0717)
Removida: Mn <= 1.01 -> Ti ka <= 0.53 (0.0669) | Mantida: Ti ka <= 0.53 -> Mn <= 1.01 (0.1379)
Removida: Ca ka > -1.50 -> Ti ka <= 0.53 (0.0497) | Mantida: Ti ka <= 0.53 -> Ca ka > -1.50 (0.0599)
Removida: Ti kb > 0.03 -> background3 > -1.50 (0.0681) | Mantida: background3 > -1.50 -> Ti kb > 0.03 (0.0864)
Removida: Fe kb <= 0.33 -> Mn <= 1.01 (0.0307) | Mantida: Mn <= 1.01 -> Fe kb <= 0.33 (0.0547)
Removida: sum Fe <= -0.28 -> Fe kb <= 0.33 (0.0388) | Mantida: Fe kb <= 0.33 -> sum Fe <= -0.28 (0.0450)
Removida: P <= 0.08 -> Fe kb <= 0.33 (0.0309) | Mantida: Fe kb <= 0.33 -> P <= 0.08 (0.0396)
Removida: Ni > -0.14 -> Fe kb <= 0.33 (0.0411) | Mantida: Fe kb <= 0.33 -> Ni > -0.14 (0.0553)
Removida: P <= 0.08 -> Compton scattering <= -0.40 (0.0396) | Mantida: Compton scattering <= -0.40 -> P <= 0.08 (0.0398)
Removida: Ni <= 0.13 -> P <= 0.08 (0.0477) | Mantida: P <= 0.08 -> Ni <= 0.13 (0.0653)
Removida: Mn <= 1.01 -> S <= 0.55 (0.0612) | Mantida: S <= 0.55 -> Mn <= 1.01 (0.0638)
Removida: Ni <= 0.13 -> sum Fe <= -0.28 (0.0127) | Mantida: sum Fe <= -0.28 -> Ni <= 0.13 (0.0574)
Removida: Ni > -0.14 -> sum Fe <= -0.28 (0.0294) | Mantida: sum Fe <= -0.28 -> Ni > -0.14 (0.0474)
Removida: Ni > -0.14 -> S <= 0.55 (0.0345) | Mantida: S <= 0.55 -> Ni > -0.14 (0.0473)
Removida: S <= 0.09 -> Ni > -0.14 (0.0426) | Mantida: Ni > -0.14 -> S <= 0.09 (0.0829)
Removida: Ni <= 0.13 -> Ni > -0.14 (0.0295) | Mantida: Ni > -0.14 -> Ni <= 0.13 (0.0412)
Removida: S > 0.09 -> P <= 1.06 (0.0171) | Mantida: P <= 1.06 -> S > 0.09 (0.0356)
Removida: background3 > -0.49 -> Rh L + Ar <= -0.77 (0.0183) | Mantida: Rh L + Ar <= -0.77 -> background3 > -0.49 (0.0456)
Removida: Ni <= 0.13 -> S <= 0.55 (0.0493) | Mantida: S <= 0.55 -> Ni <= 0.13 (0.2190)
Removida: S <= -0.27 -> S <= 0.55 (0.0364) | Mantida: S <= 0.55 -> S <= -0.27 (0.0541)
Removida: S <= 0.09 -> Compton scattering <= -0.40 (0.0435) | Mantida: Compton scattering <= -0.40 -> S <= 0.09 (0.0668)
Removida: background4 <= 0.14 -> Compton scattering <= -0.40 (0.0278) | Mantida: Compton scattering <= -0.40 -> background4 <= 0.14 (0.0366)
Removida: background2 > 0.11 -> Ti kb <= 0.20 (0.0187) | Mantida: Ti kb <= 0.20 -> background2 > 0.11 (0.0260)
Removida: Ti kb <= 0.20 -> Mn > -1.22 (0.0188) | Mantida: Mn > -1.22 -> Ti kb <= 0.20 (0.0195)
Removida: Ti kb <= 0.20 -> Ca kb > -0.59 (0.0180) | Mantida: Ca kb > -0.59 -> Ti kb <= 0.20 (0.0204)
Removida: Al <= 0.19 -> background3 <= 1.60 (0.0103) | Mantida: background3 <= 1.60 -> Al <= 0.19 (0.0180)
Removida: background3 <= 1.60 -> sum Fe <= 0.07 (0.0114) | Mantida: sum Fe <= 0.07 -> background3 <= 1.60 (0.0193)
Removida: Rayleight scattering <= -0.25 -> Ca kb > -0.59 (0.0180) | Mantida: Ca kb > -0.59 -> Rayleight scattering <= -0.25 (0.0196)
Removida: Mn <= -0.41 -> Al > 0.19 (0.0137) | Mantida: Al > 0.19 -> Mn <= -0.41 (0.0194)
Removida: Rh L + Ar <= -0.77 -> Al > 0.19 (0.0402) | Mantida: Al > 0.19 -> Rh L + Ar <= -0.77 (0.0426)
Removida: Ni > 0.13 -> Ni > -0.60 (0.0168) | Mantida: Ni > -0.60 -> Ni > 0.13 (0.0224)
Removida: Ni > -0.60 -> S > 0.09 (0.0162) | Mantida: S > 0.09 -> Ni > -0.60 (0.0336)
Removida: Rh L + Ar <= -0.16 -> Ni > 0.13 (0.0112) | Mantida: Ni > 0.13 -> Rh L + Ar <= -0.16 (0.0159)
Removida: Ni > 0.13 -> Al <= 0.19 (0.0090) | Mantida: Al <= 0.19 -> Ni > 0.13 (0.0398)
Removida: background2 <= 0.30 -> Ni <= 0.59 (0.0160) | Mantida: Ni <= 0.59 -> background2 <= 0.30 (0.0563)
Removida: background2 <= -0.08 -> Al <= 0.19 (0.0136) | Mantida: Al <= 0.19 -> background2 <= -0.08 (0.0310)
Removida: Ni <= -0.14 -> background2 <= -0.08 (0.0123) | Mantida: background2 <= -0.08 -> Ni <= -0.14 (0.0282)
Removida: background2 <= 0.11 -> Al <= -0.19 (0.0096) | Mantida: Al <= -0.19 -> background2 <= 0.11 (0.0240)
Removida: background1 > -0.14 -> Mn <= 0.23 (0.0083) | Mantida: Mn <= 0.23 -> background1 > -0.14 (0.0137)
Removida: background1 > -0.14 -> sum Fe <= 0.07 (0.0066) | Mantida: sum Fe <= 0.07 -> background1 > -0.14 (0.0138)
Removida: sum Fe <= 0.07 -> Ti kb <= 0.03 (0.0103) | Mantida: Ti kb <= 0.03 -> sum Fe <= 0.07 (0.0122)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 778 | Removidas: 109
Nós predicados: 114
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 118
Removida: Fe ka > -2.26 -> Fe ka > -3.74 (2.4692) | Mantida: Fe ka > -3.74 -> Fe ka > -2.26 (21.5329)
Removida: Si > -2.51 -> Ca ka <= 3.95 (1.2874) | Mantida: Ca ka <= 3.95 -> Si > -2.51 (4.8229)
Removida: Ca ka <= 3.95 -> K > -6.69 (2.4119) | Mantida: K > -6.69 -> Ca ka <= 3.95 (4.1614)
Removida: Si > -1.67 -> Si > -2.51 (3.8365) | Mantida: Si > -2.51 -> Si > -1.67 (7.7200)
Removida: K > -6.69 -> Si > -1.67 (1.3168) | Mantida: Si > -1.67 -> K > -6.69 (3.7810)
Removida: Si > -2.51 -> K > -6.69 (1.2361) | Mantida: K > -6.69 -> Si > -2.51 (3.7923)
Removida: K <= 6.26 -> Ca ka <= 1.77 (1.1523) | Mantida: Ca ka <= 1.77 -> K <= 6.26 (6.8908)
Removida: K > -1.46 -> K <= 6.26 (1.8939) | Mantida: K <= 6.26 -> K > -1.46 (3.8274)
Removida: Si > -0.72 -> K > -1.46 (3.6116) | Mantida: K > -1.46 -> Si > -0.72 (4.3846)
Removida: Ca ka <= -1.50 -> Ca ka > -4.65 (0.5023) | Mantida: Ca ka > -4.65 -> Ca ka <= -1.50 (1.0607)
Removida: Ti ka > -0.70 -> Ca ka > -4.65 (0.5782) | Mantida: Ca ka > -4.65 -> Ti ka > -0.70 (1.7056)
Removida: Rh L + Ar > -0.16 -> Rh L + Ar > -0.77 (0.9478) | Mantida: Rh L + Ar > -0.77 -> Rh L + Ar > -0.16 (1.3658)
Removida: Rh L + Ar > -0.16 -> Ca kb <= 0.62 (0.4861) | Mantida: Ca kb <= 0.62 -> Rh L + Ar > -0.16 (0.8895)
Removida: Ca kb <= 1.58 -> Rh L + Ar > -0.77 (0.5485) | Mantida: Rh L + Ar > -0.77 -> Ca kb <= 1.58 (1.0654)
Removida: Fe kb > -0.91 -> Rh L + Ar > -0.77 (0.4356) | Mantida: Rh L + Ar > -0.77 -> Fe kb > -0.91 (0.5347)
Removida: Ca kb <= 0.62 -> Rh L + Ar > -0.77 (0.4459) | Mantida: Rh L + Ar > -0.77 -> Ca kb <= 0.62 (0.8694)
Removida: Rh L + Ar > -0.77 -> Ti ka > -0.52 (0.3975) | Mantida: Ti ka > -0.52 -> Rh L + Ar > -0.77 (0.9674)
Removida: Rh L + Ar > -0.77 -> background4 > 0.14 (0.3446) | Mantida: background4 > 0.14 -> Rh L + Ar > -0.77 (0.3461)
Removida: Ca ka <= -1.50 -> Ca kb <= 1.58 (0.5042) | Mantida: Ca kb <= 1.58 -> Ca ka <= -1.50 (1.0629)
Removida: Ca kb <= 1.58 -> Ti ka > -0.52 (0.5195) | Mantida: Ti ka > -0.52 -> Ca kb <= 1.58 (1.0739)
Removida: Fe kb > -0.44 -> Ca kb <= 1.58 (0.5118) | Mantida: Ca kb <= 1.58 -> Fe kb > -0.44 (1.0450)
Removida: Ca ka <= -1.50 -> Ti ka > -0.70 (0.4752) | Mantida: Ti ka > -0.70 -> Ca ka <= -1.50 (0.6125)
Removida: Fe kb > -0.63 -> Ca ka <= -1.50 (0.5654) | Mantida: Ca ka <= -1.50 -> Fe kb > -0.63 (1.0598)
Removida: Ca ka <= -1.50 -> Fe kb > -0.91 (0.5368) | Mantida: Fe kb > -0.91 -> Ca ka <= -1.50 (0.5373)
Removida: Ca ka <= -1.50 -> Ti ka > -0.86 (0.5223) | Mantida: Ti ka > -0.86 -> Ca ka <= -1.50 (0.5951)
Removida: Ti ka > -0.70 -> Si <= 3.71 (0.4982) | Mantida: Si <= 3.71 -> Ti ka > -0.70 (0.5871)
Removida: Ca kb <= 0.62 -> Si <= 3.71 (0.4410) | Mantida: Si <= 3.71 -> Ca kb <= 0.62 (0.9358)
Removida: Rh L + Ar > -1.66 -> Ca kb <= 0.62 (0.4549) | Mantida: Ca kb <= 0.62 -> Rh L + Ar > -1.66 (0.8928)
Removida: K <= 2.15 -> Rh L + Ar > -1.66 (0.2677) | Mantida: Rh L + Ar > -1.66 -> K <= 2.15 (0.4179)
Removida: Ti ka > -0.86 -> Fe kb > -0.63 (1.5203) | Mantida: Fe kb > -0.63 -> Ti ka > -0.86 (2.1996)
Removida: Fe kb > -0.91 -> Fe kb > -0.63 (0.5431) | Mantida: Fe kb > -0.63 -> Fe kb > -0.91 (0.9980)
Removida: Ti ka > -0.52 -> Fe kb > -0.91 (0.4434) | Mantida: Fe kb > -0.91 -> Ti ka > -0.52 (0.5218)
Removida: Ti ka > -0.52 -> Fe kb > -0.44 (0.4881) | Mantida: Fe kb > -0.44 -> Ti ka > -0.52 (1.3887)
Removida: Fe kb > -0.44 -> Fe kb > -0.91 (0.5339) | Mantida: Fe kb > -0.91 -> Fe kb > -0.44 (1.0722)
Removida: Ca kb <= 0.62 -> Fe kb > -0.44 (0.4240) | Mantida: Fe kb > -0.44 -> Ca kb <= 0.62 (0.4678)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -3.05,Fe ka > -3.05,Fe ka > -3.05,Fe ka > -3.05
1,Fe ka > -3.74,Fe ka > -3.74,Fe ka > -3.74,Fe ka > -3.74
2,Fe ka > -2.26,Fe ka > -2.26,Fe ka > -2.26,Fe ka > -2.26
3,Ca ka <= 3.95,Si > -2.51,Ca ka <= 3.95,Ca ka <= 3.95
4,K <= 6.26,Ca ka <= 3.95,Si > -2.51,Si > -2.51
...,...,...,...,...
112,S > -0.27,Rayleight scattering <= 0.03,Rayleight scattering <= 0.03,background1 > -0.05
113,background1 <= 0.16,Class_A,Fe kb <= -0.44,background1 > 0.05
114,Class_A,Class_B,background1 <= -0.05,Rayleight scattering <= 0.53
115,Class_B,NaN,Class_A,Class_A
116,NaN,NaN,Class_B,Class_B

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -3.05,17.628047,Fe ka,-3.05,>
1,Ca ka <= 3.95,5.095014,Ca ka,3.95,<=
2,Si > -2.51,4.901034,Si,-2.51,>
3,K > -6.69,4.153909,K,-6.69,>
4,Ti ka > -0.70,1.768803,Ti ka,-0.70,>
5,Fe kb > -0.44,1.583324,Fe kb,-0.44,>
6,Ca kb <= 1.58,1.420909,Ca kb,1.58,<=
7,Rh L + Ar > -1.66,1.378105,Rh L + Ar,-1.66,>
8,background4 > -0.62,0.986794,background4,-0.62,>
9,Compton scattering > 0.05,0.884686,Compton scattering,0.05,>
10,sum Fe > -0.28,0.646593,sum Fe,-0.28,>
11,Rayleight scattering > -0.25,0.589936,Rayleight scattering,-0.25,>
12,Al > -0.68,0.549645,Al,-0.68,>
13,background3 <= -0.49,0.419496,background3,-0.49,<=
14,Ti kb > -0.32,0.387946,Ti kb,-0.32,>
15,P > -1.23,0.369020,P,-1.23,>
16,Mn > 0.23,0.359496,Mn,0.23,>
17,S <= 0.55,0.303393,S,0.55,<=
18,Ni <= 0.13,0.281471,Ni,0.13,<=
19,background2 <= 0.30,0.250466,background2,0.30,<=
20,background1 <= -0.05,0.236875,background1,-0.05,<=
21,Class_B,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Al': VE = 95.14%, dim = 12 variáveis
Zona 'Si': VE = 99.71%, dim = 12 variáveis
Zona 'P': VE = 97.48%, dim = 16 variáveis
Zona 'S': VE = 93.90%, dim = 15 variáveis
Zona 'Rh L + Ar': VE = 96.86%, dim = 34 variáveis
Zona 'K': VE = 99.17%, dim = 19 variáveis
Zona 'Ca ka': VE = 93.72%, dim = 21 variáveis
Zona 'Ca kb': VE = 98.47%, dim = 16 variáveis
Zona 'background1': VE = 53.38%, dim = 12 variáveis
Zona 'Ti ka': VE = 98.49%, dim = 15 variáveis
Zona 'Ti kb': VE = 76.99%, dim = 22 variáveis
Zona 'background2': VE = 66.94%, dim = 33 variáveis
Zona 'Mn': VE = 95.57%, dim = 20 variáveis
Zona 'Fe ka': VE = 99.73%, dim = 34 variáveis
Zona 'Fe kb': VE = 94.82%, dim = 23 variáveis
Zona 'Ni': VE = 79.28%, dim = 25 variáveis
Zona 'background3': VE = 84.69%, dim = 271 variáveis
Zona 'sum Fe': VE = 88.64%, dim = 27 variáveis
Zona 'background4': VE = 87.63%, dim = 219 variáveis
Zona 'Compton scattering': VE = 89.25%, dim = 85 variáveis
Zona 'Rayleight scattering': VE = 84.72%, dim = 56 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > -3.05,17.628047,Fe ka,-3.05,>,-11.993967,102.0,0.012499,Fe ka > -11.993967
1,Fe ka > -3.74,12.375786,Fe ka,-3.74,>,-14.394181,68.0,0.017162,Fe ka > -14.394181
2,Fe ka > -2.26,6.057059,Fe ka,-2.26,>,-8.585461,77.0,0.009247,Fe ka > -8.585461
3,Ca ka <= 3.95,5.095014,Ca ka,3.95,<=,24.763583,89.0,0.045885,Ca ka <= 24.763583
4,Si > -2.51,4.901034,Si,-2.51,>,-6.726367,45.0,0.014243,Si > -6.726367
...,...,...,...,...,...,...,...,...,...
116,Rayleight scattering <= 0.53,0.190050,Rayleight scattering,0.53,<=,0.683403,73.0,0.010942,Rayleight scattering <= 0.683403
117,background1 <= 0.05,0.068144,background1,0.05,<=,0.062920,64.0,0.002636,background1 <= 0.062920
118,background1 <= 0.16,0.000132,background1,0.16,<=,0.220244,63.0,0.001524,background1 <= 0.220244
119,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
120,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 34 variáveis espectrais
  - Range de energias: 6.1 - 6.76
  - Variância explicada pela PC1: 99.73%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=svm_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 127 | Descartados: 41
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 126 | Descartados: 42
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 126 predicados...
  Predicado: Al > -0.68 (n=87)
    Zona: 12 colunas
    Importance: 0.000095
  Predicado: Al <= -0.19 (n=43)
    Zona: 12 colunas
    Importance: 0.000134
  Predicado: Al > -0.19 (n=65)
    Zona: 12 colunas
    Importance: 0.000111
  Predicado: Al <= 0.19 (n=67)
    Zona: 12 colunas
    Importance: 0.000091
  Predicado: Al > 0.19 (n=41)
    Zona: 12 colunas
    Importance: 0.000167
  Predicado: Al <= 0.62 (n=87)
    Zona: 12 colunas
    Importance: 0.000095
  Predicado: Si > -2.51 (n=83)
    Zona: 12 colunas
    Importance: 0.081886
  Predicado: Si <= -1.67 (n=45)
    Zona: 12 colunas
    Importance: 0.008934
  Predicado: Si > -1.67 (n=63)
    Zona: 12 colunas
    Importance: 0.106700
  Predicado: Si <= -0.72 (n=65)
    Zona: 12 colunas
    Importance: 0.006353
  Predicado: Si > -0.72 (n=43)
    Zona: 12 colunas
    Importance: 0.156075
  Predicado: Si <= 3.71 (n=85)
    Zona: 12 colunas
    Importance: 0.032263
  Predicado: P > -1.23 (n=88)
    Zona: 16 colunas
    Importance: 0.000438
  Predicado: P <= -0.59 (n=42)
    Zona: 16 colunas
    Importance: 0.000242
  Predicado: P > -0.59 (n=66)
    Zona: 16 colunas
    Importance: 0.000527
  Predicado: P <= 0.08 (n=63)
    Zona: 16 colunas
    Importance: 0.000197
  Predicado: P > 0.08 (n=45)
    Zona: 16 colunas
    Importance: 0.000722
  Predicado: P <= 1.06 (n=84)
    Zona: 16 colunas
    Importance: 0.000236
  Predicado: S > -0.55 (n=86)
    Zona: 15 colunas
    Importance: 0.000230
  Predicado: S <= -0.27 (n=43)
    Zona: 15 colunas
    Importance: 0.000288
  Predicado: S > -0.27 (n=65)
    Zona: 15 colunas
    Importance: 0.000256
  Predicado: S <= 0.09 (n=62)
    Zona: 15 colunas
    Importance: 0.000221
  Predicado: S > 0.09 (n=46)
    Zona: 15 colunas
    Importance: 0.000333
  Predicado: S <= 0.55 (n=84)
    Zona: 15 colunas
    Importance: 0.000214
  Predicado: Rh L + Ar > -1.66 (n=90)
    Zona: 34 colunas
    Importance: 0.002135
  Predicado: Rh L + Ar <= -0.77 (n=37)
    Zona: 34 colunas
    Importance: 0.000741
  Predicado: Rh L + Ar > -0.77 (n=71)
    Zona: 34 colunas
    Importance: 0.002546
  Predicado: Rh L + Ar <= -0.16 (n=63)
    Zona: 34 colunas
    Importance: 0.000504
  Predicado: Rh L + Ar > -0.16 (n=45)
    Zona: 34 colunas
    Importance: 0.003921
  Predicado: Rh L + Ar <= 1.37 (n=89)
    Zona: 34 colunas
    Importance: 0.000823
  Predicado: K > -6.69 (n=87)
    Zona: 19 colunas
    Importance: 0.005400
  Predicado: K <= -1.46 (n=42)
    Zona: 19 colunas
    Importance: 0.006013
  Predicado: K > -1.46 (n=66)
    Zona: 19 colunas
    Importance: 0.006035
  Predicado: K <= 2.15 (n=66)
    Zona: 19 colunas
    Importance: 0.004241
  Predicado: K > 2.15 (n=42)
    Zona: 19 colunas
    Importance: 0.008833
  Predicado: K <= 6.26 (n=86)
    Zona: 19 colunas
    Importance: 0.004683
  Predicado: Ca ka > -4.65 (n=86)
    Zona: 21 colunas
    Importance: 0.010622
  Predicado: Ca ka <= -1.50 (n=44)
    Zona: 21 colunas
    Importance: 0.058835
  Predicado: Ca ka > -1.50 (n=64)
    Zona: 21 colunas
    Importance: 0.006939
  Predicado: Ca ka <= 1.77 (n=67)
    Zona: 21 colunas
    Importance: 0.039625
  Predicado: Ca ka > 1.77 (n=41)
    Zona: 21 colunas
    Importance: 0.009220
  Predicado: Ca ka <= 3.95 (n=87)
    Zona: 21 colunas
    Importance: 0.031605
  Predicado: Ca kb > -1.81 (n=86)
    Zona: 16 colunas
    Importance: 0.001330
  Predicado: Ca kb <= -0.59 (n=45)
    Zona: 16 colunas
    Importance: 0.004176
  Predicado: Ca kb > -0.59 (n=63)
    Zona: 16 colunas
    Importance: 0.000875
  Predicado: Ca kb <= 0.62 (n=66)
    Zona: 16 colunas
    Importance: 0.002953
  Predicado: Ca kb > 0.62 (n=42)
    Zona: 16 colunas
    Importance: 0.001146
  Predicado: Ca kb <= 1.58 (n=87)
    Zona: 16 colunas
    Importance: 0.002385
  Predicado: background1 > -0.14 (n=87)
    Zona: 12 colunas
    Importance: 0.000014
  Predicado: background1 <= -0.05 (n=43)
    Zona: 12 colunas
    Importance: 0.000016
  Predicado: background1 > -0.05 (n=65)
    Zona: 12 colunas
    Importance: 0.000014
  Predicado: background1 <= 0.05 (n=68)
    Zona: 12 colunas
    Importance: 0.000012
  Predicado: background1 > 0.05 (n=40)
    Zona: 12 colunas
    Importance: 0.000018
  Predicado: background1 <= 0.16 (n=90)
    Zona: 12 colunas
    Importance: 0.000014
  Predicado: Ti ka > -0.86 (n=87)
    Zona: 15 colunas
    Importance: 0.001296
  Predicado: Ti ka <= -0.70 (n=44)
    Zona: 15 colunas
    Importance: 0.000208
  Predicado: Ti ka > -0.70 (n=64)
    Zona: 15 colunas
    Importance: 0.001722
  Predicado: Ti ka <= -0.52 (n=63)
    Zona: 15 colunas
    Importance: 0.000156
  Predicado: Ti ka > -0.52 (n=45)
    Zona: 15 colunas
    Importance: 0.002434
  Predicado: Ti ka <= 0.53 (n=87)
    Zona: 15 colunas
    Importance: 0.000268
  Predicado: Ti kb > -0.32 (n=88)
    Zona: 22 colunas
    Importance: 0.000091
  Predicado: Ti kb <= -0.14 (n=45)
    Zona: 22 colunas
    Importance: 0.000098
  Predicado: Ti kb > -0.14 (n=63)
    Zona: 22 colunas
    Importance: 0.000113
  Predicado: Ti kb <= 0.03 (n=66)
    Zona: 22 colunas
    Importance: 0.000073
  Predicado: Ti kb > 0.03 (n=42)
    Zona: 22 colunas
    Importance: 0.000159
  Predicado: Ti kb <= 0.20 (n=86)
    Zona: 22 colunas
    Importance: 0.000074
  Predicado: background2 > -0.26 (n=90)
    Zona: 33 colunas
    Importance: 0.000032
  Predicado: background2 <= -0.08 (n=43)
    Zona: 33 colunas
    Importance: 0.000071
  Predicado: background2 > -0.08 (n=65)
    Zona: 33 colunas
    Importance: 0.000030
  Predicado: background2 <= 0.11 (n=70)
    Zona: 33 colunas
    Importance: 0.000051
  Predicado: background2 > 0.11 (n=38)
    Zona: 33 colunas
    Importance: 0.000038
  Predicado: background2 <= 0.30 (n=91)
    Zona: 33 colunas
    Importance: 0.000048
  Predicado: Mn > -1.22 (n=88)
    Zona: 20 colunas
    Importance: 0.000203
  Predicado: Mn <= -0.41 (n=43)
    Zona: 20 colunas
    Importance: 0.000378
  Predicado: Mn > -0.41 (n=65)
    Zona: 20 colunas
    Importance: 0.000212
  Predicado: Mn <= 0.23 (n=67)
    Zona: 20 colunas
    Importance: 0.000257
  Predicado: Mn > 0.23 (n=41)
    Zona: 20 colunas
    Importance: 0.000312
  Predicado: Mn <= 1.01 (n=90)
    Zona: 20 colunas
    Importance: 0.000228
  Predicado: Fe ka > -3.74 (n=86)
    Zona: 34 colunas
    Importance: 0.013876
  Predicado: Fe ka <= -3.05 (n=44)
    Zona: 34 colunas
    Importance: 0.002210
  Predicado: Fe ka > -3.05 (n=64)
    Zona: 34 colunas
    Importance: 0.018221
  Predicado: Fe ka <= -2.26 (n=63)
    Zona: 34 colunas
    Importance: 0.001678
  Predicado: Fe ka > -2.26 (n=45)
    Zona: 34 colunas
    Importance: 0.025725
  Predicado: Fe ka <= 1.10 (n=87)
    Zona: 34 colunas
    Importance: 0.003733
  Predicado: Fe kb > -0.91 (n=87)
    Zona: 23 colunas
    Importance: 0.001182
  Predicado: Fe kb <= -0.63 (n=41)
    Zona: 23 colunas
    Importance: 0.000156
  Predicado: Fe kb > -0.63 (n=67)
    Zona: 23 colunas
    Importance: 0.001507
  Predicado: Fe kb <= -0.44 (n=66)
    Zona: 23 colunas
    Importance: 0.000115
  Predicado: Fe kb > -0.44 (n=42)
    Zona: 23 colunas
    Importance: 0.002375
  Predicado: Fe kb <= 0.33 (n=87)
    Zona: 23 colunas
    Importance: 0.000167
  Predicado: Ni > -0.60 (n=88)
    Zona: 25 colunas
    Importance: 0.000102
  Predicado: Ni <= -0.14 (n=44)
    Zona: 25 colunas
    Importance: 0.000135
  Predicado: Ni > -0.14 (n=64)
    Zona: 25 colunas
    Importance: 0.000116
  Predicado: Ni <= 0.13 (n=64)
    Zona: 25 colunas
    Importance: 0.000122
  Predicado: Ni > 0.13 (n=44)
    Zona: 25 colunas
    Importance: 0.000126
  Predicado: Ni <= 0.59 (n=90)
    Zona: 25 colunas
    Importance: 0.000117
  Predicado: background3 > -1.50 (n=88)
    Zona: 271 colunas
    Importance: 0.000564
  Predicado: background3 <= -0.49 (n=44)
    Zona: 271 colunas
    Importance: 0.000964
  Predicado: background3 > -0.49 (n=64)
    Zona: 271 colunas
    Importance: 0.000558
  Predicado: background3 <= 0.36 (n=67)
    Zona: 271 colunas
    Importance: 0.000698
  Predicado: background3 > 0.36 (n=41)
    Zona: 271 colunas
    Importance: 0.000765
  Predicado: background3 <= 1.60 (n=89)
    Zona: 271 colunas
    Importance: 0.000660
  Predicado: sum Fe > -0.60 (n=89)
    Zona: 27 colunas
    Importance: 0.000156
  Predicado: sum Fe <= -0.28 (n=44)
    Zona: 27 colunas
    Importance: 0.000144
  Predicado: sum Fe > -0.28 (n=64)
    Zona: 27 colunas
    Importance: 0.000174
  Predicado: sum Fe <= 0.07 (n=69)
    Zona: 27 colunas
    Importance: 0.000102
  Predicado: sum Fe > 0.07 (n=39)
    Zona: 27 colunas
    Importance: 0.000268
  Predicado: sum Fe <= 0.62 (n=89)
    Zona: 27 colunas
    Importance: 0.000100
  Predicado: background4 > -1.28 (n=88)
    Zona: 219 colunas
    Importance: 0.000522
  Predicado: background4 <= -0.62 (n=42)
    Zona: 219 colunas
    Importance: 0.000926
  Predicado: background4 > -0.62 (n=66)
    Zona: 219 colunas
    Importance: 0.000572
  Predicado: background4 <= 0.14 (n=67)
    Zona: 219 colunas
    Importance: 0.000618
  Predicado: background4 > 0.14 (n=41)
    Zona: 219 colunas
    Importance: 0.000860
  Predicado: background4 <= 1.47 (n=90)
    Zona: 219 colunas
    Importance: 0.000532
  Predicado: Compton scattering > -0.88 (n=86)
    Zona: 85 colunas
    Importance: 0.000280
  Predicado: Compton scattering <= -0.40 (n=42)
    Zona: 85 colunas
    Importance: 0.000421
  Predicado: Compton scattering > -0.40 (n=66)
    Zona: 85 colunas
    Importance: 0.000311
  Predicado: Compton scattering <= 0.05 (n=68)
    Zona: 85 colunas
    Importance: 0.000283
  Predicado: Compton scattering > 0.05 (n=40)
    Zona: 85 colunas
    Importance: 0.000474
  Predicado: Compton scattering <= 0.87 (n=88)
    Zona: 85 colunas
    Importance: 0.000252
  Predicado: Rayleight scattering > -0.50 (n=86)
    Zona: 56 colunas
    Importance: 0.000111
  Predicado: Rayleight scattering <= -0.25 (n=43)
    Zona: 56 colunas
    Importance: 0.000154
  Predicado: Rayleight scattering > -0.25 (n=65)
    Zona: 56 colunas
    Importance: 0.000128
  Predicado: Rayleight scattering <= 0.03 (n=67)
    Zona: 56 colunas
    Importance: 0.000108
  Predicado: Rayleight scattering > 0.03 (n=41)
    Zona: 56 colunas
    Importance: 0.000187
  Predicado: Rayleight scattering <= 0.53 (n=89)
    Zona: 56 colunas
    Importance: 0.000097

[Bag_2] Processando 126 predicados...
  Predicado: Al > -0.68 (n=84)
    Zona: 12 colunas
    Importance: 0.000102
  Predicado: Al <= -0.19 (n=46)
    Zona: 12 colunas
    Importance: 0.000139
  Predicado: Al > -0.19 (n=62)
    Zona: 12 colunas
    Importance: 0.000119
  Predicado: Al <= 0.19 (n=66)
    Zona: 12 colunas
    Importance: 0.000102
  Predicado: Al > 0.19 (n=42)
    Zona: 12 colunas
    Importance: 0.000168
  Predicado: Al <= 0.62 (n=86)
    Zona: 12 colunas
    Importance: 0.000102
  Predicado: Si > -2.51 (n=83)
    Zona: 12 colunas
    Importance: 0.067264
  Predicado: Si <= -1.67 (n=47)
    Zona: 12 colunas
    Importance: 0.009207
  Predicado: Si > -1.67 (n=61)
    Zona: 12 colunas
    Importance: 0.090334
  Predicado: Si <= -0.72 (n=68)
    Zona: 12 colunas
    Importance: 0.006532
  Predicado: Si > -0.72 (n=40)
    Zona: 12 colunas
    Importance: 0.137473
  Predicado: Si <= 3.71 (n=87)
    Zona: 12 colunas
    Importance: 0.026663
  Predicado: P > -1.23 (n=84)
    Zona: 16 colunas
    Importance: 0.000416
  Predicado: P <= -0.59 (n=44)
    Zona: 16 colunas
    Importance: 0.000395
  Predicado: P > -0.59 (n=64)
    Zona: 16 colunas
    Importance: 0.000508
  Predicado: P <= 0.08 (n=65)
    Zona: 16 colunas
    Importance: 0.000302
  Predicado: P > 0.08 (n=43)
    Zona: 16 colunas
    Importance: 0.000705
  Predicado: P <= 1.06 (n=87)
    Zona: 16 colunas
    Importance: 0.000317
  Predicado: S > -0.55 (n=87)
    Zona: 15 colunas
    Importance: 0.000234
  Predicado: S <= -0.27 (n=44)
    Zona: 15 colunas
    Importance: 0.000227
  Predicado: S > -0.27 (n=64)
    Zona: 15 colunas
    Importance: 0.000271
  Predicado: S <= 0.09 (n=66)
    Zona: 15 colunas
    Importance: 0.000184
  Predicado: S > 0.09 (n=42)
    Zona: 15 colunas
    Importance: 0.000362
  Predicado: S <= 0.55 (n=87)
    Zona: 15 colunas
    Importance: 0.000187
  Predicado: Rh L + Ar > -1.66 (n=88)
    Zona: 34 colunas
    Importance: 0.002937
  Predicado: Rh L + Ar <= -0.77 (n=42)
    Zona: 34 colunas
    Importance: 0.000473
  Predicado: Rh L + Ar > -0.77 (n=66)
    Zona: 34 colunas
    Importance: 0.003778
  Predicado: Rh L + Ar <= -0.16 (n=67)
    Zona: 34 colunas
    Importance: 0.000360
  Predicado: Rh L + Ar > -0.16 (n=41)
    Zona: 34 colunas
    Importance: 0.005978
  Predicado: Rh L + Ar <= 1.37 (n=90)
    Zona: 34 colunas
    Importance: 0.000731
  Predicado: K > -6.69 (n=85)
    Zona: 19 colunas
    Importance: 0.005490
  Predicado: K <= -1.46 (n=45)
    Zona: 19 colunas
    Importance: 0.006353
  Predicado: K > -1.46 (n=63)
    Zona: 19 colunas
    Importance: 0.006199
  Predicado: K <= 2.15 (n=64)
    Zona: 19 colunas
    Importance: 0.004871
  Predicado: K > 2.15 (n=44)
    Zona: 19 colunas
    Importance: 0.008288
  Predicado: K <= 6.26 (n=87)
    Zona: 19 colunas
    Importance: 0.005077
  Predicado: Ca ka > -4.65 (n=89)
    Zona: 21 colunas
    Importance: 0.008919
  Predicado: Ca ka <= -1.50 (n=41)
    Zona: 21 colunas
    Importance: 0.061474
  Predicado: Ca ka > -1.50 (n=67)
    Zona: 21 colunas
    Importance: 0.006477
  Predicado: Ca ka <= 1.77 (n=67)
    Zona: 21 colunas
    Importance: 0.038646
  Predicado: Ca ka > 1.77 (n=41)
    Zona: 21 colunas
    Importance: 0.008906
  Predicado: Ca ka <= 3.95 (n=87)
    Zona: 21 colunas
    Importance: 0.030894
  Predicado: Ca kb > -1.81 (n=89)
    Zona: 16 colunas
    Importance: 0.001244
  Predicado: Ca kb <= -0.59 (n=41)
    Zona: 16 colunas
    Importance: 0.004717
  Predicado: Ca kb > -0.59 (n=67)
    Zona: 16 colunas
    Importance: 0.000844
  Predicado: Ca kb <= 0.62 (n=66)
    Zona: 16 colunas
    Importance: 0.003056
  Predicado: Ca kb > 0.62 (n=42)
    Zona: 16 colunas
    Importance: 0.001149
  Predicado: Ca kb <= 1.58 (n=87)
    Zona: 16 colunas
    Importance: 0.002475
  Predicado: background1 > -0.14 (n=86)
    Zona: 12 colunas
    Importance: 0.000013
  Predicado: background1 <= -0.05 (n=42)
    Zona: 12 colunas
    Importance: 0.000022
  Predicado: background1 > -0.05 (n=66)
    Zona: 12 colunas
    Importance: 0.000012
  Predicado: background1 <= 0.05 (n=63)
    Zona: 12 colunas
    Importance: 0.000017
  Predicado: background1 > 0.05 (n=45)
    Zona: 12 colunas
    Importance: 0.000015
  Predicado: background1 <= 0.16 (n=83)
    Zona: 12 colunas
    Importance: 0.000016
  Predicado: Ti ka > -0.86 (n=84)
    Zona: 15 colunas
    Importance: 0.001427
  Predicado: Ti ka <= -0.70 (n=45)
    Zona: 15 colunas
    Importance: 0.000254
  Predicado: Ti ka > -0.70 (n=63)
    Zona: 15 colunas
    Importance: 0.001852
  Predicado: Ti ka <= -0.52 (n=67)
    Zona: 15 colunas
    Importance: 0.000182
  Predicado: Ti ka > -0.52 (n=41)
    Zona: 15 colunas
    Importance: 0.002827
  Predicado: Ti ka <= 0.53 (n=88)
    Zona: 15 colunas
    Importance: 0.000247
  Predicado: Ti kb > -0.32 (n=84)
    Zona: 22 colunas
    Importance: 0.000090
  Predicado: Ti kb <= -0.14 (n=44)
    Zona: 22 colunas
    Importance: 0.000140
  Predicado: Ti kb > -0.14 (n=64)
    Zona: 22 colunas
    Importance: 0.000106
  Predicado: Ti kb <= 0.03 (n=65)
    Zona: 22 colunas
    Importance: 0.000100
  Predicado: Ti kb > 0.03 (n=43)
    Zona: 22 colunas
    Importance: 0.000149
  Predicado: Ti kb <= 0.20 (n=86)
    Zona: 22 colunas
    Importance: 0.000092
  Predicado: background2 > -0.26 (n=89)
    Zona: 33 colunas
    Importance: 0.000030
  Predicado: background2 <= -0.08 (n=44)
    Zona: 33 colunas
    Importance: 0.000094
  Predicado: background2 > -0.08 (n=64)
    Zona: 33 colunas
    Importance: 0.000027
  Predicado: background2 <= 0.11 (n=65)
    Zona: 33 colunas
    Importance: 0.000070
  Predicado: background2 > 0.11 (n=43)
    Zona: 33 colunas
    Importance: 0.000030
  Predicado: background2 <= 0.30 (n=84)
    Zona: 33 colunas
    Importance: 0.000061
  Predicado: Mn > -1.22 (n=85)
    Zona: 20 colunas
    Importance: 0.000228
  Predicado: Mn <= -0.41 (n=42)
    Zona: 20 colunas
    Importance: 0.000625
  Predicado: Mn > -0.41 (n=66)
    Zona: 20 colunas
    Importance: 0.000233
  Predicado: Mn <= 0.23 (n=66)
    Zona: 20 colunas
    Importance: 0.000410
  Predicado: Mn > 0.23 (n=42)
    Zona: 20 colunas
    Importance: 0.000347
  Predicado: Mn <= 1.01 (n=86)
    Zona: 20 colunas
    Importance: 0.000348
  Predicado: Fe ka > -3.74 (n=85)
    Zona: 34 colunas
    Importance: 0.011652
  Predicado: Fe ka <= -3.05 (n=45)
    Zona: 34 colunas
    Importance: 0.002336
  Predicado: Fe ka > -3.05 (n=63)
    Zona: 34 colunas
    Importance: 0.015202
  Predicado: Fe ka <= -2.26 (n=68)
    Zona: 34 colunas
    Importance: 0.001708
  Predicado: Fe ka > -2.26 (n=40)
    Zona: 34 colunas
    Importance: 0.023668
  Predicado: Fe ka <= 1.10 (n=89)
    Zona: 34 colunas
    Importance: 0.003274
  Predicado: Fe kb > -0.91 (n=87)
    Zona: 23 colunas
    Importance: 0.001309
  Predicado: Fe kb <= -0.63 (n=41)
    Zona: 23 colunas
    Importance: 0.000227
  Predicado: Fe kb > -0.63 (n=67)
    Zona: 23 colunas
    Importance: 0.001671
  Predicado: Fe kb <= -0.44 (n=64)
    Zona: 23 colunas
    Importance: 0.000162
  Predicado: Fe kb > -0.44 (n=44)
    Zona: 23 colunas
    Importance: 0.002521
  Predicado: Fe kb <= 0.33 (n=89)
    Zona: 23 colunas
    Importance: 0.000185
  Predicado: Ni > -0.60 (n=87)
    Zona: 25 colunas
    Importance: 0.000101
  Predicado: Ni <= -0.14 (n=42)
    Zona: 25 colunas
    Importance: 0.000190
  Predicado: Ni > -0.14 (n=66)
    Zona: 25 colunas
    Importance: 0.000111
  Predicado: Ni <= 0.13 (n=62)
    Zona: 25 colunas
    Importance: 0.000157
  Predicado: Ni > 0.13 (n=46)
    Zona: 25 colunas
    Importance: 0.000121
  Predicado: Ni <= 0.59 (n=86)
    Zona: 25 colunas
    Importance: 0.000144
  Predicado: background3 > -1.50 (n=88)
    Zona: 271 colunas
    Importance: 0.000601
  Predicado: background3 <= -0.49 (n=42)
    Zona: 271 colunas
    Importance: 0.001103
  Predicado: background3 > -0.49 (n=66)
    Zona: 271 colunas
    Importance: 0.000610
  Predicado: background3 <= 0.36 (n=63)
    Zona: 271 colunas
    Importance: 0.000801
  Predicado: background3 > 0.36 (n=45)
    Zona: 271 colunas
    Importance: 0.000803
  Predicado: background3 <= 1.60 (n=85)
    Zona: 271 colunas
    Importance: 0.000742
  Predicado: sum Fe > -0.60 (n=87)
    Zona: 27 colunas
    Importance: 0.000143
  Predicado: sum Fe <= -0.28 (n=40)
    Zona: 27 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Si > -0.72,Si > -0.72,Si > -0.72,Si > -0.72
1,Si > -1.67,Si > -1.67,Si > -1.67,Si > -1.67
2,Si > -2.51,Si > -2.51,Si > -2.51,Si > -2.51
3,Ca ka <= -1.50,Ca ka <= -1.50,Ca ka <= -1.50,Ca ka <= -1.50
4,Ca ka <= 1.77,Ca ka <= 1.77,Ca ka <= 1.77,Ca ka <= 1.77
...,...,...,...,...
126,background1 > -0.05,background1 > -0.05,background1 <= 0.05,background1 <= 0.05
127,background1 > -0.14,Class_A,background1 > -0.05,background1 > -0.14
128,Class_A,Class_B,Class_A,background1 > -0.05
129,Class_B,NaN,Class_B,Class_A
130,NaN,NaN,NaN,Class_B

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

                Predicate  Perturbation
0              Si > -0.72      0.156075
1              Si > -1.67      0.106700
2              Si > -2.51      0.081886
3          Ca ka <= -1.50      0.058835
4           Ca ka <= 1.77      0.039625
..                    ...           ...
121  background1 <= -0.05      0.000016
122   background1 > -0.05      0.000014
123   background1 <= 0.16      0.000014
124   background1 > -0.14      0.000014
125   background1 <= 0.05      0.000012

[126 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Si > -0.72,22.750431,Si,-0.72,>
1,Ca ka <= -1.50,9.047055,Ca ka,-1.50,<=
2,Fe ka > -2.26,3.710399,Fe ka,-2.26,>
3,K > 2.15,0.882055,K,2.15,>
4,Rh L + Ar > -0.77,0.604089,Rh L + Ar,-0.77,>
5,Ca kb <= -0.59,0.598031,Ca kb,-0.59,<=
6,Ti ka > -0.52,0.538745,Ti ka,-0.52,>
7,Fe kb > -0.44,0.411061,Fe kb,-0.44,>
8,background3 <= -0.49,0.172267,background3,-0.49,<=
9,background4 <= -0.62,0.124626,background4,-0.62,<=
10,P > 0.08,0.089228,P,0.08,>
11,Mn <= -0.41,0.077067,Mn,-0.41,<=
12,Compton scattering > 0.05,0.073844,Compton scattering,0.05,>
13,S > 0.09,0.071270,S,0.09,>
14,sum Fe > 0.07,0.056641,sum Fe,0.07,>
15,Ti kb > 0.03,0.049060,Ti kb,0.03,>
16,Al > 0.19,0.048097,Al,0.19,>
17,Ni <= -0.14,0.047060,Ni,-0.14,<=
18,Rayleight scattering > 0.03,0.046465,Rayleight scattering,0.03,>
19,background2 <= -0.08,0.038734,background2,-0.08,<=
20,background1 <= -0.05,0.000184,background1,-0.05,<=
21,Class_B,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Si > -0.72,22.750431,Si,-0.72,>,-2.087044,129.0,0.038926,Si > -2.087044
1,Si > -1.67,16.061179,Si,-1.67,>,-4.200922,133.0,0.023527,Si > -4.200922
2,Si > -2.51,12.145635,Si,-2.51,>,-6.726367,45.0,0.014243,Si > -6.726367
3,Ca ka <= -1.50,9.047055,Ca ka,-1.50,<=,-9.476439,94.0,0.083086,Ca ka <= -9.476439
4,Ca ka <= 1.77,6.526871,Ca ka,1.77,<=,11.953266,82.0,0.013408,Ca ka <= 11.953266
...,...,...,...,...,...,...,...,...,...
128,background1 <= 0.05,0.000113,background1,0.05,<=,0.062920,64.0,0.002636,background1 <= 0.062920
129,background1 > -0.14,0.000101,background1,-0.14,>,-0.162473,129.0,0.000043,background1 > -0.162473
130,background1 > -0.05,0.000071,background1,-0.05,>,-0.076696,26.0,0.002030,background1 > -0.076696
131,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None
132,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None

In [24]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Si':
  - Dimensão: 12 variáveis espectrais
  - Variância explicada pela PC1: 99.71%

In [17]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = svm_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = svm_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba                  Zone
0    6.42                      0.011520                 Fe ka
1    3.32                      0.005267                     K
2     3.7                      0.005229                 Ca ka
3    1.74                      0.004396                    Si
4    2.62                      0.000850             Rh L + Ar
5    4.02                      0.000557                 Ca kb
6    4.52                      0.000392                 Ti ka
7    7.06                      0.000326                 Fe kb
8       2                      0.000172                     P
9    5.88                      0.000111                    Mn
10    2.3                      0.000082                     S
11   1.62                      0.000052                    Al
12  13.41                      0.000037                sum Fe
13   7.54                      0.000030                    Ni
14   4.94                      0.000027                 Ti kb
15  11.95                      0.000021           background3
16  18.81                      0.000019    Compton scattering
17  14.13                      0.000015           background4
18  20.25                      0.000011  Rayleight scattering
19   4.14                      0.000007           background1
20    5.6                      0.000006           background2

In [18]:
import numpy as np

max_len = max(
    len(pvector_unique_df['Zone']),
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'SVM_pvector': pad_list(pvector_unique_df['Zone'], max_len),
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

,SVM_pvector,Shap,Permutation,LRC_perturbation,LRC_covariance
0,Fe ka,Si,Fe ka,Si,Fe ka
1,Ca ka,Ca ka,K,Ca ka,Ca ka
2,Si,Fe ka,Ca ka,Fe ka,Si
3,K,K,Si,K,K
4,Ca kb,background4,Rh L + Ar,Rh L + Ar,Ti ka
5,Ti ka,Rh L + Ar,Ca kb,Ca kb,Fe kb
6,Fe kb,background3,Ti ka,Ti ka,Ca kb
7,Rh L + Ar,Compton scattering,Fe kb,Fe kb,Rh L + Ar
8,P,S,P,background3,background4
9,S,sum Fe,Mn,background4,Compton scattering
10,sum Fe,Al,S,P,sum Fe
11,Al,Rayleight scattering,Al,Mn,Rayleight scattering
12,Ti kb,background2,sum Fe,Compton scattering,Al
13,Ni,Ti kb,Ni,S,background3
14,Mn,background1,Ti kb,sum Fe,Ti kb
15,Compton scattering,Ti ka,background3,Ti kb,P
16,background3,Mn,Compton scattering,Al,Mn
17,Rayleight scattering,P,background4,Ni,S
18,background4,Ca kb,Rayleight scattering,Rayleight scattering,Ni
19,background1,Fe kb,background1,background2,background2
20,background2,Ni,background2,background1,background1
21,None,None,None,None,None

In [19]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_19108\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
3       SVM_pvector    LRC_covariance   0.944600
5              Shap  LRC_perturbation   0.920197
1       SVM_pvector       Permutation   0.788690
8       Permutation    LRC_covariance   0.777155
2       SVM_pvector  LRC_perturbation   0.534558
9  LRC_perturbation    LRC_covariance   0.527365
6              Shap    LRC_covariance   0.501752
0       SVM_pvector              Shap   0.498619
7       Permutation  LRC_perturbation   0.408410
4              Shap       Permutation   0.356854

In [20]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')