In [1]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import kennard_stone as ks
pd.options.plotting.backend = 'plotly'  # setting plotly as the backend for pandas plotting

# Add parent directory to sys.path so local module 'synthetic' (one level up) can be imported
import sys
from pathlib import Path # for path manipulations
parent_dir = Path.cwd().parent.parent.parent.resolve() # move two levels up from current working directory
if str(parent_dir) not in sys.path: # check to avoid duplicates
    sys.path.insert(0, str(parent_dir)) # insert at the start of sys.path to prioritize local modules

# Loading a soil spectral dataset based on X-ray fluorescence (XRF)
data_complete = pd.read_csv(f'{parent_dir}/XRF_databases/bank_notes/plsda/bank_notes.csv', sep=';') # local copy of Toledo 2022 dataset (os ... indica para omitir o caminho longo)
data = data_complete.loc[:, '2.74':'22.71']

# Split dataset by class and create calibration/prediction sets using Kennard-Stone (as in original pipeline)
data_A = data_complete[data_complete['Class'] == 'A'].reset_index(drop=True)
data_B = data_complete[data_complete['Class'] == 'B'].reset_index(drop=True)

# splitting the data into calibration and prediction sets by kennard-stone algorithm
XA_cal, XA_pred = ks.train_test_split(data_A.loc[:, '2.74':'22.71'], test_size=0.30)  # class A
XA_cal = XA_cal.reset_index(drop=True)
XA_pred = XA_pred.reset_index(drop=True)

XB_cal, XB_pred = ks.train_test_split(data_B.loc[:, '2.74':'22.71'], test_size=0.30)  # class B
XB_cal = XB_cal.reset_index(drop=True)
XB_pred = XB_pred.reset_index(drop=True)

Xcalclass = pd.concat([XA_cal, XB_cal], axis=0).reset_index(drop=True)  # concatenating both classes
Xpredclass = pd.concat([XA_pred, XB_pred], axis=0).reset_index(drop=True)
ycalclass = pd.Series(['A']*XA_cal.shape[0] + ['B']*XB_cal.shape[0])  # target for calibration set
ypredclass = pd.Series(['A']*XA_pred.shape[0] + ['B']*XB_pred.shape[0])  # target for prediction set

# preprocessings
import preprocessings as prepr  # preprocessing methods for XRF data

Xcalclass_prep, mean_calclass, mean_calclass_poisson  = prepr.poisson(Xcalclass, mc=True)
Xpredclass_prep = ((Xpredclass/np.sqrt(mean_calclass)) - mean_calclass_poisson)

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:22:06,029 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:22:06,169 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:22:06,241 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
2026-02-09 05:22:06,289 - kennard_stone.utils._pairwise:109[INFO] - Calculating pairwise distances using scikit-learn.

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
from modeling import mlp_optimized

mlp_model = mlp_optimized(Xcalclass_prep, ycalclass, Xpredclass_prep, ypredclass, 
                          aim='classification', 
                          hidden_layer_sizes=(64,32),
                          activation='tanh',
                          learning_rate='adaptive',
                          max_iter=10,
                          random_state=1)
mlp_model[0]

C:\Users\Usuario\AppData\Roaming\Python\Python313\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

,Model,Accuracy Cal,Sensitivity Cal,Specificity Cal,CM Cal,Accuracy Pred,Sensitivity Pred,Specificity Pred,CM Pred
0,MLP,1.0,1.0,1.0,"[[175, 0], [0, 109]]",1.0,1.0,1.0,"[[76, 0], [0, 47]]"

## Definição das Zonas Espectrais

In [3]:
spectral_cuts = [
('Ar ka + Ag L', 2.76, 3.47),
('Ca ka', 3.5, 3.91),
('Ca kb', 3.93, 4.24),
('Ti ka', 4.26, 4.72),
('Ti kb', 4.75, 5.13),
('background1', 5.16, 6.12),
('Fe ka', 6.15, 6.76),
('Fe kb', 6.79, 7.32),
('background2', 7.35, 7.78),
('Cu ka', 7.81, 8.29),
('Zn ka', 8.29, 8.80),
('Cu kb', 8.80, 9.26),
('Zn kb', 9.26, 10.00),
('background3', 10.00, 21.46),
('Ag ka scattering', 21.49, 22.71)
]

## SHAP

In [5]:
shap_global_importance = pd.read_csv('shap_bank_notes.csv', sep=';') # loading previously saved shap_unique_df
# vamos gerar uma nova coluna em shap_global_importance com o nome da zona espectral correspondente de acordo com a lista spectral_cuts
energy_to_zone_shap = {}
for zone_name, start, end in spectral_cuts:
    for i in shap_global_importance['energy']:
        i_float = float(i)
        if start <= i_float <= end:
            energy_to_zone_shap[i] = zone_name
shap_global_importance['Zone'] = shap_global_importance['energy'].map(energy_to_zone_shap)

# agora vamos filtrar shap_global_importance para manter apenas as zonas espectrais únicas com maior SHAP score
shap_unique_df = shap_global_importance.sort_values(by='Mean_Abs_SHAP', ascending=False).reset_index(drop=True)
shap_unique_df = shap_unique_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
shap_unique_df

    energy  Mean_Abs_SHAP              Zone
0     3.73       0.041364             Ca ka
1     4.54       0.028252             Ti ka
2     6.38       0.013990             Fe ka
3     8.09       0.007152             Cu ka
4     4.88       0.003056             Ti kb
5     7.04       0.002463             Fe kb
6    22.28       0.002394  Ag ka scattering
7     4.06       0.000760             Ca kb
8    19.40       0.000475       background3
9     9.33       0.000432             Zn kb
10    8.98       0.000338             Cu kb
11    5.92       0.000264       background1
12    8.49       0.000243             Zn ka
13    7.45       0.000235       background2
14    3.07       0.000207      Ar ka + Ag L
15    2.74       0.000131               NaN

## Funções de Agregação por PCA

Aqui implementamos as funções para agregar zonas espectrais usando PCA com 1 componente principal.

In [6]:
import explaining as exp

# Extração das zonas espectrais
spectral_zones_class = exp.extract_spectral_zones(Xcalclass_prep, spectral_cuts)
zone_scores_df, pca_info_dict = exp.aggregate_spectral_zones_pca(spectral_zones_class) # apca aggregation
print(f"\nScores DataFrame shape: {zone_scores_df.shape}")

Zona 'Ar ka + Ag L': VE = 5.85%, dim = 29 variáveis
Zona 'Ca ka': VE = 98.41%, dim = 17 variáveis
Zona 'Ca kb': VE = 90.24%, dim = 13 variáveis
Zona 'Ti ka': VE = 96.36%, dim = 19 variáveis
Zona 'Ti kb': VE = 80.62%, dim = 16 variáveis
Zona 'background1': VE = 12.07%, dim = 39 variáveis
Zona 'Fe ka': VE = 99.63%, dim = 25 variáveis
Zona 'Fe kb': VE = 96.66%, dim = 22 variáveis
Zona 'background2': VE = 8.40%, dim = 18 variáveis
Zona 'Cu ka': VE = 97.03%, dim = 20 variáveis
Zona 'Zn ka': VE = 20.69%, dim = 21 variáveis
Zona 'Cu kb': VE = 63.49%, dim = 19 variáveis
Zona 'Zn kb': VE = 5.72%, dim = 30 variáveis
Zona 'background3': VE = 2.51%, dim = 451 variáveis
Zona 'Ag ka scattering': VE = 27.73%, dim = 49 variáveis

Scores DataFrame shape: (284, 15)

In [7]:
y_pred = mlp_model[4]['MLP'].values # using the continuous predictions from SVM, extracting as 1D array
predicates_quantiles = exp.predicates_by_quantiles(zone_scores_df, [0.2, 0.4, 0.6, 0.8])
predicate_info_dict = exp.create_predicate_info_dict(
    predicates_df=predicates_quantiles[0],
    predicate_indicator_df=predicates_quantiles[1],
    zone_aggregated_df=zone_scores_df,
    y_predicted_numeric=y_pred
)

In [8]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_cov = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

y_pred = pd.Series(mlp_model[4]['MLP'].values) # using the continuous predictions from SVM, extracting as 1D array

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist
    
    # Calcular MI
    cov_results_dict_seed = exp.calculate_predicate_metrics(
        bags_result=bags_result_seed,
        metric='covariance', # covariance ou mutual_information
        threshold=0.01, # threshold para cortar predicados irrelevantes
        n_neighbors=5
    )
    
    # Salvar no dicionário principal
    all_results_cov[seed] = {
        'bags_result': bags_result_seed,
        'cov_results_dict': cov_results_dict_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_cov[seed]['bags_result'],
        predicate_ranking_dict=all_results_cov[seed]['cov_results_dict'],
        metric_column='Covariance',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )
    # Armazenar grafo
    graphs_by_seed[seed] = DG

# Calcular LRC usando a função pronta do explaining.py
lrc_cov_by_seed = {}
for seed in random_seeds:
    DG = graphs_by_seed[seed]
    lrc_cov_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_cov_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_cov_by_seed[seed] = lrc_cov_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_cov_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_cov_df_seed = lrc_cov_by_seed[seed].rename(columns={'Node': f'Predicate_Cov_Seed_{seed}'})
    lrc_cov_all_seeds_df = pd.concat([lrc_cov_all_seeds_df, lrc_cov_df_seed[[f'Predicate_Cov_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_cov_unique_by_seed = {}
for seed, lrc_df in lrc_cov_by_seed.items():
    lrc_cov_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_cov_unique_df = lrc_cov_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_cov_unique_by_seed[seed] = lrc_cov_unique_df

lrc_cov_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 1
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 2
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando semente: 3
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Calculando Covariance para Predicados
Métrica: covariance
Threshold: 0.01

======================================================================
Processando Grafo - Semente: 0
======================================================================


Total de pares bidirecionais encontrados: 103
Removida: Ca ka > -21.19 -> Ca ka > -26.11 (62.0257) | Mantida: Ca ka > -26.11 -> Ca ka > -21.19 (63.6147)
Removida: Ca ka > -6.65 -> Fe kb > -7.02 (9.3037) | Mantida: Fe kb > -7.02 -> Ca ka > -6.65 (59.9828)
Removida: Ti ka <= 19.85 -> Fe kb > -7.02 (8.0830) | Mantida: Fe kb > -7.02 -> Ti ka <= 19.85 (28.0884)
Removida: Ti ka <= 19.85 -> Ca ka > -6.65 (15.9971) | Mantida: Ca ka > -6.65 -> Ti ka <= 19.85 (59.8550)
Removida: Ti ka > -28.53 -> Fe kb > -7.41 (19.4972) | Mantida: Fe kb > -7.41 -> Ti ka > -28.53 (21.0586)
Removida: Ti ka <= 9.34 -> Fe kb > -7.41 (17.8996) | Mantida: Fe kb > -7.41 -> Ti ka <= 9.34 (19.4735)
Removida: Ti ka <= 9.34 -> Ti ka > -28.53 (12.6583) | Mantida: Ti ka > -28.53 -> Ti ka <= 9.34 (38.9792)
Removida: Ca kb > -8.59 -> Ca kb > -6.07 (7.9923) | Mantida: Ca kb > -6.07 -> Ca kb > -8.59 (30.8124)
Removida: Cu ka > -9.68 -> Cu ka > -10.68 (6.5758) | Mantida: Cu ka > -10.68 -> Cu ka > -9.68 (29.1975)
Removida: Ti kb <= 6.95 -> Ca kb > -2.67 (9.2100) | Mantida: Ca kb > -2.67 -> Ti kb <= 6.95 (13.5502)
Removida: Ca kb > -2.67 -> Cu ka > -8.43 (2.5096) | Mantida: Cu ka > -8.43 -> Ca kb > -2.67 (12.6557)
Removida: Ti kb <= 6.95 -> Cu ka > -8.43 (4.5170) | Mantida: Cu ka > -8.43 -> Ti kb <= 6.95 (6.2391)
Removida: Ca ka <= 33.38 -> Ti kb <= 6.95 (2.8206) | Mantida: Ti kb <= 6.95 -> Ca ka <= 33.38 (4.5319)
Removida: Ti kb > -10.26 -> Cu ka > -8.43 (2.1886) | Mantida: Cu ka > -8.43 -> Ti kb > -10.26 (7.9488)
Removida: Ti kb > -10.26 -> Ca ka <= 33.38 (2.0605) | Mantida: Ca ka <= 33.38 -> Ti kb > -10.26 (10.3781)
Removida: Ca ka <= 33.38 -> Ti kb <= 2.45 (4.7858) | Mantida: Ti kb <= 2.45 -> Ca ka <= 33.38 (5.2005)
Removida: Cu kb > -2.30 -> Ti ka <= -4.69 (0.7390) | Mantida: Ti ka <= -4.69 -> Cu kb > -2.30 (4.9555)
Removida: Cu kb > -2.30 -> Cu kb > -1.61 (0.6620) | Mantida: Cu kb > -1.61 -> Cu kb > -2.30 (2.1236)
Removida: Ag ka scattering <= 3.49 -> Cu kb > -2.88 (0.2719) | Mantida: Cu kb > -2.88 -> Ag ka scattering <= 3.49 (1.7855)
Removida: Ag ka scattering <= -0.18 -> Ag ka scattering <= 3.49 (0.2399) | Mantida: Ag ka scattering <= 3.49 -> Ag ka scattering <= -0.18 (1.6011)
Removida: Cu kb > -2.88 -> Cu kb > -1.61 (0.5842) | Mantida: Cu kb > -1.61 -> Cu kb > -2.88 (0.6450)
Removida: Cu kb > -2.88 -> Ag ka scattering <= 1.67 (0.5187) | Mantida: Ag ka scattering <= 1.67 -> Cu kb > -2.88 (0.5232)
Removida: Cu kb > -2.88 -> Ca kb <= 12.61 (1.1982) | Mantida: Ca kb <= 12.61 -> Cu kb > -2.88 (1.6454)
Removida: Ag ka scattering <= -0.18 -> Cu kb > -1.61 (0.7902) | Mantida: Cu kb > -1.61 -> Ag ka scattering <= -0.18 (1.1623)
Removida: Ag ka scattering <= 1.67 -> Ca ka <= -6.65 (0.6868) | Mantida: Ca ka <= -6.65 -> Ag ka scattering <= 1.67 (2.3805)
Removida: background3 <= 1.29 -> Ca kb <= 12.61 (0.0154) | Mantida: Ca kb <= 12.61 -> background3 <= 1.29 (1.2415)
Removida: background3 <= 2.86 -> background3 <= 1.29 (0.0138) | Mantida: background3 <= 1.29 -> background3 <= 2.86 (0.0866)
Removida: background3 <= -0.30 -> background3 <= 2.86 (0.0251) | Mantida: background3 <= 2.86 -> background3 <= -0.30 (0.0844)
Removida: background3 <= -0.30 -> Ag ka scattering > -1.65 (0.0476) | Mantida: Ag ka scattering > -1.65 -> background3 <= -0.30 (0.1112)
Removida: Ag ka scattering > -1.65 -> Ti kb <= -2.91 (0.3256) | Mantida: Ti kb <= -2.91 -> Ag ka scattering > -1.65 (1.6179)
Removida: Ag ka scattering > -0.18 -> Ti kb <= -2.91 (0.0953) | Mantida: Ti kb <= -2.91 -> Ag ka scattering > -0.18 (0.8607)
Removida: Ca kb <= -2.67 -> Ag ka scattering > -0.18 (0.2626) | Mantida: Ag ka scattering > -0.18 -> Ca kb <= -2.67 (0.3425)
Removida: Zn ka > -1.75 -> Ag ka scattering > -0.18 (0.0620) | Mantida: Ag ka scattering > -0.18 -> Zn ka > -1.75 (0.2571)
Removida: Zn ka > -1.75 -> Ca kb <= -2.67 (0.1707) | Mantida: Ca kb <= -2.67 -> Zn ka > -1.75 (0.5385)
Removida: Cu ka <= -3.28 -> Ca kb <= -2.67 (0.4748) | Mantida: Ca kb <= -2.67 -> Cu ka <= -3.28 (0.7486)
Removida: Zn ka > -1.75 -> Cu ka <= -3.28 (0.0529) | Mantida: Cu ka <= -3.28 -> Zn ka > -1.75 (0.5272)
Removida: background1 <= 2.08 -> Zn ka > -1.75 (0.0296) | Mantida: Zn ka > -1.75 -> background1 <= 2.08 (0.0527)
Removida: Ti ka > -4.69 -> Cu ka <= -3.28 (0.5133) | Mantida: Cu ka <= -3.28 -> Ti ka > -4.69 (0.7699)
Removida: Zn ka > -0.78 -> Cu ka <= -3.28 (0.1050) | Mantida: Cu ka <= -3.28 -> Zn ka > -0.78 (0.4561)
Removida: background1 <= 2.08 -> Ti ka > -4.69 (0.0502) | Mantida: Ti ka > -4.69 -> background1 <= 2.08 (0.2558)
Removida: Zn ka <= 1.38 -> background1 <= 2.08 (0.0474) | Mantida: background1 <= 2.08 -> Zn ka <= 1.38 (0.0514)
Removida: Zn ka <= 1.38 -> Ca ka <= -21.19 (0.1313) | Mantida: Ca ka <= -21.19 -> Zn ka <= 1.38 (0.3904)
Removida: Ag ka scattering > 1.67 -> Zn ka <= 1.38 (0.0579) | Mantida: Zn ka <= 1.38 -> Ag ka scattering > 1.67 (0.0832)
Removida: background1 <= 2.08 -> Zn ka > -0.78 (0.0251) | Mantida: Zn ka > -0.78 -> background1 <= 2.08 (0.1354)
Removida: background1 <= 2.08 -> Ag ka scattering > 1.67 (0.0256) | Mantida: Ag ka scattering > 1.67 -> background1 <= 2.08 (0.0516)
Removida: Zn ka > -0.78 -> Ca ka <= -21.19 (0.0424) | Mantida: Ca ka <= -21.19 -> Zn ka > -0.78 (0.2105)
Removida: Ag ka scattering > 1.67 -> Zn ka > -0.78 (0.0490) | Mantida: Zn ka > -0.78 -> Ag ka scattering > 1.67 (0.1340)
Removida: Ag ka scattering > 1.67 -> Ca ka <= -21.19 (0.0605) | Mantida: Ca ka <= -21.19 -> Ag ka scattering > 1.67 (0.4021)
Removida: background3 > -2.55 -> background1 <= -0.11 (0.0110) | Mantida: background1 <= -0.11 -> background3 > -2.55 (0.0462)
Removida: background3 > -2.55 -> Zn ka <= 0.08 (0.0090) | Mantida: Zn ka <= 0.08 -> background3 > -2.55 (0.0251)
Removida: background3 > -2.55 -> Cu ka <= -8.43 (0.0032) | Mantida: Cu ka <= -8.43 -> background3 > -2.55 (0.1263)
Removida: background1 <= -0.11 -> Zn ka <= 0.08 (0.0179) | Mantida: Zn ka <= 0.08 -> background1 <= -0.11 (0.0235)
Removida: background3 > 1.29 -> background1 <= -0.11 (0.0031) | Mantida: background1 <= -0.11 -> background3 > 1.29 (0.0276)
Removida: background1 <= -0.11 -> background1 > -0.11 (0.0151) | Mantida: background1 > -0.11 -> background1 <= -0.11 (0.0159)
Removida: background1 > -1.87 -> background1 <= -0.11 (0.0114) | Mantida: background1 <= -0.11 -> background1 > -1.87 (0.0172)
Removida: Zn ka <= 0.08 -> Ca kb <= -6.07 (0.0683) | Mantida: Ca kb <= -6.07 -> Zn ka <= 0.08 (0.1101)
Removida: background1 > -0.11 -> Zn ka <= 0.08 (0.0141) | Mantida: Zn ka <= 0.08 -> background1 > -0.11 (0.0289)
Removida: Ar ka + Ag L <= 0.28 -> Zn ka <= -0.78 (0.0126) | Mantida: Zn ka <= -0.78 -> Ar ka + Ag L <= 0.28 (0.0387)
Removida: Zn ka <= -0.78 -> Ca kb <= -6.07 (0.0241) | Mantida: Ca kb <= -6.07 -> Zn ka <= -0.78 (0.0894)
Removida: Ar ka + Ag L <= 0.28 -> Ar ka + Ag L <= 1.07 (0.0046) | Mantida: Ar ka + Ag L <= 1.07 -> Ar ka + Ag L <= 0.28 (0.0129)
Removida: Ca kb <= -6.07 -> Ti kb > -2.91 (0.1021) | Mantida: Ti kb > -2.91 -> Ca kb <= -6.07 (0.1656)
Removida: background1 > -1.87 -> Ca kb <= -6.07 (0.0092) | Mantida: Ca kb <= -6.07 -> background1 > -1.87 (0.0956)
Removida: background3 > 1.29 -> Ca kb <= -6.07 (0.0031) | Mantida: Ca kb <= -6.07 -> background3 > 1.29 (0.0972)
Removida: Ar ka + Ag L <= 1.07 -> background1 <= -1.03 (0.0053) | Mantida: background1 <= -1.03 -> Ar ka + Ag L <= 1.07 (0.0120)
Removida: background2 <= -0.37 -> Ar ka + Ag L <= 1.07 (0.0060) | Mantida: Ar ka + Ag L <= 1.07 -> background2 <= -0.37 (0.0082)
Removida: background1 <= -1.03 -> Cu ka <= -8.43 (0.0109) | Mantida: Cu ka <= -8.43 -> background1 <= -1.03 (0.0913)
Removida: background3 > 1.29 -> background1 <= -1.03 (0.0026) | Mantida: background1 <= -1.03 -> background3 > 1.29 (0.0132)
Removida: Ar ka + Ag L > -1.05 -> background1 <= -1.03 (0.0037) | Mantida: background1 <= -1.03 -> Ar ka + Ag L > -1.05 (0.0093)
Removida: background1 <= -1.03 -> Zn ka > 0.08 (0.0155) | Mantida: Zn ka > 0.08 -> background1 <= -1.03 (0.0196)
Removida: background2 <= -0.37 -> background1 <= -1.03 (0.0065) | Mantida: background1 <= -1.03 -> background2 <= -0.37 (0.0103)
Removida: Ar ka + Ag L <= -0.29 -> background1 > -0.11 (0.0042) | Mantida: background1 > -0.11 -> Ar ka + Ag L <= -0.29 (0.0161)
Removida: background3 > -0.30 -> Ar ka + Ag L <= -0.29 (0.0019) | Mantida: Ar ka + Ag L <= -0.29 -> background3 > -0.30 (0.0045)
Removida: Ar ka + Ag L > -1.05 -> background2 <= -0.37 (0.0038) | Mantida: background2 <= -0.37 -> Ar ka + Ag L > -1.05 (0.0125)
Removida: Zn kb > 0.29 -> background2 <= -0.37 (0.0032) | Mantida: background2 <= -0.37 -> Zn kb > 0.29 (0.0055)
Removida: background3 > -0.30 -> background2 <= -0.37 (0.0039) | Mantida: background2 <= -0.37 -> background3 > -0.30 (0.0060)
Removida: background3 > -0.30 -> Ar ka + Ag L > -1.05 (0.0018) | Mantida: Ar ka + Ag L > -1.05 -> background3 > -0.30 (0.0038)
Removida: Cu kb <= 0.18 -> Fe ka <= -23.71 (0.0348) | Mantida: Fe ka <= -23.71 -> Cu kb <= 0.18 (0.0533)
Removida: background2 > -0.92 -> Fe ka <= -23.71 (0.0047) | Mantida: Fe ka <= -23.71 -> background2 > -0.92 (0.0320)
Removida: background1 > -1.87 -> Cu kb <= 0.18 (0.0084) | Mantida: Cu kb <= 0.18 -> background1 > -1.87 (0.0278)
Removida: Cu kb <= 0.18 -> Fe ka <= -22.90 (0.0267) | Mantida: Fe ka <= -22.90 -> Cu kb <= 0.18 (0.0407)
Removida: Cu kb <= 0.18 -> Cu ka <= -9.68 (0.0440) | Mantida: Cu ka <= -9.68 -> Cu kb <= 0.18 (0.0443)
Removida: background1 > -1.87 -> Fe ka <= -22.90 (0.0052) | Mantida: Fe ka <= -22.90 -> background1 > -1.87 (0.0507)
Removida: Zn kb > -1.05 -> Fe ka <= -22.90 (0.0017) | Mantida: Fe ka <= -22.90 -> Zn kb > -1.05 (0.0502)
Removida: background2 <= 0.98 -> Fe ka <= -22.90 (0.0043) | Mantida: Fe ka <= -22.90 -> background2 <= 0.98 (0.0280)
Removida: Fe ka <= -22.90 -> Fe ka <= -24.15 (0.0358) | Mantida: Fe ka <= -24.15 -> Fe ka <= -22.90 (0.0449)
Removida: Fe ka <= -22.90 -> Cu ka <= -9.68 (0.0377) | Mantida: Cu ka <= -9.68 -> Fe ka <= -22.90 (0.0403)
Removida: Ar ka + Ag L > 0.28 -> Fe ka <= -22.90 (0.0014) | Mantida: Fe ka <= -22.90 -> Ar ka + Ag L > 0.28 (0.0515)
Removida: background2 > 0.27 -> Fe ka <= -24.15 (0.0035) | Mantida: Fe ka <= -24.15 -> background2 > 0.27 (0.0326)
Removida: background2 > 0.27 -> Fe kb <= -7.02 (0.0032) | Mantida: Fe kb <= -7.02 -> background2 > 0.27 (0.0292)
Removida: Ar ka + Ag L > 0.28 -> Zn kb <= -0.29 (0.0014) | Mantida: Zn kb <= -0.29 -> Ar ka + Ag L > 0.28 (0.0020)
Removida: Ar ka + Ag L > 0.28 -> background2 <= 0.98 (0.0020) | Mantida: background2 <= 0.98 -> Ar ka + Ag L > 0.28 (0.0023)
Removida: Ar ka + Ag L > 0.28 -> background2 > -0.37 (0.0015) | Mantida: background2 > -0.37 -> Ar ka + Ag L > 0.28 (0.0026)
Removida: Fe kb <= -7.02 -> Fe ka <= -24.15 (0.0347) | Mantida: Fe ka <= -24.15 -> Fe kb <= -7.02 (0.0575)
Removida: Fe kb <= -7.02 -> Fe kb <= -6.37 (0.0286) | Mantida: Fe kb <= -6.37 -> Fe kb <= -7.02 (0.0382)
Removida: background2 > -0.37 -> Cu kb <= -1.61 (0.0019) | Mantida: Cu kb <= -1.61 -> background2 > -0.37 (0.0200)
Removida: background2 > -0.92 -> Ti ka > 9.34 (0.0019) | Mantida: Ti ka > 9.34 -> background2 > -0.92 (0.0202)
Removida: Zn kb > -1.05 -> background2 > -0.92 (0.0006) | Mantida: background2 > -0.92 -> Zn kb > -1.05 (0.0025)
Removida: background2 > -0.92 -> Fe kb <= -6.37 (0.0017) | Mantida: Fe kb <= -6.37 -> background2 > -0.92 (0.0284)
Removida: Ti ka > 9.34 -> Fe kb <= -6.37 (0.0414) | Mantida: Fe kb <= -6.37 -> Ti ka > 9.34 (0.0444)
Removida: Cu kb <= -2.30 -> Fe kb <= -6.37 (0.0178) | Mantida: Fe kb <= -6.37 -> Cu kb <= -2.30 (0.0243)
Removida: Cu kb <= -2.30 -> Ti kb > 2.45 (0.0093) | Mantida: Ti kb > 2.45 -> Cu kb <= -2.30 (0.0114)
Removida: Ar ka + Ag L > -0.29 -> Fe kb <= -7.41 (0.0008) | Mantida: Fe kb <= -7.41 -> Ar ka + Ag L > -0.29 (0.0126)
Removida: Ti kb > 2.45 -> Fe kb <= -7.41 (0.0107) | Mantida: Fe kb <= -7.41 -> Ti kb > 2.45 (0.0284)

======================================================================
RESUMO DO GRAFO CONSTRUÍDO
======================================================================
Arestas iniciais: 526 | Removidas: 103
Nós predicados: 90
Métrica: Covariance
Ponderação por variância explicada: ATIVADA

======================================================================
Processando Grafo - Semente: 1
======================================================================


Total de pares bidirecionais encontrados: 91
Removida: Ca ka > -21.19 -> Ca ka > -26.11 (12.5875) | Mantida: Ca ka > -26.11 -> Ca ka > -21.19 (114.4447)
Removida: Ti ka <= 19.85 -> Fe kb > -7.02 (7.9467) | Mantida: Fe kb > -7.02 -> Ti ka <= 19.85 (37.6257)
Removida: Ti ka <= 19.85 -> Ca ka > -6.65 (32.0407) | Mantida: Ca ka > -6.65 -> Ti ka <= 19.85 (50.0024)
Removida: Ti ka > -28.53 -> Fe kb > -7.41 (12.9141) | Mantida: Fe kb > -7.41 -> Ti ka > -28.53 (27.5015)
Removida: Fe kb > -7.41 -> Ti ka <= 9.34 (6.2159) | Mantida: Ti ka <= 9.34 -> Fe kb > -7.41 (24.3429)
Removida: Ti ka <= 9.34 -> Ti ka > -28.53 (6.2746) | Mantida: Ti ka > -28.53 -> Ti ka <= 9.34 (51.0169)
Removida: Ca kb > -8.59 -> Fe kb > -7.79 (3.9793) | Mantida: Fe kb > -7.79 -> Ca kb > -8.59 (20.4455)
Removida: Ca kb > -8.59 -> Ca kb > -6.07 (15.5001) | Mantida: Ca kb > -6.07 -> Ca kb > -8.59 (19.4292)
Removida: Cu ka > -9.68 -> Cu ka > -10.68 (11.0363) | Mantida: Cu ka > -10.68 -> Cu ka > -9.68 (25.1180)
Removida: Ti kb <= 6.95 -> Ca kb > -2.67 (4.5217) | Mantida: Ca kb > -2.67 -> Ti kb <= 6.95 (18.3668)
Removida: Ti kb > -10.26 -> Ca kb > -2.67 (2.0482) | Mantida: Ca kb > -2.67 -> Ti kb > -10.26 (4.9008)
Removida: Ca ka <= 33.38 -> Ti kb <= 6.95 (5.9585) | Mantida: Ti kb <= 6.95 -> Ca ka <= 33.38 (9.2002)
Removida: Ti kb > -10.26 -> Ca ka <= 33.38 (6.2447) | Mantida: Ca ka <= 33.38 -> Ti kb > -10.26 (10.2824)
Removida: Cu kb > -2.30 -> Cu kb > -1.61 (1.4529) | Mantida: Cu kb > -1.61 -> Cu kb > -2.30 (2.1525)
Removida: Cu kb > -2.30 -> Ti ka <= -4.69 (0.6832) | Mantida: Ti ka <= -4.69 -> Cu kb > -2.30 (2.4760)
Removida: Cu kb > -1.61 -> Cu kb > -2.88 (0.6161) | Mantida: Cu kb > -2.88 -> Cu kb > -1.61 (0.6329)
Removida: Ag ka scattering <= -0.18 -> Cu kb > -1.61 (0.5417) | Mantida: Cu kb > -1.61 -> Ag ka scattering <= -0.18 (1.3234)
Removida: Cu kb > -1.61 -> Ti ka <= -4.69 (0.7051) | Mantida: Ti ka <= -4.69 -> Cu kb > -1.61 (2.4401)
Removida: Cu kb > -2.88 -> Ca kb <= 12.61 (0.5655) | Mantida: Ca kb <= 12.61 -> Cu kb > -2.88 (1.7700)
Removida: Ag ka scattering <= -0.18 -> Ca kb <= 12.61 (0.2523) | Mantida: Ca kb <= 12.61 -> Ag ka scattering <= -0.18 (2.6429)
Removida: Ag ka scattering <= 1.67 -> Ca kb <= 12.61 (0.4870) | Mantida: Ca kb <= 12.61 -> Ag ka scattering <= 1.67 (0.8147)
Removida: Ag ka scattering <= 3.49 -> Cu kb > -2.88 (0.5217) | Mantida: Cu kb > -2.88 -> Ag ka scattering <= 3.49 (1.2117)
Removida: Ag ka scattering <= 1.67 -> Cu kb > -2.88 (0.5008) | Mantida: Cu kb > -2.88 -> Ag ka scattering <= 1.67 (1.7347)
Removida: Ag ka scattering <= -0.18 -> Cu kb > -2.88 (0.2631) | Mantida: Cu kb > -2.88 -> Ag ka scattering <= -0.18 (1.2014)
Removida: Ag ka scattering <= -0.18 -> Ag ka scattering <= 3.49 (0.2651) | Mantida: Ag ka scattering <= 3.49 -> Ag ka scattering <= -0.18 (0.5193)
Removida: Ag ka scattering <= 1.67 -> Ti ka <= -4.69 (0.2327) | Mantida: Ti ka <= -4.69 -> Ag ka scattering <= 1.67 (0.9405)
Removida: background3 <= 2.86 -> background3 <= 1.29 (0.0306) | Mantida: background3 <= 1.29 -> background3 <= 2.86 (0.0829)
Removida: background3 <= -0.30 -> background3 <= 2.86 (0.0283) | Mantida: background3 <= 2.86 -> background3 <= -0.30 (0.0780)
Removida: Ti kb <= -2.91 -> Ag ka scattering > -1.65 (0.3192) | Mantida: Ag ka scattering > -1.65 -> Ti kb <= -2.91 (0.8337)

,Predicate_Cov_Seed_0,Predicate_Cov_Seed_1,Predicate_Cov_Seed_2,Predicate_Cov_Seed_3
0,Fe ka > -23.71,Fe ka > -23.71,Fe ka > -23.71,Fe ka > -23.71
1,Fe ka > -24.15,Fe ka > -24.15,Fe ka > -24.15,Fe ka > -24.15
2,Fe ka > -24.62,Fe ka > -24.62,Fe ka > -24.62,Fe ka > -24.62
3,Ca ka > -26.11,Ca ka > -26.11,Ca ka > -26.11,Ca ka > -21.19
4,Ca ka > -21.19,Ca ka > -21.19,Ca ka > -21.19,Ca ka > -26.11
...,...,...,...,...
87,Zn kb <= 1.07,Zn kb <= 0.29,background2 > -0.37,Fe kb <= -7.41
88,Zn kb <= -0.29,Fe kb <= -7.41,Zn kb <= 0.29,Zn kb > -1.05
89,Zn kb <= 0.29,Zn kb <= 1.07,Zn kb > 0.29,background2 <= 0.27
90,Class_A,Class_A,Class_A,Class_A
91,Class_B,Class_B,Class_B,Class_B

In [9]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_cov_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_cov = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_cov = lrc_summed_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_cov = lrc_summed_df_cov.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
#lrc_summed_unique_df_cov = lrc_summed_unique_df_cov.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_cov

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Fe ka > -23.71,15.988192,Fe ka,-23.71,>
1,Ca ka > -26.11,6.489697,Ca ka,-26.11,>
2,Fe kb > -7.02,5.279888,Fe kb,-7.02,>
3,Ti ka <= 19.85,3.638187,Ti ka,19.85,<=
4,Ca kb > -6.07,2.314792,Ca kb,-6.07,>
5,Cu ka > -10.68,1.694605,Cu ka,-10.68,>
6,Ti kb <= 6.95,0.731985,Ti kb,6.95,<=
7,Cu kb > -2.30,0.177316,Cu kb,-2.30,>
8,Ag ka scattering <= 3.49,0.128208,Ag ka scattering,3.49,<=
9,background3 <= -0.30,0.045245,background3,-0.30,<=
10,Zn ka > -1.75,0.028257,Zn ka,-1.75,>
11,background1 <= 2.08,0.019317,background1,2.08,<=
12,background2 <= -0.37,0.011678,background2,-0.37,<=
13,Zn kb > 0.29,0.010995,Zn kb,0.29,>
14,Ar ka + Ag L <= 1.07,0.010958,Ar ka + Ag L,1.07,<=
15,Class_A,0.000000,None,None,None

In [10]:
# Criar zone_sums_df para dados NÃO pré-processados (Xcalclass)
spectral_zones_original = exp.extract_spectral_zones(Xcalclass, spectral_cuts)
zones_original = exp.aggregate_spectral_zones_pca(spectral_zones_original) # apca aggregation

# Aplicar o mapeamento
lrc_summed_df_cov_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_cov,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_cov_natural

Zona 'Ar ka + Ag L': VE = 9.76%, dim = 29 variáveis
Zona 'Ca ka': VE = 99.20%, dim = 17 variáveis
Zona 'Ca kb': VE = 93.13%, dim = 13 variáveis
Zona 'Ti ka': VE = 98.39%, dim = 19 variáveis
Zona 'Ti kb': VE = 85.13%, dim = 16 variáveis
Zona 'background1': VE = 12.27%, dim = 39 variáveis
Zona 'Fe ka': VE = 99.86%, dim = 25 variáveis
Zona 'Fe kb': VE = 97.91%, dim = 22 variáveis
Zona 'background2': VE = 8.43%, dim = 18 variáveis
Zona 'Cu ka': VE = 98.29%, dim = 20 variáveis
Zona 'Zn ka': VE = 24.14%, dim = 21 variáveis
Zona 'Cu kb': VE = 66.75%, dim = 19 variáveis
Zona 'Zn kb': VE = 7.95%, dim = 30 variáveis
Zona 'background3': VE = 2.98%, dim = 451 variáveis
Zona 'Ag ka scattering': VE = 38.41%, dim = 49 variáveis

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Fe ka > -23.71,15.988192,Fe ka,-23.71,>,-228.336686,46.0,0.003068,Fe ka > -228.336686
1,Fe ka > -24.15,11.434537,Fe ka,-24.15,>,-232.833909,112.0,0.002150,Fe ka > -232.833909
2,Fe ka > -24.62,8.060821,Fe ka,-24.62,>,-240.227437,43.0,0.003827,Fe ka > -240.227437
3,Ca ka > -26.11,6.489697,Ca ka,-26.11,>,-287.239935,110.0,0.000994,Ca ka > -287.239935
4,Ca ka > -21.19,6.180080,Ca ka,-21.19,>,-238.439137,152.0,0.149595,Ca ka > -238.439137
...,...,...,...,...,...,...,...,...,...
87,Fe kb <= -7.41,0.008405,Fe kb,-7.41,<=,-32.289144,4.0,0.001335,Fe kb <= -32.289144
88,background2 <= 0.27,0.008022,background2,0.27,<=,0.811175,47.0,0.000881,background2 <= 0.811175
89,Zn kb <= 1.07,0.007872,Zn kb,1.07,<=,-2.546607,108.0,0.003444,Zn kb <= -2.546607
90,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
91,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

## Reconstrução de Thresholds Multivariados

Agora vamos pegar os thresholds dos predicados mais importantes e reconstruí-los como espectros completos.

In [11]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_cov_natural.iloc[n]['Zone']
threshold_score = float(lrc_summed_df_cov_natural.iloc[n]['Threshold_Natural'])  # Corrigido: usa n em vez de 7

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
print(f"  - Range de energias: {threshold_spectrum.index[0]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_cov_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Fe ka':
  - Dimensão: 25 variáveis espectrais
  - Range de energias: 6.15 - 6.76
  - Variância explicada pela PC1: 99.86%

In [12]:
import explaining as exp

# LISTA DE SEMENTES A TESTAR
random_seeds = [0, 1, 2, 3]

all_results_pert = {}
training_samples = len(Xcalclass)

# LOOP: PROCESSAR CADA SEMENTE

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando semente: {seed}")
    print(f"{'='*70}\n")
    # Bagging
    bags_result_seed = exp.bagging_predicates(
        zone_sums_df=zone_scores_df,
        y_predicted_numeric=y_pred,
        predicates_df=predicates_quantiles[0],
        n_bags=10,
        #n_predicates_per_bag=40,
        n_samples_per_bag=int(training_samples*0.8), # 80 % da base para amostrar (convertido para int)
        min_samples_per_predicate=int(training_samples*0.2), # 20 % da base para limitar (convertido para int)
        replace=False,
        sample_bagging=True,
        predicate_bagging=False,
        random_seed=seed
    )
    # Inserir classe prevista
    for bag_name, pred_dict in bags_result_seed.items(): # iterando sobre cada bag
        for pred_rule, df_info in pred_dict.items():
            df_info['Class_Predicted'] = np.where(df_info['Predicted_Y'] >= 0.5, 'A', 'B') # binarizando com threshold 0.5, A = eut, B = dist

    pert_results_seed = exp.calculate_predicate_perturbation(
        estimator=mlp_model[3],
        Xcalclass_prep=Xcalclass_prep,
        folds_struct=bags_result_seed,
        predicates_df=predicates_quantiles[0],
        spectral_cuts=spectral_cuts,
        #perturbation_value=0,
        perturbation_mode='median', # valores entre 'mean' ou 'min'
        stats_source='full', # full indica usar todas as amostras para calcular estatísticas enquanto que 'fold' usa apenas as amostras do fold atual
        #metric='mean_abs_diff',   # Média com sinal (pode ser negativo)
        aim='classification',
        metric='probability_shift', 
        verbose=True
    )

    # Salvar no dicionário principal
    all_results_pert[seed] = {
        'bags_result': bags_result_seed,
        'pert_results_dict': pert_results_seed
    }

# CONSTRUÇÃO DE GRAFOS PARA MÚLTIPLAS SEMENTES (LOOP EXTERNO)
# Dicionário para armazenar grafos
graphs_pert_by_seed = {}

for seed in random_seeds:
    print(f"\n{'='*70}")
    print(f"Processando Grafo - Semente: {seed}")
    print(f"{'='*70}\n")
    
    # Construir grafo para esta semente (sem predicates_df - extraído da regra)
    DG = exp.build_predicate_graphv3_pca(
        bags_result=all_results_pert[seed]['bags_result'],
        predicate_ranking_dict=all_results_pert[seed]['pert_results_dict'],
        metric_column='Perturbation',
        random_state=seed,
        show_details=True,
        var_exp=True,
        pca_info_dict=pca_info_dict
    )

    # Armazenar grafo
    graphs_pert_by_seed[seed] = DG  

# Calcular LRC usando a função pronta do explaining.py
lrc_pert_by_seed = {}
for seed in random_seeds:
    DG = graphs_pert_by_seed[seed]
    lrc_pert_df_seed = exp.calculate_lrc_single_graph(DG, predicates_quantiles[0])
    lrc_pert_df_seed['Seed'] = seed  # Adicionar coluna com a semente
    lrc_pert_by_seed[seed] = lrc_pert_df_seed

# junando todas as colunas 'Node' de lrc_by_seed em um único dataframe
lrc_pert_all_seeds_df = pd.DataFrame()
for seed in random_seeds:
    lrc_pert_df_seed = lrc_pert_by_seed[seed].rename(columns={'Node': f'Predicate_pert_Seed_{seed}'})
    lrc_pert_all_seeds_df = pd.concat([lrc_pert_all_seeds_df, lrc_pert_df_seed[[f'Predicate_pert_Seed_{seed}']]], axis=1)

# vamos filtrar lrc_by_seed em cada semente para manter apenas as zonas espectrais únicas com maior LRC em um mesmo dataframe
lrc_pert_unique_by_seed = {}
for seed, lrc_df in lrc_pert_by_seed.items():
    lrc_pert_unique_df = lrc_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
    lrc_pert_unique_df = lrc_pert_unique_df.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
    lrc_pert_unique_by_seed[seed] = lrc_pert_unique_df

lrc_pert_all_seeds_df # exibindo o dataframe consolidado com predicados de todas as sementes

======================================================================
Processando semente: 0
======================================================================

Bag_1 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_2 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_3 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_4 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_5 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_6 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_7 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_8 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_9 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
Bag_10 | Amostras: Sim | Predicados: Não (Todos) | Válidos: 90 | Descartados: 30
======================================================================
PERTURBATION IMPORTANCE PARA PREDICADOS
======================================================================
Tipo de tarefa (aim): classification
Modo de perturbação: median
Fonte das estatísticas: full
Métrica: probability_shift
Total de folds: 10


[Bag_1] Processando 90 predicados...
  Predicado: Ar ka + Ag L > -1.05 (n=177)
    Zona: 29 colunas
    Importance: 0.001439
  Predicado: Ar ka + Ag L <= -0.29 (n=98)
    Zona: 29 colunas
    Importance: 0.002036
  Predicado: Ar ka + Ag L > -0.29 (n=129)
    Zona: 29 colunas
    Importance: 0.001110
  Predicado: Ar ka + Ag L <= 0.28 (n=138)
    Zona: 29 colunas
    Importance: 0.001689
  Predicado: Ar ka + Ag L > 0.28 (n=89)
    Zona: 29 colunas
    Importance: 0.001232
  Predicado: Ar ka + Ag L <= 1.07 (n=183)
    Zona: 29 colunas
    Importance: 0.001636
  Predicado: Ca ka > -26.11 (n=175)
    Zona: 17 colunas
    Importance: 0.031840
  Predicado: Ca ka <= -21.19 (n=94)
    Zona: 17 colunas
    Importance: 0.016269
  Predicado: Ca ka > -21.19 (n=133)
    Zona: 17 colunas
    Importance: 0.040061
  Predicado: Ca ka <= -6.65 (n=140)
    Zona: 17 colunas
    Importance: 0.011086
  Predicado: Ca ka > -6.65 (n=87)
    Zona: 17 colunas
    Importance: 0.060982
  Predicado: Ca ka <= 33.38 (n=183)
    Zona: 17 colunas
    Importance: 0.009760
  Predicado: Ca kb > -8.59 (n=174)
    Zona: 13 colunas
    Importance: 0.000916
  Predicado: Ca kb <= -6.07 (n=94)
    Zona: 13 colunas
    Importance: 0.001921
  Predicado: Ca kb > -6.07 (n=133)
    Zona: 13 colunas
    Importance: 0.000830
  Predicado: Ca kb <= -2.67 (n=140)
    Zona: 13 colunas
    Importance: 0.001403
  Predicado: Ca kb > -2.67 (n=87)
    Zona: 13 colunas
    Importance: 0.001087
  Predicado: Ca kb <= 12.61 (n=182)
    Zona: 13 colunas
    Importance: 0.001232
  Predicado: Ti ka > -28.53 (n=184)
    Zona: 19 colunas
    Importance: 0.022458
  Predicado: Ti ka <= -4.69 (n=91)
    Zona: 19 colunas
    Importance: 0.060808
  Predicado: Ti ka > -4.69 (n=136)
    Zona: 19 colunas
    Importance: 0.005426
  Predicado: Ti ka <= 9.34 (n=136)
    Zona: 19 colunas
    Importance: 0.042351
  Predicado: Ti ka > 9.34 (n=91)
    Zona: 19 colunas
    Importance: 0.005623
  Predicado: Ti ka <= 19.85 (n=181)
    Zona: 19 colunas
    Importance: 0.032945
  Predicado: Ti kb > -10.26 (n=182)
    Zona: 16 colunas
    Importance: 0.003327
  Predicado: Ti kb <= -2.91 (n=91)
    Zona: 16 colunas
    Importance: 0.010883
  Predicado: Ti kb > -2.91 (n=136)
    Zona: 16 colunas
    Importance: 0.001435
  Predicado: Ti kb <= 2.45 (n=138)
    Zona: 16 colunas
    Importance: 0.007738
  Predicado: Ti kb > 2.45 (n=89)
    Zona: 16 colunas
    Importance: 0.001323
  Predicado: Ti kb <= 6.95 (n=185)
    Zona: 16 colunas
    Importance: 0.006072
  Predicado: background1 > -1.87 (n=181)
    Zona: 39 colunas
    Importance: 0.001004
  Predicado: background1 <= -1.03 (n=91)
    Zona: 39 colunas
    Importance: 0.003216
  Predicado: background1 > -1.03 (n=136)
    Zona: 39 colunas
    Importance: 0.000944
  Predicado: background1 <= -0.11 (n=136)
    Zona: 39 colunas
    Importance: 0.002438
  Predicado: background1 > -0.11 (n=91)
    Zona: 39 colunas
    Importance: 0.000984
  Predicado: background1 <= 2.08 (n=183)
    Zona: 39 colunas
    Importance: 0.002073
  Predicado: Fe ka > -24.62 (n=183)
    Zona: 25 colunas
    Importance: 0.001365
  Predicado: Fe ka <= -24.15 (n=86)
    Zona: 25 colunas
    Importance: 0.000870
  Predicado: Fe ka > -24.15 (n=141)
    Zona: 25 colunas
    Importance: 0.001616
  Predicado: Fe ka <= -23.71 (n=136)
    Zona: 25 colunas
    Importance: 0.000868
  Predicado: Fe ka > -23.71 (n=91)
    Zona: 25 colunas
    Importance: 0.002029
  Predicado: Fe ka <= -22.90 (n=179)
    Zona: 25 colunas
    Importance: 0.000808
  Predicado: Fe kb > -7.79 (n=181)
    Zona: 22 colunas
    Importance: 0.001462
  Predicado: Fe kb <= -7.41 (n=91)
    Zona: 22 colunas
    Importance: 0.000804
  Predicado: Fe kb > -7.41 (n=136)
    Zona: 22 colunas
    Importance: 0.001684
  Predicado: Fe kb <= -7.02 (n=135)
    Zona: 22 colunas
    Importance: 0.000940
  Predicado: Fe kb > -7.02 (n=92)
    Zona: 22 colunas
    Importance: 0.001905
  Predicado: Fe kb <= -6.37 (n=181)
    Zona: 22 colunas
    Importance: 0.000901
  Predicado: background2 > -0.92 (n=177)
    Zona: 18 colunas
    Importance: 0.000809
  Predicado: background2 <= -0.37 (n=96)
    Zona: 18 colunas
    Importance: 0.000667
  Predicado: background2 > -0.37 (n=131)
    Zona: 18 colunas
    Importance: 0.000928
  Predicado: background2 <= 0.27 (n=142)
    Zona: 18 colunas
    Importance: 0.000736
  Predicado: background2 > 0.27 (n=85)
    Zona: 18 colunas
    Importance: 0.000954
  Predicado: background2 <= 0.98 (n=186)
    Zona: 18 colunas
    Importance: 0.000808
  Predicado: Cu ka > -10.68 (n=181)
    Zona: 20 colunas
    Importance: 0.006378
  Predicado: Cu ka <= -9.68 (n=93)
    Zona: 20 colunas
    Importance: 0.002513
  Predicado: Cu ka > -9.68 (n=134)
    Zona: 20 colunas
    Importance: 0.008219
  Predicado: Cu ka <= -8.43 (n=140)
    Zona: 20 colunas
    Importance: 0.001955
  Predicado: Cu ka > -8.43 (n=87)
    Zona: 20 colunas
    Importance: 0.012199
  Predicado: Cu ka <= -3.28 (n=182)
    Zona: 20 colunas
    Importance: 0.001667
  Predicado: Zn ka > -1.75 (n=181)
    Zona: 21 colunas
    Importance: 0.001010
  Predicado: Zn ka <= -0.78 (n=89)
    Zona: 21 colunas
    Importance: 0.001380
  Predicado: Zn ka > -0.78 (n=138)
    Zona: 21 colunas
    Importance: 0.000907
  Predicado: Zn ka <= 0.08 (n=138)
    Zona: 21 colunas
    Importance: 0.001178
  Predicado: Zn ka > 0.08 (n=89)
    Zona: 21 colunas
    Importance: 0.000959
  Predicado: Zn ka <= 1.38 (n=184)
    Zona: 21 colunas
    Importance: 0.001168
  Predicado: Cu kb > -2.88 (n=177)
    Zona: 19 colunas
    Importance: 0.000747
  Predicado: Cu kb <= -2.30 (n=92)
    Zona: 19 colunas
    Importance: 0.001142
  Predicado: Cu kb > -2.30 (n=135)
    Zona: 19 colunas
    Importance: 0.000709
  Predicado: Cu kb <= -1.61 (n=137)
    Zona: 19 colunas
    Importance: 0.000954
  Predicado: Cu kb > -1.61 (n=90)
    Zona: 19 colunas
    Importance: 0.000779
  Predicado: Cu kb <= 0.18 (n=180)
    Zona: 19 colunas
    Importance: 0.000915
  Predicado: Zn kb > -1.05 (n=182)
    Zona: 30 colunas
    Importance: 0.001449
  Predicado: Zn kb <= -0.29 (n=93)
    Zona: 30 colunas
    Importance: 0.001706
  Predicado: Zn kb > -0.29 (n=134)
    Zona: 30 colunas
    Importance: 0.001220
  Predicado: Zn kb <= 0.29 (n=142)
    Zona: 30 colunas
    Importance: 0.001476
  Predicado: Zn kb > 0.29 (n=85)
    Zona: 30 colunas
    Importance: 0.001325
  Predicado: Zn kb <= 1.07 (n=182)
    Zona: 30 colunas
    Importance: 0.001322
  Predicado: background3 > -2.55 (n=179)
    Zona: 451 colunas
    Importance: 0.004685
  Predicado: background3 <= -0.30 (n=95)
    Zona: 451 colunas
    Importance: 0.027621
  Predicado: background3 > -0.30 (n=132)
    Zona: 451 colunas
    Importance: 0.002861
  Predicado: background3 <= 1.29 (n=133)
    Zona: 451 colunas
    Importance: 0.021069
  Predicado: background3 > 1.29 (n=94)
    Zona: 451 colunas
    Importance: 0.002122
  Predicado: background3 <= 2.86 (n=184)
    Zona: 451 colunas
    Importance: 0.015876
  Predicado: Ag ka scattering > -1.65 (n=180)
    Zona: 49 colunas
    Importance: 0.002292
  Predicado: Ag ka scattering <= -0.18 (n=93)
    Zona: 49 colunas
    Importance: 0.017216
  Predicado: Ag ka scattering > -0.18 (n=134)
    Zona: 49 colunas
    Importance: 0.002795
  Predicado: Ag ka scattering <= 1.67 (n=133)
    Zona: 49 colunas
    Importance: 0.012885
  Predicado: Ag ka scattering > 1.67 (n=94)
    Zona: 49 colunas
    Importance: 0.002787
  Predicado: Ag ka scattering <= 3.49 (n=180)
    Zona: 49 colunas
    Importance: 0.010037

[Bag_2] Processando 90 predicados...
  Predicado: Ar ka + Ag L > -1.05 (n=182)
    Zona: 29 colunas
    Importance: 0.001079
  Predicado: Ar ka + Ag L <= -0.29 (n=91)
    Zona: 29 colunas
    Importance: 0.001523
  Predicado: Ar ka + Ag L > -0.29 (n=136)
    Zona: 29 colunas
    Importance: 0.001037
  Predicado: Ar ka + Ag L <= 0.28 (n=137)
    Zona: 29 colunas
    Importance: 0.001265
  Predicado: Ar ka + Ag L > 0.28 (n=90)
    Zona: 29 colunas
    Importance: 0.001182
  Predicado: Ar ka + Ag L <= 1.07 (n=181)
    Zona: 29 colunas
    Importance: 0.001306
  Predicado: Ca ka > -26.11 (n=182)
    Zona: 17 colunas
    Importance: 0.032924
  Predicado: Ca ka <= -21.19 (n=93)
    Zona: 17 colunas
    Importance: 0.015540
  Predicado: Ca ka > -21.19 (n=134)
    Zona: 17 colunas
    Importance: 0.042744
  Predicado: Ca ka <= -6.65 (n=136)
    Zona: 17 colunas
    Importance: 0.010822
  Predicado: Ca ka > -6.65 (n=91)
    Zona: 17 colunas
    Importance: 0.062651
  Predicado: Ca ka <= 33.38 (n=179)
    Zona: 17 colunas
    Importance: 0.009665
  Predicado: Ca kb > -8.59 (n=183)
    Zona: 13 colunas
    Importance: 0.000863
  Predicado: Ca kb <= -6.07 (n=93)
    Zona: 13 colunas
    Importance: 0.001650
  Predicado: Ca kb > -6.07 (n=134)
    Zona: 13 colunas
    Importance: 0.000902
  Predicado: Ca kb <= -2.67 (n=137)
    Zona: 13 colunas
    Importance: 0.001239
  Predicado: Ca kb > -2.67 (n=90)
    Zona: 13 colunas
    Importance: 0.001161
  Predicado: Ca kb <= 12.61 (n=179)
    Zona: 13 colunas
    Importance: 0.001141
  Predicado: Ti ka > -28.53 (n=178)
    Zona: 19 colunas
    Importance: 0.021356
  Predicado: Ti ka <= -4.69 (n=94)
    Zona: 19 colunas
    Importance: 0.051522
  Predicado: Ti ka > -4.69 (n=133)
    Zona: 19 colunas
    Importance: 0.005114
  Predicado: Ti ka <= 9.34 (n=134)
    Zona: 19 colunas
    Importance: 0.037346
  Predicado: Ti ka > 9.34 (n=93)
    Zona: 19 colunas
    Importance: 0.005578
  Predicado: Ti ka <= 19.85 (n=178)
    Zona: 19 colunas
    Importance: 0.029107
  Predicado: Ti kb > -10.26 (n=182)
    Zona: 16 colunas
    Importance: 0.003195
  Predicado: Ti kb <= -2.91 (n=94)
    Zona: 16 colunas
    Importance: 0.009640
  Predicado: Ti kb > -2.91 (n=133)
    Zona: 16 colunas
    Importance: 0.001419
  Predicado: Ti kb <= 2.45 (n=131)
    Zona: 16 colunas
    Importance: 0.007408
  Predicado: Ti kb > 2.45 (n=96)
    Zona: 16 colunas
    Importance: 0.001296
  Predicado: Ti kb <= 6.95 (n=179)
    Zona: 16 colunas
    Importance: 0.005693
  Predicado: background1 > -1.87 (n=185)
    Zona: 39 colunas
    Importance: 0.001003
  Predicado: background1 <= -1.03 (n=88)
    Zona: 39 colunas
    Importance: 0.002654
  Predicado: background1 > -1.03 (n=139)
    Zona: 39 colunas
    Importance: 0.000955
  Predicado: background1 <= -0.11 (n=132)
    Zona: 39 colunas
    Importance: 0.002073
  Predicado: background1 > -0.11 (n=95)
    Zona: 39 colunas
    Importance: 0.000975
  Predicado: background1 <= 2.08 (n=179)
    Zona: 39 colunas
    Importance: 0.001865
  Predicado: Fe ka > -24.62 (n=180)
    Zona: 25 colunas
    Importance: 0.001253
  Predicado: Fe ka <= -24.15 (n=91)
    Zona: 25 colunas
    Importance: 0.000841
  Predicado: Fe ka > -24.15 (n=136)
    Zona: 25 colunas
    Importance: 0.001514
  Predicado: Fe ka <= -23.71 (n=140)
    Zona: 25 colunas
    Importance: 0.000851
  Predicado: Fe ka > -23.71 (n=87)
    Zona: 25 colunas
    Importance: 0.001877
  Predicado: Fe ka <= -22.90 (n=183)
    Zona: 25 colunas
    Importance: 0.000791
  Predicado: Fe kb > -7.79 (n=178)
    Zona: 22 colunas
    Importance: 0.001425
  Predicado: Fe kb <= -7.41 (n=89)
    Zona: 22 colunas
    Importance: 0.000817
  Predicado: Fe kb > -7.41 (n=138)
    Zona: 22 colunas
    Importance: 0.001623
  Predicado: Fe kb <= -7.02 (n=136)
    Zona: 22 colunas
    Importance: 0.000917
  Predicado: Fe kb > -7.02 (n=91)
    Zona: 22 colunas
    Importance: 0.001888
  Predicado: Fe kb <= -6.37 (n=183)
    Zona: 22 colunas
    Importance: 0.000892
  Predicado: background2 > -0.92 (n=184)
    Zona: 18 colunas
    Importance: 0.000750
  Predicado: background2 <= -0.37 (n=86)
    Zona: 18 colunas
    Importance: 0.000630
  Predicado: background2 > -0.37 (n=141)
    Zona: 18 colunas
    Importance: 0.000870
  Predicado: background2 <= 0.27 (n=131)
    Zona: 18 colunas
    Importance: 0.000695
  Predicado: background2 > 0.27 (n=96)
    Zona: 18 colunas
    Importance: 0.000893
  Predicado: background2 <= 0.98 (n=184)
    Zona: 18 colunas
    Importance: 0.000765
  Predicado: Cu ka > -10.68 (n=180)
    Zona: 20 colunas
    Importance: 0.004675
  Predicado: Cu ka <= -9.68 (n=93)
    Zona: 20 colunas
    Importance: 0.002178
  Predicado: Cu ka > -9.68 (n=134)
    Zona: 20 colunas
    Importance: 0.005907
  Predicado: Cu ka <= -8.43 (n=139)
    Zona: 20 colunas
    Importance: 0.001741
  Predicado: Cu ka > -8.43 (n=88)
    Zona: 20 colunas
    Importance: 0.008547
  Predicado: Cu ka <= -3.28 (n=186)
    Zona: 20 colunas
    Importance: 0.001547
  Predicado: Zn ka > -1.75 (n=179)
    Zona: 21 colunas
    Importance: 0.000954
  Predicado: Zn ka <= -0.78 (n=95)
    Zona: 21 colunas
    Importance: 0.001063
  Predicado: Zn ka > -0.78 (n=132)
    Zona: 21 colunas
    Importance: 0.000854
  Predicado: Zn ka <= 0.08 (n=142)
    Zona: 21 colunas
    Importance: 0.000977
  Predicado: Zn ka > 0.08 (n=85)
    Zona: 21 colunas
    Importance: 0.000882
  Predicado: Zn ka <= 1.38 (n=186)
    Zona: 21 colunas
    Importance: 0.001016
  Predicado: Cu kb > -2.88 (n=178)
    Zona: 19 colunas
    Importance: 0.000632
  Predicado: Cu kb <= -2.30 (n=89)
    Zona: 19 colunas
    Importance: 0.001078
  Predicado: Cu kb > -2.30 (n=138)
    Zona: 19 colunas
    Importance: 0.000626
  Predicado: Cu kb <= -1.61 (n=139)
    Zona: 19 colunas
    Importance: 0.000886
  Predicado: Cu kb > -1.61 (n=88)
    Zona: 19 colunas
    Importance: 0.000673
  Predicado: Cu kb <= 0.18 (n=184)
    Zona: 19 colunas
    Importance: 0.000830
  Predicado: Zn kb > -1.05 (n=183)
    Zona: 30 colunas
    Importance: 0.001294
  Predicado: Zn kb <= -0.29 (n=94)
    Zona: 30 colunas
    Importance: 0.001850
  Predicado: Zn kb > -0.29 (n=133)
    Zona: 30 colunas
    Importance: 0.000809
  Predicado: Zn kb <= 0.29 (n=144)
    Zona: 30 colunas
    Importance: 0.001507
  Predicado: Zn kb > 0.29 (n=83)
    Zona: 30 colunas
    Importance: 0.000776
  Predicado: Zn kb <= 1.07 (n=189)
    Zona: 30 colunas
    Importance: 0.001322
  Predicado: background3 > -2.55 (n=180)
    Zona: 451 colunas
    Importance: 0.004469
  Predicado: background3 <= -0.30 (n=92)
    Zona: 451 colunas
    Importance: 0.018407
  Predicado: background3 > -0.30 (n=135)
    Zona: 451 colunas
    Importance: 0.003056
  Predicado: background3 <= 1.29 (n=140)
    Zona: 451 colunas
    Importance: 0.013650
  Predicado: background3 > 1.29 (n=87)
    Zona: 451 colunas
    Importance: 0.002242
  Predicado: background3 <= 2.86 (n=184)
    Zona: 451 colunas
    Importance: 0.010971
  Predicado: Ag ka scattering > -1.65 (n=180)
    Zona: 49 colunas
    Importance: 0.001993
  Predicado: Ag ka scattering <= -0.18 (n=92)
    Zona: 49 colunas
    Importance: 0.015779
  Predicado: Ag ka scattering > -0.18 (n=135)
    Zona: 49 colunas
    Importance: 0.002366
  Predicado: Ag ka scattering <= 1.67 (n=135)
    Zona: 49 colunas
    Importance: 0.011079
  Predicado: Ag ka scattering > 1.67 (n=92)
    Zona: 49 colunas
    Importance: 0.002994
  Predicado: Ag ka scattering <= 3.49 (n=180)
    Zona: 49 colunas
    Importance: 0.008830

[Bag_3] Processando 90 predicados...
  Predicado: Ar ka + Ag L > -1.05 (n=181)
    Zona: 29 colunas
    Importance: 0.001423
  Predicado: Ar ka + Ag L <= -0.29 (n=89)
    Zona: 29 colunas
    Importance: 0.001945
  Predicado: Ar ka + Ag L > -0.29 (n=138)
    Zona: 29 colunas
    Importance: 0.001079
  Predicado: Ar ka + Ag L <= 0.28 (n=136)
    Zona: 29 colunas
    Importance: 0.001587
  Predicado: Ar ka + Ag L > 0.28 (n=91)
    Zona: 29 colunas
    Importance: 0.001168
  Predicado: Ar ka + Ag L <= 1.07 (n=180)
    Zona: 29 colunas
    Importance: 0.001546
  Predicado: Ca ka > -26.11 (n=183)
    Zona: 17 colunas
    Importance: 0.029189
  Predicado: Ca ka <= -21.19 (n=90)
    Zona: 17 colunas
    Importance: 0.016731
  Predicado: Ca ka > -21.19 (n=137)
    Zona: 17 colunas
    Importance: 0.036852
  Predicado: Ca ka <= -6.65 (n=135)
    Zona: 17 colunas
    Importance: 0.011305
  Predicado: Ca ka > -6.65 (n=92)
    Zona: 17 colunas
    Importance: 0.054656
  Predicado: Ca ka <= 33.38 (n=183)
    Zona: 17 colunas
    Importance: 0.010241
  Predicado: Ca kb > -8.59 (n=180)
    Zona: 13 colunas
    Importance: 0.000927
  Predicado: Ca kb <= -6.07 (n=91)
    Zona: 13 colunas
    Importance: 0.001849
  Predicado: Ca kb > -6.07 (n=136)
    Zona: 13 colunas
    Importance: 0.000838
  Predicado: Ca kb <= -2.67 (n=135)
    Zona: 13 colunas
    Importance: 0.001375
  Predicado: Ca kb > -2.67 (n=92)
    Zona: 13 colunas
    Importance: 0.001051
  Predicado: Ca kb <= 12.61 (n=183)
    Zona: 13 colunas
    Importance: 0.001203
  Predicado: Ti ka > -28.53 (n=185)
    Zona: 19 colunas
    Importance: 0.023050
  Predicado: Ti ka <= -4.69 (n=92)
    Zona: 19 colunas
    Importance: 0.060267
  Predicado: Ti ka > -4.69 (n=135)
    Zona: 19 colunas
    Importance: 0.005362
  Predicado: Ti ka <= 9.34 (n=138)
    Zona: 19 colunas
    Importance: 0.042147
  Predicado: Ti ka > 9.34 (n=89)
    Zona: 19 colunas
    Importance: 0.005080
  Predicado: Ti ka <= 19.85 (n=179)
    Zona: 19 colunas
    Importance: 0.033320
  Predicado: Ti kb > -10.26 (n=182)
    Zona: 16 colunas
    Importance: 0.003515
  Predicado: Ti kb <= -2.91 (n=94)
    Zona: 16 colunas
    Importance: 0.010739
  Predicado: Ti kb > -2.91 (n=133)
    Zona: 16 colunas
    Importance: 0.001470
  Predicado: Ti kb <= 2.45 (n=137)
    Zona: 16 colunas
    Importance: 0.007900
  Predicado: Ti kb > 2.45 (n=90)
    Zona: 16 colunas
    Importance: 0.001363
  Predicado: Ti kb <= 6.95 (n=182)
    Zona: 16 colunas
    Importance: 0.006263
  Predicado: background1 > -1.87 (n=182)
    Zona: 39 colunas
    Importance: 0.001064
  Predicado: background1 <= -1.03 (n=90)
    Zona: 39 colunas
    Importance: 0.003048
  Predicado: background1 > -1.03 (n=137)
    Zona: 39 colunas
    Importance: 0.001026
  Predicado: background1 <= -0.11 (n=136)
    Zona: 39 colunas
    Importance: 0.002302
  Predicado: background1 > -0.11 (n=91)
    Zona: 39 colunas
    Importance: 0.001119
  Predicado: background1 <= 2.08 (n=179)
    Zona: 39 colunas
    Importance: 0.002080
  Predicado: Fe ka > -24.62 (n=185)
    Zona: 25 colunas
    Importance: 0.001236
  Predicado: Fe ka <= -24.15 (n=93)
    Zona: 25 colunas
    Importance: 0.000962
  Predicado: Fe ka > -24.15 (n=134)
    Zona: 25 colunas
    Importance: 0.001430
  Predicado: Fe ka <= -23.71 (n=137)
    Zona: 25 colunas
    Importance: 0.000947
  Predicado: Fe ka > -23.71 (n=90)
    Zona: 25 colunas
    Importance: 0.001680
  Predicado: Fe ka <= -22.90 (n=177)
    Zona: 25 colunas
    Importance: 0.000889
  Predicado: Fe kb > -7.79 (n=179)
    Zona: 22 colunas

,Predicate_pert_Seed_0,Predicate_pert_Seed_1,Predicate_pert_Seed_2,Predicate_pert_Seed_3
0,Ca ka > -6.65,Ca ka > -6.65,Ca ka > -6.65,Ca ka > -6.65
1,Ti ka <= -4.69,Ti ka <= -4.69,Ti ka <= -4.69,Ti ka <= -4.69
2,Ti ka <= 9.34,Ca ka > -21.19,Ti ka <= 9.34,Ti ka <= 9.34
3,Ca ka > -26.11,Ti ka <= 9.34,Ca ka > -21.19,Ca ka > -26.11
4,Ca ka > -21.19,Ca ka > -26.11,Ca ka > -26.11,Ca ka > -21.19
...,...,...,...,...
87,Cu kb > -2.30,Cu kb > -2.30,Zn kb > 0.29,background2 > -0.37
88,background2 <= 0.27,background2 <= 0.27,Cu kb > -2.30,Cu kb > -2.30
89,background2 <= -0.37,background2 > -0.92,background2 <= -0.37,background2 <= -0.37
90,Class_A,Class_A,Class_A,Class_A
91,Class_B,Class_B,Class_B,Class_B

In [13]:
all_results_pert[0]['pert_results_dict']['Bag_1']

               Predicate  Perturbation
0          Ca ka > -6.65      0.060982
1         Ti ka <= -4.69      0.060808
2          Ti ka <= 9.34      0.042351
3         Ca ka > -21.19      0.040061
4         Ti ka <= 19.85      0.032945
..                   ...           ...
85         Cu kb > -1.61      0.000779
86         Cu kb > -2.88      0.000747
87   background2 <= 0.27      0.000736
88         Cu kb > -2.30      0.000709
89  background2 <= -0.37      0.000667

[90 rows x 2 columns]

In [14]:
# Somar LRCs de predicados equivalentes entre diferentes seeds
lrc_combined_list = []

for seed in random_seeds:
    lrc_df = lrc_pert_by_seed[seed].copy()
    lrc_combined_list.append(lrc_df) # o append adiciona o dataframe ao final da lista

# Concatenar todos os dataframes
lrc_all_seeds = pd.concat(lrc_combined_list, ignore_index=True) 

# Agrupar por predicado (Node) e somar as LRCs, mantendo Zone, Threshold e Operator
lrc_summed_df_pert = lrc_all_seeds.groupby('Node').agg({ # o .agg pode ser usado para aplicar múltiplas funções de agregação
    'Local_Reaching_Centrality': 'mean', # sum = somando as LRCs, poderia ser média ou outro agregado
    'Zone': 'first',
    'Threshold': 'first',
    'Operator': 'first'
}).reset_index()

# Ordenar pelo valor de LRC somado (maior para menor)
lrc_summed_df_pert = lrc_summed_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
# vamoss pegar so os valore sunicos de lrc_summed_df baseado na zona espectral
lrc_summed_unique_df_pert = lrc_summed_df_pert.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
lrc_summed_unique_df_pert = lrc_summed_unique_df_pert.sort_values(by='Local_Reaching_Centrality', ascending=False).reset_index(drop=True)
lrc_summed_unique_df_pert

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator
0,Ca ka > -6.65,10.655246,Ca ka,-6.65,>
1,Ti ka <= -4.69,7.334458,Ti ka,-4.69,<=
2,background3 <= -0.30,2.112321,background3,-0.30,<=
3,Cu ka > -8.43,2.080085,Cu ka,-8.43,>
4,Ag ka scattering <= -0.18,1.706129,Ag ka scattering,-0.18,<=
5,Ti kb <= -2.91,1.337856,Ti kb,-2.91,<=
6,background1 <= -1.03,0.203091,background1,-1.03,<=
7,Fe ka > -23.71,0.201094,Fe ka,-23.71,>
8,Fe kb > -7.02,0.193328,Fe kb,-7.02,>
9,Ca kb <= -6.07,0.182308,Ca kb,-6.07,<=
10,Zn kb <= -0.29,0.145015,Zn kb,-0.29,<=
11,Ar ka + Ag L <= -0.29,0.138472,Ar ka + Ag L,-0.29,<=
12,Cu kb <= -2.30,0.113720,Cu kb,-2.30,<=
13,Zn ka <= -0.78,0.097402,Zn ka,-0.78,<=
14,background2 > 0.27,0.088469,background2,0.27,>
15,Class_A,0.000000,None,None,None

In [15]:
# Aplicar o mapeamento
lrc_summed_df_pert_natural = exp.map_thresholds_to_natural(
    lrc_df=lrc_summed_df_pert,
    zone_sums_preprocessed=zone_scores_df,
    zone_sums_natural=zones_original[0]
)

lrc_summed_df_pert_natural

,Node,Local_Reaching_Centrality,Zone,Threshold,Operator,Threshold_Natural,Reference_Sample_Index,Approximation_Error,Node_Natural
0,Ca ka > -6.65,10.655246,Ca ka,-6.65,>,-72.180511,102.0,0.000511,Ca ka > -72.180511
1,Ti ka <= -4.69,7.334458,Ti ka,-4.69,<=,-49.917691,64.0,0.070519,Ti ka <= -49.917691
2,Ti ka <= 9.34,5.280687,Ti ka,9.34,<=,101.580304,11.0,0.037350,Ti ka <= 101.580304
3,Ca ka > -21.19,4.919432,Ca ka,-21.19,>,-238.439137,152.0,0.149595,Ca ka > -238.439137
4,Ca ka > -26.11,3.974427,Ca ka,-26.11,>,-287.239935,110.0,0.000994,Ca ka > -287.239935
...,...,...,...,...,...,...,...,...,...
87,background2 <= 0.27,0.071704,background2,0.27,<=,0.811175,47.0,0.000881,background2 <= 0.811175
88,Cu kb > -2.30,0.041151,Cu kb,-2.30,>,-8.474542,221.0,0.000430,Cu kb > -8.474542
89,background2 <= -0.37,0.019814,background2,-0.37,<=,-1.184782,277.0,0.010577,background2 <= -1.184782
90,Class_A,0.000000,None,None,None,NaN,NaN,NaN,None
91,Class_B,0.000000,None,None,None,NaN,NaN,NaN,None

In [16]:
import plotly.graph_objects as go

n = 0
zone_name = lrc_summed_df_pert_natural.iloc[n]['Zone'] # o n indica a linha do dataframe lrc_summed_df_pert_natural que queremos acessar para pegar o nome da zona espectral (coluna 'Zone')
threshold_score = float(lrc_summed_df_pert_natural.iloc[n]['Threshold_Natural']) # o iloc acessa a linha n e a coluna 'Threshold_Natural' para pegar o valor do threshold já mapeado para o espaço natural (não pré-processado)

# Usar pca_info_dict dos dados ORIGINAIS (zones_original[1])
pca_info_dict_original = zones_original[1]

# Reconstrução: τ = mean + threshold * loadings (no espaço original)
threshold_spectrum = exp.reconstruct_threshold_to_spectrum(
    threshold_value=threshold_score,
    zone_name=zone_name,
    pca_info_dict=pca_info_dict_original
)
print(f"\nEspectro de threshold reconstruído para zona '{zone_name}':")
print(f"  - Dimensão: {len(threshold_spectrum)} variáveis espectrais")
#print(f"  - Range de energias: {threshold_spectrum.index[n]} - {threshold_spectrum.index[-1]}")
print(f"  - Variância explicada pela PC1: {pca_info_dict_original[zone_name]['variance_explained']:.2%}")

# Usar dados ORIGINAIS para plotar (spectral_zones_original)
zone_df = spectral_zones_original[zone_name]

# Plotar zona com threshold (inline)
fig = go.Figure()
x_values = pd.to_numeric(zone_df.columns, errors='coerce')

# Plotar espectros das amostras coloridas por classe
colors = {'A': 'gold', 'B': 'blue'}
for idx, row in zone_df.iterrows():
    class_label = ycalclass.iloc[idx] if idx < len(ycalclass) else 'Unknown'
    fig.add_trace(go.Scatter(
        x=x_values,
        y=row.values,
        mode='lines',
        line=dict(color=colors.get(class_label, 'rgba(128,128,128,0.3)'), width=0.5),
        name=f'Class {class_label}',
        showlegend=False,
        hoverinfo='skip'
    ))

# Plotar espectro de threshold (destaque)
fig.add_trace(go.Scatter(
    x=x_values,
    y=threshold_spectrum.values,
    mode='lines',
    line=dict(color='red', width=4, dash='dash'),
    name=f'Threshold Spectrum ({threshold_spectrum.name})'
))

# Layout do gráfico
fig.update_layout(
    title=f"Zona '{zone_name}' com Threshold Multivariado (Predicado: {lrc_summed_df_pert_natural.iloc[n]['Node_Natural']})",
    xaxis_title='Energia / Comprimento de Onda',
    yaxis_title='Intensidade',
    template='plotly_white',
    showlegend=True,
    legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
)

fig.show()

Espectro de threshold reconstruído para zona 'Ca ka':
  - Dimensão: 17 variáveis espectrais
  - Variância explicada pela PC1: 99.20%

In [18]:
# Permutation importance baseado em mudança nas probabilidades previstas (predict_proba)
# Medimos a média da diferença absoluta entre as probabilidades originais e as probabilidades
# obtidas após permutar cada variável. Isso fornece uma métrica contínua de importância.
n_repeats = 10
rng = np.random.RandomState(42)
# Probabilidades base (classe 'B' mapeada para 1)
baseline_proba = mlp_model[3].predict_proba(Xcalclass_prep)[:, 1]
importance_list = []
X_arr = Xcalclass_prep.copy()
for col in Xcalclass_prep.columns:
    diffs = []
    for _ in range(n_repeats):
        X_perm = X_arr.copy()
        X_perm[col] = rng.permutation(X_perm[col].values)
        perm_proba = mlp_model[3].predict_proba(X_perm)[:, 1]
        diffs.append(np.mean(np.abs(baseline_proba - perm_proba)))
    importance_list.append(np.mean(diffs))

permutation_df = pd.DataFrame({
    'energy': Xcalclass_prep.columns,
    'Permutation_importance_proba': importance_list
})
permutation_df.sort_values(by='Permutation_importance_proba', ascending=False, inplace=True)
energy_to_zone_vip = {}
for zone_name, start, end in spectral_cuts:
    for e in permutation_df['energy']:
        ef = float(e)
        if start <= ef <= end:
            energy_to_zone_vip[e] = zone_name
permutation_df['Zone'] = permutation_df['energy'].map(energy_to_zone_vip)
permutation_unique_df = permutation_df.drop_duplicates(subset=['Zone'], keep='first').reset_index(drop=True)
permutation_unique_df = permutation_unique_df.sort_values(by='Permutation_importance_proba', ascending=False)
permutation_unique_df

   energy  Permutation_importance_proba              Zone
0    6.38                      0.018148             Fe ka
1    3.73                      0.005747             Ca ka
2    4.49                      0.004113             Ti ka
3    8.06                      0.002176             Cu ka
4    7.07                      0.001709             Fe kb
5    4.88                      0.001061             Ti kb
6    4.06                      0.001044             Ca kb
7   22.28                      0.000854  Ag ka scattering
8    8.98                      0.000675             Cu kb
9   12.75                      0.000597       background3
10   8.65                      0.000506             Zn ka
11   5.92                      0.000416       background1
12   9.36                      0.000404             Zn kb
13   2.79                      0.000386      Ar ka + Ag L
14   7.35                      0.000294       background2
15   2.74                      0.000216               NaN

In [19]:
import numpy as np

max_len = max(
    len(shap_unique_df['Zone']),
    len(permutation_unique_df['Zone']),
    len(lrc_summed_unique_df_pert['Zone']),
    len(lrc_summed_unique_df_cov['Zone'])
)

def pad_list(lst, length):
    return list(lst) + [None] * (length - len(lst))

features_importance = pd.DataFrame({
    'Shap': pad_list(shap_unique_df['Zone'], max_len),
    'Permutation' : pad_list(permutation_unique_df['Zone'], max_len),
    'LRC_perturbation' : pad_list(lrc_summed_unique_df_pert['Zone'], max_len),
    'LRC_covariance' : pad_list(lrc_summed_unique_df_cov['Zone'], max_len),
})

features_importance.to_csv('feature_importance.csv', index=False, sep=';')
features_importance

                Shap       Permutation  LRC_perturbation    LRC_covariance
0              Ca ka             Fe ka             Ca ka             Fe ka
1              Ti ka             Ca ka             Ti ka             Ca ka
2              Fe ka             Ti ka       background3             Fe kb
3              Cu ka             Cu ka             Cu ka             Ti ka
4              Ti kb             Fe kb  Ag ka scattering             Ca kb
5              Fe kb             Ti kb             Ti kb             Cu ka
6   Ag ka scattering             Ca kb       background1             Ti kb
7              Ca kb  Ag ka scattering             Fe ka             Cu kb
8        background3             Cu kb             Fe kb  Ag ka scattering
9              Zn kb       background3             Ca kb       background3
10             Cu kb             Zn ka             Zn kb             Zn ka
11       background1       background1      Ar ka + Ag L       background1
12             Zn ka             Zn kb             Cu kb       background2
13       background2      Ar ka + Ag L             Zn ka             Zn kb
14      Ar ka + Ag L       background2       background2      Ar ka + Ag L
15               NaN               NaN              None              None

In [20]:
import rbo
rbo_comparison = pd.DataFrame(columns=['Method_1', 'Method_2', 'RBO_Score'])
methods = features_importance.columns.tolist()
for i in range(len(methods)):
    for j in range(i + 1, len(methods)):
        method_1 = methods[i]
        method_2 = methods[j]
        # Remove None values from the lists
        list_1 = [x for x in features_importance[method_1].tolist() if x is not None]
        list_2 = [x for x in features_importance[method_2].tolist() if x is not None]
        # Truncate both lists to the same length (minimum of both)
        min_len = min(len(list_1), len(list_2))
        list_1_trunc = list_1[:min_len]
        list_2_trunc = list_2[:min_len]
        rbo_score = rbo.RankingSimilarity(list_1_trunc, list_2_trunc).rbo(p=0.7, k=10)
        rbo_comparison = pd.concat([rbo_comparison, pd.DataFrame({
            'Method_1': [method_1],
            'Method_2': [method_2],
            'RBO_Score': [rbo_score]
        })], ignore_index=True)
rbo_comparison.sort_values(by='RBO_Score', ascending=False, inplace=True)
rbo_comparison.to_csv('rbo_rank.csv', index=False, sep=';')
rbo_comparison

C:\Users\Usuario\AppData\Local\Temp\ipykernel_10992\3097109587.py:16: FutureWarning:

The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

           Method_1          Method_2  RBO_Score
4       Permutation    LRC_covariance   0.871130
1              Shap  LRC_perturbation   0.832015
0              Shap       Permutation   0.544172
2              Shap    LRC_covariance   0.443549
3       Permutation  LRC_perturbation   0.420052
5  LRC_perturbation    LRC_covariance   0.319429

In [21]:
lrc_summed_df_cov_natural.to_csv('lrc_cov_natural.csv', index=False, sep=';')
lrc_summed_df_pert_natural.to_csv('lrc_pert_natural.csv', index=False, sep=';')